
# GROTE UITVINDINGEN EN HET LEVEN IN EEN SPECIALE EEUW {-}


Amsterdam, augustus 2017

Beste Robert Gordon,


In 1870 was de levensstandaard van de gemiddelde Amerikaan laag. Niet zoals in de middeleeuwen, maar toch. Die was lager dan die van de Brit en weer hoger dan de Duitse levensstandaard toen. Het mensenleven was kort (gemiddeld 45 jaar) en de kindersterfte bijzonder hoog. Mensen woonden met grote gezinnen in kleine huizen, eigen groenten werden verbouwd en tot eten gemaakt. Mensen consumeerden zo’n 3,5 euro per week en dat ging bijna helemaal op aan eten, kleren en onderdak. 75 procent van de mensen woonde enkele jaren na de Amerikaanse burgeroorlog nog op het platteland en de samenleving was agrarisch opgebouwd. Indien er sprake was van onderwijs was dat vaak niet meer dan de lagere school. De huizen waren niet met elkaar verbonden: er waren geen sanitaire voorzieningen en iedereen verwarmde het eigen huis op zijn eigen wijze. Men vervoerde zich met het paard en het leven van gezinnen was vaak afhankelijk van dat paard. ’s Avonds was het donker op straat. De gezondheidszorg was vooral homeopathisch van aard en op kruiden gericht. Maar zo vanaf 1870 gebeurt er veel in Amerika en begint een speciale eeuw die het leven van mensen totaal gaat veranderen. De levensstandaard gaat als nooit tevoren omhoog en het karakter van de samenleving past zich aan. In jouw formidabele (iets anders kan ik er niet tegen jou over zeggen)**‘The Rise and Fall of American Growth’** laat jij zien hoe met de vele grote uitvindingen en innovaties dat leven in honderd jaar totaal verandert. Nooit eerder was er zo’n economische ontwikkeling en het is volgens jou ook maar zeer de vraag of dit ooit nog weer zal gebeuren. Jij bent macro-econoom en economisch historicus en werkt aan de Northwestern University en de ideale persoon om deze geschiedenis te schrijven. Jij ziet de sterke economische groei als een eenmalige en unieke gebeurtenis die aan het einde van de negentiende eeuw start, vooral zichtbaar wordt in de periode 1920-1970 en die daarna weer afvlakt. 



Maar waarom is die eeuw zo speciaal? Volgens jou vinden er vanaf 1870 op heel veel terreinen tegelijkertijd veranderingen plaats. Steden worden met spoorlijnen met elkaar verbonden. Door de telegraaf kunnen kranten op de dag zelf over nationale en internationale gebeurtenissen rapporteren. Steden en huizen worden van elektriciteit voorzien en worden ook op andere wijzen aan elkaar gekoppeld via gas, telefoon, riolering en lopend water; het begin van de netwerksamenleving. Het eetpatroon wordt aangepast en de voedselproductie verandert. Kleren worden minder in huis gemaakt maar meer in fabrieken en vervolgens in winkels verkocht. Het paard verdwijnt langzaam uit het straatbeeld en maakt plaats voor motorische voertuigen. Het plezier en de verbeelding veranderen met de komst van de fotografie, de muziek, de radio en de film. Mensen gaan korter werken en maken bij de uitvoering van zwaar werk gebruik van hulpmiddelen. Steeds meer mensen gaan in een stad wonen en daar zijn in 1940 elektriciteit en water- en rioolverbindingen al heel gewoon en bijna de helft van de huishoudens heeft daar dan al een wasmachine en koelkast. De huizen worden kleiner en efficiënter ingericht, krijgen een douche en binnen een wc, worden centraal verwarmd en voorzien van elektrische apparaten. De bungalow doet zijn intrede. Het transport en het vervoer gaat sneller en sneller. De auto komt er en wegen worden aangelegd. Alles rondom informatie, communicatie en vermaak verandert in deze periode. Het postsysteem wordt opgezet en telefoonlijnen aangelegd. De levensverwachting van mensen stijgt snel, zeker omdat het percentage kindersterfte sterk afneemt en de kennis over gezondheid toeneemt. De invloed van voedsel, schoon water, riolering en dergelijke op gezondheid wordt blootgelegd en het gezondheidssysteem met ziekenhuizen en technologieën verandert. Bacteriële ziektes worden aangepakt. Kinderarbeid neemt af en de arbeidsomstandigheden verbeteren. Mensen kunnen hypotheken krijgen, kunnen zich tegen risico’s verzekeren en er komt sociale wetgeving. Het leven van 1870 kunnen we ons nu nauwelijks nog echt goed voorstellen. Maar het dagelijks leven van veel mensen in 1940 lijkt voor een groot deel op het leven zoals wij dat nu nog kennen. Jij maakt duidelijk dat kwaliteit van het leven misschien nog wel meer toeneemt dan de economische opbrengst. Jij maakt ook duidelijk dat Amerika internationaal voorop loopt waar het ontdekkingen, innovaties en vooruitgang na 1870 betreft. 
In de periode na de WOII gaat alles in een economische stroomversnelling. Niet iedereen kon in het eerste deel van de speciale eeuw aan alle ontwikkelingen meedoen; zeker niet mensen in het landelijk zuiden, de armere mensen en grote delen van de zwarte bevolking. De economische ontwikkeling zal zich verder verbreden en er komen ook weer nieuwe ontwikkelingen bij waardoor alles nog weer wat sneller gaat. De modernisering van Amerika wordt verder voortgedreven door de auto die op grote schaal gebruikt gaat worden. Dan komen de airconditioning, de snelwegen, het fastfood en de antibiotica. Het commerciële luchtverkeer komt op gang en, bovenal, komt de televisie in iedere huiskamer te staan, halverwege de jaren zeventig ook nog in kleur. Na 1970 stagneert de groei en ontwikkelingen vinden al lang niet meer overal plaats. De publieke gezondheidzorg (waar zoveel gezondheidswinst mee gemaakt is) maakt na 1970 plaats voor meer specialistische gezondheidszorg, waarvan de kosten enorm zullen toenemen. Grote veranderingen vinden alleen plaats op het terrein van informatie, communicatie en vermaak. De digitale media personaliseren en fragmenteren dan alles ook nog eens vanaf de jaren negentig met de I-pod, de computer, het internet en de diverse websites. De sociale media verbinden mensen nog verder met elkaar. Rond het jaar 2000 is er dan nog een kleine economische opleving te bemerken, maar die is tijdelijk van aard. 


Waarom, vraag jij je af, neemt het succes na de zeventiger jaren dan af? De innovaties gaan dan nog wel verder door maar vinden, misschien wel anders dan we vaak denken, op beperktere gebieden plaats. Dus wel op het gebied van informatie, communicatie en vermaak maar veel minder op het gebied van voedsel, kleding, elektronische apparaten, huisvesting, transport, gezondheid, onderwijs en arbeidsomstandigheden. Dan mogen bijvoorbeeld al die ICT en 3D-ontwikkelaars van tegenwoordig nog wel optimistisch aankijken tegen de toekomst, jijzelf bent daar veel gereserveerder over dan die techno-optimisten. Allicht dat jouw pessimisme hier doorschiet en dat je deze ontwikkelingen onderschat. Jouw verdienste zit er vooral in dat jij zichtbaar maakt dat innovatieve kracht in de breedte zit. Die brede blik verliezen we tegenwoordig nogal eens uit het oog. Maar hoe belangrijk innovatie voor jou ook is, er zijn tegenwoordig andere maatschappelijke ontwikkelingen die volgens jou ook een negatieve invloed hebben op economische groei. Zo heeft die huidige samenleving te maken met een sterke toename van sociale en economische ongelijkheid, ook binnen het onderwijs waar bovendien schooluitval toeneemt. Dan zijn er nog demografische ontwikkelingen waar we de komende tijd mee te maken hebben en die er toe leiden dat de arbeidsparticipatie verder zal afnemen. In Amerika neemt de staatsschuld steeds verder toe. En dan heb je nog de belabberde sociale situatie waar bepaalde groepen aan de onderkant van de Amerikaanse samenleving mee te maken hebben. Naast de verenging van de innovatieve kracht zorgen deze zaken voor tegenwind in de Amerikaanse samenleving en tezamen zorgen ze ervoor dat de economische groei afneemt. Jij doet hier nog wel een aantal concrete voorstellen maar hier ligt niet de kracht van jouw boek. Het boek lezen was voor mij een groot genot, waarschijnlijk ook omdat ik verschillende veranderingen zelf heb mee gemaakt. Daar ben ik oud genoeg voor. Ik heb de melk- en schillenboer nog met het paard zien rondrijden, bij mijn oma moest ik nog buiten naar de wc en als jongetje moest ik in de winter een paar keer per week kolen scheppen. Ik heb de tv en de kleuren-tv, de centrale verwarming en de wasmachine zien komen. Begin jaren tachtig zag ik de computer op het secretariaat binnen komen en volg allerlei digitale ontwikkelingen van tegenwoordig. Jij maakt mij duidelijk dat economische indicatoren zoals het bruto nationaal product te beperkt zijn om economische ontwikkelingen te begrijpen, laat staan de kwaliteit van leven en de levensstandaard vast te stellen en te vergelijken. Jij laat ons, lezers, helemaal om ons heen kijken en maakt ons vooral duidelijk dat om te zien waar je staat je moet weten waar je vandaan komt.

Dank je wel.

Grote groet, -Harrie

Gordon, R.J. (2016). **The rise and fall of American growth. The U.S. standard of living since the civil war**. Princeton and Oxford: Princeton University Press, 762 pag., €47,95.

