# DE WERELD IN EEN ZANDKORREL


Amsterdam, september 2016

Beste Kritina Rizga,

In *‘De grote vlucht inwaarts. Essays over cultuur in een onoverzichtelijke cultuur’*  onderstreept de Groningse cultuurfilosoof Thijs Lijster nog eens wat we allemaal wel weten en voelen: de wereld is complex en onoverzichtelijk geworden. Over heel weinig hebben we controle en allicht daarom sluiten we ons af van die grote en boze buitenwereld die we als een natuurgegeven zijn gaan beschouwen. Het enige wat we kunnen doen is naar binnen keren en vasthouden aan wat we nog wel in eigen hand denken te hebben: de gezellige huiskamer, onze spirituele huishouding en de lokale tradities en gewoonten. De wereld is verinnerlijkt en de grote slachtoffers van deze beweging zijn de sociale kritiek en de geschiedenis. Vergezichten en het geheel zijn in de ban gedaan en hebben plaats gemaakt voor verscheidenheid en verschillen. Als je een beetje filosoof van naam was de laatste decennia kondigde je wel ergens het einde van aan: Foucault kondigde het einde van de mens aan, Barthes van de auteur, Daniel Bell van de ideologie, Fukuyama van de geschiedenis en Lyotard van het grote verhaal. Niets mocht en kon meer allesomvattend worden beschreven. Maar een ander samenhangend licht werpen op zaken was daarmee ook verdwenen en dat laat ook een leegte achter. Daarom pleit Lijster in het verlengde van René Boomkens voor sterke verhalen die dan, misschien niet meer alles en totaal omvattend zijn, maar die wel degelijk eenheid aanbrengen in dat wat voor anderen nog onoverzichtelijk en onsamenhangend is. Eigenlijk gaat het volgens Lijster erom de wereld in een zandkorrel te zien, zoals William Blake dat ooit zo mooi omschreef. Tegenover het vooruitgangsgeloof en het pessimisme plaatst hij sterke verhalen; verhalen die kritisch zijn tegenover het bestaande en mensen uitdagen ook zo’n houding aan te nemen, die het denkbeeldige naar voren halen en waarbij schrijvers niet bang zijn voor de consequenties en conflicten met het bestaande.


Aan sterke verhalen moest ik denken toen ik jouw nieuwe boek las: *‘Mission high. One school, how experts tried to fail it, and the students and teachers who made it triumph’*. In dat boek stel je de op zich simpele vraag waarom het voor het rijkste en machtigste land van de wereld (jouw Amerika) zo moeilijk is om goede scholen te bouwen in iedere buurt? Je vraagt je af waarom jouw vrienden hun kinderen naar scholen aan buitenkant van San Fransico sturen of, zelfs, om die reden verhuizen. Is het niet mogelijk om binnen enkele maanden op die simpele vraag een antwoord te vinden. Je bent journalist en de hoofdredacteur van het tijdschrift waarvoor je werkt, adviseert jou om een school te zoeken waar jij je kunt verdiepen in de levens van studenten en docenten. Het kost jouw maanden om zo’n school te vinden en uiteindelijk vind je zo’n school en begin je in 2009 met jouw onderzoek. Maar die enkele maanden worden uiteindelijk toch een dikke vier jaar. 
De Mission High-school is de oudste openbare voortgezet onderwijs school van San Fransico, in 1890 opgezet. Er hebben bekende personen opgezeten zoals Maya Angelou en Carlos Santana. De school maakt in haar bestaan de hele Amerikaanse onderwijsgeschiedenis mee. In de beginjaren natuurlijk de meer kindgerichte benadering waar John Dewey zich hard voor maakte. Dan vanaf eind jaren vijftig wordt er voorzichtig een begin gemaakt met de afbraak van de segregatie toen duidelijk werd dat de samenleving meer talenten nodig had tot en met de toets- en afrekencultuur die er kwam vanuit de hoop dat de toetsen van taal en rekenen zicht geven op de toekomst van kinderen. In het jaar dat jij jouw onderzoek afrondt (2014) zitten er nog 950 studenten op, met name zwarte en Spaanstalige leerlingen. 75% van deze leerlingen leeft in armoede en voor slechts 38% van hen is Engels de eerste taal. Wanneer je met jouw onderzoek begint scoort de Mission High school bijzonder laag op de officiële lijstjes en behoort het tot de 5% laagste scorende scholen van Amerika. Daarom staat de school onder grote maatschappelijke druk, zoals zoveel van deze Amerikaanse scholen: moet de school gesloten worden, de directeur worden vervangen of de helft van het personeel worden ontslagen? Maar er zijn andere lijstje waaruit een heel ander verhaal spreekt: 84% van de leerlingen wordt op vervolgopleidingen aangenomen, 89% van de leerlingen vindt deze school goed, het slagingspercentage van het zwarte deel van de studenten is 20% hoger en van hen stroomt 14% meer door. Het niveau, het slagings- en aanwezigheidspercentages van leerlingen zijn gestegen en het schorsingspercentage nam sterk af. 
Jij laat in jouw boek zien hoe studenten en docenten het dagelijkse leven op zo’n school vormgeven. Daarvoor portretteert je de studente Maria die het geweld in El Salvador ontvlucht en op de school langzaam vertrouwen krijgt in zichzelf, leert schrijven en zich op school thuis gaat voelen; de Chinese student George die naar Amerika komt om zijn Engels te verbeteren en om met verschillen te leren omgaan en er dan achter komt dat dat allemaal niet zo makkelijk is maar toch leert om vragen te stellen, mee te doen aan discussies en werk durft te laten zien aan medeleerlingen; Pablo uit Guatemala die er achter komt dat hij homo is, daar een tijd mee zit maar op deze school een omgeving vindt die hem ruimte en mogelijkheden biedt dit een plaats te geven; de Afrikaans Amerikaanse Jesmyn die door haar moeder wordt opgevoed in de armste en gewelddadigste buurt van San Fransico en zich weet op te werken tot leerkracht, maar voor wie het leven uiteindelijk te veel is. Maar in jouw boek komt ook een groep docenten aan het woord waaronder Mr Roth, de oude activist die geschiedenis geeft en die er in slaagt om het onderwijs op school te verbinden met waar kinderen vandaan komen; Mr. Hsu, de wiskunde leraar, die kinderen niet alleen leert rekenen maar hen ook verbanden, patronen en strategieën leert zien; en Ms McKansey, de zwarte lerares die de leerlingen leert schrijven en die haar eigen passie overbrengt en dagelijks laat zien dat hetzelfde doel heel verschillend kan worden bereikt. Rizga portretteert ook Mr. Guthartez, de directeur van de school die er in slaagt om een positieve schoolcultuur te creëren en laat zien dat stabiliteit en continuïteit zo belangrijk zijn voor deze kinderen met deze ingewikkelde achtergronden. 


Volgens jou kan de democratie en de economie niet functioneren zonder openbare scholen die toegankelijk en voor iedereen goed zijn. Maar het is duidelijk dat de scholen niet goed zijn wanneer je zwart of spaanstalig bent. Amerika moet hier beter mee om leren gaan en deze talenten weten aan te spreken. Maar wat kan er dan volgens jou gedaan worden? Bij goed onderwijs gaat het om enkele zaken: kritisch denken, intrinsieke motivatie, veerkracht, zelfmanagement, vindingrijkheid en sociale vaardigheden. Die zijn niet met statistische maten en computer algoritmen vast te pakken. Lang dacht jij dat goed onderwijs zich moet baseren op wetenschappelijke inzichten, op wat er in bepaalde landen gebeurt en dat het meest te leren is van hoogscorende scholen met vergelijkbare achtergronden. Maar nu kijk jij er anders tegen aan en vind je dat de gestandaardiseerde wijze van toetsen leidt tot eenvormige instructie en nauwelijks vast kan stellen wat individuele kinderen kunnen en wat hun motivaties zijn. Goede docenten weten wat individuele kinderen nodig hebben, wat hen interesseert en welke uitdagingen ze nodig hebben. Scholen moeten daarom volgens jou op zoek gaan naar nieuwe ideeën en leren van anderen. Bruikbare kennis van buiten moet worden getoetst in het dagelijkse proces met individuele en collectieve elementen. De grote jongens en snelle meisjes van Amerika hebben grootse plannen met de toekomst van het Amerikaanse onderwijs. Zij hebben het hoogste woord in de discussie. Maar in dat land, zo stel je subtiel vast, gaan er iedere dag zo’n 50 miljoen studenten naar school onder begeleiding van 3 miljoen leraren. Hun stemmen hoor je nauwelijks. Jij hoopt dat hun inzichten en expertise onze verbeelding zullen versterken en ons laten nadenken over wat die kwaliteit van onderwijs precies inhoudt. Jouw verhaal over de Mission High is een sterk verhaal. Jouw verhaal over de Mission High-school is zo’n zandkorrel waar een hele wereld in is te kennen. 

Dank je wel,

Grote groet, -Harrie

Rizga, K. (2015). *Mission High. One school, how experts tried to fail it, and the students and teachers who made it triumph.* New York: Nation Books. 320 pagina’s, Eur: 24,50
