# KANSEN EN KLASSEN


Amsterdam, oktober 2017


Beste Paul de Beer, Maisha van Pinxteren en anderen,

Michael Young was een bekend onderwijssocioloog en sociaal entrepeneur. Hij was nog erg jong toen hij vlak na de Tweede Wereldoorlog *‘Facing the future’* schreef, het politieke programma waarmee Labour in Engeland de Conservatieven onder leiding van Winston Churchill zou verslaan. Het vormde de politieke basis voor dat beroemde kabinet dat onder leiding van Attlee de Engelse verzorgingsstaat zou opbouwen en waarmee het ook andere landen inspireerde. Michael Young zou verschillende boeken schrijven en werkte mee aan de opbouw van talloze Engelse en internationale organisaties waaronder bijvoorbeeld zijn eigen Centre for Community Studies, de Engelse Consumentenbond en de Open University. Maar bekend werd hij vooral met zijn boek *‘The Rise of the Meritocracy’* uit 1958. Het is een satirisch boek waarin hij vanuit het jaar 2033 en het perspectief van een meritocratische apostel terugkijkt op de hele periode vanaf 1870. In die periode worden de kansen niet meer zozeer zoals daarvoor verdeeld op basis van afkomst maar op basis van verdienste. Verschillen tussen mensen worden op basis van het meritocratisch principe vastgesteld (‘je verdient het want jij kunt het en hebt er hard voor gewerkt’). Het onderwijs is er vooral voor de kinderen die het verdienen. Van de kinderen die het niet goed kunnen of er met de pet naar gooien wordt verwacht dat ze het onderwijs zo snel mogelijk verlaten. De wetenschap ondersteunt bij het soepel verlopen van dat selectieprincipe en weet de verschillen op steeds jongere leeftijd te detecteren. De competitie ligt er op een zo’n jong mogelijk moment en daarna zijn de kaarten geschut. De sociale positie die iemand inneemt wordt gelegitimeerd door intelligentie en inspanning. Maar met de nieuwe verdeling van de kansen groeien klassen steeds verder uit elkaar en de sociale situatie eindigt dan in 2033 in een revolte waarin de verteller, zo lezen we in een voetnoot, wordt vermoord.


Ook in Nederland wordt na de Tweede Wereldoorlog expliciet afstand genomen van het op afkomst gebaseerde onderwijssysteem en gaat het meer en meer om de talenten van individuen. Anders dan in Michael Youngs dystopie wordt het meritocratisch principe, zoals in vele landen, een maatschappelijk ideaal. Over dat principe en die Nederlandse samenleving schreven jullie (Paul, Maisha en de veertien anderen) een bijzonder interessant boek: ‘Meritocratie. Op weg naar een nieuwe klassensamenleving?’. Het meritocratisch principe kan als een doelmatig principe worden gezien omdat zo iedereen op de plek terecht komt die bij hem of haar past en de samenleving daarmee de mensen krijgt die het op verschillende posities nodig heeft. Het is ook een rechtvaardig principe omdat iedereen gelijke kansen heeft om zijn of haar talenten te ontwikkelen. Kunnen we, zo vragen jullie je af, zestig jaar later ook zeggen dat de kansen in Nederland eerlijker verdeeld worden en de sociale afkomst (maar ook etniciteit en sekse) daarbij niet meer leidend is? Verdienste is intelligentie en inspanning en is met onderzoek niet makkelijk ‘te pakken’. Dat kan alleen op basis van het opleidingsniveau van jongeren en hoe dat de onderwijsloopbaan en het maatschappelijk succes vervolgens beïnvloedt. Dat is waar jullie naar kijken. De maatschappij stond zelf natuurlijk ook niet stil. Zo was er in deze jaren sprake van expansie van het onderwijs, upgrading van de beroepenstructuur en emancipatie van de vrouw die op zich ook zelf weer interacteren met het meritocratisch principe. Jullie kijken aan de ene kant naar de rol van het onderwijs en de opvoeding en stellen je de vraag of iemands persoonlijke capaciteiten veelmeer de toekomst zijn gaan bepalen dan sociale afkomst. Hier laten jullie zien dat jongeren steeds meer aan het onderwijs deelnemen en dat onderwijs en opleiding voor het verwerven van een maatschappelijke positie belangrijk zijn geworden. Dat is echter al decennia lang het geval. Wel is het zo dat steeds meer jongeren aan het onderwijs deelnemen en dat de waarde van het diploma is afgenomen. Hier valt verder op dat het niet zozeer meer de sociaal economische positie van vader is die de onderwijsloopbaan bepaalt maar meer het opleidingsniveau van de ouders. Die ouders spelen met hun hulpbronnen en culturele capaciteiten over langere tijd een ondersteunende en constante rol hierbij.
Aan de andere kant kijken jullie naar de vraag of de maatschappelijke positie ook daadwerkelijk wordt bepaald door de individuele verdienste. Je mag verwachten dat in onze moderne samenleving het opleidingsniveau belangrijker is geworden voor de positie op de arbeidsmarkt. Dat kunnen jullie niet overduidelijk aantonen. Veel hoger opgeleiden werken onder het niveau. Wel is het risico op werkloosheid voor lager opgeleiden duidelijk groter. Daarnaast zijn er andere factoren die de positie op de arbeidsmarkt bepalen, zoals de samenstelling van het huishouden en de etnische achtergronden. Alleenstaanden, alleenstaande ouders en niet-westerse allochtonen lopen een hoger risico op werkloosheid, hebben een lager onderwijsniveau en werken vaker in onzekere, flexibele arbeidscontracten. Bij de verdeling van kansen lijken niet-cognitieve vaardigheden (sociale en communicatieve vaardigheden) een rol te spelen. De sociale achtergrond van de ouders lijkt, naast het opleidingsniveau, nog een steeds een eigen en constante rol te spelen in de uiteindelijke maatschappelijke positie van mensen. Enkele andere zaken vallen in die tegenwoordige samenleving ook nog op. In het algemeen wordt het meritocratisch principe door mensen als rechtvaardig ervaren. In het politieke domein (zoals Eerste en Tweede Kamer, maar ook in gemeenteraden en onder wethouders)zitten tegenwoordig personen die hoger zijn opgeleid. Jullie stellen vast dat de politiek elite uit de hoge lagen is vervangen door de universitaire geschoolde middenklasse en dat er sprake is van een diplomademocratie. Aan de onderkant van de meritocratische samenleving, waar de verliezers zitten zoals de langdurige werklozen, wordt het meritocratisch principe ook onderschreven. Jullie stellen het systeem niet ter discussie maar zoeken een excuus waarom het hen niet is gelukt.


Aan het einde van het boek vragen jullie je af wat dit betekent en wat het beleid zou kunnen doen? Allereerst zouden, volgens jullie, de kinderen met sociale achterstanden vanaf jonge leeftijd binnen schoolse en buitenschoolse omgevingen op materieel, cultureel en sociaal terrein moeten worden ondersteund. Daar waar kinderen het niet van huis uit mee krijgen, zou er van hogerhand steun moeten worden geboden. Keuze voor het vervolgonderwijs zou weer meer naar wat latere leeftijd moeten worden verplaatst omdat sommige kinderen gewoon meer tijd nodig hebben. Niet-cognitieve vaardigheden, zeker voor kinderen uit zwakkere sociale milieus, verdienen meer aandacht. Op de arbeidsmarkt verdient levenslang leren aandacht evenals het aanleren van niet-cognitieve vaardigheden. Misschien, zo schrijven jullie, is het onvermijdelijk dat verschillen samenhangen met het opleidingsniveau van kinderen. Maar die verschillen (met name belonings- en inkomensverschillen) hoeven dan weer niet zo groot te zijn. Die verschillen zijn ook op de arbeidsmarkt te bemerken zoals kans op werk en de onzekerheid van werk. Op bepaalde momenten moeten we ook weer niet te sterk de nadruk leggen op opleiding omdat bepaalde groepen mensen niet aan de gestelde eisen kunnen voldoen. 
En toen was ik weer terug bij Young zelf. Kort voor zijn dood in 2002 en tijdens de hoogtijdagen van Tony Blair bracht Michael Young in The Guardian in zijn artikel *‘Down with Meritocracy’* nogmaals in herinnering dat zijn boek toch echt als satire en waarschuwing was bedoeld en niet zozeer als ideaal. Hij zegt in dat artikel dat veel van het boek meer dan veertig jaren na dato waren uitgekomen: de onderklasse staat met lege handen en zonder perspectief en de leiders zijn rijker en rijker geworden en lijken verder af te staan van de mensen waarvoor ze zeggen op te komen. Bij Michael Young gaat het om het tegengaan van ongelijkheid, versterken van lokaal beleid, betrekken van mensen bij de politiek en het verheffen van alle jongeren. Het wij is bij hem veel belangrijker dan het ik. Daar waar Young vooral kritisch was over de meritocratie, leggen jullie aan het einde van het boek de nadruk op het versterken van de meritocratie. De kritiek heeft bij jullie aandacht maar die kritiek had veel meer expliciete aandacht verdient. Bij het lezen van jullie lezenswaardig boek is het goed het werk in herinnering te roepen van deze sociale gigant: Michael Young, Lord of Dartington.
 
Beer, P. de & Pinxteren, M. van. (red., 2016). *Meritocratie. Op weg naar een nieuwe klassensamenleving?* Amsterdam: Amsterdam University Press, 253 pag., €29,95.

