# HET BELANG VAN MISSCHIEN EN IK ZOU DENKEN denken


Amsterdam, november 2017


Beste Richard Sennett,

De solidariteit met mensen die hetzelfde zijn lijkt verder toe te nemen en de verschillen met mensen die anders zijn lijken alsmaar toe te nemen. Mensen in de westerse wereld trekken zich op eilanden terug, lijken steeds meer moeite te hebben om op gelijke voet te komen met de ander en steeds meer is er sprake van wij tegenover zij. In jouw laatste boek, dat zojuist in een Nederlandse vertaling verscheen onder de titel *‘Samen, een pleidooi voor samenwerken en solidariteit’*, ben je heel duidelijk: in onze complexe samenleving kunnen we het ons niet veroorloven de ander steeds meer uit de weg gaan. Problemen die dit alles namelijk oplevert op het schoolplein, op de straat en in de media zijn zo groot dat we (weer) moeten leren om te gaan met die ander; wellevendheid zie jij als een maatschappelijke opdracht. Onze wereld is overvol met materiële zaken en op dat gebied maken we grootse ontwikkelingen door. De ontwikkelingen op het immateriële terrein, echter, blijven daar ver bij achter. We moeten beter leren omgaan met mensen die we misschien niet zo aardig vinden, die we niet helemaal begrijpen en die gewoon net iets anders zijn dan wijzelf. 
Grote praktische problemen waar we vandaag de dag tegenaan lopen brachten jou ertoe om een trilogie te schrijven over de ervaringen van het alledaagse. Jij omschrijft het zelf als een homo-faber project waarin je ingaat op vaardigheden die we nodig hebben om het beter met elkaar te rooien en weer meester worden over onszelf. Die trilogie begon met jouw studie ‘De Ambachtsman. De mens als maker’, een cultuurgeschiedenis over het werk. Daarin houdt jij een pleidooi houdt om werk goed te doen vanwege het werk en niet vanwege onszelf. De trilogie sluit jij straks af met een derde boek waaraan jij op dit moment werkt. Dat boek zal gaan over hoe steden zijn gebouwd en hoe met stedenbouw het leven van mensen is te verbeteren. Maar nu ligt jouw tweede deel hiervan voor, ‘Samen, een pleidooi voor samenwerken en solidariteit’, dat het vermogen van mensen om samen te werken wil vergroten.


Dit boek bestaat uit drie grote delen. In het eerste deel laat je zien hoe samenwerking vorm is gegeven in met name de linkse politiek. In Europa wilden de sterke Duitse vakbond, Kautsky, Lenin en alles wat daarmee was verbonden solidariteit vooral van boven af organiseren en alles was daarbij op het Grote Gelijk gericht. Het top-down denken leidde er op een gegeven moment toe dat de top zich langzaamaan steeds meer vervreemde van de basis. Hiertegenover is er de Amerikaanse bottom-up benadering met nadruk op de gemeenschap en de burgersamenleving. Hierbij denk je aan vrijwilligersorganisaties die in arme, stedelijke gebieden arbeiders onderwijs en perspectief bieden en aan opbouwwerkers die apathische armen in beweging proberen te krijgen en gemeenschapsbanden weten te verbeteren. Het gaat jou hier om bewegingen en personen die voortbouwden op het werk van Europese sociale hervormers als Robert Owen in Wales en Charles Fourier in Frankrijk. Voor jou is het duidelijk dat wij als soort alleen niet kunnen overleven. Wij zijn sociale dieren en daarom moeten we samenwerken, ook omdat de omgeving waarin we leven steeds verandert. Samenwerken doen we door geven en nemen en vergelijken en tegen elkaar afzetten. Zo geven wij onze ervaringen op bepaalde manieren vorm. Rituelen spelen mee bij het omgaan met verschillen. 
Maar in de moderne tijd vinden er veranderingen plaats in de cultuur, het werk en het dagelijkse leven waardoor samenwerking minder open, minder dialogisch is geworden en daarmee problematischer. In het tweede deel laat je dan zien hoe samenwerking tegenwoordig wordt verzwakt. Allereerst is er de ondermijnende invloed van ongelijkheid die kinderen die opgroeien asocialer maakt. Gevoelens van inferioriteit worden geïnternaliseerd en de ongelijkheid laat bepaalde groepen denken dat ze het toch niet ver zullen schoppen op school en de samenleving. Dan zijn er ook de sociale relaties op het werk die onze houding verder verzuren. Informele relaties op het werk waren lange tijd sterk. Dat kwam omdat de arbeiders respect hadden voor nette werkgevers en de werkgevers op hun beurt voor betrouwbare werknemers. Problemen werden onderling besproken en als het erop aan kwam werden tijdelijke en acute problemen aangepakt. Het werk werd zo van drie kanten sociaal ondersteund en gaf vorm aan gestandaardiseerde of informele wellevendheid. Dit werk veranderde de laatste decennia in ons ‘durfkapitalisme’ en onze ‘kortetermijneconomie’. Van die verandering profiteerde de top wel maar niet de gewone arbeiders, nu autoriteit, vertrouwen en samenwerking zijn ondermijnd. Door structurele ongelijkheid en verandering op het werk ontstond er een mens die niet goed meer kan omgaan met de complexiteit van het systeem en die zich individueel terugtrekt. En wanneer de sociale orde dan ook nog zwak is georganiseerd trekken mensen zich verder in zichzelf terug. Zo krijgen we mensen die bang zijn om met de ander om te gaan en dat zorgt voor narcisme en zelfgenoegzaamheid, individualisme en onverschilligheid. Dat zorgt er vervolgens weer voor dat mensen problemen van hun eigen mensen wel vanzelfsprekend vinden en dat de problemen van de anderen jou niet zoveel kunnen schelen. Jij schetst een donker beeld.
Als samenwerking kan worden verzwakt kan deze ook weer worden versterkt. Hier ben je weer optimistisch en daaraan besteed jij in het derde deel aandacht. De moderne samenleving is, volgens jou, aan flink herstel toe en daarbij heb je vooral oog voor het herstellen van de samenwerking. Hoe maken wij ons dat weer eigen en waar kunnen we van leren? Als musicus haal jij veel inspiratie uit de wereld van muziek. Om daarin verder te komen is het belangrijk dat je veel oefent, dat je naar elkaar luistert en je je openstelt voor de ander. Er zijn meer voorbeelden waar we veel van kunnen leren wat samenwerken betreft. Van arbeidsconsulenten, bijvoorbeeld, die de moeilijke taak hebben om langdurige werklozen, die een teruggetrokken leven leiden, angstig zijn of schaamte kennen, weer aan het werk te krijgen. In situaties waarmee deze consulenten worden geconfronteerd helpt sympathie en meevoelen niet. Het helpt wel als de emotionele temperatuur van de werkloze wordt verlaagd en zij weer aan het werk komen. Conflictmanagement, vergadertechnieken en professionele diplomatie zijn andere voorbeelden waar je uit put om van samenwerken te leren. Het gaat jou om vaardigheden waarmee grenzen worden verlegd, waarmee zorgen en belangen worden geherformuleerd, zaken open wordt gebroken, sociale distantie wordt gecreëerd en er een basis ontstaat om verder te gaan met de ander. 


Drie personen hebben jou als student beinvloed: David Riesman (bekend van zijn studie *‘The Lonely Crowd’* waarin hij laat zien hoe het karakter van de Amerikaan vlak na de WOII veranderd is en traditie en autonomie plaats hebben gemaakt voor het nadoen van ander), Erik Erikson (de moderne psycho-analyticus die over identiteit en identiteitscrises in verschillende levensfasen schreef) en Hannah Arendt (de grote filosofe van de twintigste eeuw die de moderne mens, het kwaad en totalitaire systemen analyseerde). Met zulke leermeesters kan het bijna niet meer misgaan. ‘Samen’ doet misschien wel het meest aan Hannah Ahrendts boek ‘The Human Condition’ denken dat gaat over het goede leven dat bestaat uit arbeid, werk en handelen. In de moderne tijd gaat het volgens Arendt steeds om consumeren, produceren en onze eigen wereld en steeds minder om de publieke zaak. Jijzelf bent minder filosofisch en abstract en meer praktisch. Ook jou gaat het om het goede leven, dat voor jou een leven met de ander is, en het ontwikkelen van een innerlijk levensdoel door middel van samenwerking. Samenwerking zie jij als een vaardigheid die we nodig hebben in deze tijd, een ambacht bijna, om dialogische relaties aan te gaan, ruimte te geven en te luisteren naar wat de ander wil zeggen en wat hij of zij nodig heeft. Wanneer je als lezer het boek uit hebt, roept het boek in eerste instantie ook irritatie op. Althans bij mij. Waarom houdt je de lijn niet meer vast, hadden die redacteuren jou niet meer op koers kunnen houden? Dat soort vragen. Als je het nog eens doorleest en ook jouw aanhangsel leest (‘Coda. De kat van Montaigne’) begrijp je jou beter. Het gaat je om de kunst van luisteren, op gezette tijden zwijgen en tact tonen. Net als Montaigne, jouw grote voorbeeld, wil je de lezer op dwaalsporen zetten, onderwerpen van onverwachte invalshoeken voorzien en er uiteindelijk een mozaïek van fragmenten van maken dat toch één geheel vormt. Net zoals Montaigne dat in zijn ‘Essays’ heeft gedaan. Montaigne kijkt tegen de ander aan zoals hij tegen zijn kat aankijkt: blij dat hij anders is en soms verwonderd over wat hij doet. Dat wil jij ook en die raadselachtigheid moeten we terug zien te krijgen. Nu gaat het niet zozeer om wat jij schrijft maar vooral om de aannames die je daarbij heeft. Als je dat als lezer doorhebt en als je zo naar jou luistert, spreekt dit boek bijzonder aan. Ik heb het boek net op tijd gelezen om het verkiezingsjaar 2017 aan te kunnen. Het maakt duidelijk dat samenwerking niet vanzelf komt maar uitgebreide ervaring en oefening vraagt. De kunst ook om misschien te zeggen en ik zou denken dat.     

Sennett, R. (2016). *Samen. Een pleidooi voor samenwerken en solidariteit.* Amsterdam: Meulenhoff, 399 pag., €24,99.

