# GRIT {-}


Amsterdam, december 2016


Beste Paul en Angela,

Zo nu en dan zijn er van die Engelse woorden die op de een of andere wijze een eigen leven gaan leiden. Jaren geleden was er plotseling het woord ‘flow’ dat werd geïntroduceerd door, en nu moet ik even goed opletten of ik het goed schrijf, Mihaly Csikszentmihalyi. Het gaat hier om een geestelijke toestand van iemand die volledig opgaat in zijn of haar bezigheid. De laatste jaren is er een nieuw woord dat steeds vaker opduikt, ook weer uit de hoek van de positieve psychologie, en dat we nog veel tegen zullen komen de komende tijd: ‘grit’. Let maar op. Het is zoiets als vastberadenheid, maar het Nederlandse woord is natuurlijk veel minder krachtig. 


Paul, jij bent een Amerikaanse publicist en schreef een paar jaar geleden *‘How Children Succeed: Grit, Curiosity and the Hidden Power of Character’*. Recent kwam jouw nieuwe boek uit onder de titel (hoe kan het anders, jij bent een Amerikaan): *‘Helping Children Succeed: What Works and Why?* Het is, schrijf je, duidelijk dat er een grote groep kinderen qua schoolresultaten en onderwijssucces achterblijft. Het gaat hier met name om kinderen uit de gezinnen met lagere sociale economische achtergronden. Onderwijzers hebben er vaak hun handen vol aan om, in ieder geval een deel van die jongeren, te motiveren en mee te krijgen in het dagelijkse onderwijsritme. We weten waarom bepaalde kinderen uitvallen maar veel minder goed weten we waarom bepaalde kinderen succes hebben. Hoe wordt succes behaald en langs welke lijnen loopt dit? Het onderzoek dat er naar gedaan is, heeft volgens jou duidelijk gemaakt dat de link naar succes niet zozeer in de cognitieve zaken en het leren zelf zit. Nee, het zit veel meer in niet-cognitieve zaken zoals weerbaarheid, optimisme, zelfcontrole en (dus dat ene woord) ‘grit’ (dat in het Nederlands misschien nog wel het beste met vastberadenheid is te vertalen). Het zijn deze kwaliteiten die het verschil maken en die in het onderwijs aan kinderen uit met name de sociaal zwakkere milieus zo essentieel zijn. Juist deze kinderen moeten leren omgaan met tegenslag en weten hoe ze hun ervaringen naar hun hand kunnen zetten. Juist voor deze kinderen zijn rustige, consistente en wederkerige interacties van het grootste belang voor de toekomst. Dat moeten ze vooral meekrijgen in hun vroege jaren aan de hand van hun ouders en opvoeders. Ook in voorschoolse en schoolse settings kunnen ze hun aandacht en concentratie leren te versterken en hun stress onder controle krijgen. Juist daarom moeten ouders en leerkrachten omgevingen vormen waar deze niet-cognitieve competenties, autonomie en verbondenheid worden ontwikkeld, waar kinderen grip krijgen op houdingen, percepties en representaties en daarmee op hun academische taken en gedrag. Kinderen en jongeren moeten over een langere tijd het gevoel krijgen dat ze erbij horen, dat hun inspanningen beloond worden, dat ze soms succes kunnen hebben en dat wat ze doen waarde heeft. 
Angela, jij bent een andere machinist van deze grit-trein die op dit moment door Amerika dendert. Ooit was je wiskundelerares en nu werk je als psychologe in de wetenschap. Al vroeg werd het jou duidelijk dat het IQ van een kind niet zo belangrijk is voor het succes van het kind. Succes heeft volgens jou veel meer met motivatie te maken en daar moet in het onderwijs meer aandacht voor komen. Uit jouw onderzoek naar succes in verschillende situaties kwam er één duidelijke voorspeller uit. Niet dus de sociaal economische situatie waarin kinderen opgroeien of de toets gegevens, nee, nee, het is ook volgens jou de ‘grit’, wat je definieert als passie en volharding. Oftewel, de wijze waarop je iedere dag en over langere tijd met je toekomst bezig bent en hard werken. Daarover weten we eigenlijk betrekkelijk weinig en het enige wat we weten is dat het verandert met inspanning. 


Het idee van de ‘grit’ slaat enorm aan in Amerika en krijgt heel veel aandacht op televisie en internet en in de kranten. Grote potten onderzoeksgeld gaan naar dit onderwerp toe. Het is natuurlijk ook een echt Amerikaans onderwerp waarin het maatschappelijk opklimmen verbonden wordt met hard werken, koers houden, doorzettingsvermogen en karaktervorming. Je hebt hierbij meteen die spijkerbroek en de opgestroopte mouwen voor ogen. Dat is op zich niet zo nieuw en misschien ook wel de basis van de Amerikaanse droom. Het perspectief dat jullie positieve psychologen (Paul en Angela) is natuurlijk heel anders dan dat van Robert Putnam. Putnam prikte vorige jaar die Amerikaanse droom nog door toen hij in ‘Our Kids’ heel duidelijk maakte dat van gelijkheid van onderwijskansen al heel lang geen sprake meer is in Amerika. De Amerikaanse samenleving is uit elkaar gedreven en twee groepen leven overduidelijk gescheiden van elkaar.   
Er is nog een andere opmerking te maken over ‘grit’ en dat is iets waar de onderwijsjournalist Paul Thomas ons onlangs terecht op heeft gewezen. Hij plaatst verschillende kritische kanttekeningen bij het nieuwe perspectief waar jullie, Paul en Angela, warm voor lopen. We moeten zo’n perspectief niet zomaar meteen met z’n allen omarmen en we moeten er op z’n minst en zeker in de beginfase een aantal vragen bijstellen. Grit wordt bijvoorbeeld gepresenteerd als een karaktertrek van de hogere orde met sterk voorspellende waarde naar zowel toekomstig maatschappelijk succes als schoolresultaten van kinderen. Maar onderzoek naar honderden effect-sizes in tientallen studies met tienduizenden individuen geeft vooralsnog toch een ander beeld van die effecten. De effecten die jullie (Paul en Angela) schetsen zijn helemaal niet zo duidelijk als jullie overtuigd in de media naar voren brengen. De verbanden liggen toch net wat anders. Vastberadenheid als karaktereigenschap lijkt veel meer op iets als zorgvuldigheid en dat is nu juist een karaktereigenschap die net wat moeilijker te veranderen is. Kortom, de wetenschappelijke basis waarop grit gebaseerd is en waar met name jij, Angela, naar refereert, lijkt vooralsnog dun. Daarom alleen al moeten we zo’n idee niet direct zomaar omarmen. We moeten er naar luisteren, we moeten er van leren en onderzoeken wat mogelijk is. Maar we moeten er vooral ook kritische vragen over blijven stellen. Zo’n kritische houding wordt tegenwoordig nogal eens gemist. Journalisten moeten niet bij één verhaal van een buitengewone school blijven steken, ze moeten wetenschappelijk onderzoek niet te simpel opvatten, ze moeten historische patronen herkennen, niet te optimistisch zijn over de mogelijkheden van het onderwijs, de invloed van de leraar niet overdrijven, niet alleen naar het individuele maar ook naar de maatschappelijke context kijken, mythen doorprikken, onderwijzers meer zelf aan het woord laten en de verbeelding laten spreken. Van journalisten mag en moet je vooral kritiek verwachten. Ook tegenover zo’n nieuw begrip als grit dat aantrekkelijk lijkt en waar zoveel mensen mee weglopen. Allicht moeten we vastberaden zijn om kinderen vastberaden te maken en daar van alles voor doen. Ook in Nederland. Maar we moeten ook vastberaden zijn en blijven om de goede vragen te blijven stellen, ook aan jullie, Paul en Angela.

Dank jullie wel.

Grote groet, -Harrie 

Tough, P. (2012). *How Children Succeed: Grit, Curiosity, and the Hidden Power of Character.* New York: Houghton Mofflin Harcourt Publishing Company.  pag., €,.

Tough, P. (2016). *Helping Children Succeed: What Works and Why.* New York: Houghton Mofflin Harcourt Publishing Company.  pag., €,.

Duckworth, A. (2016). Grit. The Power of Passion and Perseverance. New York: Scribner. pag., €,. 

