# DE OUDER ALS MEUBELMAKER OF TUINMAN


Amsterdam, januari 2017

Beste Alison Gopnik,


Jij moet een moedig persoon zijn. Over opvoeden zijn er alleen al bij Amazon 60.000 titels en toch heb je onlangs over dat onderwerp een boek geschreven. Je bent bekend geworden met boeken als *‘The scientist in the crib. What early learning tells us about the mind’* en *‘The Philosophical baby: what children’s minds tells us about truth, love, and the meaning of life’*. In die boeken laat je zien dat er grote overeenkomsten zijn tussen hoe wetenschappers en hoe jonge kinderen denken. In jouw laatste boek schrijf je over opvoeden en de rol van ouders daarbij. Misschien is dat boek niet zozeer vernieuwend, maar het zet je wel aan het denken. Ik heb het hier over *‘The gardener and the carpenter. What the new science of child development tells us about the relationship between parents and children’*. Jij bent in dat boek zeer kritisch over hoe ouders tegenwoordig kinderen opvoeden en hoe ze erover denken. ‘Parenting’ heet het in het Engels en dat is net wat specifieker dan opvoeden zoals wij het in Nederland noemen. Dat ‘parenting’ of opvoeden door ouders is volgens jou tegenwoordig een doelgerichte activiteit geworden, een soort werk dat kinderen beter, gelukkiger en succesvoller wil maken. Opvoeden is al lang niet meer alleen wat we doen met kinderen maar opvoeden schrijft vooral voor wat er moet gebeuren. Die doelgerichte benadering leidt er volgens jou toe dat we onze kinderen eindeloos met kinderen van onze vrienden vergelijken, kijken naar wat onze kinderen op school presteren en dat vergelijken met hoe andere kinderen het doen. We zijn niet met het nu maar vooral met de toekomst bezig. Als ouder willen we de laatste technieken toepassen en volgen we de aanwijzingen van diverse experts. We zijn alleen maar tevreden als we een goed uitgewerkt opvoedingsmodel kunnen toepassen en als onze opvoeding een bepaald resultaat oplevert. 


Jijzelf groeide op in de zestiger jaren, die gelukkige vijf minuten, zoals je dat zo mooi omschrijft, tussen de pil en AIDS. Jij maakte deel uit van die kritische generatie die nogal wat had op te merken over ouders die zelf vaak in de crisistijd waren opgevoed. Nu stel je, onder tussen zelf moeder en grootmoeder, dat jouw generatie (onze generatie) het er niet heel veel beter vanaf heeft gebracht. Volgens jou is de manier waarop we tegen opvoeden aankijken een verkeerde manier omdat die niet past bij wetenschappelijke inzichten die laten zien dat we het de kinderen veel meer op hun eigen manier moeten laten doen. Je hebt gelijk dat het ouders van tegenwoordig veel te weinig gaat om variatie, risico en innovatie en dat de opvoeding op die manier misschien wel te weinig aansluit bij het evolutionaire doel van de kindertijd. Kindertijd is vooral de tijd van exploratie, nieuwsgierigheid en spel en dat heb je nodig voorafgaand aan de fase van exploiteren, verantwoordelijkheid en werk. Wat er van elk kind wordt is onvoorspelbaar en uniek en het resultaat van vreemde combinaties van genen, ervaringen, cultuur en geluk. We moeten niet te snel een kind willen maken maar veelmeer liefde, veiligheid en stabiliteit bieden waarin kinderen op hun manier kunnen groeien. We kunnen nu één keer niet kinderen lerend maken, maar we kunnen ze wel laten leren. Ouderschap zie jij terecht als een belangrijk deel van de levenscyclus waarbij onze ouders ons het verleden gaven en wij op onze beurt de toekomst aan onze kinderen doorgeven. 
Meer dan bij welk ander levend soort ook zijn kinderen bij ons mensen lange tijd afhankelijk van opvoeders. Zelfs in vroegere tijden waren ze niet voor hun vijftiende zelfstandig. Kinderen waren daarbij niet alleen afhankelijk van hun eigen ouders maar ook van ‘allo-ouders’, het netwerk van grootouders, ooms, tantes, neven, nichten en vrienden. Alleen komen we als soort nergens en we ontwikkelen onszelf alleen in zo’n netwerk van zorg en liefde. Lange tijd groeiden kinderen op in uitgebreide families maar vandaag de dag is dat netwerk veel kleiner geworden. De opvoedingstaak ligt nu meer dan ooit bij de ouders, die zelf lange tijd naar school zijn geweest en al enige tijd werken voordat ze ouder zijn geworden. Op school en werk hebben ze zich dat doelgerichte, met de nadruk op kennis en competenties, eigen gemaakt. Op school en werk leidt dat natuurlijk tot succes. Maar in de opvoeding thuis is dat niet zozeer het geval. Ook lijkt het er op dat ouders van nu alleen maar oog voor het detail hebben. Ze stellen zichzelf vragen als hoe lang moeten ze hun kinderen moeten laten huilen, of de computer wel goed voor ze is en of ze wel lang genoeg huiswerk maken. De grote lijn lijken ze uit het oog te zijn verloren.


Van jouw boek heb ik veel geleerd. Als ontwikkelingspsycholoog bied je de lezer nieuwe inzichten, als filosoof lever je interessante dilemma’s en als ouder/grootouder laat je zien met welke concrete situaties je te maken hebt gehad. Opvoeden tegenwoordig, zo schrijf jij, lijkt misschien wel het meest op het werk van een meubelmaker. Er is ruim aandacht voor het juiste materiaal waarmee gewerkt wordt, voor de juiste bewerking en ouders willen net als de meubelmaker ervoor zorgen dat het juiste product wordt afgemaakt. In het proces gaat het om precisie en controle en chaos en verschil moeten zoveel mogelijk worden voorkomen. Maar jijzelf hebt veel op met het idee dat opvoeden als het zorgen voor een tuin is. Want als tuinman moet je de tuin beschermen en planten ruimte geven waar nodig. Je moet er veel voor doen maar het onverwachte is hier veel belangrijker. Net als de tuinman kun je als ouder niet alles voorspellen en variatie en wanorde lijken er hier wel degelijk toe te doen. Ik moet je eerlijk zeggen dat ik samen met mijn vrouw vaak in de tuin werk. Ik weet (en mijn vrouw nog veel beter) dat tuinieren wel degelijk doelgerichte kanten kent. Je moet soms dingen doen om een half jaar later bepaalde resultaten te bereiken. Niet alles maar wel voor een groot deel. Bovendien heb je hele verschillende tuinen. Natuurlijke tuinen en tuinen waar precisie en controle wel van afspatten. Je hebt Engelse tuinen en je hebt Franse tuinen. Kinderen waarvan de ontwikkeling in gevaar komt om welke redenen dan ook, zullen ondersteund moeten worden. Over hoe dat het beste kan en waar we rekening mee moeten houden moeten we na blijven denken. Dan doen we ook in de tuin als planten niet tot hun recht komen. Dat zullen we doelgericht moeten blijven doen en ik neem aan dat je die gedachte deelt. Met het vergelijken van opvoeden met houtbewerken aan de ene kant en tuinieren aan de andere kant kan ik niet helemaal met jou meekomen. Misschien, denk ik zelf, had je voor jouw boek veel beter de metafoor van het lange en avontuurlijke reizen met het aankomen als doel kunnen nemen, zoals Kavafis dat zo treffend in zijn beroemde gedicht ‘Ithaka’ beschrijft. De reis die vele jaren duurt maar rijk is aan wat je onderweg beleeft. Bij opvoeden gaat het om het aankomen maar veel meer nog om die mooie reis. Maar laat ik zelf ook de grote lijn van jouw boek in de gaten houden en het punt dat je maakt is terecht. 

Dank je wel, 

Grote groet, -Harrie

  

Gopnik, A.(2016). *The gardener and the carpenter. What the new science of child development tells us about the relationship between parents and children.* New York: Farrar, Strauss and Giroux, 320 pag., €22,16.


