# GRENZEN VERLEGGEN {-}


Amsterdam, februari 2017

Beste Julian Baggini,


Wij zijn ons verstand verloren en met die hartenkreet val je in jouw nieuwe boek meteen met de deur in huis. Was ons rede en rationaliteit meer dan 2000 jaar bijzonder dierbaar, tegenwoordig lijken die er minder toe te doen. Verschillende politici stellen openlijk de vraag of experts nog wel zo nodig zijn. Feiten zijn minder belangrijk dan emoties. Wij hebben, zo lijkt het, steeds minder vertrouwen in de rede. Wat maakt het allemaal nog uit. Het kapitalisme heeft veel van de menselijkheid weggenomen, we hebben Auschwitz gehad, veel wordt bepaald door onze genen en de grote multinationals doen toch wat ze niet laten kunnen. We volgen tegenwoordig ons hart en onze passie omdat we denken dat we daar nog greep op hebben. Over dat irrationele landschap maak jij je nogal zorgen. Jij vindt jezelf een geschikt persoon om hierover een boek te schrijven. Ik geloof dat je gelijk hebt. Je bent universitair geschoold en staat daarmee met één been in de wetenschap. Maar de standaard academische stijl die is jou te ‘high brow’, te precies en niet zelden rigide. Je voelt je de laatste jaren thuis buiten de universiteit waar je werkt als redacteur, journalist en schrijver. Zo sta je met het andere been in de samenleving. Je hebt de afgelopen jaren honderden wetenschappers geïnterviewd en weet maar al te goed als buitenstaander wat er in die wereld speelt. Je hebt je bezig gehouden met filosofie en religie. Jij overziet, zeg je zelf, het hele bos en niet, zoals wetenschappers zelf vaak, een boom, een enkele struik of zelfs een blad. In *‘The edge of reason. A rational skeptic in an irrational world’* vraag jij je af hoe het allemaal zo ver heeft kunnen komen met de rede en wat er moet gebeuren om die weer betekenis te geven.  



Sinds Plato is de rede altijd het hoogst haalbare geweest. De wereld is veel complexer geworden maar volgens jou kennen rede en rationaliteit vier uitgangspunten die terug te voeren zijn op Plato. Elk uitgangspunt zie jij als een mythe die volgens jou een voor een moet worden doorgeprikt. De eerste van de vier mythes, waar we nog steeds last van hebben, is de mythe dat subjectiviteit er in het vormen van een oordeel er niet toe doet. Rede zou eigenlijk altijd tot een bepaalde conclusie moeten leiden. Maar jij laat zien dat er altijd een subjectief element meespeelt. Op het hoogste niveau van de natuurwetenschap, bijvoorbeeld, is een klein groepje topwetenschappers het helemaal niet met elkaar eens over de centraal onderliggende theorie en kunnen niet tot een vergelijk komen hoe het in elkaar zit. Ook de tweede mythe is al duizenden jaren oud en houdt in dat de ziel zou worden voortgetrokken door twee paarden: het intellect of rede aan de ene kant en de emotie aan de andere kant. Als de rede maar de touwtjes in handen heeft, komt het goed. Maar die rede kan helemaal niet functioneren zonder die emotie en die onderlinge verbondenheid moet ook erkend worden. Het was ook Plato die met het idee kwam dat rationaliteit en rede ons op een goede manier aanzet tot handelen en het dan vanzelf wel tot het goede handelen leidt. Tot slot zou het volgens diezelfde goede, oude Plato goed zijn als in gemeenschappen filosofen koningen zouden zijn. Zover is het nooit gekomen maar de geschiedenis heeft wel overduidelijk gemaakt wat het betekent als er teveel vertrouwen is in objectieve waarheid en als systemen menen te weten hoe mensen zouden moeten leven. De geschiedenis heeft duidelijk gemaakt dat een rationele staat veel meer subtiliteit veronderstelt.   
Misschien moeten we wel erkennen dat de rede van de troon is gestoten juist omdat haar ster zo hoog was gerezen. Maar nu die zo in twijfel wordt getrokken, moet de positie ervan worden geherdefinieerd en opnieuw bezien. Die herdefiniëring is nodig omdat de rede en rationaliteit zijn gestrand in het mulle zand van populisme en postmodernisme. Om de kar weer aan het rijden te krijgen moeten we meer los komen van de harde, steriele wetenschappelijke kijk op de zaak die zo de boventoon die zo de boventoon voert. Volgens jou is het belangrijk dat de grenzen van de rede opnieuw worden vastgesteld en we meer oog hebben voor kritisch denken waar denken nodig is. Jijzelf plaatst diverse kanttekeningen bij rede en rationaliteit en je vraagt je inderdaad als lezer af, wat heb jijzelf nog met die rede: ben je niet veel te kritisch om die nog te kunnen verdedigen? Maar jij kijkt daar juist anders tegen aan. Juist omdat je zoveel met rede en rationaliteit op hebt, wil je snappen wat er scheelt. Jij vergelijkt jezelf met een topatleet. Die moet ook heel veel trainen en er voor zorgen dat zijn zwakke plekken aandacht krijgen. Volgens jou is het nodig dat intellectuelen en academici zelf ook nagaan denken over waar het bij rede en rationaliteit om moet gaan en welke vorm bij deze tijd past. Jij staat een sceptische houding ten opzicht van de rede voor en een bredere benadering dan die waar nu sprake van is. Het gaat jou om duidelijke en vanzelfsprekende principes, om duidelijke stappen die gezet kunnen worden, om het regelmatig herbezien van conclusies en het steeds onder ogen zien van de consequenties ervan. Dat betekent volgens jou per definitie dat we er heel langzaam op vooruit gaan, dat totale waarheid misschien wel nooit wordt bereikt, maar wel dat er een soort stabiliteit en zekerheid nodig is en dat in de basis duidelijk is waar we voor staan. Jij voelt je in deze zin erg thuis in de gedachtewereld van Hume, die ook vindt dat we de beperkingen van de rede moeten accepteren en dat er daarbij altijd een bepaalde graad van twijfel aanwezig moet zijn. Jij vindt dat we weer geloof moeten krijgen in de kracht en de reikwijdte van rationaliteit. Maar ook dat academici en intellectuelen zich weer verantwoordelijk gaan voelen voor dat rationele domein en ervoor zorgen dat we hierbinnen weer met elkaar kunnen discussiëren en argumenteren. Verschillen zullen en moeten er ook blijven als we het maar eens zijn over de gedeelde basis van de rationaliteit en die basis zelf niet teveel in twijfel trekken. 



In jouw boek heb je vooral ook voor het proces en hoe we met elkaar omgaan. Je geeft er zelfs een hele gids met 50 tips bij, die voor mij niet hadden gehoeven. Maar het belangrijkste voor jou is dat we weer kunnen schaatsen met elkaar ook al is het ijs dun. Wij hebben geen andere keuze. Als ik naar buiten kijk zie ik dat er vandaag een dun laagje ijs ligt op het water waar mijn woning ligt. Wat lijkt mij dat weer heerlijk, schaatsen. Misschien zijn we het met z’n allen wel een beetje verleerd. Met enkele aanwijzingen, zoals jij die in dit mooie boek geeft, moet dat toch weer lukken.  
 
Dank je wel.

Grote groet, -Harrie

Baggini, J.(2016). *The edge of reason. A rational skeptic in an irrational world.* New Heaven and London: Yale University Press. €18,10



Jijzelf groeide op in de zestiger jaren, die gelukkige vijf minuten, zoals je dat zo mooi omschrijft, tussen de pil en AIDS. Jij maakte deel uit van die kritische generatie die nogal wat had op te merken over ouders die zelf vaak in de crisistijd waren opgevoed. Nu stel je, onder tussen zelf moeder en grootmoeder, dat jouw generatie (onze generatie) het er niet heel veel beter vanaf heeft gebracht. Volgens jou is de manier waarop we tegen opvoeden aankijken een verkeerde manier omdat die niet past bij wetenschappelijke inzichten die laten zien dat we het de kinderen veel meer op hun eigen manier moeten laten doen. Je hebt gelijk dat het ouders van tegenwoordig veel te weinig gaat om variatie, risico en innovatie en dat de opvoeding op die manier misschien wel te weinig aansluit bij het evolutionaire doel van de kindertijd. Kindertijd is vooral de tijd van exploratie, nieuwsgierigheid en spel en dat heb je nodig voorafgaand aan de fase van exploiteren, verantwoordelijkheid en werk. Wat er van elk kind wordt is onvoorspelbaar en uniek en het resultaat van vreemde combinaties van genen, ervaringen, cultuur en geluk. We moeten niet te snel een kind willen maken maar veelmeer liefde, veiligheid en stabiliteit bieden waarin kinderen op hun manier kunnen groeien. We kunnen nu één keer niet kinderen lerend maken, maar we kunnen ze wel laten leren. Ouderschap zie jij terecht als een belangrijk deel van de levenscyclus waarbij onze ouders ons het verleden gaven en wij op onze beurt de toekomst aan onze kinderen doorgeven. 
Meer dan bij welk ander levend soort ook zijn kinderen bij ons mensen lange tijd afhankelijk van opvoeders. Zelfs in vroegere tijden waren ze niet voor hun vijftiende zelfstandig. Kinderen waren daarbij niet alleen afhankelijk van hun eigen ouders maar ook van ‘allo-ouders’, het netwerk van grootouders, ooms, tantes, neven, nichten en vrienden. Alleen komen we als soort nergens en we ontwikkelen onszelf alleen in zo’n netwerk van zorg en liefde. Lange tijd groeiden kinderen op in uitgebreide families maar vandaag de dag is dat netwerk veel kleiner geworden. De opvoedingstaak ligt nu meer dan ooit bij de ouders, die zelf lange tijd naar school zijn geweest en al enige tijd werken voordat ze ouder zijn geworden. Op school en werk hebben ze zich dat doelgerichte, met de nadruk op kennis en competenties, eigen gemaakt. Op school en werk leidt dat natuurlijk tot succes. Maar in de opvoeding thuis is dat niet zozeer het geval. Ook lijkt het er op dat ouders van nu alleen maar oog voor het detail hebben. Ze stellen zichzelf vragen als hoe lang moeten ze hun kinderen moeten laten huilen, of de computer wel goed voor ze is en of ze wel lang genoeg huiswerk maken. De grote lijn lijken ze uit het oog te zijn verloren.


Van jouw boek heb ik veel geleerd. Als ontwikkelingspsycholoog bied je de lezer nieuwe inzichten, als filosoof lever je interessante dilemma’s en als ouder/grootouder laat je zien met welke concrete situaties je te maken hebt gehad. Opvoeden tegenwoordig, zo schrijf jij, lijkt misschien wel het meest op het werk van een meubelmaker. Er is ruim aandacht voor het juiste materiaal waarmee gewerkt wordt, voor de juiste bewerking en ouders willen net als de meubelmaker ervoor zorgen dat het juiste product wordt afgemaakt. In het proces gaat het om precisie en controle en chaos en verschil moeten zoveel mogelijk worden voorkomen. Maar jijzelf hebt veel op met het idee dat opvoeden als het zorgen voor een tuin is. Want als tuinman moet je de tuin beschermen en planten ruimte geven waar nodig. Je moet er veel voor doen maar het onverwachte is hier veel belangrijker. Net als de tuinman kun je als ouder niet alles voorspellen en variatie en wanorde lijken er hier wel degelijk toe te doen. Ik moet je eerlijk zeggen dat ik samen met mijn vrouw vaak in de tuin werk. Ik weet (en mijn vrouw nog veel beter) dat tuinieren wel degelijk doelgerichte kanten kent. Je moet soms dingen doen om een half jaar later bepaalde resultaten te bereiken. Niet alles maar wel voor een groot deel. Bovendien heb je hele verschillende tuinen. Natuurlijke tuinen en tuinen waar precisie en controle wel van afspatten. Je hebt Engelse tuinen en je hebt Franse tuinen. Kinderen waarvan de ontwikkeling in gevaar komt om welke redenen dan ook, zullen ondersteund moeten worden. Over hoe dat het beste kan en waar we rekening mee moeten houden moeten we na blijven denken. Dan doen we ook in de tuin als planten niet tot hun recht komen. Dat zullen we doelgericht moeten blijven doen en ik neem aan dat je die gedachte deelt. Met het vergelijken van opvoeden met houtbewerken aan de ene kant en tuinieren aan de andere kant kan ik niet helemaal met jou meekomen. Misschien, denk ik zelf, had je voor jouw boek veel beter de metafoor van het lange en avontuurlijke reizen met het aankomen als doel kunnen nemen, zoals Kavafis dat zo treffend in zijn beroemde gedicht ‘Ithaka’ beschrijft. De reis die vele jaren duurt maar rijk is aan wat je onderweg beleeft. Bij opvoeden gaat het om het aankomen maar veel meer nog om die mooie reis. Maar laat ik zelf ook de grote lijn van jouw boek in de gaten houden en het punt dat je maakt is terecht. 

Dank je wel, 

Grote groet, -Harrie

  

Gopnik, A.(2016). *The gardener and the carpenter. What the new science of child development tells us about the relationship between parents and children.* New York: Farrar, Strauss and Giroux, 320 pag., €22,16.


