
# BRITS WERELDERFGOED {-}

Maart, 2017

Beste Helen Pearson,

Jij noemt de naoorlogse Britse cohortstudies (de vijf studies die er in jouw land sinds 1946 zijn opgezet om de ontwikkeling van het leven van gewone mensen van geboorte tot en met de dood te volgen) een juweel in de kroon van de Britse wetenschap. In ieder geval maak jij in *‘The Life Project. The extraordinary story of our ordinary lives’* wel heel duidelijk hoe uitzonderlijk deze studies zijn, welke schat aan inzichten en beleidsmaatregelen ze hebben opgeleverd en hoe ze duidelijke antwoorden geven op belangrijke vragen als waarom sommige mensen in het leven gelukkig, gezond en succesvol worden en dit voor anderen niet is weggelegd. Inderdaad, buitengewone studies van grote groepen hele gewone mensen. Veel wetenschappers hebben de levens van vijf generaties zorgvuldig gevolgd en dat heeft geleid tot terabytes data, tientallen boeken, duizenden artikelen, vriezers vol met DNA materiaal, dozen vol met nagels, babytandjes en zelfs opslag van duizenden placenta’s. Jij bent wetenschapsjournalist en de eindredacteur van het bekende blad *‘Nature’*. In 2010 las je voor het eerst over deze studies en in 2011 bezocht je een feestje van een van deze cohorten. Daarna was je niet meer te houden. In de vijf jaar erna werk je aan en beschrijf je heel zorgvuldig de geschiedenis van deze cohortstudies. Je bezoekt in die tijd talloze bibliotheken, laboratoria en onderzoekkelders en spreekt met genetici, economen, epidemiologen, sociale wetenschappers en statistici. Jouw verhaal is een verhaal geworden van overleven, van strijdvaardige en bijzondere wetenschappers die voortdurend hard vechten om hun studie overeind te houden en die met hun geloof, verbondenheid, eigenwijsheid, kennis, verbeelding en, toch ook wel, excentriciteit ervoor zorgen dat deze studies doorgezet worden. Jouw boek is een sociale en wetenschapsgeschiedenis tegelijkertijd en het lezen ervan, moet ik jou zeggen, deed mij heel veel plezier, niet in de laatste plaats vanwege jouw jaloersmakende schrijfstijl.



Jouw boek begint wanneer in 1946 een gek groepje wetenschappers alle informatie gaat verzamelen over de geboorte van elke Britse baby die er in een kille maartse week van dat jaar werd geboren en wanneer talloze verpleegsters op de fiets het land doortrekken. Het leven van duizenden van hen wordt sinds die eerste meting gevolgd en deze eerste Britse cohort hield vorig jaar zijn zeventigste verjaardag. Vergelijkbare cohorten worden daarna nogmaals uitgezet onder kinderen die in 1958 zijn geboren, in 1970, begin jaren negentig en in 2000 (millennium kinderen). In totaal worden er meer dan 70.000 kinderen op hun levenspad gevolgd. In de eerste jaren is er uiteraard veel aandacht voor vraagstukken die met de geboorte van kinderen te maken hebben. De eerste inzichten zijn schokkend toen duidelijk werd hoe sterk het land door klassen was verdeeld en de kindersterfte 70% hoger was onder kinderen van de werkende klasse. De inzichten leiden er in deze tijd toe dat ondersteuning rond de geboorte in het aanbod van de net opgerichte Nationale Health Service wordt opgenomen. Vanaf de jaren zestig wordt er steeds meer over het onderwijs gesproken. Er zou sprake zijn van het verlies van talent en dat kwam met name voor onder de arme kinderen. De cohortstudies brengen deze onderwijsachterstanden duidelijk aan het licht. Begin jaren zeventig wordt er nog volop gerookt in de westerse samenleving en roken was ondertussen als een duidelijke risicofactor voor ziekten en een verkorte levensduur gedetecteerd. Vanwege roken stierven volwassenen eerder, maar wat betekent dat roken voor kinderen? 40% van de zwangere vrouwen rookte begin jaren zeventig nog en de cohortstudies laten in deze jaren overduidelijk zien dat dit roken samenhangt met kindersterfte en lage geboortegewicht. Nadat de ergste naoorlogse armoede is weggewerkt en de mensen het weer wat beter krijgen, steken nieuwe ziekten de kop op. Obesitas en overgewicht nemen met de welvaart toe en de cohortstudies laten zien dat gewicht onder de verschillende cohorten tegelijkertijd sterk toeneemt. De leeftijden van de cohortdeelnemers nemen verder toe en nieuwe problemen steken de kop op. Zo wordt duidelijk gemaakt dat één op de drie ouders cognitieve vaardigheden heeft die op het niveau van elf-jarigen liggen. Talloze tests worden er onder deze volwassenen uitgezet om dit duidelijk te maken. De data zijn zo sterk dat er ook inzichten kunnen worden gegeven in de sociale mobiliteit en de intergenerationele overdracht ervan. De sociaal economische toekomst van kinderen die in de jaren zeventig zijn geboren is sterker aan die van hun ouders verbonden dan van kinderen die in de jaren vijftig zijn geboren. Ook maken de cohortstudies duidelijk hoe belangrijk de betrokkenheid van ouders in de eerste jaren is voor een succesvol leven. Ondertussen zijn de eerste cohortdeelnemers senior geworden en laat het zien met welke toename van stoornissen en ziekten deze groep ouderen te maken heeft. In jouw boek maak ik, aandachtige lezer, ook kennis met een groep hele bijzondere wetenschappers zoals Douglas, Butler, Bynner, Wadsworth, Goldstein, Chalmers, Golding, Kellner, Sullivan, Elliot, Goodman, Fitzesimon, Dezacourt en vele anderen. In eerste instantie zijn het allemaal mannen, tegenwoordig zijn alle cohortstudies in handen van vrouwen. In eerste instantie wordt de verklaring voor onderliggende uitkomsten veelal gezocht in de omgeving waarin mensen opgroeien, later spelen genetische elementen een belangrijke rol. De studies zijn opgezet in een tijd dat er nog helemaal geen gebruik van computers kan worden gemaakt. Daar kun je tegenwoordig helemaal geen voorstelling van maken maar de gegevens werden toch allemaal met de hand ingevoerd en op betrekkelijke eenvoudige manier geanalyseerd. Jij laat ook zien waar er strijd wordt geleverd tussen wetenschap en politiek maar ook tussen wetenschappelijke disciplines onderling (sociale wetenschap bijvoorbeeld ten opzichte van medische wetenschap).     



Daar waar de cohortstudies doorgaan, wat jij van harte toejuicht, eindigt jouw boek in 2015. Je laat zien hoe de vijf studies er dan voorstaan, wat de verschillen tussen de vijf studies zijn en wie er voor welke studie verantwoordelijk is. Ondertussen zijn er ook longitudinale studies uitgezet in andere landen, zoals in Noorwegen, Denemarken, Zweden en Amerika en ook in ons eigen land (bijvoorbeeld Generation R in Rotterdam). Hier zijn ze dan misschien niet zo vroeg met deze levensloop studies maar over de decennia heen zien we hier wel vergelijkbare beleidsmaatregelen. Wat brachten de studies dan weer aan extra informatie in en wat veranderde in Engeland wel en in de andere landen niet? Dat haal ik toch niet helemaal uit jouw boek. Je maakt wel weer expliciet duidelijk dat er geen land op dit gebied zoiets heeft gepresteerd als het Verenigd Koninkrijk. Het Verenigd Koninkrijk kent 28 door de Unesco erkende werelderfgoederen. Daaronder vallen onder andere Stonehedge, de Tower of London en de Canterbury Castle. Misschien zijn die cohortstudies nog wel meer dan dat juweel in de Britse wetenschappelijke kroon, waar jij het over hebt, en verdienen ze zelfs een plaatsje in dat prachtig rijtje Brits werelderfgoederen. Daar waar het Britse wereldrijk na de Tweede Wereldoorlog werd afgebroken, zijn jullie in ieder geval op dit terrein wereldleider gebleven. Dat besef is er helemaal niet maar jouw studie maakt duidelijk waar de Brit trots op moet zijn en dat we ook wel wat breder tegen het cultureel erfgoed kunnen aankijken.     

Dank je wel.

Grote groet, -Harrie

Pearson, H.(2016). *The Life Project. The extraordinary story of our ordinary lives.* London: Penguin Books Ltd. 416 pagina’s. €23,99





Jijzelf groeide op in de zestiger jaren, die gelukkige vijf minuten, zoals je dat zo mooi omschrijft, tussen de pil en AIDS. Jij maakte deel uit van die kritische generatie die nogal wat had op te merken over ouders die zelf vaak in de crisistijd waren opgevoed. Nu stel je, onder tussen zelf moeder en grootmoeder, dat jouw generatie (onze generatie) het er niet heel veel beter vanaf heeft gebracht. Volgens jou is de manier waarop we tegen opvoeden aankijken een verkeerde manier omdat die niet past bij wetenschappelijke inzichten die laten zien dat we het de kinderen veel meer op hun eigen manier moeten laten doen. Je hebt gelijk dat het ouders van tegenwoordig veel te weinig gaat om variatie, risico en innovatie en dat de opvoeding op die manier misschien wel te weinig aansluit bij het evolutionaire doel van de kindertijd. Kindertijd is vooral de tijd van exploratie, nieuwsgierigheid en spel en dat heb je nodig voorafgaand aan de fase van exploiteren, verantwoordelijkheid en werk. Wat er van elk kind wordt is onvoorspelbaar en uniek en het resultaat van vreemde combinaties van genen, ervaringen, cultuur en geluk. We moeten niet te snel een kind willen maken maar veelmeer liefde, veiligheid en stabiliteit bieden waarin kinderen op hun manier kunnen groeien. We kunnen nu één keer niet kinderen lerend maken, maar we kunnen ze wel laten leren. Ouderschap zie jij terecht als een belangrijk deel van de levenscyclus waarbij onze ouders ons het verleden gaven en wij op onze beurt de toekomst aan onze kinderen doorgeven. 
Meer dan bij welk ander levend soort ook zijn kinderen bij ons mensen lange tijd afhankelijk van opvoeders. Zelfs in vroegere tijden waren ze niet voor hun vijftiende zelfstandig. Kinderen waren daarbij niet alleen afhankelijk van hun eigen ouders maar ook van ‘allo-ouders’, het netwerk van grootouders, ooms, tantes, neven, nichten en vrienden. Alleen komen we als soort nergens en we ontwikkelen onszelf alleen in zo’n netwerk van zorg en liefde. Lange tijd groeiden kinderen op in uitgebreide families maar vandaag de dag is dat netwerk veel kleiner geworden. De opvoedingstaak ligt nu meer dan ooit bij de ouders, die zelf lange tijd naar school zijn geweest en al enige tijd werken voordat ze ouder zijn geworden. Op school en werk hebben ze zich dat doelgerichte, met de nadruk op kennis en competenties, eigen gemaakt. Op school en werk leidt dat natuurlijk tot succes. Maar in de opvoeding thuis is dat niet zozeer het geval. Ook lijkt het er op dat ouders van nu alleen maar oog voor het detail hebben. Ze stellen zichzelf vragen als hoe lang moeten ze hun kinderen moeten laten huilen, of de computer wel goed voor ze is en of ze wel lang genoeg huiswerk maken. De grote lijn lijken ze uit het oog te zijn verloren.


Van jouw boek heb ik veel geleerd. Als ontwikkelingspsycholoog bied je de lezer nieuwe inzichten, als filosoof lever je interessante dilemma’s en als ouder/grootouder laat je zien met welke concrete situaties je te maken hebt gehad. Opvoeden tegenwoordig, zo schrijf jij, lijkt misschien wel het meest op het werk van een meubelmaker. Er is ruim aandacht voor het juiste materiaal waarmee gewerkt wordt, voor de juiste bewerking en ouders willen net als de meubelmaker ervoor zorgen dat het juiste product wordt afgemaakt. In het proces gaat het om precisie en controle en chaos en verschil moeten zoveel mogelijk worden voorkomen. Maar jijzelf hebt veel op met het idee dat opvoeden als het zorgen voor een tuin is. Want als tuinman moet je de tuin beschermen en planten ruimte geven waar nodig. Je moet er veel voor doen maar het onverwachte is hier veel belangrijker. Net als de tuinman kun je als ouder niet alles voorspellen en variatie en wanorde lijken er hier wel degelijk toe te doen. Ik moet je eerlijk zeggen dat ik samen met mijn vrouw vaak in de tuin werk. Ik weet (en mijn vrouw nog veel beter) dat tuinieren wel degelijk doelgerichte kanten kent. Je moet soms dingen doen om een half jaar later bepaalde resultaten te bereiken. Niet alles maar wel voor een groot deel. Bovendien heb je hele verschillende tuinen. Natuurlijke tuinen en tuinen waar precisie en controle wel van afspatten. Je hebt Engelse tuinen en je hebt Franse tuinen. Kinderen waarvan de ontwikkeling in gevaar komt om welke redenen dan ook, zullen ondersteund moeten worden. Over hoe dat het beste kan en waar we rekening mee moeten houden moeten we na blijven denken. Dan doen we ook in de tuin als planten niet tot hun recht komen. Dat zullen we doelgericht moeten blijven doen en ik neem aan dat je die gedachte deelt. Met het vergelijken van opvoeden met houtbewerken aan de ene kant en tuinieren aan de andere kant kan ik niet helemaal met jou meekomen. Misschien, denk ik zelf, had je voor jouw boek veel beter de metafoor van het lange en avontuurlijke reizen met het aankomen als doel kunnen nemen, zoals Kavafis dat zo treffend in zijn beroemde gedicht ‘Ithaka’ beschrijft. De reis die vele jaren duurt maar rijk is aan wat je onderweg beleeft. Bij opvoeden gaat het om het aankomen maar veel meer nog om die mooie reis. Maar laat ik zelf ook de grote lijn van jouw boek in de gaten houden en het punt dat je maakt is terecht. 

Dank je wel, 

Grote groet, -Harrie

  

Gopnik, A.(2016). *The gardener and the carpenter. What the new science of child development tells us about the relationship between parents and children.* New York: Farrar, Strauss and Giroux, 320 pag., €22,16.


