
# WE ZULLEN HET ZELF MOETEN DOEN {-}


Amsterdam, april 2017

Beste Paul Verhaeghe,

De drievuldigheid of triniteit die we van het Christendom kennen paste Freud op de mens toe door hem te begrijpen vanuit id, ego en superego. Freud zette de mens met beide benen op de grond. Het id is, volgens Freud, de onbewuste laag van de persoonlijkheid, daar waar onze wensen en verlangens zitten. Aan de andere kant zit het superego, het geweten, het deel dat ons zegt wat mag en niet mag; een soort Japie als het ware, de groene krekel van Pinokkio. Tussen id en superego zit ego dat voortdurend bemiddelt tussen individuele wensen en verlangens en maatschappelijke regels. Die drievuldige interactie tussen het menselijke organisme en zijn omgeving zien we ook bij de Amerikaanse socioloog George Herbert Mead. Hij had het over het zelf dat communiceert met het ik, de pure vorm van het zelf, en het mij, de sociale vorm van het zelf. 
Jijzelf bent psycholoog die na Freud en Mead ook greep wil krijgen op de mens, maar nu die van honderd jaar later. Jij vraagt je al langer af waarom er tegenwoordig zoveel mensen zijn die tegen allerlei problemen aanlopen in het dagelijkse leven. Zij hebben met existentiële vragen te maken die samenhangen met maatschappelijke veranderingen die mensen ongelukkig maken. Anders dan bij Freud (waar jij een kenner van bent) en anders dan bij Mead (waarop jouw werk misschien wel veel mee lijkt) gaat het bij jou om identiteit, dat aan de bovenkant bemiddelt met autoriteit en aan de onderkant met intimiteit. Over identiteit en autoriteit schreef jij de afgelopen jaren achtereenvolgens twee boeken: *Identiteit* (Verhaege 2012) en *Autoriteit* (Verhaege 2015). Aan het derde boek, *Intimiteit*, werk je op dit moment. 



Onlangs maakte je de tussenbalans op en sprak je in de Kohmstammlezing over *Identiteit, Autoriteit, Onderwijs* (Verhaege, 2017). Ik zat bij die lezing ergens vooraan en luisterde vol interesse naar jouw verhaal. Daar vertelde je nog maar weer eens dat onze identiteit door de maatschappelijke veranderingen een andere invulling heeft gekregen. Identiteit wordt, zeker vandaag de dag, nogal eens opgevat als iets dat niet verandert en een harde kern heeft. Daarover denk jij terecht heel anders. Identiteit is veel minder eigen dan wij vaak denken en verbonden met een maatschappelijke omgeving waarbinnen wij ons ontwikkelen. Kan identiteit zelf steeds verschillend zijn, het proces naar identiteitsontwikkeling, waar je misschien wel meer over te zeggen hebt, is steeds hetzelfde. Dat zie jij als een constructieproces dat over de tijd invulling krijgt en waarbij tegelijk sprake is van identificatie en separatie, van optrekken aan en afzetten tegen, van meekrijgen en zelf bepalen. Identificatie (waar we veel over weten) verklaart vooral waarom bepaalde mensen uit dezelfde omgeving en cultuur meer op elkaar lijken. Separatie (waar we weinig over weten) laat de eigen en andere keuzes zien. Deze twee wisselen elkaar niet over de tijd af maar zijn voortdurend en altijd met elkaar in de weer. Omdat bij jou identiteit iets relationeels is en jij het steeds hebt over verhoudingen tot de ander, stel je identiteitsverhoudingen centraal. Voor jou zijn dat er vier: de verhouding tot jezelf, het andere geslacht, de andere-gelijke en de andere-autoriteit.   
In je hele werk ben je bijzonder kritisch over de neoliberale organisatie van onze samenleving met een economische ondertoon die zo bepalend is voor wie we zijn. Met jouw kritiek ben ik het eens, maar of dat door onze economische kijk op dingen komt vraag ik mij af. Je hebt economen van diverse pluimage en volgens mij heeft het veelmeer met onze eenzijdige instrumentele rationaliteit te maken, die inderdaad minder oog heeft voor het gemeenschapsgevoel en het individu centraal stelt met nadruk op competentie, concurrentie en eigen succes. In deze hyperindividuele, instrumentele samenleving moet je het maken. Lukt dat niet dan ben je een loser en voel je je schuldig. Natuurlijk kan niet iedereen aan die hoge eisen voldoen, dat zie jij dagelijks. 
Maar er zijn ook problemen waar je met identiteit alleen niet wegkomt en waarbij je misschien wel een laag hoger moet kijken. Veel problemen vandaag de dag hebben namelijk met gebrek aan gezag of autoriteit te maken, van internationaal terrorisme tot en met ouders en leerkrachten die niet meer goed weten hoe ze met hun kinderen om moeten gaan. Hier gaat het jou niet zozeer om existentiële problemen maar meer om problemen die te maken hebben met westerse waarden en normen. In jouw boeken en lezing ontrafel je eerst wat het is en waarom we hier tegenwoordig problemen mee hebben. Veel mensen denken dat die met de teloorgang van de westerse samenleving samenhangen, de vreemdeling die in ons leven is gekomen en het verdwijnen van een overzichtelijke samenleving. Veel mensen denken ook dat het allemaal iets van de laatste tien tot twintig jaar is. Terecht, denk ik, wijs jij er fijntjes op dat dat helemaal niet zo nieuw is. Vanaf de zeventiende eeuw al zijn we de autoriteit van Kerk en Koning in twijfel gaan trekken en is er een democratiseringsproces op gang gekomen dat op bepaalde momenten maatschappelijk zichtbaar wordt. Zo dachten we in de zestiger jaren dat we het maar beter zonder autoriteit af konden. Werd er toen een teveel aan autoriteit ervaren, nu, enkele decennia later, denken we weer dat er veel te weinig autoriteit is. Autoriteit kent volgens jou geen natuurlijke bron maar regelt, zoals je in het verlengde van Hannah Arendt schrijft, de verhoudingen tussen mensen op grond van vrijwillige onderwerping gebaseerd op een interne dwang. Bij jou gaat het daarbij om de verhouding tot de ander. Hiermee weten we nog steeds niet goed raad. Autoriteit verschilt zo fundamenteel van macht waarbij het gaat om iets wat van buiten wordt opgelegd, waaraan je bent onderworpen en dat je kan dwingen. 



Het vrijemarktmodel dat ons cultureel op allerlei manieren omringt, beïnvloedt het onderwijs natuurlijk sterk. Om succesvol te kunnen zijn is hier de nadruk komen te liggen op competenties en vaardigheden en gaat het om zelfmanagement en ondernemerschap. En natuurlijk krijgen we nu de leerlingen die we gevraagd hebben en die vanuit zichzelf vragen wat het onderwijs hen oplevert. Maar jij bent niet alleen kritisch over de eenzijdige identiteitsontwikkeling waar het onderwijs aan bijdraagt. Het onderwijs, eigenlijk de hele opvoeding, is ook nog eens verlegen geworden ten aanzien van zijn eigen handelen. Ouders en leerkrachten zijn onzeker geworden en voelen zich niet door het systeem gesteund. Autoriteit moet volgens jou opnieuw gegrond worden en onderlinge verhoudingen opnieuw gedefinieerd. Autoriteit kan niet meer van buiten en bovenaf opgelegd worden maar moet van onderop tot stand komen. Jij hebt veel op met autonome individuen die onderdeel uitmaken van een netwerk waar ze zelf in geloven en die niet naar boven en beneden kijken maar naar hoe anderen opzij reageren. Het onderwijs moet netwerken rondom de leerling vormen, waar docenten en bestuurders, ouders en de sociale omgeving deel van uitmaken. Scholen waar mensen naast elkaar staan en naar elkaar verwijzen. Veel hiervan zul jij (zullen wij) in de toekomst verder moeten uitwerken. Ook verdient de samenhang tussen identiteit en autoriteit, en straks ook nog intimiteit, veel van jouw aandacht. Maar je hebt gelijk dat we op zoek moeten naar nieuwe vormen van sociale organisatie die bovendien volume krijgen op verschillende niveaus van de samenleving. Maar hoe dit op schaal te brengen, vroeg is mij wel direct af. Duidelijk werd het mij wel dat er veel is te doen, dat drong die middag wel zachtjes tot mij door. Jouw boek ‘Autoriteit’ eindigde er al mee en jouw lezing sloot je er ook mee af; woorden die mij heel erg aanspreken, waarmee je mij deelgenoot maakt van een lange, interessante traditie, mij wakker schudt in het kerkbankje en mij aan het werk zet: we zullen het zelf moeten doen.   

Dank je wel.

Grote groet, -Harrie

Verhaege, P.(2017). *Identiteit, Autoriteit, Onderwijs*. Kohnstammlezing. Amsterdam: Vossiuspers UvA.

Verhaege, P. (2015). *Autoriteit*. Amsterdam|Antwerpen: De Bezige Bij.

Verhaege, P. (2012). *Identiteit*. Amsterdam: De Bezige Bij.  






Jijzelf groeide op in de zestiger jaren, die gelukkige vijf minuten, zoals je dat zo mooi omschrijft, tussen de pil en AIDS. Jij maakte deel uit van die kritische generatie die nogal wat had op te merken over ouders die zelf vaak in de crisistijd waren opgevoed. Nu stel je, onder tussen zelf moeder en grootmoeder, dat jouw generatie (onze generatie) het er niet heel veel beter vanaf heeft gebracht. Volgens jou is de manier waarop we tegen opvoeden aankijken een verkeerde manier omdat die niet past bij wetenschappelijke inzichten die laten zien dat we het de kinderen veel meer op hun eigen manier moeten laten doen. Je hebt gelijk dat het ouders van tegenwoordig veel te weinig gaat om variatie, risico en innovatie en dat de opvoeding op die manier misschien wel te weinig aansluit bij het evolutionaire doel van de kindertijd. Kindertijd is vooral de tijd van exploratie, nieuwsgierigheid en spel en dat heb je nodig voorafgaand aan de fase van exploiteren, verantwoordelijkheid en werk. Wat er van elk kind wordt is onvoorspelbaar en uniek en het resultaat van vreemde combinaties van genen, ervaringen, cultuur en geluk. We moeten niet te snel een kind willen maken maar veelmeer liefde, veiligheid en stabiliteit bieden waarin kinderen op hun manier kunnen groeien. We kunnen nu één keer niet kinderen lerend maken, maar we kunnen ze wel laten leren. Ouderschap zie jij terecht als een belangrijk deel van de levenscyclus waarbij onze ouders ons het verleden gaven en wij op onze beurt de toekomst aan onze kinderen doorgeven. 
Meer dan bij welk ander levend soort ook zijn kinderen bij ons mensen lange tijd afhankelijk van opvoeders. Zelfs in vroegere tijden waren ze niet voor hun vijftiende zelfstandig. Kinderen waren daarbij niet alleen afhankelijk van hun eigen ouders maar ook van ‘allo-ouders’, het netwerk van grootouders, ooms, tantes, neven, nichten en vrienden. Alleen komen we als soort nergens en we ontwikkelen onszelf alleen in zo’n netwerk van zorg en liefde. Lange tijd groeiden kinderen op in uitgebreide families maar vandaag de dag is dat netwerk veel kleiner geworden. De opvoedingstaak ligt nu meer dan ooit bij de ouders, die zelf lange tijd naar school zijn geweest en al enige tijd werken voordat ze ouder zijn geworden. Op school en werk hebben ze zich dat doelgerichte, met de nadruk op kennis en competenties, eigen gemaakt. Op school en werk leidt dat natuurlijk tot succes. Maar in de opvoeding thuis is dat niet zozeer het geval. Ook lijkt het er op dat ouders van nu alleen maar oog voor het detail hebben. Ze stellen zichzelf vragen als hoe lang moeten ze hun kinderen moeten laten huilen, of de computer wel goed voor ze is en of ze wel lang genoeg huiswerk maken. De grote lijn lijken ze uit het oog te zijn verloren.


Van jouw boek heb ik veel geleerd. Als ontwikkelingspsycholoog bied je de lezer nieuwe inzichten, als filosoof lever je interessante dilemma’s en als ouder/grootouder laat je zien met welke concrete situaties je te maken hebt gehad. Opvoeden tegenwoordig, zo schrijf jij, lijkt misschien wel het meest op het werk van een meubelmaker. Er is ruim aandacht voor het juiste materiaal waarmee gewerkt wordt, voor de juiste bewerking en ouders willen net als de meubelmaker ervoor zorgen dat het juiste product wordt afgemaakt. In het proces gaat het om precisie en controle en chaos en verschil moeten zoveel mogelijk worden voorkomen. Maar jijzelf hebt veel op met het idee dat opvoeden als het zorgen voor een tuin is. Want als tuinman moet je de tuin beschermen en planten ruimte geven waar nodig. Je moet er veel voor doen maar het onverwachte is hier veel belangrijker. Net als de tuinman kun je als ouder niet alles voorspellen en variatie en wanorde lijken er hier wel degelijk toe te doen. Ik moet je eerlijk zeggen dat ik samen met mijn vrouw vaak in de tuin werk. Ik weet (en mijn vrouw nog veel beter) dat tuinieren wel degelijk doelgerichte kanten kent. Je moet soms dingen doen om een half jaar later bepaalde resultaten te bereiken. Niet alles maar wel voor een groot deel. Bovendien heb je hele verschillende tuinen. Natuurlijke tuinen en tuinen waar precisie en controle wel van afspatten. Je hebt Engelse tuinen en je hebt Franse tuinen. Kinderen waarvan de ontwikkeling in gevaar komt om welke redenen dan ook, zullen ondersteund moeten worden. Over hoe dat het beste kan en waar we rekening mee moeten houden moeten we na blijven denken. Dan doen we ook in de tuin als planten niet tot hun recht komen. Dat zullen we doelgericht moeten blijven doen en ik neem aan dat je die gedachte deelt. Met het vergelijken van opvoeden met houtbewerken aan de ene kant en tuinieren aan de andere kant kan ik niet helemaal met jou meekomen. Misschien, denk ik zelf, had je voor jouw boek veel beter de metafoor van het lange en avontuurlijke reizen met het aankomen als doel kunnen nemen, zoals Kavafis dat zo treffend in zijn beroemde gedicht ‘Ithaka’ beschrijft. De reis die vele jaren duurt maar rijk is aan wat je onderweg beleeft. Bij opvoeden gaat het om het aankomen maar veel meer nog om die mooie reis. Maar laat ik zelf ook de grote lijn van jouw boek in de gaten houden en het punt dat je maakt is terecht. 

Dank je wel, 

Grote groet, -Harrie

  

Gopnik, A.(2016). *The gardener and the carpenter. What the new science of child development tells us about the relationship between parents and children.* New York: Farrar, Strauss and Giroux, 320 pag., €22,16.


