
# VRIJE SCHOOLKEUZE


Amsterdam, mei 2017

Beste Mercedes Schneider,

Jij bent vooral en in de eerste plaats lerares (Engels en Duits) op het voortgezet onderwijs. Je volgde nog enkele aanvullende onderwijsopleidingen en promoveerde op het terrein van statistiek en onderzoeksmethoden. Na wat omzwervingen over het land en verschillende werkplekken ben je weer terug in het zuiden van Amerika (Louisiana, waar je vandaan komt) en geef je weer les op een school voor het voortgezet onderwijs. Jij geniet van jouw werk en bent trots op wat je doet. Jij bent geen gewone lerares, jij bent een hele bijzondere lerares. Je blogt met grote regelmaat over de bedreigingen van het Amerikaans openbaar onderwijs. Daarnaast schrijf je boeken over dat Amerikaanse openbare onderwijs. De afgelopen jaren drie stuks; ieder jaar één en die rond jij steeds in een lange zomerperiode af. In ‘Chronicle of Echoes: Who’s Who in the Implosion of American Public Edcuation’ ga jij in op al die mensen en organisaties die volgens jou dat openbaar onderwijs bedreigen. In ‘Common Core Dilemma: Who Owns Our School’ vraag jij je af voor wie het onderwijs eigenlijk is; is het een publieke zaak met een maatschappelijk doel of is het een speeltje voor een klein aantal rijke personen om wat zinvols te doen. Het antwoord daarop is voor jou wel duidelijk. Het onderwijs zelf moet weer het heft in handen krijgen en het belangrijke democratische karakter ervan vorm geven. Jij wilt daar van binnenuit stem aan geven. Over dat tweede boek was ik bijzonder enthousiast, niet in de laatste plaats omdat het leest als een echte detective. Recent verscheen jouw ‘School Choice: The End of Public Education?’, ook weer mooi geschreven. Voor jou kan het openbare of publieke Amerikaanse onderwijssysteem alleen werken als het de deuren openhoudt voor alle studenten die, om welke reden en waar dan ook vandaan, aankloppen en de garantie hebben dat er maximaal aan hun toekomstmogelijkheden wordt gewerkt. Maar die schoolkeuze is niet meer voor iedereen zo vrij en aan het begin van de 21ste eeuw staat het Amerikaanse openbare onderwijs flink onder vuur. Jij laat zien hoe dat zo is gekomen en waarom jij je daar zo’n zorgen over maakt. Ook over jouw derde boek ben ik bijzonder enthousiast. 



De vrije schoolkeus heeft een andere betekenis gekregen en in de nieuwe betekenis is het de leus geworden van een groot aantal hervormers en organisaties waar jij bijzonder kritisch over bent. Niet meer het publiek belang maar veel meer het privébelang lijkt voorop te staan. Met vouchers (speciale toegangsbewijs) en inzet van belastinggeld kunnen nu bepaalde groepen ouders hun kinderen naar privé onderwijs laten gaan. In Amerika had het lang geduurd voordat dat het onderwijs ook werkelijk kon werken met gelijke kansen voor iedereen en aan sociale harmonie voor alle groepen. Zeker in het zuiden waar steeds weer gepoogd werd om integratie tegen te gaan, zoals het voucher systeem. Het is, zo schrijf jij, de invloedrijke vrijemarkt econoom Milton Friedman die ook kan worden gezien als de ‘vader van de schoolkeuze’. Hij bedacht het voucher systeem bedacht waarmee ouders onder het juk van de overheid vandaan kunnen komen en helemaal vrij zijn dat onderwijs te kiezen dat bij hun kind past. De charter school is de andere ontwikkeling die eraan heeft bijgedragen dat de vrije schoolkeuze in en ander daglicht is komen te staan. Dat idee werd al in e zeventiger jaren door Budde gepresenteerd, toen om lerarenteams de mogelijkheid te geven het onderwijs naar hun hand te zetten. Dat idee werd vervolgens in de tachtiger jaren door Albert Shanker, de charismatische leider van de Amerikaanse onderwijsvakbond, opgepikt om de kracht van de ouders en vooral de onderwijzers te versterken. Al snel werd duidelijk (zeker voor Shanker zelf) dat met dit concept nieuwe privé scholen werden opgezet met inzet van publieke middelen. Het oorspronkelijke idee pakte totaal anders uit. Er ontstond een ware charterindustrie waar vanwege het vrijmarkt model, de deregulering en de zakenideologie conservatieven heel enthousiast over zijn maar ook gesteund door de democraten. Via verschillende beleidsmaatregelen (zoals Bush’ No Child Left Behind en Obama’s Racing to the Top-beleid) wordt de charter-school echt iets groots. Niet alleen politici ook grote financiële investeerders zoals bijvoorbeeld de Walton-familie en diverse hedge-funders, die met dat onderwijs geld willen maken, dragen steentjes bij. Het onderwijs lijkt zo wel langzaamaan een vrijemarkt idee te zijn geworden in plaats van een openbare school in een buurt die wil bijdragen aan democratisch gehalte en sociale harmonie in de samenleving. Met de inzet van grote geldbedragen en deregulering is de kans op financiële fraude groot. Dat is ook wat gebeurde en jij laat zien hoe organisaties en personen met publieke gelden winst maken en de kinderen er zelf niet zo toe doen. Net als in jouw andere twee boeken ga je in op die personen en organisatie die hierbij de afgelopen meer dan 25 jaar belangrijk waren. De charter scholen worden vooral populair in Amerikaanse steden en onder de arme bevolking en de minderheidsgroepen. Maar in al die tijd is er nauwelijks onderzoek dat aantoont dat deze vorm van onderwijs op langere termijn voor deze studenten effect heeft. 
De Gulen charter scholen is een goed voorbeeld hiervan en jij gaat er uitgebreid op in. Dat had je gedaan voor juli 2016, voor de Turkse opstand. Fetullah Gulen is enige jaren geleden met zijn mensen in Pennsylvania neergestreken en bereidt van hieruit ook zijn Gulen beweging in Amerika uit. Gulen mag zichzelf graag met Gandhi en Maarten Luther King vergelijken en predikt tolerantie, dialoog tussen verschillende geloven en vooral onderwijs. Maar Gulen blijft een mysterieuze man die niet in het openbaar optreedt, die grote macht heeft en waarvan niet duidelijk is wat hij zelf precies wil en ook niet met het onderwijs. Een machtig man die ook heel veel geld met zijn onderwijs verdient. Moeten Amerikaanse kinderen aan dit onderwijs worden toevertrouwd als we er zo weinig over weten, als de leerkrachten niet over voldoende diploma’s beschikken en als we nauwelijks zicht hebben op wat er met de financiën gebeurt, zo vraag jij je zeer terecht af. 
 


Ondertussen staat het voucher-systeem in enkele staten onder druk, maar in andere staten en op het federaal niveau wordt het nog steeds gesteund. Ondanks de vele schandalen van charter scholen (over een aantal van deze schandalen schrijf jij uitgebreid), heeft dat idee nog steeds brede steun. Voor jou is het duidelijk. Deze charter-scholen worden niet goed in de gaten gehouden, belastinggeld wordt individueel gebruikt en dit systeem heeft een negatieve invloed op het openbare onderwijs. Dat openbare onderwijs moet zich, daar gaat het jou om, van de situatie bewust worden en zich niet bij deze situatie neerleggen. Deze nieuwe inhoud van vrije schoolkeus heeft een negatieve invloed op het Amerikaanse onderwijs en democratie. Ouders, leerkrachten en bestuurders moeten het niet over zich heen laten gaan maar juist stelling nemen, vind jij. Als dat openbaar onderwijs wil overleven, moet het voucher systeem en die charter-scholen stoppen omdat ze dat openbaar onderwijs bedreigen. In ieder geval en allereerst moet de controle op deze scholen toenemen. Als ze kwalitatief en financieel niet aan standaarden voldoen moeten ze gewoon weer een openbare school worden onder controle van een openbaar bestuur. Of de charterscholen beter zijn is zeer onduidelijk. Duidelijk is wel dat ze hun studenten zorgvuldig selecteren en dat publieke gelden niet terecht komen waar ze terecht moeten komen. Scholen moeten alle kinderen welkom heten. Voor dat democratisch ideaal wil je vechten en voor jou is het duidelijk dat dat moet gebeuren. Toen moesten de verkiezingen in Amerika nog worden gehouden.     
                                                                                                                                                
 

Dank je wel.

Grote groet, -Harrie

Schneider, M.K.(2016). **School choice. The end of public education?**. New York/London: Teachers College Press. 224 pagina’s. €41,99.


