
# VRIJHEID VAN DE EEN IS VOORWAARDE VOOR DIE VAN DE ANDER


Amsterdam, juni 2017   


Beste Axel Honneth,   

Iedere keer als ik in Duitsland ben zoek ik een Duits boek op. Ik ben opgegroeid met de Duitse cultuur en soms moet ik het weer even proeven. In de boekenzaak zag ik jouw ‘Die Idee des Sozialismus: Versuch einer Aktualisierung’ staan dat je twee jaar geleden hebt geschreven. Naast de oorspronkelijke uitgave stond ook de recente vertaling. Ik weet dat jij hoogleraar filosofie bent aan de Universiteit van Frankfurt en de Columbia Universiteit (New York). Bovendien ben jij directeur van het legendarische ‘Institut für Sozialforschung’, dat instituut dat Horkheimer, Adorno en Habermas wereldberoemd hebben gemaakt als de Frankfurter Schule. Wat heb jij met die achtergrond nog over dat socialisme te vertellen dat het in Nederland, Engeland, Frankrijk en, tot voor kort ook in jouw eigen land, zo ongelofelijk moeilijk heeft. Meer dan twee eeuwen had dat socialisme massa’s mensen bewogen en sprak het tot de verbeelding van vooraanstaande intellectuelen. De geest lijkt uit de fles. Maar, zo stel jij je zelf de vraag, wat betekent socialisme eigenlijk? Jij noemde jou zelf eigenlijk altijd wel zo, maar wat is de kern ervan? Je had kort ervoor de omvangrijke studie ‘Freedom’s right’ uitgebracht waarin je schrijft over de sociale fundamenten van het democratisch leven. Daarbij gaat het jou niet zozeer om de principes van rechtvaardigheid (waar het John Rawls om te doen was) maar om de vraag hoe vrijheid tot stand komt in de familie, het burgerleven en de staat. Drie praktijken die volgens jou door macht en economische kracht worden beïnvloed, per slot van rekening ben jij de ‘Directeur van de Frankfurter Schule’. In reactie op het boek kreeg te horen dat hier een visie op de maatschappelijke toekomst ontbrak. Daarnaast ben jij, net als zovelen, bijzonder verbaasd over die vreemde tegenstelling binnen onze huidige samenleving; aan de ene kant het grote ongenoegen en onbehagen dat mensen ervaren over de toegenomen ongelijkheid, de toename van private rijkdom bij een kleine groep mensen en de afbraak van de collectieve voorzieningen, en aan de andere kant het totale gebrek aan richting. We lijken wel niet meer in staat om voorbij de huidige situatie te denken. Dat is wel eens heel anders geweest. In jouw nieuwe boek vraag jij je af wat de kern van dat socialistische idee is, waar het mis ging en waar het volgens jou om moeten gaan.



Het idee van het socialisme hangt samen met zowel de industriële als de Franse revolutie. Het begrip socialist werd al eerder binnen katholieke kringen gebruikt maar krijgt zijn originele betekenis bij Owen, Saint-Simon Fourier, die, hoe verschillend ook, alle drie de wereld meer sociaal willen maken door het opzetten van collectieve organisaties. Voor hen was individuele vrijheid, waar in die tijd al regelmatig de nadruk op werd gelegd, te beperkt en dat begrip moest in samenhang met broederschap en gelijkheid worden gezien. Anders dan het private egoïsme dat binnen de kapitalistische markt zo belangrijk gevonden werd, ging het de vroege socialisten om wederzijdse verantwoordelijkheid en solidariteit. Er werden nieuwe vormen van vrijheid gezocht, altijd binnen het bereik van het werk, in associaties, coöperaties en gemeenschappen. Proudhon, ook zo’n vroege socialist, zag de vrijheid van de ander niet zozeer als beperking van de eigen vrijheid maar als voorwaarde voor de eigen vrijheid. Het is de jonge Marx die de theoretische basis legt voor de nieuwe socialistische beweging. Zeker in Marx’ vroege werk gaat het over de beperkingen van het individualisme en het belang van sociale relaties. Bij de sociale relaties gaat het hem niet om het plunderen van de ander, zoals hij dat in het kapitalistische systeem om zich heen zag, maar is hij op zoek naar mensen die elkaar nodig hebben als leden van een geïntegreerde samenleving en die zorg dragen voor de ontwikkeling van de ander. Marx zelf, hoe anders dan tegenwoordig (ook door mij) gedacht wordt, had daarbij de liefde van twee mensen voor ogen waar doelen bereikt worden in een volledig bewustzijn van de afhankelijkheid van de ander. 
Maar ondanks dat interessante vertrekpunt van de socialistische beweging, dat samenhangende idee dat gemeenschap meer is dan het individu waarmee de basis wordt gelegd voor sociale vrijheid, is het voor jou ook duidelijk dat dat socialisme vanaf het begin beperkingen in zich draagt waar het uiteindelijk niet van los is gekomen. Voor jou zijn dat er drie. Al die vroege socialisten zoeken altijd en enkel naar sociale vrijheid binnen het domein van de arbeid. De reorganisatie van de samenleving en de nieuwe vormen van solidariteit moeten hier worden gevonden. Binnen de socialistische beweging was men bijzonder hoopvol dat de oppositionele beweging binnen de samenleving en vooral bij de industriële arbeiders gevonden zal worden. Over dat revolutionaire potentieel hadden jouw voorgangers bij de Frankfurter Schule met alle vormen van verburgerlijking al de nodige twijfels, daar kun je in onze huidige post-industriële samenleving wel helemaal vragen bij stellen. Tot slot is er het deterministische toekomstbeeld van de socialisten dat de volgende fase in de geschiedenis vaststaat en onoverkomelijk is. Dat beeld van die nieuwe samenleving was wel duidelijk en het werd niet nodig gevonden mogelijkheden en de consequenties ervan onder ogen te zien. John Dewey was, volgens jou zeer terecht, kritisch over dat historisch determinisme van het socialisme. Als we zo zeker zijn over de toekomst hoeven we verandering niet te onderzoeken en ook niet uit te zoeken wat daarvoor nodig is. Voor Dewey, en ook voor jou, is dat een sociale werkelijkheid waarin alle individuen hun mogelijkheden kunnen ontwikkelen, waarin ze vrij kunnen participeren en waar iedereen deel uitmaakt van die gemeenschap. Het zou volgens jou niet moeten gaan over historisch determinisme maar over historisch experimenten die zicht geven op de verbetering van een concrete situatie. De aanval van de socialisten op het private egoïsme en het idee van sociale vrijheid beperkt zich tot het economische domein en wordt niet toegepast op andere domeinen. Maar er is ook nog de familie, het domein dat zo belangrijk is voor socialisatie en het tegemoet komen aan natuurlijke behoeften van mensen. En dan is er nog de staat die zorg draagt voor ethische en politieke integratie van het geheel. Voor deze zaken waren de vroege socialisten blind en dat heeft er ook voor gezorgd dat ze zich ten onrechte altijd maar wilden onderscheiden van de liberalen. Eigenwijs als ze waren, wilden ze het belang van liberale rechten nauwelijks zien. Wil het socialisme in onze tijd perspectief bieden, daar gaat het jou om, dan zal het zicht moeten bieden op hoe de verschillende domeinen met elkaar samenhangen en gaat niet alleen meer om het economische domein van actie maar net zo goed om persoonlijke relaties en de democratische meningsvorming. 

                      
                                                                                                                                                  
De sociale vrijheid is voor jou de kern van het socialisme, dat weet je in ieder geval na het schrijven van dit boek. Het gaat om de onderlinge verbondenheid van mensen met elkaar (‘miteinander’) en voor elkaar (‘füreinander’), om vrijheid in samenhang met gelijkheid en broederschap en de gemeenschap als uitgangspunt in plaats van het individu. De vrijheid van de een is voor jou de voorwaarde voor de vrijheid van de ander. Alleen als mensen de fysieke en emotionele, economische en politieke behoeften met elkaar delen en kunnen rekenen op sympathie en ondersteuning van anderen als dat nodig is, kunnen ze zich maximaal ontwikkelen. Als ik jouw verhaal zo lees hoor ik de socialistische partijbonzen al zeggen: ‘Dat doen we toch allang. Dat beeld dat je schetst is allang niet meer van deze tijd’ (zonder zo goed te weten als jij waar ze vandaan komen). Ik denk dat je gelijk hebt dat en niet alleen de ideologische veren zijn losgelaten maar ook de ideologische kern is verdwenen.  Dat idee dat de ander geen beperking is van jouw vrijheid maar juist jouw vrijheid kan versterken. Natuurlijk roept het boek bij mij ook veel vragen op. Ook al is jouw helder boek in stijl een verademing ten opzichte van jouw illustere voorgangers, blijft het een theoretisch boek (ik zocht ook een Duits boek). Het is heel anders dan Sennets ‘Samen’ waarmee het veel overeenkomsten heeft. In het mooie interview voor de Zwitserse televisie van een half jaar geleden vraagt de interviewster jou wat je bedoelt met ‘ik heb het boek aan mijn zonen opgedragen omdat ze vanaf het begin mijn leven makkelijker hebben gemaakt’. ‘Ach’, zeg je dan nonchalant, ‘vaak wordt met een managers-mentaliteit tegen zoiets aangekeken; kinderen kosten tijd en dat beperkt jouw vrijheid. Nee, mijn vrijheid is voorwaarde voor hun vrijheid en alleen zo voel ik mij vrij’, zeg je dan. Dit spreekt tot de verbeelding.



Dank je wel.

Grote groet, -Harrie

Honneth, A.(2017). *The idea of Socialism. Towards a renewal*. Cambridge/Malden: Polity Press. 145 pagina’s. €18,99.


