
# OPNIEUW BEGINNEN
	

Amsterdam, juli 2017


Beste Donald Trump,


Geschiedenis vertelt, hoop niet   
Aan deze kant van het graf,    
Maar dan, eens in een mensenleven   
Kan de verlangde getijdegolf   
Van rechtvaardigheid opstaan,   
En rijmen hoop en geschiedenis.    
--Seamus Heaney	


Op 8 november 2016 werd u gekozen tot de 45e president van de Verenigde Staten. U maakte meteen duidelijk dat u het land opnieuw gaat opbouwen en dat er opnieuw mag worden gedroomd. Politiek lag al te lang enkel in de handen van een kleine groep mensen en welvaart werd te weinig gedeeld. U wilt het land weer teruggeven aan uw eigen mensen. Rijkdom is teveel in handen gekomen van mensen buiten het land en te weinig bij uw eigen mensen. De tijd van praatjes is volgens u voorbij, nu breekt de tijd van actie aan. Niemand in het land mag meer genegeerd worden en samen zal er gewerkt worden aan een sterker Amerika, een trots Amerika en een groot Amerika. 
Toen het in de ochtend van 9 november duidelijk werd dat u president zou worden (u haalde 306 kiesmannen van de 538 kiesmannen), ben ik bijna direct naar de boekwinkel gegaan op zoek naar meer houvast. Uw verhaal over het land opnieuw opbouwen komt op mij al langer ongeloofwaardig over en onduidelijk blijft voor mij waar u zich, behalve uw eigen ervaringen, op baseert. Maar, stel, dat we wel opnieuw willen beginnen, waar moeten we dan beginnen? Is er een beter antwoord op deze vraag te vinden? Ik had mij al heel lang voorgenomen om John Rawls’ ’Theory of Justice’ eens te lezen. Dit boek van uw legendarische landgenoot wordt gezien als misschien wel het belangrijkste filosofische boek van de 20e eeuw, in ieder geval het belangrijkste politiek filosofische boek. Rawls laat in dat boek zien hoe we een democratische samenleving in moeten richten, hoe we daarbij rekening houden met verschillen tussen mensen, hoe vrijheid en gelijkheid met elkaar in evenwicht zijn te brengen en wat rechtvaardig en billijk is. Uw verkiezing leek mij een goed moment om eens wat langer stil te staan bij dat onderwerp van de rechtvaardige samenleving, de basis ervan en hoe hierover in uw land eerder is gedacht. Mijn manier van actie, zeg maar. 


John Rawls, over wie u waarschijnlijk niet eerder heeft gehoord en wiens boeken zeker niet op uw nachtkastje liggen, heeft zijn leven lang gezocht naar een antwoord op de vraag hoe een rechtvaardige samenleving eruit zou moeten zien. Hij dacht na over de inrichting van politieke, sociale en economische instituten, over constitutionele democratie en hoe verschillende mensen met elkaar om moeten gaan wanneer er zowel rekening wordt gehouden met vrijheidsrechten als gelijkheidsrechten. Wat hebben we nodig om een gemeenschap levensvatbaar en menselijk te maken, een gemeenschap die bovendien goed met sociale problemen weet om te gaan. Een thema dat de leider van het belangrijkste land ter wereld toch ook moet interesseren. Halverwege de vorige eeuw, de tijd dat Rawls met zijn werk begon, was er slechts één theorie die een beetje telde: het utilitarisme voor wie moralisme vooral bestond uit het wegen van kosten en baten en goed oog hebben voor de consequenties van de keuze; goed en rechtvaardig is hier nog de beste keuze voor zoveel mogelijk mensen als alles op rij is gezet. Het werd het  ‘gemaximaliseerde nettoresultaat’ genoemd. Rawls vond deze ideeën te beperkt en zocht naar betere basisprincipes voor onze samenleving. Hij wilde op zijn manier opnieuw beginnen. Dat opnieuw beginnen moet u, meneer Trump, aanspreken. Centraal in Rawls’ denken is het gedachtenexperiment dat hij ons voorschotelt: welke principes van rechtvaardigheid kiezen mensen als ze opnieuw een samenleving zouden moeten inrichten en ze geen enkele informatie hebben over de positie die zij, of anderen die ze kennen, zouden innemen. Een keus dus die door niets in de huidige situaties wordt beïnvloed, noch door de positie die iemand inneemt noch door zijn talenten. Zo denkt u natuurlijk helemaal niet want u weet al langer wat het beste is voor mensen en heeft uw inzichten in de wereld opgedaan. Ikzelf vind het een geweldige vondst. Hier wordt ‘de originele positie’ gezocht die het keuzeproces bepaalt en Rawls praat over ‘de sluier van onwetendheid’ die steeds over rechtvaardigheidskeuzes heen wordt gelegd. Juist door mensen los te weken van hun eigen particuliere kennis en positie kiezen ze voor eerlijke principes die algemeen zijn en worden ze niet beïnvloed door hun eigen interesses en omstandigheden. Natuurlijk, meneer Trump, is dit een sterke versimpeling van wat er in het dagelijks leven gebeurt. Maar toch hebben we wel degelijk zo’n hypothetisch contract met elkaar nodig. Alleen zo kunnen we de samenleving accepteren zoals ze in elkaar zit en behandelen we personen als vrije en gelijke personen. Dat is voor politici allicht ook het moeilijkste wat er is omdat zij juist voor bepaalde belangen op komen. Toch was Rawls optimistisch over de mogelijkheden van deze rechtvaardigheidsprincipes voor alle burgers. Een rechtvaardige samenleving regelt de basisprincipes voor iedereen op een juiste manier en niemand zal het vertrouwen in de samenleving verliezen als die deken een keer is opgetild.     
Het ambitieuze van John Rawls zal u aanspreken, niet zijn progressieve en veel omvattende kanten. Vanaf zijn eerste artikel in 1958 heeft uw landgenoot rustig door gebreid aan zijn rechtvaardigheidssluier, in alles een heel ander type dan u. Toch zou u als president van Amerika trots moeten zijn op dit historisch kanon. Natuurlijk, het kan niet anders dan dat zo’n sterke theorie de nodige kritische reacties oproept. Want is zo’n originele positie wel mogelijk en zijn wij wel in staat om voorbij onze posities en interesses te denken? Hoe moet je het sluiten van een hypothetisch contract eigenlijk voorstellen? Leidt dat uiteindelijk wel tot een meer rechtvaardige samenleving? En maken we wel voldoende gebruik van de sterke kanten die we hebben opgebouwd zoals talenten, intelligentie, welvaart en dergelijk? 


Met een aantal van uw weldenkende landgenoten ging Rawls over de jaren in debat, zoals Nozick, Dworkin en Cohen (Hinton, 2015). De kritiek die mijzelf het meest aanspreekt, komt van zijn leerling Amatyra Sen, een Indiër die, meneer Trump, al heel lang in uw land woont en niet voor niets de Nobelprijs ooit gewonnen heeft. Ook zo’n iemand uit uw eigen gemeenschap waar u trots op zou moeten zijn. Sen kende het werk van Rawls vanaf het begin en gebruikte een eerdere versie van Rawls’ boek al in zijn colleges eind zestiger jaren. Hij heeft zelfs meegelezen bij het tot stand komen van het uiteindelijke boek. Sens eigen boek over rechtvaardigheid van enkele jaren geleden, ‘The theory of justice’, draagt hij daarom ook op aan zijn leermeester. Rawls helpt ons, zegt Sen, om rechtvaardigheid te begrijpen en blijft de politieke filosofie verrijken. Hij definieert een vorm van objectiviteit die we bij het vaststellen van rechtvaardigheid nodig hebben, wijst ons ook op de morele kracht die mensen hebben, verbindt rechtvaardigheid met vrijheid en ziet het belang van mogelijkheden om iets met eigen leven te doen en wat het voor de samenleving betekent als we groepen buitensluiten. Volgens Sen benadrukt Rawls soms te veel de vrijheid, ook omdat honger en gebrek aan medische zorg wel degelijk die vrijheid kunnen beperken. Rawls heeft bovendien teveel oog voor de instituten en te weinig voor wat keuzes concreet voor mensen betekenen. Voor Sen gaat het bij rechtvaardigheid ook veel meer om praktische beslissingen die eraan bijdragen dat onze levens verbeteren. Hem gaat het niet zozeer om de perfecte samenleving en instituten maar wat de meest rechtvaardige sociale arrangementen zijn wanneer ze worden vergeleken en geëvalueerd. Sen legt de nadruk op publieke rede, rationaliteit en het vinden van redelijke antwoorden op grote maatschappelijke problemen. We moeten kunnen omgaan met verschillende gezichtspunten, niet naar binnen gericht zijn maar juist oplossingen zoeken voor grote maatschappelijke vraagstukken als honger, armoede en klimaatbeheersing.    
 


Elke samenleving heeft, zo stelde onze Nederlandse socioloog Kees Schuijt eens vast, steunberen nodig net zoals een kathedraal dat heeft. Een samenleving moet bij elkaar gehouden worden want anders kan deze instorten. Meneer Trump, dat werk van Rawls is zo’n steunbeer dat er voor zorgt dat er sprake kan zijn van solidariteit, dat mensen zich niet buitengesloten voelen en op een gezonde manier met tegenstellingen kunnen omgaan. Daarnaast denk ik dat Sen gelijk heeft als hij zegt dat we met Rawls theorie niet op vakantie kunnen gaan maar dat wij aan rechtvaardigheid moeten blijven werken. Sens vergelijkend, internationaal en meer praktische perspectief is een sterk zijpad van de hoofdweg die Rawls heeft aangelegd. Een hele andere weg dan waar u zelf op zit. Natuurlijk bent u, meneer Trump, het lezen van deze brief allang gestopt. Er zijn belangrijkere zaken te doen. Dit zijn weer te veel van die praatjes, zult u denken, waar niemand om vraagt. Mensen vragen om actie en het wordt tijd dat er wat gebeurt. We moeten de mensen in Amerika verder helpen, we moeten Amerika weer trots en groot maken. Uw geschiedenis en hoop rijmen niet. En ik zeg u, als we dan toch opnieuw willen beginnen, hebben uw landgenoten én de mensen in de rest van wereld veel meer aan Rawls en Sen… Ik zeg u als we dan toch opnieuw willen beginnen, ….


Dank u wel dat u mij deze kant op duwde.

Grote groet, -Harrie

Rawls, J.(2015). *Een theorie van rechtvaardigheid. 4e druk*. Rotterdam: Lemniscaat. 644 pagina’s. €39,95.

Sen, A. (2009). *The idea of justice*. London: Penguin Books.496 pagina’s. €34,99. (Verscheen in 2013 ook in de Nederlandse vertaling als Het idee van rechtvaardigheid)

Hinton,(T)(ed., 2015). *The original position*. Cambridge: Cambridge University Press, 292 pagina’s. ebook: $16,74

