
# STEDELIJKE SCHEIDSLIJNEN
	
Amsterdam, augustus 2017


Beste Richard Florida,


Eind jaren vijftig, begin jaren zestig is het druk in de Amerikaanse steden met z’n winkels, krantenkantoren, bibliotheken en fabrieken. Mensen wonen dicht in de buurt van hun werk. De steden zijn centra van economische groei en industriële en culturele activiteiten. In die jaren trekt met name de middenklasse naar de buitenwijken waar dan nieuwe en betaalbare huizen worden gebouwd. Deze mensen zijn in het begin nog nauw verbonden met de stad maar de afstand wordt allengs groter. De binnensteden raken leger, armoede blijft achter en binnensteden worden niet zelden plaatsen van criminaliteit, drugs en geweld. Dit is zeker het geval wanneer eind jaren zeventig, begin jaren tachtig de traditionele industrie wordt afgebouwd, de economie stagneert en grote groepen hun baan verliezen. Her en der wordt de traditionele industrie nog ondersteund en worden er voorzieningen getroffen die hierbij aansluiten. Er is sprake van stedelijke culturele crisis. Ondertussen heeft zich al een hele andere economie ontwikkeld waar niet alle steden direct op in springen. In ‘The Rise of the Creative Class: And How It’s Transforming Work, Leisure, Community, and Everyday Life’ kijkt je op een frisse manier tegen die nieuwe economische ontwikkeling aan. Dat boek gaat over de nieuwe creatieve klasse die is ontstaan. Jij bent ervan overtuigd dat deze klasse (van kunstenaars, wetenschappers, ingenieurs en high-tech professionals en dergelijke) de drijvende kracht is achter innovatie, vernieuwing en nieuwe economische activiteiten. Deze groep bestaat dan uit zo’n 30-40% van werkende Amerikaanse bevolking die de cultuur, de werkplaatsen en de samenleving in brede zin doet veranderen. In bepaalde steden ligt dat percentage zelfs flink hoger. Steden moeten voorwaarden creëren om juist voor deze groep aantrekkelijker te zijn. Deze creatieve klasse vraagt niet om snelwegen, stadions of supermarktketens maar heeft behoefte aan openheid, diversiteit en netwerken waar ze andere creatieve personen kunnen ontmoeten, zichzelf kunnen zijn en, misschien wel vooral, zichzelf kunnen worden. Wanneer, daar ben je van overtuigd,  rekening wordt gehouden met technologie, talent en tolerantie ontstaan er vanzelf nieuwe innovatieve plekken in de samenleving die voor verdere economische voorspoed zouden zorgen. 


Vijftien jaar later ligt jouw nieuwe boek voor: ‘The New Urban Crisis: How our cities are increasing inequality, deepening segregation, and failing the middle class – and what we can do about it’. Jouw ideeën zijn de afgelopen jaren verder geëvolueerd. Je bent minder optimistisch over wat gaande is. Het verschil tussen het rijke en arme deel van de bevolking is met name in de grote steden toegenomen. De creatieve klasse, waar je veel mee op hebt, is erin geslaagd om in de stad een goede plek voor zichzelf te vinden, veelal in homogene buurten met andere rijke mensen, top-restaurants en luxe winkels. De onderlaag van mensen die in de fabrieken, de constructie en het vervoer werken, heeft het moeilijker gekregen. Zo ontstonden er duidelijke stedelijke scheidslijnen en is er sprake van duidelijke ongelijkheid en polarisatie in de moderne succesvolle economieën van de Amerikaanse steden. De middenklasse, ooit zo sterk, lijkt hier helemaal geen rol meer te spelen. Bovendien is het ook nog zo dat die nieuwe kenniseconomie, met zijn innovatie en ontwikkeling, zich met name afspeelt in een beperkt aantal supersteden waar de huizen onbetaalbaar zijn geworden en het niveau van ongelijkheid vaak hoger is dan in Swaziland, SriLanka of Rwanda. De meerderheid van de steden blijft verder achter. Daar wonen de mensen nog vooral in de buitenwijken, verloedert de binnenstad verder en zet de deindustrialisatie verder door. Mensen met kantoorbanen en die werken in de dienstensector, in het onderwijs en de verpleging, bij de politie, in het transport en de bouw hebben het in de stad moeilijker gekregen. Er is sprake van een handjevol supersteden met z’n elitebuurten en een groot aantal andere steden waar de ontwikkeling stagneert of terugvalt. Er is een nieuwe stedelijke crisis ontstaan met een cluster getalenteerde professionals en een selecte groep superstersteden en de rest die achterblijft. 
In de steden vindt er een proces plaats van wat tegenwoordig gentrificatie wordt genoemd: het proces waarin welvaart toeneemt en de populatie rijker, witter en jonger wordt. De groep winnaars wil weer dichter bij het werk wonen dat nu weer in de stad is te vinden en gebruik maken van het culturele aanbod dat de stad hen en hun kinderen biedt. Mensen die het niet meer kunnen betalen worden als het ware met de elleboog uit die buurten gewerkt. Maar de problemen doen zich vooral voor in de buurten met achterstand waar de meerderheid van de mensen in armoede woont. Vaak zijn dat dan weer de buitenwijken waar immigranten en minderheden wonen (nu verder weg van het werk) en waar ouderen en gepensioneerden zijn achtergebleven. Gentrificatie is, volgens jou, misschien wel niet zozeer het probleem als we maar aandacht houden voor de problemen in bepaalde buurten waar de criminaliteit, drugsgebruik en werkloosheid het hoogste is. Het oude stedelijk patroon van de rijke buitenwijk en de arme binnenstad maakt plaats voor het patroon van een ruimtelijke lappendeken met stukjes rijkdom hier en stukjes armoede daar.    


We moeten er voor zorgen dat er strategische investeringen komen in de economische basisstructuur van een stad, daar ben je van overtuigd. Deze moeten ervoor zorgen dat isolatie en armoede van bepaalde groepen worden teruggedrongen, dat talent breed wordt aangeboord en capaciteiten van de gehele bevolking worden ontwikkeld. Steden moeten daarvoor zorgen maar kunnen dat niet zonder de ondersteuning van nationale en internationale overheden. Burgemeesters, beleidsmakers en organisaties hebben informatie en kennis nodig die hen vooruit helpt. Daaraan ontbreekt het nog veel te veel op dit moment en jouw boek en inzichten willen dat gat (soms te nadrukkelijk) opvullen. Jij denkt dat die nieuwe stedelijke crisis er de oorzaak van is dat we niet helemaal uit de economische crisis van het laatste decennium komen. Sommige politici en wetenschappers pleiten voor het investeren in wegen en bruggen. Jij vindt dat niet meer van deze tijd. We hebben strategische investeringen nodig in de infrastructuur en een scenario dat niet op het verleden maar op de toekomst is gericht. We moeten oog hebben voor compactheid en overdracht van kennis en de basisstructuur die zorgt voor economische groei. Bij jou gaat het niet om meer land maken. Jij wilt dat het land intensiever en efficiënter wordt gebruikt. Naast de intensieve landbouw zouden we moeten zorgen voor een intensieve kenniseconomie. Daarbij moeten we niet meer zo de nadruk leggen op auto’s die individuele burgers verplaatsen maar op het verplaatsen van grote groepen tegelijkertijd. Allicht moeten we, volgens jou, niet zozeer meer de huiseigenaren verdedigen maar zorgen voor betaalbare huurhuizen in stedelijke omgevingen. We zouden groepen in de onderklasse, die jaren op de nullijn hebben gezeten, financieel tegemoet moeten komen en er zo voor zorgen dat ze deel uitmaken van de middenklasse. Probleemgroepen en -gebieden behoeven ondersteuning. De onderwerpen stad en urbanisatie hebben nationale en internationale aandacht nodig. Ten slotte moeten er gereedschappen komen waarmee gericht beleid gevoerd kan worden, steden eigen problemen kunnen oplossen en ze rekening kunnen houden met lokale variatie. 
Jouw boek gaat over Amerika, Canada en een beetje Engeland. De aandacht die jij besteedt aan de rest van de wereld (met name Azië en Afrika) is bescheiden. In mijn eigen land zullen ze zich afvragen: ‘Wat hebben wij aan deze Amerikaanse inzichten? De ongelijkheid is daar zoveel groter dat deze kennis niet van toepassing is op onze omgeving’. De patronen die jij schetst zijn zeer herkenbaar, ook hier. Deze historische ontwikkelingen hebben zich, veel minder scherp maar toch, ook bij ons afgespeeld. Ook in ons land heeft de creatieve klasse bezit genomen van de grote stad, heeft de onderklasse het er moeilijker en zijn er grote verschillen in economische ontwikkeling tussen steden vast te stellen. Jouw boek laat ons goed zien wat er om ons heen gebeurt en waar wij op moeten letten.  Misschien is verbondenheid wel het belangrijkste woord in jouw boek. Stedelijke ontwikkeling lijkt niet meer met iedereen te zijn verbonden en zo’n inclusief perspectief hebben we weer nodig. ‘Steden hebben de mogelijkheid om iets voor iedereen te bieden, alleen omdat en alleen wanneer ze door iedereen zijn gemaakt’, schreef Jane Jacobs in haar klassieker ‘The death and life of great American cities’ begin jaren zestig. Het is terecht dat jij dit citaat aan het begin van jouw boek aanhaalt. Het is vooral deze boodschap die je ons meegeeft en die we heel serieus moeten nemen. 




Dank je wel.

Grote groet, -Harrie

Florida, R.(2015). *The New Urban Crisis. How our cities are increasing inequality, deepening segregation, and failing the middle class – and what we can do about it*. New York: Basic Books. 310 pagina’s. €25,99.

