
# LEREN VAN FOUTEN
	

Amsterdam, september 2017


Beste Michael Lewis,

Als journalist, columnist en schrijver schreef je veel over flitshandel, innovatie, crisis op de huizenmarkt en financiële zaken. Je bent een Wall-street journalist en schreef boeken als The Big Short, Flash Boys en Liar’s Poker. Een ander bekend boek van jou is Moneyball, dat in 2003 uitkwam. Dat gaat over het MLB Oaklands-honkbalteam van de charismatische manager Billy Beane. Deze club had veel minder financiële armslag dan al die andere superrijke teams en jij stelde je in dat boek de vraag hoe het kwam deze kleine David het steeds maar weer van die grote Goliath-mannen kon winnen. Dat kwam door het gedetailleerde datamanagementsysteem waarmee ze een sterk scoutingsysteem opzetten en een perfect team opbouwden. In *Moneyball* gaat het jou om de vraag hoe het komt dat in die wereld met die grote bedragen toch steeds weer zoveel fouten worden gemaakt, waarom de managers altijd maar weer vanuit zichzelf denken en waarom zo’n analytische  benadering van Billy Beane er niet eerder was. Dat boek werd in 2003 door de bekende wetenschappers Thaler en Sunstein enthousiast gerecenseerd omdat jij over gedragseconomie schreef en economie en psychologie zo goed wist te combineren. In hun recensie wezen zij jou op het werk van Kahneman en Tversky, die enkele decennia eerder juist op jouw vragen ingingen. Misschien, zo stelden ze, moest je dat werk er nog eens op na slaan. Maar zo serieus als je nu hebt gedaan in jouw nieuwe boek ‘The Undoing Project. A Friendship that Changed the World’ bedoelden Thaler en Sunstein het vast ook weer niet.  


Kahneman en Tversky zijn hele verschillende personen, dat maak je goed duidelijk. Daniel Kahneman groeit op in Parijs en maakt als Joodse jongen in Frankrijk de Duitse bezetting mee. Zijn vader overleeft de oorlog niet en zijn moeder wil na de oorlog niet in het verraderlijk Europa blijven. Met zijn moeder vertrekt hij naar Palestina en daar maakt hij in 1948 de oprichting van Israël mee. Jij schrijft dat Kahneman daar in Israël een buitenstaander is en blijft, een vluchteling die zijn leven lang afstand bewaard. Met psychologie kan Kahneman vanuit een natuurlijke verontwaardiging de wereld vanuit mensen zelf begrijpen en zien. Hij is vooral geïnteresseerd in hoe die menselijke geest werkt. Hij verdient zijn sporen met persoonlijkheids- en perceptie onderzoek en gaat in Amerika werken. Daar houdt hij zich bezig met de vraag hoe mensen aandacht vasthouden en wanneer ze die aandacht verliezen. Hij wil weten welke kennis mensen gebruiken als ze niet weten wat ze moeten doen. 
Amos Tversky is een hele andere persoon, een insider veel meer. Zijn ouders waren in de twintiger jaren als Zionist Rusland uit gevlucht en hij voelt zich van jongs af aan sterk met Israël verbonden. Hij is op jonge leeftijd lid van een linkse jeugdbeweging en ontwikkelt zich snel tot elitesoldaat. Ook Tversky gaat psychologie studeren, wil weten hoe mensen beslissingen nemen en promoveert daarop in Amerika.  
Kahneman is de twijfelaar, de rommelpot, de ochtendmens, veel meer de poëet, de denker, de wijze, de verhalen-verteller en de psycholoog. Tversky is veel meer overtuigd van zichzelf, georganiseerd, de nachtbraker, de slimme, de vechter, het genie, de scherpslijper en de analyticus. Verschillende typen, maar allebei Israëlische psychologen die eind jaren zestig in Amerika werken. Ze kennen elkaar van naam maar hebben nog nooit met elkaar te maken gehad wanneer Kahneman Tversky in het voorjaar van 1969 uitnodigt voor een voordracht. Die voordracht gaat over hoe mensen omgaan met nieuwe informatie. Nieuwe informatie wordt, zo vertelt Tversky, op een juiste manier verwerkt maar vaak niet sterk genoeg. Eigenlijk zijn mensen behoudende Bayesianen; ze houden wel rekening met bestaande kennis maar gebruiken deze in nieuwe situaties te beperkt. Kahneman reageert sceptisch. Voor Kahneman is de mens geen statisticus die van weinig informatie eenvoudig over kan stappen naar grote conclusies. Statistiek, waar hij zelf veel van weet, geeft wel aan hoe we over mogelijkheden zouden moeten denken maar niet hoe we denken. Oordelen en beslissingen hebben vaak met hele andere zaken te maken en daarom zegt hij tegen zijn Israëlische collega: ‘Briljant praatje hoor, maar ik geloof er geen snars van.’ Zo’n reactie was Tversky natuurlijk helemaal niet gewend. Met jouw prachtige schrijfstijl maak je duidelijk waar ze beiden in geïnteresseerd zijn, welk onderzoek naar menselijke beslissingen ze samen opzetten en hoe ze dat uitvoeren. Hun ‘aanvaring’ is het begin van een hele succesvolle periode waarin ze laten zien dat mensen niet alleen rationeel beslissen, maar ook hoe die menselijk geest werkt, waar deze niet goed werkt, hoe oordelen en beslissingen tot stand komen en wat daarin meespeelt. Kahneman en Tversky sluiten zich op in studeerkamers en lopen urenlang met elkaar door steden. Niemand komt er echt tussen wanneer ze met elkaar nadenken over hoe mensen denken, oordelen en beslissen. Mensen volgen daarbij vaak een beperkt aantal regels die ze ‘heuristieken’ noemen. Een daarvan is representativiteit of vergelijkbaarheid. Als je, bijvoorbeeld, een donderwolk ziet aankomen vergelijk je die met de wolk die je kent. Maar er zijn meer van dat soort vaste patronen, zoals beschikbaarheid: hoe makkelijker mensen iets voor hun geest kunnen halen, hoe waarschijnlijker ze de kans erop achten. Als je net een ongeluk hebt gezien hebt, acht je de kans erop groter. Ankering is een derde heuristiek die ze onderscheiden waarbij je blijft hangen bij informatie die er niet toe doet. Kahneman en Tversky leggen mensen de meest gekke vragen voor om te zien hoe ze informatie verwerken en jij geeft daar talloze voorbeelden van. Als gevraagd wordt hoeveel is 8x7x6x5x4x3x2x1, zegt 50% 2,250. Maar bij de vraag hoeveel is 1x2x3x4x5x6x7x8 antwoordt 50% 512. Mensen blijven bij de eerste getallen hangen. Het gaat hen niet alleen om oordelen maar ook om voorspellingen die mensen maken. Als we geen aanvullende informatie hebben, houden we rekening met basisgetallen en gaat het redelijk goed. Maar niet als er waardeloze informatie aan wordt toegevoegd die onze onzekerheid onnodig beïnvloedt. Irrationaliteit en fouten maken deel uit van ons oordeelvermogen en als we bepaalde hypothesen hebben opgesteld is het heel moeilijk om ons daar vanaf te krijgen. Bij het vaststellen van medische diagnoses worden de nodige fouten gemaakt; die zouden we moeten herkennen en niet ontkennen. In het beslissingsproces van mensen gaat het niet zozeer om het vergroten van het nut of de opbrengst en veel meer op het beperken van het verdriet of het verlies. Het lijkt minder over de positieve uitkomsten en veel meer om het voorkomen van het negatieve proces te gaan. Dat zijn hele nieuwe inzichten in een tijd waarin heel anders over rationaliteit wordt gedacht. 
Eind jaren zeventig groeien Kahneman en Tversky langzaam maar zeker uit elkaar. Ze hebben een tiental baanbrekende artikelen samen geschreven maar het lijkt erop dat er geen lucht meer in de band zit. Tversky krijgt een aanstelling op Harvard en ontvangt een grote prijs. Kahneman krijgt zo’n aanstelling niet en wordt niet in de prijsuitreiking genoemd. Ze brengen veel minder tijd met elkaar door en ze komen in een soort scheiding terecht. In 1993 wordt er bij Tversky een melanoomkanker vastgesteld en enkele maanden later overlijdt hij.       


In 2002 ontvangt Kahneman de Nobelprijs voor de economie, gebaseerd op het werk dat hij in de zeventiger jaren met Tversky heeft verricht. Zij hebben nieuwe patronen ontdekt in hoe wij met de wereld omgaan, hoe we omgaan met onzekerheid en twijfel en wat de basis is van menselijk feilbaarheid en irrationaliteit. Ons wereldbeeld gaat er maar al te makkelijk vanuit dat we slim en rationeel zijn. Maar iedereen weet dat het vaak heel anders werkt (zie ook Kahneman, 2011). Van dat verkeerde wereldbeeld zouden we ons moeten ontdoen, althans zo heb ik jouw titel begrepen. In Monyeball schreef je daar al over, in The Undoing Project nog veel meer. Jij laat in jouw mooie nieuwe boek zien dat impulsiviteit, emoties en eigenwijze weerstand wel degelijk deel uitmaken van ons denken. Die delen moeten we herkennen en zichtbaar maken. Alleen zo kan ons vermogen tot oordelen en beslissen erop vooruit gaan. Dat is de kern van jouw boek. Toch enkele kritische opmerkingen als het mag. Jij begint vreemd (eerste hoofdstuk) en jouw boek mist een goed einde (laatste hoofdstuk). De ondertitel, vind ik, is sterk overdreven want of die vriendschap die in de herfst van 1969 ontstond de wereld heeft veranderd, daarover heb ik na de economische crisis van tien jaar geleden en politieke ontwikkelingen van de laatste jaren zo mijn twijfels. Of om het scherper te zeggen: ‘Ik geloof er geen snars van’. Maar de rode draad van jouw boek is ijzersterk en je maakt op een verhalende manier duidelijk dat politiek, instituten en mensen van fouten moeten leren. 


Dank je wel.

Grote groet, -Harrie

Lewis, M.(2017). *The Undoing Project. A Friendship that Changed the World*. London: Allen Lane/Penguin Random House. 368 pagina’s. €29,99.

Kahneman, D. (2011). *Thinking, Fast and Slow*. London: Penguin Books. 512 pagina’s. €14,99.


