
# GEKLEURD RECHT
	

Amsterdam, oktober 2017


Beste Richard Rothstein,


Zo halverwege jouw formidabele ‘The Color of Law’-boek schrijf je over Andrew Wade, een Afrikaans-Amerikaanse handelaar in elektrische spullen, een net uit Korea teruggekeerde veteraan, die in 1954 een huis zoekt in Louisville, Kentucky. In de zwarte buurt kan hij geen geschikte woning vinden. Een blanke vriend koopt dan voor hem en zijn jonge gezin een huis in een witte buitenwijk van die stad. Op de dag dat deze jonge familie erin wil trekken, vormt zich een vijandige menigte voor het huis. Een kruis wordt aangestoken en ’s avonds vliegt er een steen door de voorruit met de tekst ‘Neger wegwezen’, later ook nog gevolgd door tien schoten door het keukenraam. Zo gaat het een maand lang door tot het huis wordt opgeblazen. De politie staat erbij en kijkt er naar. Alleen Andrew Wade zelf wordt opgepakt vanwege opruiing en de blanke vriend wordt veroordeeld omdat hij het huis niet had mogen doorverkopen aan een zwarte familie. Zijn blanke vriend krijgt vijftien jaar gevangenisstraf opgelegd. Jouw boek staat vol met deze verhalen die je steeds bij de keel grijpen. Jij weet er een indringend geheel van te maken. Jij laat zien hoe de segregatie tussen het blanke en zwarte deel van de bevolking tot stand kwam en het land in honderd jaar systematisch is verkaveld. Jij laat zien dat de scheiding tussen blank en zwart (zo kenmerkend voor jouw land) niet het resultaat is van persoonlijke keuzes of toeval, zoals zo vaak wordt gedacht en gezegd; het idee, zeg maar, dat slechts enkele witte families besluiten om een buurt te verlaten, dat daardoor het aantal zwarte families toeneemt en dat daarom veel witte families de buurt uitvluchten, dat zwarten niet willen trouwen of liever met elkaar willen wonen etc. Nee, jij bent heel duidelijk en draait er niet omheen: segregatie is met wetgeving en overheidsbeleid afgedwongen en talloze partijen op allerlei fronten speelden hierin openlijk mee. Segregatie is het resultaat van een veel grotere gemene deler, die van systematische discriminatie en uitsluiting over langere tijd. Sinds het einde van de 19e eeuw tot een kwart eeuw geleden maakt de Amerikaanse overheid zich op alle niveaus schuldig aan racisme, deelt het land gescheiden in en beslist zo waar witte Amerikanen moeten wonen en waar het zwarte deel van de bevolking. Jou gaat het niet om die schrijnende, individuele verhalen, hoe belangrijk jij die ook vindt en hoe sterk die jou boek ook maken. Het gaat jou om de lappendeken en de rol die de overheid tijdens deze nationale herverkaveling speelt. Niet zo lang geleden verklaarde de hoogste Amerikaanse rechter nog dat segregatie het product is van persoonlijke keuzen (de facto-segregatie) en niet van overheidsingrijpen met constitutionele gevolgen(de jure-segregatie). Eigenlijk bedoelde die rechter dat wij segregatie langzaam hebben ontdekt. Jij kijkt daar anders tegen aan. Dat beleid, waar honderd jaar lang sprake van was, heeft segregatie gecreëerd en gaat in alle opzichten in tegen de Constitutie en de Amerikaanse grondrechten. Met de sociale gevolgen heeft de Amerikaanse samenleving nog dagelijks te maken. 



Na de afschaffing van de slavernij tot aan het begin van de twintigste eeuw leefde het zwarte deel van de Amerikaanse bevolking in betrekkelijke rust. Aan het begin van de twintigste eeuw verandert dat. Wanneer in 1917 in Rusland de revolutie uitbreekt, wordt in het verruimen van private huisvesting een goed middel gezien om mensen aan het kapitalistische systeem te binden en opstand te voorkomen. Vanaf de jaren dertig is bovendien de krapte op de Amerikaanse huizenmarkt groot en wordt er door de overheid op brede schaal in huizen geïnvesteerd. De mogelijkheden daartoe zijn enkel voor de blanke Amerikanen weggelegd. Vanaf die tijd krijgt de segregatie in alle projecten en op allerlei manieren openlijk vorm. De atmosfeer van maatschappelijke en culturele scheiding en van zwarte inferioriteit spreidt zich langzaam maar zeker uit over het hele land en presidenten (waaronder Wilson en Roosevelt) dragen daaraan bij. Overheden zoeken antwoorden op de vraag hoe witte en zwarte bevolkingsgroepen van elkaar zijn te scheiden en als ze uit elkaar wonen hoe die scheiding goed in stand is te houden. En zo komen er getto’s en slums om de zwarte bevolking te huisvesten en ze als het ware van de buitenwereld af te sluiten. Je noemt ze zo omdat niet alleen het gemeenschapsleven maar ook de zwarte bevolking toegang tot werk en sociale ondersteuning wordt onthouden. In alles moet voorkomen worden dat zwarten in de witte buurten gaan wonen en blanken met zwarten worden geconfronteerd. Voor de blanke bevolking zijn er hypotheekmogelijkheden die er niet voor de zwarte bevolking zijn, behalve voor woekerprijzen waar ze nooit meer vanaf komen. Blanke buitenwijken worden er opgezet en snelwegen houden de zwarte bevolking hier buiten. Tot 1962 zijn er federale fondsen die discriminatie op de huizenmarkt in stand houden. In alles is duidelijk dat nationale, federale en lokale overheden de zwarte bevolking als een lagere kaste zien en de segregatie de verbinding is met de slavernij.

 

Vanaf halverwege de jaren vijftig tot einde jaren zestig worden er in Amerika wetten aangenomen die een einde moeten maken aan verschillen in mogelijkheden qua transport, stemmen, opleiding en werk. Echter, een einde maken aan de segregatie en de opdeling van het land, is een heel ander verhaal. Pas eind jaren zestig wordt er een wet aangenomen waarmee Afrikaanse Amerikanen kunnen gaan wonen waar ze willen en kunnen kopen wat zij zich kunnen veroorloven. Die wet kan natuurlijk niet de wereld veranderen want die was ondertussen al volledig in scene gezet. De achterstand en grote ongelijkheid in inkomen en, vooral, bezit hebben dan reeds hun duidelijke vorm gekregen. Eind jaren zeventig stagneren de inkomens van alle Amerikanen. De meeste zwarte Amerikanen huren een huis en als ze al een huis hebben is de waarde ervan een fractie van de ‘blanke’ huizenprijzen. De afname van discriminatie vertaalt zich niet in een opwaartse mobiliteit want als je in de onderklasse van de zwarte bevolking wordt geboren, is hard werken, verantwoordelijkheid, onderwijs, ambitie en geluk niet voldoende om vooruit te komen. De grote ongelijkheid is stabiel en in jouw analyse schuw je harde en duidelijke taal niet. Waarom zou je ook? Bijna de helft van de Afrikaanse Amerikaanse families heeft twee generaties lang in arme buurten gewoond ten opzichte van 7% van de blanke bevolking. Veel van de sociale problemen waar de binnensteden van Amerika nu nog mee te maken hebben, zijn het gevolg van discriminatie en segregatie. De gevolgen van opgroeien in arme buurten is misschien nog wel sterker dan in armoede zelf opgroeien. Jouw boek vind ik zo goed omdat je zo duidelijk laat zien hoe ongelijkheid tot stand komt, wordt gereproduceerd en wat er daarbij meespeelt. En misschien ook wel dat je er fijntjes op wijst dat geschiedenis vaak ten onrechte wordt geschetst als een lange, lineaire lijn naar vrijheid en rechtvaardigheid. De jaren na de afschaffing van slavernij was een redelijke goede periode voor de zwarte bevolking. In de twintigste eeuw verandert dit en wordt de segregatie systematisch ter hand genomen, ook al zijn er tot in de twintiger jaren buurten te vinden waar verschillende bevolkingsgroepen met en naast elkaar wonen. Daar waar zoveel personen en partijen verantwoordelijk zijn voor segregatie, zijn ook weer zoveel personen en partijen verantwoordelijk voor de verdere integratie van deze bevolkingsgroep binnen de Amerikaanse samenleving. Aan het begin van jouw boek schrijf je al dat het de constitutionele verantwoordelijkheid van alle Amerikanen is om de systematische segregatie aan te pakken. 
Na het lezen van jou boek kijk je wel anders tegen de recente rassenrellen in Ferguson, Baltimore, Milwaukee en Charlotte aan. De segregatie heeft, stel je vast, wel degelijk constitutionele implicaties en ik denk nu dat je gelijk hebt. Op basis van de Grondwet en de grondrechten had de Amerikaanse overheid op alle niveaus (nationaal, staat en lokaal) de rechten van de zwarte bevolking moeten erkennen en moeten ingaan tegen hoe er langere tijd breed over bevolkingsgroepen en rassenscheiding werd gedacht. In plaats van zo’n kritische houding heeft ze racisme en discriminatie juist bevestigt en versterkt en dat, je laat het heel duidelijk zien, actief en agressief. 
Jij zegt dat we ons er geen voorstelling van kunnen maken hoe de samenleving in elkaar had gezeten als de regering dit niet had gedaan en als de staten en gemeenten hier tegenin waren gegaan. Wat was er gebeurd wanneer ze hun wettelijke en morele verplichtingen waren nagekomen ten opzichte van de verschillende bevolkingsgroepen? Wat was er gebeurd als de rechtelijke macht, de kerken, de universiteiten, de ziekenhuizen, de politie, de banken en verzekeringsmaatschappijen, de schoolbesturen en de stadsplanners niet voor een gesegregeerde maar juist voor een geïntegreerde samenleving hadden gekozen? Hoe had het land er dan uitgezien? We zullen het nooit te weten komen. Maar met jouw boek kunnen we wel een hele duidelijke voorstelling maken hoe deze verkaveling tot stand is gekomen. Wil je wat tegen segregatie doen dan moet die geschiedenis niet zijn vergeten. 


Dank je wel.


Grote groet, -Harrie Jonkman


Rothstein, R.(2017). *The Color of Law. A Forgotten History of How Our Government Segregated America*. New York/London: Liveright/W.W. Norton & Company. 368 pagina’s. €23,99.

