
# DE KEUS IS AAN ONS	


Amsterdam, december 2017


Beste Suzan Neiman,


De afgelopen week heb ik wat achter je aan gezeten. Dat klinkt niet netjes, dus moet ik je eerst rustig uitleggen wat het geval was. Ik lag met een longontsteking op bed en had niet veel zin om daar buiten wat te doen. Wel kon ik jouw nieuwe boek ‘Verzet en rede in tijden van nepnieuws’ in stukjes lezen. Tegelijkertijd kon ik de andere boeken die ik van jou heb en onder handbereik lagen, erbij pakken. ‘Morele helderheid. Goed en kwaad in de 21ste eeuw’, bijvoorbeeld, heb ik alweer een paar jaar geleden met een studiegroepje gelezen en over deze gids voor volwassen idealisten was ik bijzonder enthousiast. Je moet je, schrijf je in dat boek, niet neerleggen bij onnadenkendheid en gebrek aan redelijkheid. Het is goed een ideaal te hebben voor een betere wereld, je daarvoor in te zetten en verantwoordelijk te voelen en in staat te zijn te oordelen. De Verlichting, met het streven naar geluk, redelijkheid, eerbied en hoop, heeft ons eerder laten zien het niet gaat om bij de feiten neer te leggen maar dat idealen wel degelijk wat opleveren. In ‘Afgezien van de feiten’ gaat ook weer over de kloof tussen hoe de wereld is en zou moeten zijn en laat je ons via Kant, Eichmann en Job zien hoe we over moreel handelen kunnen nadenken. Eerder schreef ik een recensie over jouw ‘Waarom zou je volwassen worden’ waarin je schrijft dat we weer moedig moeten durven zijn en ons moeten verzetten tegen maatschappelijke krachten die ons alleen maar klein willen houden. Met Rousseau roep je dat we de ketenen moeten afgooien, weg met de bloemsiersels eromheen. Je schreeuwt het bijna uit: Laten we volwassen worden.  Daarnaast heb ik, lamlendig als ik was, een tiental filmpjes van jou op Youtube bekeken met interviews en verschillende lezingen die op jouw website staan gelezen. Ik had echt het gevoel dat ik je achterna zat en daarvoor wil ik mij verontschuldigen. Maar jouw tegengeluid pepte mij in ieder geval geestelijk op.  



‘Verzet en rede in tijden van nepnieuws’ is niet jouw beste boek. Je schreef het snel op kort na de Amerikaanse verkiezingen. Je wilde begrijpen wat er was gebeurd en zocht antwoorden op vragen, in een tijd dat zoveel mensen naar een antwoord zochten. Je wilde anderen laten zien wat jij zag en met hen een alternatief delen. In ‘Verzet en rede’ laat je zien dat onze relatie met de waarheid is veranderd. Verzinsels en leugens zijn onderdeel geworden van ons dagelijks nieuws en post-waarheid is een nieuw fenomeen. Tegenwoordig wordt tegenover een zwaar rapport van een groep vooraanstaande wetenschappers een rapport geplaatst dat er net zo goed uitziet maar waarin het met de feiten niet zo nauw wordt genomen. Er zijn websites die een serieuze indruk maken maar eigenlijk van verzinsels aan elkaar hangen. Het kaf is tegenwoordig moeilijk nog van het koren te scheiden. Nepnieuws is natuurlijk ook weer niet helemaal nieuw want uit het recentere verleden zijn er ook een aantal goede voorbeelden te noemen, bijvoorbeeld toen de Bush-regering na de aanval op de Twin-Towers het nepnieuws over Sadam Hoesseins vernietigingswapens naar buiten bracht. Nauwelijks werd de moeite genomen om deze informatie goed te checken en vooraanstaande kranten deden aan de verspreiding van deze leugens mee. Die zinloze oorlog waar we ‘ingerommeld’ zijn, om met een vooraanstaande politicus uit mijn eigen land te spreken, kostte meer dan honderdduizend Irakezen en vijfduizend alliantie-soldaten het leven. Ik denk dat je gelijk hebt als je stelt dat die oorlog veel grotere gevolgen heeft gehad dan we waar we ons van bewust zijn. Nepnieuws is dus niet zozeer een nieuw verschijnsel. Nieuw is volgens jou wel de schaamteloze minachting voor de werkelijkheid en het feit dat de alternatieve werkelijkheid het meer en meer voor het zeggen heeft gekregen. De steun voor die alternatieve werkelijkheid komt niet zozeer van het arme deel van de bevolking, zoals je zou mogen verwachten, maar vooral van hen die onzekerheid ervaren. Mensen vooral die het nodige hebben opgebouwd en bang en angstig zijn delen daarvan te verliezen. Daarnaast speelt er in jouw Amerika (waar je geboren en opgeleid bent maar ondertussen al jaren niet meer woont)ook nog dat ingewikkelde racisme mee dat weer nadrukkelijk de kop op steekt. De zwarte mens wordt getolereerd zolang hij of zij maar niets bereikt. En dat is natuurlijk niet het geval als een zwarte president laat zien dat hem dat presidentschap goed afgaat. Jij verzet je tegen dit soort maatschappelijke en politieke ontwikkelingen. Als je je daartegen wilt verzetten, moet je wel weten hoe het intellectuele falen en de politieke hulpeloosheid van tegenwoordig tot stand is gekomen, vind jij. Je moet snappen hoe die neo-liberale wortels die zo diep in onze westerse samenleving zitten, tot stand zijn gekomen en je moet oog hebben voor alternatieven. Voor jou brachten Reagan en Thatcher processen op gang die uiteindelijk tot Trump en de Brexit hebben geleid. Onder leiding van deze twee hardliners is de deregulering van de markten in gang gezet, is de kracht van vakbonden gebroken, is de kloof tussen arm en rijk groter geworden en zijn alle waarden tot marktwaarden gereduceerd. De postwaarheid waar we nu mee te maken hebben, steunt volgens jou op drie pijlers: het neo-liberalisme (dat eigenlijk alleen maar marktwaarden erkend), de postmoderne filosofie (die ervan uitgaat dat achter elke aanspraak op waarheid een verborgen aanspraak op macht en eigenbelang schuil gaat) en de evolutiebiologie (die er in dit boek wat mij betreft wat onduidelijke bij hangt, maar die volgens jou ervanuit gaat dat we evolutionair zo zijn geprogrammeerd dat we zoveel mogelijk exemplaren van onszelf willen voortbrengen). Als we weer in reële alternatieven willen denken in plaats van in een alternatieve werkelijkheid, daar gaat het jou uiteindelijk om, is het goed om niet meer zo in stambelangen te denken maar om weer universeel te durven denken. Het alternatief ligt volgens jou, zoals je ook in jouw andere boeken naar voren hebt gebracht, in de Verlichting waar mensen als Kant, Rousseau en Voltaire wezen op het vermogen om gebruik te maken van universele waarden, waarheid en rechtvaardigheid. Rede en logica vereisen instrumenteel denken, maken gebruik emoties en persoonlijke overtuigingen maar ook van waarden en moraliteit. Vragen durven stellen en redenen willen vinden. Met de idealen moeten we onze ervaringshorizon weer durven oprekken en dan blijkt er veel meer mogelijk te zijn dan we nu denken. Waarheid en moraal moeten uit het beklaagdenbankje en universele idealen als mogelijkheden die gerealiseerd kunnen worden. 


We kunnen in de alternatieve werkelijkheid berusten of we kunnen ons ertegen verzetten, de keus is aan ons. Jouw keus is duidelijk en ik snap dat jij tegen de achtergrond van de Amerikaanse verkiezingen dit opgewonden neerschreef. Voor de Nederlandse uitgave voorzag je het later, iets geruster geworden door de uitslagen van de Nederlandse en Franse verkiezingen, van een nieuw voorwoord. In jouw boek zet je je vooral af tegen Trump en alles wat daarbij hoort. Hoe kan het ook anders met Kant als grote voorbeeld en Rawls als leermeester. In alles is Trump jouw tegenbeeld. “De enige persoon die ik ken die werkelijk de gedachte lijkt te belichamen dat er geen andere waarden bestaan dan marktwaarden, dat er geen verschil is tussen aanspraken op waarheid en aanspraken op macht, en wiens voornaamste doel is zoveel mogelijk kopieën van zichzelf te produceren, of in ieder geval van zijn naam, is Donald J. Trump”. De recente geschiedenis maakt duidelijker dan wat ook dat we voorbij de huidige tijd moeten durven denken en op zoek moeten naar alternatieven. Onlangs schreef een bekende filosoof in de Volkskrant een korte recensie over jouw boek. Hij was niet enthousiast en noemde het een lui boek. Dat ben ik niet met hem eens. Eerlijk gezegd vond ik zijn recensie een beetje lui omdat hij nauwelijks de moeite nam die snelschrift te verbinden met jouw andere werk. Dat geheel vind ik bijzonder inspirerend. Jouw optimisme en geloof in maatschappelijke en morele vooruitgang spreken mij aan. We moeten beter doorkrijgen wat er allemaal gelukt en wat er nog te doen is. Jij laat zien dat we in ons Europese deel van wereld erin geslaagd zijn om democratische waarden tot stand te brengen en konden zorgen voor sociale rechtvaardigheid. Oorlogen hebben plaats gemaakt voor vrede, er is (met alles wat er over te zeggen is) sprake maatschappelijke solidariteit en onderwijs, zorg en huisvesting gelden er als rechten. Daar moeten we inspiratie voor de toekomst uit halen. En uiteindelijk heb je gelijk dat we idealen niet moeten afmeten aan de realiteit, maar de realiteit moeten beoordelen aan de hand van idealen. Soms is het goed om ziek te zijn. 


Dank je wel.

Grote groet, -Harrie Jonkman

Neiman, S.(2017). *Verzet en rede in tijden van nepnieuws*. Rotterdam: Lemniscaat. 79 pagina’s. €9,95.

