
# WAT DENK JIJ ERVAN?


Amsterdam, januari 2018


Beste Geoffrey Galt Harpham,


In mijn land maken ze zich nogal druk om de vaderlandsliefde de afgelopen jaren. Sommigen vinden dat Nederland te weinig patriottisch en nationalistisch is en wat meer trots kunnen we best gebruiken. De Nederlandse vlag is daar het symbool van en zou wat vaker fier moeten wapperen. Niet voor niets dat er sinds kort zo’n vlag in de grote zaal van de Tweede Kamer (het politieke centrum van ons land) wappert. Het is natuurlijk geen grote vlag geworden zoals je dat bijvoorbeeld wel eens in een land als Turkije ziet. Een kleine, bescheiden en, vooral, goedkope vlag is genoeg. Zo’n vlag staat er nu en dat is nieuw. Ook bepaalde gemeenten willen er één ophangen in hun eigen, lokale raadzaal. Dit om de Nederlandse identiteit ook lokaal te beklemtonen. Ook andere, concrete voorstellen zijn naar voren geschoven. Scholieren zouden het Wilhelmus (het Nederlandse volkslied) moeten kennen en snappen. Kinderen verplicht naar ons nationale Rijksmuseum laten gaan en kennis laten maken met ons rijke (niet altijd even verheven!) verleden, is een derde voorstel. Maar gaat het wel om deze symbolen als je trots en eenheid onder de bevolking wilt nastreven? Zou de discussie niet veel meer  om de onderliggende principes van trots moeten gaan en zouden we niet meer moeten nadenken over hoe we dat moeten overbrengen? Jouw  ‘What Do You Think, Mr. Ramirez? The American Revolution in Education’ gaat eigenlijk over die vragen en laat op een subtiele wijze zien hoe jouw land daar een tijd lang heel succesvol in was. Het onderwijs stond daarin toen centraal. Dat hele onderwijssysteem, en zeker het hoger onderwijs, is tegenwoordig in verwarring met zijn grote verschillen van mening over de doelen en verwachtingen van het onderwijs, de methode van overdracht en de ongelijkheid die verder toeneemt. Dat was anders in de gouden periode van het algemeen onderwijs toen er toch wel degelijk een soort consensus bestond over de basisprincipes. Dat rijke culturele verleden roep jij terecht in herinnering in jouw mooie boek.


Niet lang geleden ontmoette jij meneer Ramirez, een wat oudere man die jou zijn verhaal van vijftig jaar geleden vertelde. Hij, deze meneer Ramirez, kwam toen als Cubaans vluchteling in Amerika aan, zonder geld, contacten en papieren. Hij kreeg een kleine beurs om een opleiding te volgen en koos toen voor een taalcursus. Daar keek zijn leraar Engels hem op een bepaalde dag aan toen ze een sonnet van Shakespeare bespraken en vroeg: “Nou, meneer Ramirez, wat denk jij ervan?” Het was de allereerste keer dat iemand hem zo’n vraag stelde. Die simpele vraag schudde hem wakker en zorgde er uiteindelijk voor dat deze meneer Ramirez ging studeren om uiteindelijk zelf hoogleraar te worden. Voor jou gaat het in dit verhaal niet alleen om een persoonlijk succes maar jij ziet dit als het resultaat van een weloverwogen politiek, van een onderwijssysteem dat zijn vinger naar het individu wijst en het beste uit een individu haalt. Dat idee kreeg in de twintiger en dertiger jaren van de vorige eeuw langzaam vorm als het algemene onderwijs, wanneer het er niet alleen meer is voor de aristocratie maar voor de brede bevolking. Eerder begrepen de stichters van Amerika (Adams en Jefferson) al de centrale rol van het onderwijs in de vooruitgang van de samenleving. Echter, het zijn vooral mensen als Horace Mann en John Dewey die er dan op wijzen dat het onderwijs niet alleen voor meer Amerikanen toegankelijk moet zijn maar ook dat het die bredere groep moet voorbereiden op deelname aan die samenleving. Het bracht een hele democratiseringsgolf op gang waarbinnen een belangrijke plaats was weggelegd voor dat algemene onderwijs. Die beweging werd helemaal sterk na de Tweede Wereldoorlog wanneer er ook in Amerika wordt gepleit voor maatschappelijke vernieuwing. In 1945 kwam er een publicatie uit die voor deze ontwikkeling model stond: ‘General Education in a Free Society’, ook wel het ‘Rode Boek’ genoemd. Daniel Bell, de beroemde Amerika socioloog, noemde dit ooit, zo schrijf jij, de ‘Bijbel van het algemeen onderwijs en het nationale symbool van de vernieuwing na de oorlog’. De taal ervan mag ons dan nu wat gedateerd in de oren klinken, de principes, waar mensen als Ahrendt en Cassirer zich zeer bij thuis voelden, staan nog recht overeind. Jij ziet dat onderwijs als een grote, brede advertentie voor openheid, vrijheid, gelijkheid en mogelijkheden, dat bovendien de buitenwereld duidelijk moest maken waar een welvarend land als Amerika toe in staat is: een meritocratisch systeem met oog voor het belang van de samenleving waarbinnen mensen laveren tussen individuele zelfrealisatie en maatschappelijke betrokkenheid. Dat onderwijs moest expliciet toegankelijk zijn voor minderheden en immigranten, mensen met achterstanden zoals Mr. Ramirez, die persoonlijk werden aangesproken om een mening te vormen. Dit mening vormen aan de hand van teksten, het interpreteren van de Bijbel maar ook van klassieke documenten zoals de Constitutie en de Bill of Rights, zit natuurlijk ook wel opgesloten in de Protestantse genen van de Amerikanen. De kracht zit hier, volgens jou, ook niet zozeer in het afdwingen maar veel meer in samen nadenken over hoe individuele intelligentie is aan te spreken. Het democratisch experiment, het basisprincipe van het Rode Boek, kan alleen overleven als mensen feiten weten te interpreteren, respectvol met elkaar van gedachten wisselen en er rekening wordt gehouden met het belang van iedereen. Die wijsheid, zo essentieel voor democratie, leer je in het onderwijs en met de Engelse taal. Ik denk dat je gelijk hebt als je zegt dat Mr. Ramirez niet in de eerste plaats werd uitgenodigd om iets te zeggen over de betekenis van Shakespeare’s gedicht maar dat hij eigenlijk werd uitgenodigd om op gelijke voet deel te nemen aan een nationale conversatie. De taal moest Mr Ramirez de cognitieve en politieke vaardigheden geven om daaraan mee te doen. Dat begreep Ramirez’ leraar heel goed. De algemene toegang tot onderwijs zorgde er verder voor dat grote groepen ook na het voortgezet onderwijs nog onderwijs volgen. Dat onderwijs was dan breed opgezet en richt zich op de ontwikkeling van ‘heel de mens’. De ideeën van algemene toegankelijkheid, individuele zelfrealisatie en maatschappelijke betrokkenheid kwamen natuurlijk onder druk te staan wanneer dit tijdens de Koude Oorlog als te democratisch werd beschouwd en te veel gericht op sociale mobiliteit, gelijke verdeling van middelen en het belang van de geesteswetenschappen. Dat was niet meer zo zeer wat de samenleving nodig had. Er kwamen kleine scheurtjes in deze Amerikaanse droom die allengs groter worden. Het resultaat en dat wat het onderwijs oplevert werden belangrijker, eerst voorzichtig maar steeds duidelijker.       


Die principes en praktijken van het algemeen onderwijs die jij in jouw boek beeldend beschrijft, zijn wat anders dan het gebruik van de vlag, het zingen van het volkslied of het bezoek aan een nationaal museum. Jij bent je er zeer van bewust dat het wiel niet opnieuw moet worden uitgevonden en dat de taal van die tijd niet meer bij deze tijd past. De kern blijft overeind staan en bepaalde fundamentele principes zijn nog steeds ondersteunend voor de samenleving. Dat Rode Boek was het nationale plan hiervoor en moest er voor zorgen dat mensen zich betrokken voelen bij die samenleving en zo moest die nationale democratische identiteit worden opgebouwd. Wanneer ik jouw boek lees lijkt het wel alsof het onderwijs toen algemeen toegankelijk was voor iedereen. Zover ik weet was die toegankelijkheid voor het zwarte deel van de Amerikaanse bevolking in ieder geval helemaal niet zo groot. Daar waar zij naar het onderwijs konden, was dat in zwarte scholen in zwarte wijken. Jij wilt met jouw boek aandacht vragen voor het onderliggend principe achter de Amerikaanse revolutie in het onderwijs. Dit is geen symboolpolitiek van vlag, volkslied of een nationaal museum maar een groot en warm respect voor een gouden periode waarin werd gedacht over ‘heel de mens’ en ‘moreel burgerschap’. Het gaat jou om het pedagogische, het onderwijskundige en de culturele waarde van het algemeen onderwijs en de taal in het bijzonder waarmee mensen een kritisch perspectief leren, kunnen verbeelden en algemene waarden en culturele verschillen inzien. Die democratische principes onderbouwen nog steeds het burgerschap, laten zien hoe er met verschillen kan worden omgegaan en hoe persoonlijke vrijheid en rechtvaardigheid op elkaar kunnen worden afgestemd. Jouw boek laat zien wat er voor nodig is, hoe mensen kunnen worden voorbereid op een maatschappelijk principe en hoe de belofte daarvan  kan worden gerealiseerd. Jou gaat het niet om het overbrengen van basiskennis of een lijst van iconische boeken die iedereen moet lezen. Jij hebt een veel dynamischer beeld voor ogen, open en pluralistisch, waarin wetenschap en wiskunde, sociale wetenschappen en talen met elkaar een wat onsamenhangend en incompleet geheel vormen. Maar wel zo dat een nieuwe generatie een interpreteerbare tekst als die van Shakespeare voorgelegd krijgt en iedere nieuwe Ramirez wordt uitgenodigd om zijn of haar mening te geven, in de wetenschap dat hij of zij individuele rechten heeft en in een land woont met constitutionele rechten: het trotse principe dat meer is dan een symbool dat fier wappert in de wind.    


Dank je wel.


Grote groet, -Harrie Jonkman


Harpham, G.G.(2017). *What Do You Think, Mr. Ramirez? The American Revolution in Education*. Chicago: The University of Chicago Press. 230 pagina’s. €23,22.

