
# OVER WERK GESPROKEN


Amsterdam, februari 2018


Beste Joop Berding,


Jij bent wijsgerig en historisch pedagoog, werkte in het onderwijs, welzijn en beleid en vervolgens weer als docent bij de Hogeschool Rotterdam. Je promoveerde bijna tien jaar geleden op John Dewey en die interesse delen we in ieder geval met elkaar. Vlak voor jouw pensioen bracht jij de bundel ‘Ik ben ook een mens. Opvoeding en onderwijs aan de hand van Korczak, Dewey en Arendt’ uit. In dat boek ga je in gesprek met deze drie, originele denkers. Janusz Korcak (1878-1942) was de Poolse kinderarts, kinderboekenschrijver en de pedagogische hervormer die met allerlei vormen van kinderparticipatie experimenteerde. De Joodse kinderen uit zijn weeshuis werden door de Duitsers opgepakt en Janusz Korcak weigert ze in de steek te laten. Hij trekt ze mooie kleren aan en geeft ze waardevolle spullen mee voordat ze worden opgepakt, meegevoerd en in Treblinka om het leven worden gebracht. John Dewey (1859-1952)is een van de grote Amerikaanse filosofen die over een groot aantal onderwerpen boeken schreef. Bij elke politieke discussie wachtte iedereen op wat John Dewey ervan vond. Hij is natuurlijk ook de grote trekker van het progressieve onderwijs dat begin van de twintigste eeuw opkomt. In dat boek besteed jij ook aandacht aan Hannah Arendt (1906-1975), de tegendraadse Duitse filosofe die in de vijftiger jaren doorbreekt. Drie originele denkers die elkaar, denk ik, niet hebben gekend. Alle drie, hoe verschillend ook, hadden ze oog voor het praktisch handelen van de opvoeder en onderwijzer en de concrete situatie die hen dwingt om oplossingen te zoeken. Van die drie is Hannah Arendt misschien wel de meest filosofische en degene die het minst expliciet over opvoeding en onderwijs heeft geschreven. Toch bouw jij, met een groepje medestanders, in ‘Aan het werk met Hannah Arendt. Professionals in onderwijs, zorg en sociaal werk’ voort op haar werk. In de academische wereld, zo stel je vast, is de belangstelling voor haar werk bijzonder groot en zijn er hele bibliotheken volgeschreven. Maar deze academische literatuur is zwaar en alleen op filosofen gericht. Aan de andere kant is er binnen de journalistiek ook veel belangstelling voor haar werk en krijgt ze een soort cult-status. In haar werk is, zo dacht je, meer inspiratie te vinden voor professionals in het onderwijs, en nu ook zorg en sociaal werk. Met haar inzichten zouden deze professionals wel eens wat meer grip op hun werk met kinderen, patiënten en cliënten kunnen krijgen. 


Ten opzichte van een aantal klassieke professionals (de arts, de jurist, de priester of dominee) ontbreekt het de moderne professionals in het onderwijs, de zorg en het sociale domein aan een stevig en duidelijk kennisbestand. Hun werk is dynamisch, hectisch en altijd anders dan je denkt. Hun bestuurlijke achterban is veel zwakker dan die van de klassieke professionals. Het werk van de moderne professional is de laatste jaren nogal onder druk komen te staan. Hun autonomie verdwijnt en hun werk wordt meer en meer gecontroleerd, beheerst en op resultaten beoordeeld. Van boven af stellen hun bazen hun eisen en van onder op vertelt de directe omgeving wat ze moeten doen. En alsof dat nog niet genoeg is, neemt de invloed van de markt en de bureaucratie verder toe en komt de eigen positie van de professional steeds meer in de verdrukking. Daarom zijn er in deze tijd voor deze professionals twee vaardigheden van het grootste belang. Aan de ene kant moeten ze kunnen reflecteren op hun eigen situatie en op hoe ze daarin moeten functioneren. Tegelijkertijd is ook het vermogen om zelf na te kunnen denken over de normatieve aspecten van het werk onont-beerlijk. Juist hier heeft Hannah Arendt volgens jou wat in te brengen. 
In jouw boek wordt een aantal keren op het onderscheid gewezen dat Arendt maakt tussen arbeiden, werken en handelen, ook in het deel over onderwijs. Bij arbeiden gaat om de biologische processen van het menselijke lichaam en de cyclische processen van het huishouden; bij werken gaat het om het doelgericht inrichten van de wereld met z’n gebouwen, dingen en netwerken; en bij handelen, waar het Arendt vooral om te doen is, gaat het om het aangaan van relaties en het spreken over zaken die iedereen aangaan en waarin we, heel fenomenologisch, ‘aan elkaar verschijnen’. Het handelen van mensen, zoals zij zo mooi zegt, als een tafel waaromheen mensen zitten. Hier heeft die leerkracht de professionele verantwoordelijkheid om op die tafel cultuurgoederen te leggen waar jongeren mee in aanraking kunnen komen en waarover ze met elkaar in gesprek gaan. Zo leren ze de wereld kennen en lopen ze als het ware de wereld in. Het gezag heeft het in de moderne wereld na de religie en de traditie ook moeilijk, zeker in de opvoeding en het onderwijs. Gezag moet niet gezien worden als een individuele competentie maar iets dat tot stand komt in een gemeenschappelijke wereld. Daarvoor moet de professional naast vakkennis en didactische vaardigheden over praktische wijsheid beschikken waarmee hij of zij steeds opnieuw kan beginnen en waarbij geduld, vertrouwen, tact en standvastigheid ondersteunende eigenschappen zijn. 
In de zorg en het sociale domein kunnen professionals zich ook aan Hannah Arendt optrekken. Daar gaat het over de eigen kracht van cliënten waarover iedereen wel beschikt, als ze het maar zelf willen en kunnen zien. Netwerken moeten worden aangesproken en problemen opgelost en langzaam verdwijnt de vrije ruimte tussen professional en cliënt, raakt de hulpverlener los van de concrete leefwereld en situatie van de cliënt en verdwijnt de eigen verantwoordelijkheid en regie. De professionele ruimte is beheersbaar gemaakt en er is minder ruimte voor gesprek, het stellen van vragen, zelf nadenken over de doelen die moeten worden nagestreefd en wat we er zelf van kunnen maken. De moderne professional van tegenwoordig heeft het steeds moeilijker om te leven te midden van anderen en om te laten zien wie ze zelf zijn.   


Hannah Arendt schreef over talloze onderwerpen boeken, waaronder Joden, vluchtelingen, totalitarisme, revoluties, vrijheid, geweld, de menselijke conditie, het kwaad en het denken. Het is moedig van je dat je haar gevarieerde werk voor de Nederlandse professional toegankelijk maakt. Haar filosofie is geen systematische filosofie die zich makkelijk in enkele losse elementen laat samenvatten. Het gaat haar om hoe mensen in de wereld staan, de mogelijkheden en voorwaarden om in vrijheid te leven, het kwaad dat die vrijheid bedreigt, over zelfstandig denken en oordelen. In alles wat ze deed bleef zij een buitenstaander, in alles de non-conformist. Naar haar rustige, tegendraadse blik kijk ik graag als ik achter mijn bureau zit en mijn boekenkast inkijk. Met haar politieke verhalen wilde ze mensen inspireren en uitdagen. Jouw boek vertilt zich niet. Jij wilt met jouw medeschrijvers leraren uitdagen om buiten de beperkingen en grenzen zelf na te denken. De professionals in de zorg en het sociale domein moeten zelf vragen durven stellen en in concrete situaties oplossingen vinden voor mensen die ondersteuning nodig hebben. Moderne professionals zijn, onderstreep je, meer dan uitvoerders en hun werk is meer dan het uitstrooien van een emmer methodische interventies. Zij moeten goed nadenken over hun eigen handelen en de context waarin dat plaatsvindt, zoveel mogelijk zichzelf blijven en hun professionele ethos overeind houden. Tekstueel vond ik jouw boek niet altijd even sterk en de uitgever had wel wat strenger mogen zijn. De voorbeelden en casussen waar elk hoofdstuk mee begint, zijn niet altijd sprekend. Als in het boek zo vaak het onderscheid wordt gemaakt tussen arbeid, werk en handelen en er steeds op wordt gehamerd dat het vooral om handelen moet gaan, is de titel weer niet zo treffend gekozen, vind ik. Met Hannah Arendt ga je niet aan het werk, met haar ga je in gesprek. Wat zou ze van zo’n boek vinden, vroeg ik mijzelf wel af? Je legt je niet bij de huidige omstandigheden neer en je zoekt de vrije ruimte. Hopelijk zet het mensen aan het denken en inspireert het om eens een boek van haar zelf te lezen, of misschien wel die mooie biografie van Elisabeth Young-Bruehl ‘Hannah Ahrendt. For love of the world’(1982) of een mooi gedicht van haar, want zo kon ze ook heel mooi aan je verschijnen.


Dank je wel.


Grote groet, -Harrie Jonkman


Berding, J. (2017). *Aan het werk met Hannah Arendt. Professionals in onderwijs, zorg en sociaal werk*. Leusden: ISVW Uitgevers. 222 pagina’s. €19,95.

