
# DE POSSIBILIST 


Amsterdam, maart 2018


Beste Steven Pinker,


In 1784 gaf Immanuel Kant in een kort artikel antwoord op een eenvoudige vraag: Wat is Verlichting? In dat artikel valt hij met de deur in huis en hier is hij wel meteen heel duidelijk “Verlichting is het uittreden van de mens uit de onmondigheid die hij aan zichzelf te wijten heeft. Onmondigheid is het onvermogen zich van zijn verstand te bedienen zonder de leiding van de ander.” Kant is nog optimistisch over de mens die zijn onmondigheid van zich afschudt en de moed heeft zijn eigen verstand te gebruiken: Sapere aude! Dat optimistische beeld zijn we, volgens jou, kwijtgeraakt met Nietsche, Horkheimer en Adorno, Foucault en al die anderen voor wie macht en het instrumenteel gebruiken van de rede belangrijker leken te zijn. Hooggespannen verwachtingen hebben plaats gemaakt voor de schaduwzijden van de Verlichting. Maar jij, Steven Pinker, zoekt  weer aansluiting bij het oorspronkelijke optimisme waarmee het allemaal is begonnen. Het donkere wereldbeeld waar we elkaar in hebben geduwd en waarbinnen we leven vraagt hier om. Je bent glashelder: er is helemaal geen reden om te denken dat het einde van de tijd nabij is. We hebben het helemaal bij het verkeerde eind als we in dat zwarte denken blijven steken. Jij bent een cognitief psycholoog en hebt over taal, het menselijk brein en evolutie kloeke boeken geschreven voor een breed publiek. De laatste jaren zijn jouw boeken maatschappelijker geworden. Zo schreef je een paar jaar geleden nog ‘The Better Angels of our Nature: Why violence has declined’ (2011) waarin je de geschiedenis van geweld beschrijft en laat zien dat de tijd waarin we leven, anders dan wij vaak denken, de meest vredig tijd ooit is. Dit optimistische denken zet jij door in jouw nieuwe boek ‘Enlightment now: The case for reason, science, humanism, and progress’ dat net is verschenen en veel aandacht trekt. Ook nu wil je dat we anders tegen de wereld aan gaan kijken. We moeten inzien dat de idealen van de Verlichting ons bestaan positief hebben beïnvloed en dat de rede, de wetenschap en het humanisme ons op alle fronten voortuitgang hebben gebracht. De idealen van de Verlichting moeten we opnieuw ontdekken, moeten in onze taal, concepten en perspectieven terugkomen en zijn nu meer nodig dan ooit.


De beste manier, denk je, om dat positieve perspectief overtuigend over te brengen is met tellen, grafieken en getallen laten zien hoe we er op allerlei gebieden op vooruit zijn gegaan. Dat is precies wat je doet in dit boek. Ik ben blij dat je mij als lezer daarbij niet enkel met losse cijfers achterlaat maar deze betekenisvol aan elkaar breit. Je laat zien dat de levensverwachting van mensen enorm is toegenomen. In 2015 is dat al 71,4 jaar en weinig mensen zijn zich hiervan bewust. Dat hangt weer samen met het feit dat in elk land de kindersterfte is afgenomen en de gezondheid in het algemeen beter is geworden. We weten hoe we met verschillende infectieziekten moeten omgaan, via vaccinatie, schoon water en rioleringssystemen bijvoorbeeld. Alleen al in de 20ste eeuw zijn er nog 300 miljoen mensen aan de pokken overleden en die infectieziekte kwam in de zeventiger jaren van die eeuw voor het laatst voor. Hongersnood kwam in de vorige eeuw nog op grote schaal voor, zoals in Rusland, China, Columbia en Noord-Korea. Nog steeds komt dat voor maar als het voorkomt niet meer op zo’n schaal als voorheen omdat we weten hoe we moeten verbouwen en er zich wereldwijd een ware groene revolutie voltrok. De welvaart in de wereld is sinds 1870 sterk toegenomen, ook in landen die tot voor kort arm waren. Meer dan de helft van de volwassenen in de wereld heeft nu een mobiele telefoon, je bedoelt maar. Tegelijkertijd is de extreme armoede sterk afgenomen ook al weten we over situaties in Haïti, Kongo en Soedan. Op het ethische terrein zie jij eveneens vooruitgang. Rijken zijn er wel flink op vooruit zijn gegaan, mogelijk te veel, maar de rest kreeg het met de technische ontwikkeling en globalisering ook een stuk beter. Wat de omgeving betreft hebben we te maken met overbevolking, vervuiling en opraken van natuurlijke hulpbronnen. Echter, waar landen het beter krijgen, zo laat je zien, neemt het aantal kinderen en de vervuiling af. Daar raken bronnen misschien op maar worden ook nieuwe mogelijkheden gezien. Als mensen meer middelen hebben en onderlegd zijn, geven ze, schrijf je, meer om de omgeving, zoeken ze manieren en vinden die om de omgeving te beschermen en kunnen ze de kosten daarvoor betalen. Handel, democratie, economische ontwikkeling, vredeshandhaving en internationale wetgeving hebben voor meer vrede gezorgd en het aantal oorlogsslachtoffers is over de langere termijn sterk afgenomen ook al doet het dagelijkse journaal je heel anders denken. Hetzelfde geldt voor het terrein van veiligheid waarbinnen het aantal moorden en verkeers- en werkslachtoffers sterk af is genomen. Terrorisme veroorzaakt op lokaal niveau ellende en angst maar als we het over de langere termijn bezien, kunnen we niet anders dan dit probleem relativeren. In 2015 leeft twee derde van de wereldbevolking in vrije of relatief vrije samenlevingen, honderd jaar geleden was dat nog maar een vijfde. Grote niet-vrije landen, Rusland en China, zijn minder onderdrukkend dan ze waren ten tijde van Stalin en Breznjev en Mao. De rechten van minderheden, vrouwen en mensen met andere seksuele geaardheid zijn wereldwijd toegenomen en het onderwijs, het vlaggenschip van vooruitgang, zorgt voor economische groei, democratie en vrede. De verwachting is dat ongeletterdheid aan het einde van deze eeuw volledig is verdwenen. Met het langer, gezonder, veiliger, vrijer, rijker en wijzer leven neemt de kwaliteit van leven ook toe nu we betaald op vakantie kunnen en pensioenen en technologieën hebben die ons meer tijd geven om tijd met anderen door te brengen en intellectueel en creatief te genieten. Net als geluk overigens, waar mensen zelf vaak heel anders over denken. En de grote bedreigingen (nucleaire oorlog en klimaatverandering) zijn dan misschien niet opgelost maar met onze kennis wel oplosbaar. 


Je bent wel erg van jouzelf overtuigd. Tegelijk moet ik je zeggen dat je mij wel wakker schudde met dit lange overzicht, al werd ik er uiteindelijk misschien wel een beetje moe van. Nadat je jouw ideeën over het belang van de idealen van de Verlichting hebt geïntroduceerd en vervolgens hebt laten zien hoe ze werken, trek je mij er weer helemaal bij wanneer je de drie kernelementen van de Verlichting verdedigt: rede, wetenschap en humaniteit. Mensen zijn rationele wezens die hun capaciteiten moeten gebruiken. We moeten ons er meer van bewust zijn dat het dagelijks leven voor de Verlichting vol zat met sterfte, plagen, kindersterfte, sadistische martelingen, slavernij en kruistochten op grote schaal. Het leven floreert nu, in ieder geval in de meeste vrije landen met menswaardige normen, mensenrechten, vrije markt, sociale uitgaven en juridische regelingen. In deze lijn moeten we verder denken en dan is het goed als we nieuwe maatregelen meer zien als wetenschappelijk experiment dan als sportcompetitie. Natuurlijk zijn we soms irrationeel maar het feit dat we dat zelf inzien komt ook omdat we rationeel zijn. We maken fouten en schatten dingen niet goed in, maar ook weer niet de hele tijd. Het is goed als we weten waar we staan en op bestaande kennis voortbouwen en het is goed als we een beetje denken als een Bayesiaan. Als jonge mensen meer in dat logisch en kritisch denken worden opgeleiden en we een meer open en gedurfde sfeer creëren op het werk, in de omgang met elkaar, in het debat en als we beslissingen nemen, dan ziet het er allemaal nog beter uit. Meer experimenteren en loskomen van vooringenomen politieke standpunten, daar gaat het jou om. Daarvoor is de wetenschap nodig die voor de vooruitgang in het leven, welvaart, de kennis en de vrijheid zorgde en dat ook in de toekomst zal doen. Die wetenschap heeft het moeilijk nu fundamentalisten er niet in geloven, bepaalde politici (links en rechts) te veel met zichzelf bezig zijn en veel wetenschappers zelf ook over de kracht van hun vak twijfelen. Toch is het nodig dat we allemaal weer wat meer wetenschappelijk gaan denken en zo de geest van de Verlichting serieus nemen. Echter, met wetenschap alleen komen we er niet. Het is nodig dat alle aspecten van het leven floreren en zo kom jij bij het humanisme terecht met z’n idealen van een lang, gezond, gelukkig, rijk en stimulerend leven. Een ideaal zoals we dat tegenkomen in de Universele Verklaring van de Rechten van de Mens, dat korte document vertaald in vijfhonderd talen en dat iedere nationale constitutie heeft beïnvloed. Natuurlijk ben je niet blind voor de problemen in de wereld en je somt ze kort op, al geef je er hier geen getal of grafiek bij. Je denkt tegendraads en als lezer wil je op bepaalde plekken graag met jou in discussie waar je het bijvoorbeeld over ongelijkheid hebt of vervuiling. Het is goed dat je het positieve en optimistische geluid laat horen nu het moderne leven het zo moeilijk heeft. Ik stel mij zo voor dat mensen als Bill Gates (dat weet ik) en Arjen Lubach (dat denk ik) jouw boek zullen omarmen. Mensen in de binnenlanden van Amerika en de buitengebieden van Engeland en Nederland overtuig je er niet mee. Daarvoor is jouw verhaal, denk ik, te rechtlijnig en heeft het te weinig oog voor conflict, tegenstrijdigheden en mededogen. Maar wat een gedurfd boek dat mij in ieder geval heel duidelijk die andere kant op wijst. 


Dank je wel.


Grote groet, -Harrie Jonkman

Pinker, S. (2018). *Enlightment now: The case for reason, science, humanism, and progress*. New York: Viking. 528 pagina’s. €20,99.

