
# DE KEERZIJDE VAN EEN GROOT IDEAAL	


Amsterdam, april 2018


Beste Kees Vuyk,

In ‘I, Daniel Blake’ (2016) geeft de Engelse regisseur Ken Loach ons een indringend beeld van de 60-jarige, kinderloze weduwnaar Daniel Blake die met de moderne samenleving in de clinch ligt. Loonarbeider Blake herstelt van een hartaanval en zijn dokter verklaart dat hij nog niet moet gaan werken. Zijn verzekering denkt daar echter heel anders over en zet hem onder druk om weer te gaan werken. De film laat de doodvermoeiende strijd van Blake met de bureaucratie zien. Het lijkt alsof Blake in een wereld zonder familie en vrienden leeft en hij moet zelf zijn problemen oplossen. De enige bij wie hij gehoor vindt is een jongere vrouw met kind. Zij leeft zelf ook aan de onderkant van de samenleving en kent haar dagelijkse problemen. Zij proberen elkaar te helpen maar dat lukt hen nauwelijks. Daniel Blake is een aardige, humoristische en fatsoenlijke man die gewoon niet zijn weg kan vinden in deze moderne en complexe samenleving. Toen ik de afgelopen week jouw bijzonder goede boek ‘Oude en nieuwe ongelijkheid. Over het failliet van het verheffingsideaal’ las, moest ik regelmatig aan die indrukwekkende film denken. Jij was lang universitair hoofddocent kunst- en cultuurbeleid en daarom denk ik ook dat je de film gezien hebt en begrijpt waarom ik hieraan moest denken. Jouw boek gaat over onze huidige gespleten samenleving die steeds meer te verdelen is in groepen winnaars en verliezers. Daar waar we in de vorige eeuw lang geloofden dat we met goede opleidingen ervoor konden zorgen dat onze samenleving evenwichtig zou worden opgebouwd, door talenten boven te laten drijven en ervoor te zorgen dat zij met de meeste talenten het voor het zeggen te zouden krijgen, komt nu zo langzamerhand heel duidelijk de keerzijde van die meritocratische gedachte bloot te liggen. Als we om ons heen kijken zien we dat er duidelijke scheidslijnen zijn ontstaan tussen hoogopgeleiden en laagopgeleiden; de ene groep plukt de vruchten van de grote, open samenleving die hen alle kansen biedt en de andere groep raakt steeds verder van die samenleving afgesloten. Het verheffingsideaal kan ondertussen al lang niet meer bieden wat ze ooit zo hoopvol beloofde. Gelijke kansen zijn er, volgens jou, alleen nog maar voor gelijken. In jouw boek laat je de grote samenhang zien en hoe het komt dat we denken zoals we tegenwoordig denken. 
   


Duizenden jaren van gelijkheidsdenken, honderden jaren van gelijkheidspolitiek en tientallen jaren van verzorgingsstaat konden er niet voor zorgen dat ongelijkheden die samenhangen met afkomst zijn opgelost. De feiten spreken ondertussen duidelijk voor zich. Hoogopgeleiden verdienen gemiddeld twee keer zo veel als laagopgeleiden en de topman van Shell verdient vijfhonderd keer zo veel als zijn werknemer op minimumloonniveau. In levensverwachting leven de hoger opgeleiden zo’n 6 à 7 jaar langer en wanneer er wordt gekeken naar in goede gezondheid leven is dat verschil veel groter. De deelname aan cultuur en politiek tussen hoog- en laagopgeleiden verschilt ook totaal. De kloof tussen beide groepen wordt breder en dieper en daarover maak jij je grote zorgen. De verschillen tussen beide groepen hangen samen met de opleiding die mensen hebben gevolgd. Het aantal hoogopgeleiden is na de Tweede Wereldoorlog sterk toegenomen. Was dat vijftig jaar geleden (1968) nog maar 14%, nu volgt bijna 40% hoger onderwijs. In onderzoek naar ongelijkheid wordt altijd gezocht naar opleiding en een aantal samenhangende variabelen die te onderzoeken zijn. Wij hebben er, schrijf jij, moeite mee om het in verband te brengen met intelligentie. Toch moeten we deze onderliggende factor onder ogen durven zien en meenemen als we de relatie tussen afkomst en opleiding willen onderzoeken. Jij bent je ervan bewust dat onderzoek dan een stuk ingewikkelder wordt en dat velen van ons er zich niet erg gemakkelijk bij zullen voelen. Toch moeten we intelligentie in de discussie over afkomst en opleiding betrekken omdat we dan de verschillen tussen hoger- en lager opgeleiden kunnen begrijpen. Je gaat in op het werk van cognitief psychologen en intelligentieonderzoekers en laat zien dat intelligentie ongelijk is verdeeld over de samenleving. Intelligentie hangt samen met het opnemen en verwerken van nieuwe informatie. Verschillen tussen mensen zorgen er voor dat we problemen cognitief, maar ook ethisch en esthetisch, verschillend benaderen. In jouw boek laat je zien dat we niet alleen afkomst en opleiding moeten verbinden met die onderliggende factoren maar ons ook nog moeten afvragen hoe we in een bepaalde tijd en cultuur met deze zaken omgaan. Tegenwoordig kan iedereen met voldoende intelligentie zichzelf ontwikkelen en er maatschappelijk op vooruit gaan. Dat wat vroeger voor een kleine groep haalbaar was, is nu voor een grote groep haalbaar en dat zie jij terecht als voordeel. Tegelijk heeft die grote groep hoogopgeleiden zich in z’n eigen subcultuur opgesloten en ook de laagopgeleiden zijn een met elkaar een eigen subcultuur gaan vormen. Daar waar vroeger deze twee groepen elkaar nog weleens tegen kwamen op verjaardaagsfeestjes in de familie, in de buurt, de kerk of binnen de grote volkspartijen, is daar ondertussen al geen sprake meer van. De levens spelen zich in hele verschillende omgevingen af. Meritocratie is nu het sociale contract dat de samenleving met zijn burgers afsluit en degene die het verdient heeft het voor het zeggen gekregen en ontvangt daarvoor beloning naar verdienste. Dat contract zorgde voor maatschappelijke welvaart en mobilisatie van talent. De meritocratie zorgde er ook voor dat er een enorme competitie op gang kwam met winnaars en verliezers en voor een verwijdering tussen groepen in de samenleving. Eerst tussen ouders en kinderen en later vooral tussen hoog- en laagopgeleiden. De afstand tussen deze groepen werd de afgelopen jaren alleen maar groter (ook omdat er niet meer tussen deze groepen werd getrouwd)en de maatschappelijke kansen werden per groep verdeeld. De aandacht ging vooral uit naar de hoogopgeleiden die met de kansen die ze kregen heel goed voor zichzelf konden zorgen. De sociaaldemocratie heeft het vooral moeilijk gekregen met de verwijdering tussen deze twee groepen en slaagt er maar niet in de band met de bevolkingsgroepen, waar ze oorspronkelijk uit is voortgekomen, vast te houden. Deze laagopgeleiden trekken zich terug in hun eigen, kleine wereld en zoeken onderdak bij meer populistische partijen die de sociaaleconomische problemen in een cultureel kader weten te plaatsen en complexe problemen voor hen behapbaar weten te maken.        


Onlangs werd bekend dat jij de Socrates Wisselbeker hebt gewonnen voor het meest urgente, oorspronkelijke en prikkelende Nederlandstalig filosofieboek van 2017, zoals de jury schreef. Die prijs begrijp ik heel goed en daar wil ik je van harte mee feliciteren. Die prijs is jouw verdienste. Je schreef geen klassiek, filosofisch boek maar je laat wel heel goed zien hoe een maatschappelijk perspectief tot stand komt, wat het oplost en welke nieuwe problemen er vervolgens weer achter schuil gaan. Je kijkt op verschillende manieren tegen maatschappelijke ongelijkheid aan en voegt er vervolgens een laag aan toe waar te weinig over wordt gesproken. Ik weet dat Sir Michael Young (de belangrijke Engelse sociaaldemocraat die na de Tweede Wereldoorlog het begrip meritocratie introduceerde in dat belangrijke sociologische boek The Rise of the Meritocracy uit 1958) vanaf het begin bang was voor de keerzijde ervan (per slot van rekening schreef hij een dystopie). In de gloriejaren van de Derde Weg van de Engelse sociaaldemocratie wees Young Tony Blair hier nog eens heel fijntjes op toen Blair en zijn omgeving alleen maar oog had voor de voordelen van het systeem . Jouw boek werkt de kritiek op de meritocratie verder heel goed uit, ook al heb ik de indruk dat in de literatuur die je gebruikt rondom intelligentie niet de meest moderne inzichten worden besproken en je in dit deel ook niet helemaal overtuigd van jezelf bent. In jouw maatschappelijke perspectief op het probleem daarentegen ben jij dat wel. Jij ziet duidelijk de voordelen in van de meritocratie van meer maatschappelijke welvaart en individuele mogelijkheden. Het meritocratisch perspectief heeft de samenleving ook opgedeeld en voor subculturen gezorgd die elk op hun manier naar de omringende wereld kijken en niet meer de mogelijkheden en onmogelijkheden van de andere groep zien. De macht en de kennis ligt tegenwoordig eenzijdig bij de hoogopgeleiden. Zij lopen vaak met de borst vooruit rond en zijn zich er nauwelijks van bewust dat hun succes veelal helemaal geen persoonlijke verdienste is maar iets is dat ze bij de geboorte hebben meegekregen. Die talenten en mogelijkheden hebben mensen als Daniel Blake niet. Zij misen mensen in de omgeving waar zij zich aan kunnen optrekken, die hen helpen en zeggen wat zij het beste in zijn omstandigheid kunnen doen. Misschien vragen we vandaag de dag wel te veel van sommige mensen en hoogopgeleiden moeten zich hier meer bewust van worden. Hedendaagse maatschappelijke ongelijkheid definieer jij zo vooral weer als een rechtvaardigheidsvraagstuk dat zo langzaam maar zeker een beter antwoord verdient op de vraag hoe we jongeren moeten opvoeden en wij met elkaar samen willen leven.  

       
Dank je wel.


Grote groet, -Harrie Jonkman

Vuyk, K. (2017). *Oude en nieuwe ongelijkheid. Over het failliet van het verheffingsideaal*. Utrecht: Klement. 288 pagina’s. €27,99.

