
# FEITEN TELLEN	


Amsterdam, mei 2018


Beste Ola en Anna Rosling,


Jullie vader zag ik niet eens zo heel lang geleden voor het eerst op de Nederlandse televisie. Op een ontwapende manier presenteerde hij allerlei inzichten in een zondagavondshow en ook daar liet hij merken hoe vaak wij het verkeerd hebben als het over de wereld gaat. Na die uitzending heb ik groot aantal Rosling-video’s bekeken. Soms werd zijn stijl mij te veel, moet ik eerlijk zeggen. Ik was niet de enige die hier naar keek. Hans Rosling was een graag geziene gast die diepgaande inhoud en vlotte presentatie goed wist te combineren. Steeds liet hij zien dat hij zijn werk graag deed en zocht hij manieren waarop hij toehoorders weer fris tegen de wereld aan kon laten kijken. Niets was hem te gek als hij er maar in slaagde om roest uit de ogen van mensen weg te krabben. Aan zijn pas verschenen boek ‘Feitenkennis. 10 redenen waarom we een verkeer beeld van de wereld hebben en waarom het beter gaat dan je denkt’, heeft hij anderhalf jaar lang met jullie gewerkt en daarin zet hij de feiten nog eens op rij. De boodschap is duidelijk: ons beeld van de wereld is beperkt en verouderd en er zijn tien duidelijke redenen waarom dat zo is. Jullie vader studeerde geneeskunde, was district-arts in diverse landen en deed langere tijd onderzoek naar de wisselwerking tussen economie, samenleving, gifstoffen en voedsel. Daarnaast was hij hoogleraar internationale gezondheidszorg en in die hoedanigheid gaf hij oktober 1995 in Stockholm college aan een groep jonge studenten over de misvattingen in de wereld. Op de fiets terug naar huis drong het tot hem door dat hij van het beeld van mensen over de wereld zijn levenswerk wilde maken. Dat deed hij meer dan twintig jaar.  


Mensen kunnen het niet laten om de wereld in tweeën te delen en zetten rijk tegenover arm. Rijk zijn dan de ontwikkelde landen in het westen (Noord-Amerika en Canada, Europa en Australië en Nieuw Zeeland) en arm is de rest, de ontwikkelingslanden (Afrika, Zuid-Amerika en Azië). Als er één ding is dat jullie vader duidelijk wilde maken, is het dat dat beeld misschien halverwege de jaren zestig nog wel klopte maar ondertussen volledig is achterhaald. De wereld is veranderd en wij willen dat maar niet zien. Dat kloofinstinct zit ons behoorlijk dwars. Veel beter is het om de wereld in vier niveaus in te delen. Niveau 1 waar mensen tot twee dollar per dag verdienen, niveau 2 tot 8 dollar per dag, niveau drie tot 32 dollar en tot slot niveau 4 waar mensen meer dan 32 dollar per dag verdienen. Zo komt het meer met de werkelijkheid overeen. Als we dan naar het aantal mensen kijken en ze verdelen over de wereld, kun je zeggen dat er een miljard mensen op niveau 1, drie miljard op niveau 2, twee miljard op niveau 3 en een miljard op niveau 4 leeft (postcode 1321). Zo krijg je een hele andere kijk op de wereld. De kloof is niet meer zo duidelijk, we moeten niet alleen naar de uitersten kijken en als je van boven naar beneden kijkt, moet je oog houden voor de verschillen. Dan is er nog iets anders waardoor we niet goed om ons heen kijken. Wij zijn vaak te negatief en denken maar dat alles slechter wordt. Maar dat is gewoon niet waar: het wordt gewoon steeds beter. Extreme armoede en kindersterkte zijn afgenomen en de gemiddelde levensverwachting is ondertussen wereldwijd 72 jaar. Jullie vader wilde het overdramatische en negatieve wereldbeeld doorprikken, vooruitgang zichtbaar maken en zo hoop creëren. Dan hebben we met z’n allen ook nog het idee dat de wereldbevolking er in een rechte lijn op vooruit blijft gaan. Ook dat is niet zo. Het aantal mensen neemt in eerste instantie toe. Tegelijkertijd neemt het aantal kinderen per vrouw wereldwijd af en dat zorgt ervoor dat vanaf het jaar 2100 de wereldbevolking op 11 miljard zal stabiliseren. Jullie vader zag de spectaculaire afname van het aantal baby’s per vrouw misschien wel als grootste verandering die zich tijdens zijn leven heeft voltrokken. Ontwikkelingen moeten we ons niet altijd in rechte lijnen voorstellen. Er zijn veel meer patronen te schetsen die dichter bij de werkelijkheid komen. Dan zijn we met z’n allen ook nog behoorlijk angstige wezens. Wij zijn bang voor van alles en ook dat vertroebelt onze realiteitszin. De kans om ten gevolge van natuurrampen om het leven te komen is behoorlijk afgenomen (0,1%), de kans dat je met het vliegtuig om het leven komt is heel klein (0,0000025%), en de kans om te overlijden ten gevolge van  moorden (0,7%) en terrorisme (0,05%) is ook klein. Dan hebben we nogal moeite om alles in een goede verhouding te zien. Éen incident of een afzonderlijk slachtoffer kan daar alleen al voor zorgen. Op dat incident of slachtoffer richten we al onze aandacht, soms teveel terwijl we nauwelijks beseffen dat grote veranderingen komen door goede basisscholen, goed opgeleide verpleegkundigen en vaccinaties en dat daarmee vooral in de niveau 1/2-landen grote gezondheidswinst kan worden behaald. Mensen categoriseren en generaliseren voortdurend om zo alles wat om hen heen gebeurt wat te kunnen structureren. Deze natuurlijke neiging zorgt er ook voor dat we soms verkeerde categorieën gebruiken. Daarom is het goed als we soms twijfelen over de categorieën, niet de verschillen tussen groepen zien maar ook de overeenkomsten tussen groepen en de verschillen binnen groepen. We moeten ook oppassen om te snel vanuit de meerderheid en uitzonderlijke voorbeelden te denken. We moeten oppassen voor het generaliseren van de ene groep naar de andere en voor het blindstaren op een voorbeeld. Tot slot, dat heeft jullie vader wel gemerkt in zijn leven, is het zo dat niemand automatisch de normale persoon is en al die anderen malle idioten. We hebben soms, ook zeer ten onrechte, het idee dat samenlevingen en culturen niet veranderen of kunnen veranderen, een soort eeuwig lot waar ze aan vastzitten Als je een beetje historisch besef hebt, weet je dat je eigen samenleving vaak ooit heel anders in elkaar heeft gezeten. Van andere landen denken we nog steeds dat het daar functioneert zoals dat vijftig jaar geleden het geval was. In het westen denken we dat wij er steeds maar verder op voortuitgaan en van anderen kunnen we ons dat helemaal niet voorstellen. We kunnen maar niet loskomen van dat oude, koloniale denken. Dat het over een tijdje wel eens heel anders zou kunnen zijn, houden we liever niet voor mogelijk. Daarom is het ook goed om oog te houden op langzame veranderingen, moeten we ons blijven bijspijkeren, soms met oudere personen praten en voorbeelden zoeken van veranderingen die plaatsvinden. Misschien is het wel omdat de wereld zo complex in elkaar zit en er zoveel om ons heen gebeurt de hele dag, dat we graag vanuit één perspectief denken en graag één oorzaak en één oplossing zien. Ideologen, deskundigen en activisten denken vaak vanuit één idee. Je kunt niet vanuit één overheid alle problemen oplossen, net zo goed als de markt dat niet kan doen. Jullie vader was hierin wat genuanceerder en voor hem was niet of of, maar allebei en het verschilt ook nog eens per geval. Als het allemaal niet loopt is het ook makkelijk om een zondebok aan te wijzen. Dan hoeven we in ieder geval niet naar onszelf te kijken. Vaak heeft het veel meer zin om naar het systeem te kijken en te weten hoe dat werkt in plaats van naar een individu te kijken. Dan gaat het, zeker bij successen, om de talloze mensen achter de bühne die er voor zorgen dat het allemaal draait. Mensen die naamloos samenlevingen bouwen. Ook om technologieën die het ons een stuk makkelijker maken in het leven. Na het kloofinstinct, negativiteitsinstinct, rechte-lijn instinct, angstinstinct, grootte-instinct, generalisatieinstinct, lotsinstinct, eenperspectiefinstinct en het zondebokinstinct is er nog het laatste instinct, het urgentieinstinct, dat aandacht vraagt als we willen weten waarom ons denken vaak blokkeert. Met dat instinct willen we meteen in actie overgaan als het gevaar opdoemt. Maar het maakt ons ook blind en zorgt er niet zelden voor dat we niet goed na kunnen denken. Met goed onderbouwde data en koelbloedige analyse kunnen we beter onze geloofwaardigheid behouden. Waarheid is wat dat betreft uiteindelijk belangrijker dan steun vergaren, hoe nobel het doel ook is. Dat betekent niet dat we ons geen zorgen moeten maken over een wereldwijde pandemie bijvoorbeeld, een nieuwe financiële ineenstorting of wereldoorlog, klimaatverandering, extreme armoede of een toekomstig gevaar dat we nu nog niet kennen. We moeten hier niet gespannen over worden en blijven nadenken over hoe we dat dan het beste op kunnen lossen. 


Jullie vader neemt met dit boek afscheid van de wereld die hem lief was. Op 5 februari 2016 wordt er bij hem alvleesklierkanker vastgesteld. Nog maar een half jaar daarvoor hadden jullie besloten om samen een boek te schrijven. Nu was daar misschien niet veel tijd meer voor. Nu geen TED-talks meer, geen bestuurskamers van multinationals, wereldbanken, ministeries en wereldleiders meer. Alle afspraken werden afgezegd en alleen het boek stond nog centraal. Nog een keer wilde hij met jullie onze misvattingen over de wereld aan de kaak stellen, laten zien hoe de wereld in elkaar zit en hoe ons denken beperkt wordt. Met simpele vragen daagt hij de lezer meteen uit en toont hij aan hoe weinig mensen in deze informatiesamenleving over de wereld weten. Ons kennisniveau ligt wat dit betreft niet hoger dan dat van een chimpansee en zo schut hij de luie lezer meteen wakker. Het verzamelen van goede data was voor hem een bron van rust. Stabiliteit, vrede en natuurbehoud zijn gebaat bij internationale samenwerking. En als je goed wilt samenwerken, moet je feiten over de wereld ook goed op rij hebben. Mensenlevens druk je niet uit in cijfers, vinden sommige mensen. Maar voor Hans biedt dit hoop. Eigenlijk gaat het hem niet om de cijfers, daar heeft hij een hekel aan zegt hij (maar dat geloof ik niet) . Maar hem interesseert vooral het leven achter de cijfers en hoe het de werkelijkheid kan ondersteunen(en dat geloof ik wel weer). De laatste dagen van zijn leven (februari 2017) werkte hij in het ziekenhuis nog aan drukproeven van enkele hoofdstukken. Het boek zou hij niet af zien. Maar aan jullie kan ik zeggen dat het, zoals het jullie vader voor ogen had, inderdaad ‘een prettig leesbare tekst is geworden die een mondiaal publiek zal helpen de wereld te leren kennen’. In dit boek spreidt jullie vader nog één keer zijn armen en laat hij, de circusartiest, het publiek nog één keer juichen. Mij, bescheiden en nieuwsgierige lezer uit Nederland, heeft het zeer geholpen.     
 

Dank jullie wel.


Grote groet, -Harrie Jonkman

Rosling, H. met Ola Rosling en Anna Rosling Rönnlund (2018). *Feitenkennis. 10 redenen waarom we een verkeerd beeld van de wereld hebben en waarom het beter gaat dan je denkt*. Houten: Spectum. 243 pagina’s. €22,50.

