
# ZIEN, DOEN ÉN VERBEELDEN


Amsterdam, juni 2018


Beste Judea Pearl,


Net in de week dat ik jouw zeer interessante ‘The Book of Why. The New Science of Cause and Effect’ las, verscheen er bij ons in de kranten een oproep van 150 wetenschappers die vinden dat Europa kunstmatige intelligentie meer serieus moet gaan nemen. Daar waar China, de Verenigde Staten en Canada miljarden investeren hierin en talloos talent aantrekken, lijkt Europa op het gebied van kunstmatige intelligentie meer en meer achter te lopen in investeringen in talent, onderzoek, technologie en innovatie. Ten onrechte, volgens deze groep, omdat de KI-methodes en technologieën wereldwijd grote veranderingen teweeg brengen in de samenleving en de industrie. Daarom moet Europa zich opnieuw positioneren op dit terrein en is het nodig dat het onderzoek ernaar tot het beste in de wereld gaat behoren. Daar waar deze grote groep wetenschappers op dit terrein voor een sterk Europees topinstituut pleit waarmee de concurrentie kan worden aangegaan, heb jij (pionier en ‘frontman’ op het terrein van kunstmatige intelligentie) iets anders voor ogen. Jou gaat het niet zozeer wat we gaan doen maar veelmeer waarom we iets doen. Als we daar goed over nadenken is er veel meer winst te behalen. Kunstmatige intelligentie heeft ongelofelijk veel opgeleverd de laatste decennia. Daar ben jij ook van overtuigd. Als we echter op dit terrein werkelijk verder willen komen, moeten we niet op dezelfde manier doorgaan. Dan moet er een andere nadruk worden gelegd en over de richting waarin het zou moeten gaan gaat jouw ‘The Book of Why’?


Jij bent in Israël geboren en ging in de zestiger jaren in de Verenigde Staten studeren. Sinds de jaren zeventig ben je in hoogleraar informatica aan Universiteit van Los Angeles. Jij werd vooral bekend door jouw werk op het terrein van kunstmatige intelligentie en vanwege jouw baanbrekend won je in 2011 de prestigieuze Turing Award. In de tachtiger jaren ging jij op dit terrein opvallen, nog niet zozeer vanwege jouw werk rondom causaliteit want toen ging het jou nog in de eerste plaats om waarschijnlijkheid. Je kende het werk van David Rumelhart, een cognitief wetenschapper die veel schreef over neurale netwerken. Rumelhart liet zien hoe we bepaalde woorden lezen, dat neuronen daarin een rol spelen en daarvoor informatie van onder en van boven halen en van de ene kant naar de andere kant. Iets begrijpen werkt, om het heel simpel te zeggen, niet zozeer vanuit een bepaalde centraal systeem maar komt interacterend op verschillende niveaus tot stand. In dat cognitieve proces wordt kennis als het ware voortdurend ververst. Jij introduceerde hier de theorie van Bayesiaanse netwerken waarin jij het geheel als één grote conditionele waarschijnlijkheidstabel zag en de losse onderdelen op elkaar worden afgestemd. De Bayesiaanse netwerk theorie zou de jaren erna op vele terreinen worden uitgewerkt en bleek heel geschikt om bijvoorbeeld medische diagnoses vast te stellen. Uiteindelijk zag je ook de beperking in van de Bayesiaanse netwerk theorie die ons niet meer kon vertellen als hoe groot de kans op een bepaalde gebeurtenis is als we informatie over andere eenheden hebben en was het niet meer dan een data-gestuurde oplossing voor een probleem. Jij ziet dit als de laagste trede van een drie treden oorzaak-gevolgladder die jij in jouw boek presenteert. Hier gaat het om niet meer dan observeren van data. Op dit laagste niveau van wetenschap is er veruit het meeste gebeurd tot nu toe. Jij wilt dat we niet op het positivistische niveau van observeren alleen blijven steken. Het is nodig om naast zien ook de volgende twee treden van de ladder in ons denken te betrekken: doen en verbeelden. Bij het doen gaat het om wat er gebeurt en het inzetten van een mogelijke interventie. Dat doen is onderdeel van jouw causale lens waarvan je hoopt dat wij daarmee ook naar de werkelijkheid gaan kijken. Op dit tweede niveau gaat het om vragen als wat gebeurt er als we dit medicijn gebruiken en wat gebeurt er als we de prijs hiervan verdubbelen? We doen de hele tijd iets in de werkelijkheid en daar moeten we oog voor krijgen. Met die tweede doe-trede zijn we er nog niet want er is nog een derde, even belangrijke, wetenschappelijke trede op jouw oorzaak-gevolgladder: dat wat we het feitelijk tegenovergestelde of de verbeelde werkelijkheid noemen. Wat gebeurt er als we iets wel en wat gebeurt er als we iets niet gedaan hebben? Wat gebeurt er als we niet deze weg maar die weg inslaan? Op dit derde niveau gaat het niet zozeer meer om de data en de feiten maar wordt de werkelijke wereld met een ingebeelde wereld vergeleken. Dat verbeelden, in mogelijkheden denken en nadenken over de consequenties van ons handelen, is iets dat we als mensen kunnen en dat maakt ons zo uniek. In jouw boek schets je de weg die jij wetenschappelijk hebt gelopen en laat je en passant ook zien wat er in de wetenschap is gebeurd. Je laat zien dat de wetenschap op het eerste niveau van observeren is blijven steken met correlatietechnieken die onder anderen door Galton, Pearson en Fischer zijn ontwikkeld. Sewall Wright is jouw grote held die met zijn pad-analyses voor het eerst causale vragen kon beantwoorden. Daarmee was hij de eerste die niet alles tot data reduceerde. Willen we zaken beter begrijpen (wat zouden we anders moeten willen in wetenschap?) zullen we de waarom-vraag moeten durven stellen en daarom is de relatie tussen een bepaalde oorzaak en gevolg zo belangrijk. Tussen 1500 en 1800 overleden er zo’n 2 miljoen mensen op boten aan scheurbuik. Aan het einde van de achttiende eeuw werd eindelijk ontdekt dat scheurbuik te maken had met een tekort aan citrusvruchten en met die vaststelling werd scheurbuik een te voorkomen ziekte. Echter aan het begin van de twintigste eeuw komt de ziekte weer voor. Dat kwam omdat het mediërend effect niet helemaal goed hadden begrepen. Het was niet zo dat scheurbuik met citrusvruchten is te voorkomen(citrusvruchten -> voorkomen van scheurbuik). Het heeft te maken met vitamine C dat in de citrusvrucht zit dat dat ervoor zorgt dat scheurbuik kan worden voorkomen(citrusvruchten ->vitamine C -> voorkomen van scheurbuik). Wil iets werken, moeten causale verbanden wel goed begrepen worden.  


De laatste vijfentwintig jaar heb je veel geschreven over causaliteit en dat was vooral voor een betrekkelijk kleine groep experts. Met dit boek wil je het onderwerp breder toegankelijk maken en met dat in het achterhoofd heb je de hulp ingeroepen van de wetenschapsjournalist Dan MacKenzie. Het is je gelukt een toegankelijker boek te schrijven maar ik ben bang dat het niet door een heel breed publiek gelezen gaat worden. Bepaalde delen, moet ik je eerlijk erkennen, moest ik soms meerdere keren lezen. Of ik alles tot in detail begrepen heb, vraag ik mij eerlijk gezegd wel af. Maar waar het jou om gaat, de kern van jouw boek, is mij wel heel duidelijk geworden en dat spreekt mij bijzonder aan. In wetenschap, zo zou je denken, gaat het om oorzaak en gevolg. Tegelijkertijd is deze kwestie juist daar te weinig uit de verf gekomen. Volgens jou liep men om deze kwestie heen en was er tot voor kort ook geen taal voor ontwikkeld. Alles ging tot dan om samenhang en verbanden. Dat het een uit het ander voort komt, of ten dele daaruit voortkomt, kon nauwelijks uitgedrukt worden. Zij die dat wel probeerden, werden niet serieus genomen. Tot op heden wordt bijna alles uit data alleen gehaald en worden oplossingen voor problemen daar gezocht. Nog steeds denken veel wetenschappers dat hier de graal te vinden is. Zij hebben alle geloof in machine learning, big data en deep learning. Jij bent daar sceptisch over. Bij de ontwikkeling van computers, machines en robots moet er veel meer gekeken worden naar hoe mensen zelf met de werkelijkheid omgaan. Als we dat doen, zien we dat mensen, anders dan computers, machines en robots, in staat zijn om met elkaar te communiceren, om zich een hypothetische wereld voor te stellen, dat ze kunnen denken in oorzaak en gevolg en kunnen beargumenteren waarom het één beter is dan het ander. Jij kunt niet anders dan de wereld door zo’n causale lens zien. Daarom alleen al gaat het cognitieve systeem bij jou uit boven de data. Met anderen in de wetenschap heb je er voor gezorgd dat er een ware Causale Revolutie tot stand is gekomen. Die revolutie (in gang gezet door mensen als Donald Rubin, Chris Winship, Jamie Robins en jijzelf) heeft er ook voor gezorgd dat er ondertussen een assymetrische taal is gekomen die er lange tijd niet was en die wel met causale relaties kan werken. Causaliteit is gemathematiseerd, zoals je eerder al schreef. Het is voor jou overduidelijk dat associaties en relaties alleen niet meer genoeg zijn en dat we in causale modellen moeten leren denken. Zo schuift kunstmatige intelligentie meer en meer op naar hoe mensen zelf denken; denken in alternatieven en deze contrasteren met de werkelijkheid. Niet alleen zien, maar ook doen en verbeelden. Jij hebt computers, machines en robots voor ogen die over zichzelf kunnen reflecteren, van eigen fouten kunnen leren, die naar zichzelf en de wereld kunnen kijken, deze met elkaar kunnen verbinden en die met menselijke eigenschappen zelf beslissingen kunnen nemen. Om dat te bereiken moeten we de oplossing niet alleen in data zelf zoeken maar causale modellen bouwen en theorieën formuleren waarmee we grote en klein data kunnen interpreteren. Je hebt een visionair boek geschreven. Het is te hopen dat de 150 wetenschappers die voor dat Europese KI-centrum pleiten de tijd hebben en nemen om dit boek te lezen.


Dank je wel.


Grote groet, -Harrie Jonkman


Pearl, J.& Mackenzie, D.(2018). *The Book of Why. The New Science of Cause and Effect*. New York: Basic Books. 418 pagina’s. €26,99.

