
# MEDICIJN VOOR DE TOEKOMST


Amsterdam, juli 2018


Beste Nadine Burke Harris,


Afgelopen zaterdag was ik op een begrafenis van de moeder van een vriendin van mij. Die vriendin vertelde op deze afscheidsdienst over haar moeder en de moeilijke jeugd die ze in de jaren rond de Tweede Wereldoorlog gehad heeft. Haar moeder voelde zich nooit geaccepteerd in het gezin waarin ze opgroeide, werd voortdurend achtergesteld en stelselmatig gekleineerd en mocht na de middelbare school niet verder leren terwijl ze dat goed kon en graag  wilde. Toen ze het huis uit was, ontwikkelde ze zich op haar manier en vond ze een manier om zichzelf te worden. Dat diepe gevoel van achterstelling en kleinering zou ze echter nooit kwijt raken en is onder haar huid gaan zitten. Ze kreeg een immuunziekte op middelbare leeftijd en kwam met medicatie daar weer overheen. De laatste jaren van haar leven ontwikkelde ze wanen en overleed op niet al te hoge leeftijd. Toen ik het verhaal van die vriendin hoorde in die dienst, moest ik direct aan jouw boek “The Deepest Well. Healing the Long-Term Effects of Childhood Adversity” denken, dat ik die week aan het lezen was. Ik kende die moeder van mijn vriendin verder niet en ben geen dokter. Uit het verhaal op de begrafenis maakte ik wel op dat deze moeder op jonge leeftijd traumatische tegenslagen had meegemaakt die haar leven verder sterk zouden beïnvloeden. Haar jeugd heeft haar emotioneel en psychologisch sterk beïnvloed met negatieve gevolgen, net als dat het geval is bij die vele voorbeelden die jij in jouw boek noemt en waar jij in jouw kliniek dagelijks mee te maken hebt. Allemaal personen die als kind trauma’s of stress mee maakten als mishandeling, ontkenning, geweld en of angst of die zagen dat hun ouders veel ruzie maakten, gingen scheiden, werden gearresteerd, alcohol of drugs gebruikten en of psychisch beschadigd waren. Met die ervaringen op jonge leeftijd veranderen biologisch systemen en dat laat vervolgens op langere termijn negatieve effecten zien. Maar hoe werkt dat precies vraag jij je af en als we dat weten wat kunnen en moeten we dan doen?


Jouw vader is een bekende professor biochemie in Jamaica (waar jij ook geboren bent) die in jouw opvoeding voortdurend alles om hem heen aan natuurkunde, chemie en biologie koppelt. Jij studeert in de Verenigde Staten medicijnen en met jouw achtergrond is dat niet gek. Jij werkt na jouw studie een tijdje op het laboratorium waar je onderzoek doet naar het gedrag van kikkervisjes. Je onderzoekt hoe kikkervisjes zich na stresssituaties kunnen aanpassen. Waar dat toe leidt, zo laat je zien, is medeafhankelijk van het moment waarop ze er mee te maken krijgen en de duur ervan. In dat lab leer je in ieder geval nadenken over de relatie tussen stress en langere termijn uitkomsten. Vervolgens ga je als kinderarts in de publieke gezondheidszorg van San Francisco werken en krijg je al snel werk in het Bayview Child Health Centre, middenin een achterstandswijk van de stad. Dat is dan nog een kleine kliniek, met weinig personeel en beperkte middelen. Hier help je kinderen die dat nodig hebben en zet je preventieve programma’s op. De problemen waarmee je te maken hebt zijn ontwikkelingsproblemen en je legt hier de link met jouw eerdere onderzoekswerk naar kikvisjes. Je ontdekt dat ook anderen daar studies naar hebben gedaan. Anda en Felliti, bijvoorbeeld, hebben tien jaar eerder al een groot onderzoek naar de invloed van vroege tegenspoed gedaan en introduceerden Adversity Childhood Experiences (ACE). Deze wetenschappers onderscheiden tien indicatoren; als je daar voor je 18e jaar mee te maken krijgt, verhoogt dat de kansen op negatieve gezondheidsuitkomsten. Zij laten zien dat twee derde van de bevolking te maken heeft met ten minste één indicator, terwijl een achtste van de bevolking met 4 of meer indicatoren te maken heeft. De cijfers liegen er niet om. Bijvoorbeeld, als iemand positief op vier of meer van de tien indicatoren scoort, is de kans dat hij of zij later een hartprobleem krijgt of overgewicht laat zien twee keer zo hoog. De kans op chronische longproblemen is drieëneenhalf keer zo groot en op leer- en gedragsproblemen is de kans zelfs meer dan 32 keer zo groot. De levensverwachting van mensen met een hoge score is zes tot twintig jaar korter. De scores op die indicatoren liggen in achterstandswijk waar je werkt bijzonder hoog. 
Om goede klinische tools te kunnen ontwikkelen is het nodig niet alleen verbanden te leggen maar vooral te snappen waarom dat zo is en hoe die ontwikkelingsprocessen verlopen. Jij wilt weten hoe het lichaam op stress reageert en waarom dat de gezondheid zo sterk negatief beïnvloed. Stress op zich is iets goeds omdat we er snel mee op situaties kunnen reageren als het nodig is (vechten, bevriezen of vluchten). Verschillende onderdelen van ons lichaam zijn bij het stress-antwoord systeem betrokken. Stress is alleen slecht als het toxisch is en we heel vaak op een dag op een situatie moeten reageren. Kinderen zijn heel gevoelig als zij op herhaalde stress situaties moeten reageren. Bij hen heeft overmatige stress sneller invloed op het hersen-, het immuun-, hormoon- en cardio-vasculair systeem en zelfs op de manier waarop het DNA wordt ontcijferd. 
Dat biologisch proces beschrijf je uitgebreid. De amygdala is het centrum van de angst in de hersenen en is het alarmsysteem. De locus coeruleus, dat met de adrealine te maken heeft, zorgt voor agressief gedrag en is verbonden is met de prefrontaal cortex. Deze cortex zorgt voor executieve functies en is bepalend voor redeneren, oordelen, plannen en beslissen. Als er iets angstigs gebeurt, heeft dat invloed op deze functies en gaan instincten en impulsen een belangrijkere rol spelen. De hippocampus is belangrijk voor het geheugen en stress-situaties kunnen het korte en lange termijn geheugen aantasten. Dan is er nog de ventral tegmental area dat zorgt voor dopamine dat beloningen geeft via bepaalde gevoelens. Gevoeligheid kan in toxische stress-situaties worden aangetast. Dat alles speelt zich in de hersenen af. Maar stress heeft ook invloed op de hormonen dat zorg draagt voor diverse biologische processen zoals groei of seksualiteit. Ook het immuunsysteem wordt beïnvloed door stress hormonen. We weten dat een gebalanceerd immuunsysteem goed is voor gezondheid, maar ook dat de ontwikkeling daarvan kan worden aangetast en kan zorgen voor allerlei stoornissen en eerder overlijden. Hevige stress op jongere leeftijd grijpt uiteindelijk in tot het diepste niveau van de genetica door de bescherming van het DNA aan te tasten. 
Toen je de inzichten had in hoe het biologische proces verloopt, wil je mensen overtuigen dat het nodig is om hierop te investeren. Daar blijkt het te vroeg voor te zijn wanneer je merkt dat je mensen met een probleem opzadelt. Om iets te kunnen betekenen, moet je ook laten zien wat je eraan kunt doen. Als je dat doorkrijgt, zoek je naar effectieve stressaanpakken zoals voldoende slaap, mentale gezondheid, gezonde relaties, bepaalde psychologische oefeningen en voeding en past die in je praktijk toe. Langzaamaan wordt het werk van jou groter en word je gezien wanneer jij hier op congressen over gaat vertellen, lezingen geeft en geld binnenhaalt. Dan ga je ook dromen over een eigen laboratorium voor preventie, screening en aanpak van toxische stress en zet je het Centrum voor Jeugdwelzijn op. Je zoekt ook samenwerking met anderen die op dit terrein actief zijn zoals Nancy Mannix, Jeanette Pai-Espinosa en Pam Cantor. Dan wordt het tijd iets te betekenen en er een boek over te schrijven.


Jij bent erg geïnspireerd door mensen uit preventieve gezondheidszorg, zoals John Snow bijvoorbeeld, die eind 19e eeuw zichtbaar maakte dat cholera niet via de lucht verspreid wordt maar via bacteriën en handcontact met de waterpomp. Robert Guthrie is een andere held van jou, die werk maakte van het voorkomen van mentale stoornissen en ervoor zorgde dat de hielprik in meer dan zeventig landen wordt gebruikt. Dat wat internationale kinderoncologen samen hebben bereikt door samenwerking en onderzoek, diagnose en kennisuitwisseling, past meer bij wat jou bij jouw eigen onderwerp voor ogen staat. Zestig jaar geleden overleed nog 90% van kinderen met kanker, vijftig jaar later is dat 20%. In die lijn denk je zelf ook verder want nu we weten dat overmatige stress zo’n invloed heeft op gezondheid en samenhangt met verhoogde kans op kanker, long- en hartproblemen en met leer- en gedragsproblemen, is het de moeite waard hier internationaal werk van te maken. Dat kan ook nu er zicht is op hoe het mechanisme van stress op lange termijnuitkomsten werkt en weten hoe het aangepakt kan worden. Er zullen kinderen blijven die in sterke stresssituaties opgroeien maar we kunnen, daar ben je van overtuigt, iets voor hen betekenen die ermee te maken hebben gehad. Jouw boek is een ambitieus boek waarin je epidemiologische, biologische, epi-genetisch, levensloop- en effectiviteitsonderzoek samenbrengt. Jij hebt vooral aanvullend onderzoek gedaan naar ontwikkelingsmechanisme van stress naar lange termijnuitkomsten en je richt de aandacht daar terecht op. Maar hoe het proces precies in elkaar zit, ga je je toch afvragen en behoeft in de toekomst preciezere uitwerking. Jouw boek zie ik vooral als een stimulerend boek omdat het wetenschappelijk en praktisch werk zo goed samenbrengt. Natuurlijk, het is een Amerikaans boek en als Europeaan valt het mij dan op dat het goede wel heel scherp tegenover het slechte wordt geplaatst, dat er miljoenen worden binnengehaald voor het opzetten van een centrum en TED-talks moeten worden gehouden. Maar jouw boek laat ook zien wat preventieve wetenschap kan betekenen in deze wereld en aan dat hoopvolle wil ik mij graag optrekken. Economische deprivatie, oorlogen, natuur geweld, trauma’s, honger, geweld en mishandeling hebben gevolgen voor pasgeborenen, kinderen, adolescenten en volwassenen. En in elke fase uiten die gevolgen zich weer anders. De moderne wereld met zijn veranderende bevolking moet zich hier van bewustzijn ten behoeve van haar welzijn en gezondheid. Preventie als misschien wel beste medicijn voor de toekomst.    


Dank je wel.


Grote groet, -Harrie Jonkman

Burke Harris, N., D.(2018). *The Deepest Well. Healing the Long-Term Effects of Childhood Adversity*. London: Blue Bird. 272 pagina’s. €15,99.

