
# EEN HELE HETE AARDAPPEL	

Amsterdam, augustus 2018


Beste Serhii Plokhy,


In de vroege nacht van 26 april 1986 explodeerde reactor Nr.4 op het nucleaire krachtstation van Chernobyl in de Oekraïne dat toen nog deel uitmaakte van de Sovjet-Unie. Het duurde een behoorlijke tijd voordat het doordrong wat hier was gebeurd. Ikzelf herinner me de beelden van het journaal dagen later met de talloze helikopters waarmee jonge soldaten met eindeloze zandzakken het gat in de reactor op een simpele manier probeerden te dichten. Ik herinner me ook dat ik me later wel eens afvroeg of het wel verstandig was fruit van de markt te kopen. Over de ramp werd gesproken namelijk en die maakte indruk, zeker, maar wat wisten we er eigenlijk weinig van toen. Jouw boek ‘Chernobyl. History of a Tragedy’, Serhii Plokhy, beschrijft die tragedie in de volle breedte en lengte. Jij schrijft dat de radioactiviteit die met de explosie vrij kwam vergelijkbaar was met 500 Hiroshima atoombommen. Fijntjes voeg je er aan toe dat het makkelijk allemaal veel erger had kunnen uitpakken. Heel Europa zou zijn weggevaagd als de hele reactor was ontploft en de wereld had niet meer bestaan als alle vier reactoren daar ontploft waren. Als je jouw boek leest, besef je heel goed dat dit allemaal best had gekund. Reden genoeg om de volle breedte en lengte te zoeken, zeker als je zelf niet eens zo ver van de rampplek opgegroeid bent. In jouw boek stel je eigenlijk drie vragen: hoe heeft dit kunnen gebeuren, wat is er precies gebeurd en wat kunnen we hiervan leren?



Eind jaren tachtig staat de Sovjet-Unie er slecht voor en houtworm heeft zich in het systeem ingevreten. De unie van landen vormde nog een geheel maar er was armoede, de oorlog in Afghanistan verliep desastreus en de inwoners waren gedesillusioneerd over het communistische experiment. Gorbatsjov was net aan de macht gekomen en hij luidde de tijd van ‘perestrojka’ (radicale herstructurering van het politieke en economische systeem) en ‘glasnost’ (meer openheid) in. Hij zag dat de Sovjet-Unie wel moest ontwapenen om te overleven en dat er wetenschappelijk en technologische doorbraken nodig waren voor economische voorspoed. Er werd die jaren groot gedacht, alles leek mogelijk en in dat straatje paste nucleaire energie heel goed. Dat denken bleek toch ook weer niet zo heel groot te zijn. In de zeventiger jaren was de centrale bij Chernobyl gebouwd op een heel vredig stukje land. In jouw boek citeer je een van de bouwers die daar toen over schreef: “Er was een spaarzaam bos van jonge dennen rondom met een bedwelmende sfeer zoals nergens anders. Er waren zandheuvels bedekt met een laag groeiend bos en stukken zuiver geel zand tegen een achtergrond van diepgroen mos. Geen sneeuw te zien. Groen gras verwarmd door de zon stippelde het gebied. Stilte en een gevoel van oerschepping”. In 1979 was de eerste, in 1983 de vierde reactor klaar en een vijfde zou spoedig gebouwd worden. Halverwege de jaren tachtig kon de kerncentrale 30 miljoen huizen verwarmen en de Sovjet-Unie was trots op zijn Chernobyl. Anders dan in de rest van het land was in de nieuw gebouwde reactorplaats Prypiat van alles te krijgen voor de moderne werknemers die op de centrale werkten. Hier leek geen vuiltje aan de lucht toen de mensen daar zich eind april 1986 voorbereidden op de feestdagen die op stapel stonden. Er waren een paar problemen met unit vier en die zouden, zoals zo vaak, snel zijn opgelost. In de nachtdienst van 25/26 april waren voor het klaren van die klus eigenlijk niet de juiste mensen aanwezig. Toen de meters doorsloegen wist eigenlijk niemand wat er aan de hand was en hoe het opgelost moest worden. In een soort paniek werd er op een noodknop gedrukt en kort erna ontplofte unit vier. De werknemers ter plekke zouden later zeggen dat het allemaal op een aardbeving leek (du-du-du-du). Men zag wel wat er gebeurde maar realiseerde niet echt wat het was en geloven deden ze het al helemaal niet. Er brak brand uit en de brandweer werd erbij gehaald. Nietsvermoedende brandweerlieden klommen de centrale op en probeerden te blussen alsof het een gewoon brandje betrof. Alles bleek al radioactief te zijn en de gevolgen waren snel zichtbaar. Niemand ter plekke durfde de verantwoordelijkheid op zich te nemen en zo kon het gebeuren dat de gebeurtenis gewoon ontkend werd. Radioactiviteit kwam in grote hoeveelheden vrij maar in modern Prypiat, drie kilometer verderop, speelden kinderen die zaterdag op straat, er werd getrouwd en gevoetbald en er werden ijsjes gegeten. Pas die maandag erop werden de 45.000 inwoners van Prypiat geëvacueerd. Het stadje zou spoedig een eigentijds Pompeï worden met affiches uit de Sovjet-tijd nog aan de muren. Van hogerhand werd er alles aan gedaan om paniek te voorkomen. Acht dagen en nachten lang leegden helicopters 5000 ton veelal met de schop gevulde zandzakken en klei in het gat van de reactor. Ik schreef je al dat ik mij dat beeld heel goed herinner. Niemand die wist of dit wel de juiste oplossing was, niemand die wist wat er zou gebeuren. In de Tweede Wereldoorlog, zo schrijf je, konden de mensen hier nog de bossen in vluchten maar juist dat was nu gevaarlijk. Het Russische Politbureau durfde het bericht niet naar buiten te brengen, bang als zij ook waren dat paniek zou uitbreken. Vanuit Moskou werd er een ware informatieblokkade opgebouwd hierover die vooral merkbaar was in het getroffen gebied maar ook in de buitenwereld. In Zweden, de richting waarin de wind die dagen woei, werd twee dagen later een verhoogde dosis gemeten en daar kon men het eerst niet plaatsen. Het duurde niet lang of het westen begon vragen hierover te stellen. De eerste doden vielen onder de brandweermannen, het reactorpersoneel en de inwoners van Prypiat en daarna ook onder partijleden en het establishment die bij de ramp betrokken raakten. Op belangrijke vragen wist men geen antwoord te geven. Wat zijn de ondergronds effecten van de explosie en wat gebeurt er als het grondwater op grote schaal zou vervuilen? Moesten die enorme aantallen mensen uit Kiev worden geëvacueerd of konden de rode parades gewoon doorgaan?. 600.000 mensen raakten betrokken bij het oplossen van het probleem. Pas achttien dagen na de ramp spreekt Gorbatsjov op de televisie over de ramp en dit was pas echt het begin van zijn glasnost. Met de knal werd een tijd afgesloten, met de knal brak een nieuwe tijd aan. 



Een paar maanden later werd er al gestart met het inpakken van de reactor 4 in een betonnen sarcofaag van 400.000 ton beton gebouwd door zo’n 200.000 werklieden. Toen de reactor was ingepakt brak de tijd van de afrekening aan. De schuld van de ramp kwam bij het personeel van de reactor te liggen. De directie van de reactor en degene die vrijdagavond leiding gaven werden verantwoordelijk gesteld voor de ramp. Dat diezelfde leiding voor dit soort gevaren eerder gewaarschuwd had, deed er niet toe. De bouw van de centrale en ook de hoge druk vanuit de partijleiding om de productie maar op te voeren bleven onbesproken. Met de ramp kwam de balans tussen moderniteit en traditie ook in een andere verhouding te staan en zeker in de Oekraïne werd eind jaren tachtig op het belang van publieke gezondheid en ecologisch welzijn gewezen zoals nooit eerder was gebeurd. Hier werden geen boeken en dichtbundels meer geschreven maar in de Oekraïne zette men zich in voor eco-activisme. De ramp stimuleerde ook het democratische proces in de Oekraïne en verandering was niet alleen meer nodig op het terrein van nucleaire energie. Gorbatsjov zag in dat voor economische verandering verdere democratisering nodig was. Corruptie aanpakken en lokale autoriteiten aanvallen ging daarbij nog wel. De ramp zelf en de rol die centrale overheid daarbij had gespeeld, was natuurlijk een ander verhaal. Dat raakte het Politbureau en hemzelf direct en dat ging hem ook weer te ver. Uiteindelijk zou de Chernobyl ramp de fundamenten van het Sovjet-systeem aantasten. In 1989 valt de muur en begin jaren negentig valt de Sovjet-Unie uit elkaar. In 1991 stemmen de inwoners van de Oekraïne voor onafhankelijkheid. Dan wordt er ook anders tegen de oorzaak van de ramp gekeken en wordt de oorzaak bij de communistische partij neergelegd. Wanneer het in de jonge staat economisch verder achteruit gaat wordt er toch weer anders tegen kernenergie aangekeken. Dan maakt het eco-activisme ook daar weer net zo makkelijk plaats voor nucleair-nationalisme. Over gevolgen van de ramp had je wat mij betreft wel wat uitgebreider kunnen zijn. Je schrijft dat 50 mensen direct stierven en dat schattingen van het uiteindelijke aantal doden uiteen loopt van 4.000 tot 90.000. In de jaren erna nam het kankergevallen onder kinderen met 90% toe en er zijn de langere termijn consequenties voor gezondheid en arbeidsparticipatie van de mensen aldaar. Het gebied is 20.000 jaar niet te gebruiken en de kosten van de ramp zijn enorm voor de Oekraïne, Wit-Rusland en Rusland en drukken nog steeds op het belastingsysteem. Jij hebt vooral oog voor de consequenties in de Oekraïne en minder voor wat het voor Wit-Rusland en Rusland betekende. Maar jij hebt oog voor zoveel zaken. Een adembenemend boek dat ik werkelijk in een paar dagen moest uitlezen. Jouw boek laat vooral zien wat het betekent als we economische voorspoed boven de gezondheid van mensen en het ecologisch welzijn plaatsen. We moeten heel zorgvuldig met onze omgeving omgaan, overal ter wereld. Na het lezen van dit boek zijn dat geen lege woorden meer. Op dit terrein moeten we samenwerken, kennis delen en elkaar in de gaten houden. Het is niet gek als we ons zorgen maken wanneer dit soort centrales in landen als Pakistan en Egypte geplaatst worden. Terecht dat jij je prachtige tour de force opdraagt aan de kinderen van het nucleaire tijdperk.



Dank je wel.

Grote groet, -Harrie Jonkman

Plokhy, S.(2018). *Chernobyl. History of a Tragedy*. London: Allen Lane. 404 pagina’s. €21,99.

