
# LINKSE GEDAANTEVERWISSELINGEN	


Amsterdam, september 2018


Beste Stephanie Mudge,


Tien jaar heb jij aan jouw nieuwe boek “Leftism Reinvented: Western Parties from Socialism to Neoliberalism” gewerkt. Als je jouw boek zo leest, snap je heel goed dat het jou zoveel tijd kostte. Dit was een enorme tour de force en het resultaat mag er wezen. In het boek laat je zien hoe het linkse partijen in de westerse wereld is vergaan vanaf het einde van de 19e eeuw tot en met heden. Je laat zien welke veranderingen er hebben plaats gevonden in die bijna 150 jaar. Daarvoor heb je uitgebreid onderzoek gedaan in vier landen: Duitsland, Zweden, Engeland en Amerika. Jij bent je ervan bewust dat links heel veel verschillende betekenissen heeft en dat het eigenlijk onmogelijk is hier een hele duidelijke definiëring voor te geven. Voor jouzelf heeft links in ieder geval altijd een verantwoordelijkheid gevoeld voor de armen, de minder bevoorrechten en zij die minder rechten hebben. Links wil mensen vertegenwoordigen die zichzelf om verschillende redenen moeilijk kunnen vertegenwoordigen en komt op voor gelijkheid. Om de ontwikkeling van links beter te begrijpen wil je het perspectief en de taal van links leren kennen en vooral diegenen snappen die de taal produceerden. Jij wilt weten hoe het perspectief tot stand kwam, werd overgedragen en hoe hiervoor macht werd verkregen. Jij wilt de kern van dat linkse verhaal analyseren door het comparatief te onderzoeken, het historisch te plaatsen en mensen zichtbaar te maken die de verschillende gedaanten vorm gaven. Kortom, jij wilt laten zien wat er allemaal is gebeurd in die anderhalve eeuw, hoe we dat moeten begrijpen en wat wij hier voor de toekomst van kunnen leren. 
Rond 2000 was het overduidelijk dat ook de linkse politiek voor de vrije markt had gekozen en links en rechts helemaal niet meer goed uit elkaar waren te halen. Daar moet, zo dacht jij, meer over te vertellen zijn en daar moet het idee voor dit boek ontstaan zijn. Is het toevallig, zo vroeg ik mijzelf af, dat jij in 2008 (het jaar waarin in het westen de grootste economische crisis van na de Tweede Wereld meemaakten en de vrije markt helemaal niet meer zo goed werkte) met deze studie begon? Jij startte jouw sociologische studie aan de universiteit van Berkley, die al die tijd jou thuisbasis bleef, en reisde naar de archieven van Washington, Londen, Brussel en Berlijn om deze geschiedenis te kunnen schrijven. Het resultaat: een prachtig boek. 


Dat je jouw onderzoek in Duitsland, Zweden, Engeland en Amerika laat afspelen, heeft zo zijn redenen. Duitsland was een voorloper omdat daar in 1875 de Socialistische Partij Duitsland werd opgezet. Deze volkspartij was, zeker in de beginperiode, een groot voorbeeld voor andere landen. In Zweden en Engeland kwamen er al snel ook socialistische partijen. Binnen Zweden zelf is natuurlijk de Socialistische Arbeiders Partij (SAP) altijd van groot belang geweest. Ook in het buitenland werden de Zweedse ontwikkelingen met grote belangstelling gevolgd. Aan de opbouw van de verzorgingsstaat in Engeland vlak na de Tweede Wereldoorlog gaf de Labour Party leiding en ook dit werd in andere landen op de voet gevolgd. Toen er recent naar een nieuwe weg werd gezocht, speelde Labour weer die voortrekkersrol. Jouw eigen land, Amerika, is een buitenbeentje in jouw verhaal omdat de progressieve ontwikkelingen hier veel meer in lijn van de liberale traditie stonden en de afstand tot het socialisme lang groot was. Pas in de jaren dertig en veertig zien we hier dat er een verbintenis komt met meer Europese ontwikkelingen en beïnvloedden ontwikkelingen binnen de Democratische Partij ook die in het buitenland, zeker in de jaren zestig en zeventig maar ook weer in de jaren negentig. Wat jij in ieder geval in jouw goede boek duidelijk maakt is dat in al deze vier landen de linkse politiek op twee momenten wordt geherdefinieerd. Linkse politiek kende een socialistisch start. Aan het begin van de twintigste eeuw wordt duidelijk stelling genomen wanneer op de negatieve effecten van het kapitalisme wordt gewezen, op de onvermijdelijke klassenstrijd en de overtuiging sterk is dat de socialistisch toekomst voor de deur staat. Deze socialistische toon slaat in Amerika niet aan. Begin jaren zestig is het linkse perspectief definitief veranderd in alle vier landen. Het theoretisch socialistische perspectief van links heeft definitief plaats gemaakt voor een Keynesiaans economisch perspectief, met een taal die veel technischer, praktischer en pragmatischer is en gaat het om volledige werkgelegenheid, een stabiele economie en het versterken van de productiviteit. De krachten van de markt en de rol van de overheid komen hierin naar voren. Daniel Bell schrijft dan wel dat ‘Het einde van de ideologie’ is aangebroken maar jij laat zien dat er ook in deze periode sprake is van een hele duidelijke ideologie. Met de toenemende werkloosheid en inflatie verdwijnt in de jaren tachtig de zeggingskracht van het Keynesiaanse perspectief en komen in Amerika Reagan en in Engeland Thatcher aan de macht. In reactie daarop herdefinieert links zichzelf opnieuw in de negentiger jaren en wordt er een ander register geopend. Links probeert een derde weg te zoeken, een weg tussen het eenzijdig marktdenken en het bodemloos spenderen van publieke gelden maar schuift steeds verder op naar de vrije markt. Weg was het optimisme en het eerlijk verdelen van kennis, macht en inkomen. De taal wordt nu nog technischer en het doel is het tot verder ontplooiing brengen van vrije markt. Links omarmt het neoliberalisme en de vrije markt wordt als een natuurkracht gezien waar de samenleving en de mensen zich hebben aan te passen. 
De theoretische onderbouwing van links kwam in het begin vooral van krantenmensen, journalisten en andere socialistische intellectuelen. Vanaf de economische crisis raakt er een hele nieuwe groep experts betrokken bij de linkse politiek. Dan zijn het vooral economen die geïnteresseerd zijn in armoede, werkloosheid en inkomensverdeling. In Amerika en Europa gaan die economen zich als strategen en adviseurs steeds meer met de inhoud van de politiek bezig houden. Met de stagflatie (hoge werkloosheid en inflatie) is het Keynesiaans perspectief uitgewerkt en maakt het plaats voor de monetaire economie van Milton Friedman en anderen. Dan is het politieke podium voor de financiële experts, de bedrijfsconsultants en de internationale economen, oftewel de nieuwe economen die jij de TFE’s (Transnationale, Financieel-georiënteerde Economen) noemt. Zij tappen uit een ander vaatje. De markt moet goed draaien en wat dat voor het individu, de families, de scholen en de wijken, voor jonge en oudere mensen, voor autochtonen en allochtonen betekent, lijkt er minder toe te doen. Nu wordt er een soort exclusieve taal gebruikt die door gewone mensen moeilijk meer te begrijpen is. Met deze TFE’s gaat links op in het neoliberale perspectief dat brede politieke steun heeft. De traditionele achterban voelt zich dan allang van die politiek vervreemd en neemt er afstand van of zoekt een ander politiek onderkomen.


Je schrijft niet over links Nederland maar ik denk dat je van de ontwikkelingen hier in dezelfde periode een zeer vergelijkbaar beeld kunt schetsen. Ook in mijn land zien we dat voor de Tweede Wereldoorlog door Keynes beïnvloedde economen het marxistische perspectief eerst aanvullen en na de Tweede Wereldoorlog uiteindelijk herdefiniëren. De verzorgingsstaat wordt dan opgebouwd en zo kunnen sociale problemen en armoede worden teruggedrongen. De arbeidersklasse krijgt het beter, er ontstaat een bloeiende middenklasse en de blik wordt op het buitenland gericht. Wanneer het hier in de tachtiger jaren economisch minder gaat worden ook bij ons in de negentiger jaren, voor een tweede keer lijkt het, de ideologische veren afgeschud. Dat die veren niet afgeschud maar wel degelijk neo-liberaal gekleurd zijn, wordt nauwelijks ingezien. Links versplintert en van een grote volkspartij is geen sprake meer. Met de alles overheersende nadruk op de vrije markt raken veel mensen van de politiek vervreemd die zich niet meer vertegenwoordigd voelen. Jij bent zeer kritisch over dat vrije markt denken dat geen oog meer heeft voor de gewone mens in zijn of haar dagelijkse situatie. Toch vind je het belangrijk dat links de complexe economie weer leert te begrijpen en daar een duidelijk perspectief op definieert. Maar zeker zo belangrijk vind jij dat het belang van burgers weer boven het belang van de economische markt komt te staan. Het wordt tijd dat die financiële experts niet meer alleen helemaal vooraan staan. Jij ziet een aantal interessante nieuwe ontwikkelingen en ikzelf meen ook te voelen dat er langzaamaan een andere wind opsteekt. In ieder geval is het zo dat jongeren inzien dat zij van het neoliberalisme niet zoveel hoeven te verwachten. Ook in de wetenschap gaat het niet meer alleen om de fiscale en monetaire economie. Onderwerpen als ongelijkheid en rechtvaardigheid worden weer serieus onderzocht. Of het bij links vooral moet gaan om de representatie van mensen die zichzelf niet kunnen vertegenwoordigen, waar jij zo voor bent, ben ik iets kritischer. Ik heb meer op met een politiek die zich op alle burgers richt. Een politiek die zich kan voorstellen wat maatregelen betekenen en oog houdt voor het belang van iedere burger. Politici die zich kunnen verplaatsen in de positie van verschillende mensen en doorhebben dat bepaalde situaties henzelf of hun kinderen ook zou kunnen overkomen. Een politiek die goed om zich heen kijkt, verschillen absorbeert en de toekomst in durft te kijken. Een politiek ook die weet waar ze vandaan komt en niet alleen oog heeft voor vrijheid maar dat in vredige samenhang met gelijkheid en broederschap ziet. Geweldig dat je hier tien jaar de tijd voor hebt genomen.


Dank je wel.


Grote groet, -Harrie Jonkman


Mudge, S.(2018). *Leftism Reinvented: Western Parties from Socialism to Neoliberalism*. Cambridge: Harvard University. 410 pagina’s. €40,90.

