
# ONDERWIJSJONGENS ONDER ELKAAR


Amsterdam, oktober 2018


Beste Piet de Rooy, René Leverink en Gert Biesta,


“Bombardeer het stelsel. Begin opnieuw. Bouw op, van onderaf, school voor school, geleid door bewezen goede leraren”, zo schrijft leraar en journalist Tom van Haperen in zijn nieuwe boek ‘Het bezwaar van de leraar’. Het is nodig dat het onderwijs op de schop gaat en weer van de grond af opgebouwd wordt. Er is een onderwijsrevolutie nodig waarbij mensen uit de praktijk het weer voor het zeggen krijgen. Dat geluid staat haaks op wat de vereniging Beter Onderwijs Nederland met het onderwijs in Nederland voor ogen heeft. Volgens deze vereniging wordt er ondertussen al veertig jaar aan het onderwijs gesleuteld, is het een grote en permanente bouwput geworden en wordt het tijd dat we onze vingers daar eens vanaf houden. Als er al iets aan het onderwijs verbeterd moet worden, dan graag alleen veranderingen die uit het onderwijs zelf voortkomen; het wordt eindelijk tijd dat de vakbekwame onderwijsgevende het zelf weer voor het zeggen krijgt. Ook jullie kiezen in jullie nieuwe boeken de kant van de leerkracht. Jullie doen dat alle drie vanuit een ander perspectief: jij (Piet de Rooy) als historicus, jij (René Leverink) als leraar Nederlands en onderwijsjournalist en jij, Gert Biesta, als filosoof. Jullie vinden ook dat de leraar het zelf meer voor het zeggen moet krijgen en dat de kracht van het onderwijs vooral in het goed lesgeven zit. Jullie denken er noch revolutionair noch behoudzuchtig over en kiezen hier veel meer een middenpositie. Heb ik jullie als volgt goed begrepen?


Piet, volgens jou ontstaat het verschijnsel school wanneer onze cultuur overstapt van mondelinge naar schriftelijke overlevering en taalverwerving niet meer vanzelf gaat. Om een christelijke gemeenschap uit te breiden kon de kerk vervolgens de mensen niet ongeletterd laten. Na de middeleeuwen vindt het proces van uniformering en structurering van het onderwijs plaats en wordt het schoolregime eind 19e eeuw opgebouwd. Het klassikale onderwijs wordt ingevoerd en het onderwijs wordt kind-vriendelijker en professioneler. Tegelijk komt dat onderwijs vervolgens in een maalstroom van maatschappelijke verandering en pedagogische vernieuwing terecht. Jij zet die verschillende maatschappelijke en pedagogische ontwikkelingen in Nederland goed op rij en laat zien hoe het onderwijs bij de politieke discussie aansluit, klasse-gebonden wordt opgebouwd en de behoefte aan onderwijs groter wordt. Ik denk dat je gelijk hebt als je schrijft dat het onderwijs in vorige eeuw vooral door drie ontwikkelingen beïnvloed is. Allereerst door de Reformpedagogiek wanneer het onderwijs aansluit bij de individuele ontwikkelingen van kinderen. Vervolgens verandert dat onderwijs door het thema gelijkheid en de angst dat er talenten verloren gaan. Individuele zelfstandigheid wordt gekoppeld aan diploma’s en het onderwijs krijgt een sleutelrol in de opbouw van de moderne meritocratische samenleving. Wanneer die samenleving zich vertilt aan de idealen, maakt gelijkheid plaats voor excellentie en het vaststellen van onderwijskwaliteit en individuele verschillen gaan er meer toe doen. Jij stelt vast dat de taal waarmee over het onderwijs wordt gesproken dan wel steeds verschillend mag zijn maar dat de grammatica ervan (het schoolregime dat eind 19e tot stand kwam) een sterke continuïteit kent. Je wijst erop dat we nog steeds die schoolvakken kennen net zoals de jaarklassen, de schooltypen, de beoordelingen en diploloma’s. Ondanks dat we met elkaar veel klagen dat onderwijs, zijn we er ons er eigenlijk te weinig van bewust hoe groot dat succesverhaal van het Nederlandse onderwijs eigenlijk is. Al lijkt het onderwijs voortdurend in beweging, de continuïteit ervan is misschien wel veel sterker omdat het steeds weer naar overeenkomst moet zoeken. Jij onderstreept in jouw nieuwe boek de woorden van Langeveld, die ooit eens schreef: “De school is een compromis, zij is als zodanig een oplossing voor verbetering vatbaar, maar zal steeds een compromis blijven”. 
René, jij werkt als leraar in het onderwijs en schrijft er met regelmaat over. In die praktijk valt het jou steeds weer op dat de buitenwereld zich drukker maakt over dat onderwijs dan de mensen die erin werken. Dat klagen over het onderwijs, waar Piet het over heeft, herken jij goed. Iedereen lijkt zich met dat onderwijs te bemoeien, maar staat dat onderwijs er ook zo beroerd voor, zo vraag jij je in ‘Nee, dan Finland!’ af. Jij doet geen historisch of literatuur onderzoek maar gaat in gesprek met leerkrachten, bestuurders, politici, journalisten, wetenschappers, leerlingen en studenten en vraagt hen (en misschien nog wel meer aan jezelf): wat mag weg, maar vooral, wat moet blijven? Jouw mooi geschreven boek geeft een beeld van hoe we zouden om moeten gaan met kennis, de leerkracht en de school. Jij beseft dat elk gesprek al snel gaat over wat niet moet blijven en wat anders moet. We praten gewoon makkelijker over wat anders moet dan wat moet blijven. Wat moet blijven zijn uiteindelijk kernwaarden als de kwaliteit, de verscheidenheid, de toegankelijkheid en diversiteit van het Nederlandse onderwijs. Maar vooral zijn jouw gesprekspartners en jijzelf erover eens dat we de leraar als persoon moeten waarderen en herwaarderen en dat de relatie tussen de leraar en de leerling misschien wel de kern is van dat onderwijs. Als er iets moet blijven is het respect voor de leraar en een goede relatie tussen leraar en leerling. Die rol van die leraar moeten we ook weer niet teveel aandikken en we moeten er vanuit gaan dat die leraar het nooit perfect kan doen. Want dat hoort nu een keer bij die leerkracht en opvoeder, ‘de stakker die in het duister tast’ zoals jij als leraar Nederlands instemmend Simon Carmiggelt erbij haalt.
Gert, jij herkent dat tasten in het duister heel erg, ook al denk ik dat jij die leerkracht nooit een stakker zult noemen. Ook jij hebt het over de leerkracht of allicht meer over kracht van het lesgeven. Jij hanteert in jouw nieuwe boek ‘De terugkeer van het lesgeven’ een andere taal en jouw boek laat zich niet onderuitgezakt lezen. Jij wilt de praktijk van opvoeding en onderwijs tot steun zijn en ideeën aanleveren, niet om van te leren maar om mee te denken. Dat lesgeven er toe doet is voor jou niet zo interessant. Jou gaat het om hoe het ertoe doet en waarvoor het ertoe doet. Die interactie tussen leraar en leerling, die kern waar René het ook over had, wil jij verder doordenken. Jij ziet die relatie vooral als een dialoog. De dialoog is voor jou niet zozeer een gesprek maar een existentiële vorm, een manier om in de wereld te staan, en hier laat jij je door Arendt en vooral Levinas inspireren. De kern van het onderwijs voor jou is dat de leerling het vermogen herkent om aangesproken te worden. Die moet, zoals jij dat zegt, zijn vrijheid ontmoeten, als volwassene in de wereld leren staan, als subject. Het is aan de leraar om dat verlangen op te wekken. Volgens jou gaat het bij onderwijs (of opvoeding in het algemeen) om veel meer dan ontwikkeling en groei. Het doel van het onderwijs is niet zozeer dat leerlingen zich kennis, vaardigheden, manieren en competenties eigen maken en dingen leren. Het gaat erom dat die leerling volwassen wordt en zich kan verhouden ten opzichte van anderen en de wereld. Daarom moet de leerkracht de leerling niet vanuit een kille berekening of vanuit het ongewisse benaderen. Die leraar weet het nodige maar niet alles. Hij heeft de taak het gat tussen weten en hopen te overbruggen en op zoek te gaan naar de ‘onmogelijke mogelijkheid’, zoals Derrida dat noemde en ik als lezer nog steeds rechtop jouw boek zit te lezen.


Jullie zijn onderwijsmensen waarbij ik mij thuis voel. Met het revolutionaire van Tom van Haperen en het behoudzuchtige van het BON hebben jullie weinig op, allicht omdat jullie niets met het volmaakte op hebben. Aan het einde van jouw boek, Piet, haal je Montaigne aan en dat citaat had volgens mij ook in het boek van René en Gert kunnen staan: “Overtuigd zijn van een zekerheid is een onmiskenbaar teken van dwaasheid en van de uiterste onzekerheid.” Piet, jij komt uit een onderwijsnest en je gaf zelf graag les, denk ik. Jij laat zien hoe het onderwijs zich bij de wereld aansluit. Van mensen die weten waar het heen moet met het onderwijs moet je het niet hebben en over welke kant het op kan laat je je niet uit. René, ik weet dat jij graag over dat onderwijs praat en dat je er duidelijke ideeën over hebt. Van gezeur van onwetenden en bemoeizucht van hogerhand krijg je de kriebels. Tegelijkertijd praat je graag met mensen die dat onderwijs en de relatie tussen leerkracht en leerling serieus nemen, hoe divers ook. Gert, jij bent allicht de meest serieuze van jullie drie, althans in je boek. Je bent conservatief en radicaal tegelijkertijd. Jij drukt je uit in een eigentijdse, fenomenologische Langeveld-taal, niet helemaal mijn taal moet ik je in alle eerlijkheid zeggen. Maar de kern van jouw boek (dat volwassen worden en die weg zoeken tussen weten en hopen) vind ik weer bijzonder aansprekend en stimulerend. Schrijven over onderwijs is per definitie schrijven over vernieuwing, verandering en aanpassing, ook al wil je dat niet. Dat wordt na het lezen van jullie boeken wel duidelijk. Dat kan allicht ook niet anders want schrijven over onderwijs is schrijven over de toekomst. Opgeteld schreven jullie interessante boeken over het onderwijs en hoe dat en het lesgeven weer serieus genomen kan worden. Met deze boeken voelen leerkrachten zich in ieder geval gesteund en sta ik weer midden in de wereld.


Dank jullie wel.


Grote groet, -Harrie Jonkman

Rooy, P. de (2018). *Een geschiedenis van het onderwijs in Nederland.* Amsterdam: Wereldbibliotheek. 349 pagina’s. € 22,99.

Leverink, R. (2018). *Nee, dan Finland! De kracht van ons onderwijs*. Meppel: Ten Brink uitgevers. 168 pagina’s. € 12,95.

Biesta, G. (2018). *De terugkeer van het lesgeven*. Culemborg: Phronese. 182 pagina’s. € 24,95.

