
# EEN GEVOEL VAN MENSELIJKE MOGELIJKHEID


Amsterdam, november 2018


Beste Jesse Norman,


Op de een of andere manier heb ik de laatste tijd behoefte meer van economie te begrijpen en er over te lezen. Misschien wel omdat ik zie dat het in onze samenleving om economie draait en hier tegelijkertijd onze beperktheid zit. Het onderwerp is in handen van specialisten. Het lijkt erop dat die specialisten het daar graag willen houden en dat wij, niet-economen, het daar maar laten zitten. Waar gaat het om en, vooral, waar zou het om moeten gaan? Dat soort vreemde vragen stel ik mijzelf en hoe kan ik hier wat meer grip op krijgen? Om deze reden vond ik het boek Economics for the common good (2017)van de Franse Nobelprijswinnaar Jean Tirole zo goed. Hij wil die kennis juist niet bij de specialisten houden. In betrekkelijke eenvoudige taal legt hij in dat boek complexe zaken uit waar wij in onze tijd mee te maken hebben. Of het nu gaat over klimaatverandering of de Europese crisis, Tirole legt het netjes uit voor het brede publiek en dus ook voor mij. Zijn boek is vooral een antwoord op wat de rol van economie en economen vandaag de dag zou moeten zijn. Voor hem is het simpel: als we iets niet goed begrijpen, nemen we ook niet de goede beslissingen. Met goede informatie en het delen van kennis doen we dat wel en zo trekt Tirole als het ware de economie weer naar de samenleving toe. 
Jesse, jouw prachtige nieuwe boek ‘Adam Smith. What he thought, and why it matters’ doet dat eigenlijk ook en zo vul jij Tirole heel mooi aan. Jouw boek is heel anders dan dat van Tirole en geeft juist een indirect antwoord op hedendaagse vragen. Heel vreemd eigenlijk dat we bij deze ‘oude knar’ te rade gaan want in de tijd dat Adam Smith leefde moest de hele industrialisatie nog op gang komen. Jij maakt heel duidelijk wat wij aan Smiths denken kunnen hebben en volgens jou is het niet voor niets dat alle belangrijke economen (en filosofen) altijd maar weer teruggrijpen op zijn boeken. Adam Smith was veel meer dan een econoom en het is volgens jou zeker nu belangrijk om Smith te lezen en te weten wat zijn impact is en waarom hij er zo toe doet.  


Je begint het boek met de ideeënontwikkeling van Adam Smith. Smith wordt in 1723 geboren in Kirkcaldy en het internationale karakter van deze Schotse havenstad beïnvloedt hem. Hij wordt opgevoed door zijn moeder. Op veertien jarige leeftijd gaat hij naar de moderne universiteit van Glasgow. Economisch en politiek gaat het niet goed met Schotland en veel Schotten trekken in deze tijd naar het buitenland. Het kleine Schotland en het grote Engeland zijn dan nog twee koninkrijken en proberen samen aan een economische eenheid te werken. In Glasgow maakt vooral zijn docent Hutcheson een grote indruk op Smith. Hutcheson gaat in tegen het pessimisme van Hobbes voor wie de soevereine macht van de staat en de angst voor God de individuele mens in toom moet houden. Hutcheson heeft veel meer op met gedeelde normen en de liefde voor God en met de individuele mens die zelf een keuze maakt tussen goed en slecht. Na Glasgow vertrekt Smith naar Oxford waar hij zes jaar zal blijven. Van Oxford moet hij niet zoveel hebben en in deze voorbereidende jaren houdt hij zich vooral met literatuur en taal bezig en leest hij het werk van eigentijdse, vooral continentale, schrijvers. In deze jaren legt hij de basis voor zijn twee belangrijke boeken. In Oxford leest hij met grote interesse ‘Treatise of Human Nature’ van David Hume dat gaat over kennis en menswetenschap en het willen begrijpen van de mens in al zijn aspecten gebaseerd op feiten en ervaringen. Pas veel later zullen deze twee giganten elkaar ontmoeten, vrienden worden voor het leven en blijven voor altijd de grote Schotse Verlichters. Terug in Schotland komt Smith in een sfeer terecht van rebellie waarin Schotten zich, toen al, verzetten tegen de te sterke overheersing vanuit Engeland. Hij wordt in 1750 professor Logica en Metafysica aan de universiteit van Glasgow en blijft daar dertien jaar. Hij schrijft wat kleinere werken en in 1759 komt zijn ‘Theory of the Moral Sentiments’ uit. Teveel is er volgens hem gedacht over hoe mensen zouden moeten zijn, veel minder over hoe mensen in werkelijkheid zijn en juist daar wil hij het over hebben. In dit boek is sympathie een kernbegrip waarbij het volgens Smith belangrijk is dat mensen de emoties van de ander weten te detecteren en erover weten te reflecteren. Om onszelf te leren kennen moeten we ons kunnen verplaatsen in dat wat de ander bezig houdt. Er is echter, volgens Smith, nog een ander niveau dan dat van de leefwereld, een even belangrijke kant die Smith ook naar voren wil schuiven. Hier gaat het veel meer om de principes van de wet en de overheid, over geld en kapitaal. Aan een studie over dat meer abstractere, systeemniveau werkt hij vervolgens de komende dertien jaar. Adam Smith is dan nog steeds ongetrouwd en leeft met zijn moeder en nicht in Glasgow. Hij neemt afscheid van de universiteit, gaat als een commissaris en mentor werken voor de graaf van Buccleuch en met hem trekt hij twee jaar door West-Europa en vooral Frankrijk. Hier maakt hij kennis met mensen als Voltaire en Quesnay. In 1776 verschijnt dan dat tweede, even belangrijke boek An Inquiry into the Nature and Causes of the Wealth of Nations, dat gaat over economische processen en ontwikkeling. Staten kunnen welvarend of arm zijn en met kennis en informatie zijn de juiste keuzes te maken. In dit boek biedt Smith een algemene theorie, laat hij zien hoe de welvaart in verschillende contexten wordt uitgewerkt en persoonlijke vrijheid tot stand kan komen. Dit boek is vooral een pleidooi tegen slechte politiek. Het laatste deel van zijn leven woont hij in Edinburgh en werkt vooral aan nieuwe edities van zijn boeken.
Als jij de ideeën van Smith uitgebreid hebt beschreven, ga je in op zijn impact en de vraag waarom hij belangrijk is voor ons. Wetenschappelijk is hij volgens jou belangrijk omdat hij, net als zijn vriend Hume, de menswetenschap theoretisch onderbouwd. Bij de menswetenschap gaat het om algemene theorieën die verbonden zijn met de werkelijkheid en empirisch zijn onderbouwd met feiten en ervaringen en die in de tijd kunnen veranderen. De menswetenschap onderscheidt zich zo van de natuurwetenschap waar het gaat om het ontdekken van ‘onzichtbare ketens’ van de natuur. Het economisch denken van Smith is verbonden met rechtvaardigheid en wederkerigheid en om het opzetten van een gezonde markt. Hem gaat het niet in de eerste plaats om het verdienen van geld maar om wetten, instituten, normen en identiteiten die met een ‘onzichtbare hand’ een samenleving welvarend maken en persoonlijke groei mogelijk maken en daarin wijkt hij nogal af van hoe er tegenwoordig hierover wordt gedacht. 
 

In de tijd dat ik jouw nieuwe boek las, maakt jouw land (Engeland)een moeilijke tijd door. De leiders vallen elkaar op alle mogelijke manieren aan en de burgers staan er vertwijfeld naar te kijken. Er is sprake van een soort algemene rebellie die doet denken aan de rebellie in Schotland toen Smith er vanuit Oxford terugkeerde waar hij zijn werk had voorbereid. Het eens zo roemruchtige Engeland lijkt op dit moment maar niet te weten wat het moet doen en weet geen antwoorden te geven op de grote vragen waar het antwoord op moet geven. Wat is goed voor de economie, hoe gaan we om met de globalisering en hoe met de toenemende ongelijkheid, hoe gaan we extern om met onze buren en intern met de verschillen (regio’s en bevolkingsgroepen), waar trouwens niet alleen jouw land maar alle moderne landen mee te maken hebben. Misschien omarm je Smith wel te veel en mis ik soms wat kritische distantie. Jij maakt mij in ieder geval heel duidelijk dat Adam Smith geen historisch figuur is maar dat zijn ideeën juist springlevend zijn. Tegelijkertijd prik je enkele belangrijke mythen door die er over Smith bestaan: dat Smith eenzijdig zou zijn, een zelfzuchtige mens voor ogen heeft, enkel opkomt voor de rijken, tegen overheidsingrijpen is en dat hij alleen maar een econoom is. Smith is, volgens jou, een hele andere persoon: veelzijdig, in alles gericht op het sociale aspect, met oog voor de armen en hoe beslissingen deze groep ten goede kunnen komen, overtuigd dat de overheid juist op bepaalde momenten moet ingrijpen en hij verbindt economie met psychologie, sociologie, politicologie en ethiek. Smith heeft ideeën over macht, eigendom, commercie en ook over morele en sociale aspecten en het omgaan met elkaar. De leefwereld van liefde en vertrouwen, van familie en gemeenschap is hem net zo lief als de wereld van samenwerking, de meer onpersoonlijke en anonieme systeemwereld van economie en civilisatie waar mensen sociaal profijt van hebben. Deze samenhang en veelzijdigheid hebben we, daar ben jij van overtuigd en daarin overtuig je mij in ieder geval, in deze tijd van sociale versplintering nodig. Jij was academicus en bankier en bent conservatief parlementslid maar misschien wel vooral intellectueel die weinig op heeft met het neoliberalisme en het kapitalisme. Over die toekomst denk je heel prikkelend na. We hebben een nieuw samenhangend verhaal nodig voor deze tijd en Smith geeft, denk jij, aan dat verhaal structuur. Jij hebt een samenleving voor ogen waar iedereen voor zichzelf kan zorgen. Daarin is er plaats voor een sterke staat met veerkracht en strategisch vermogen die tegelijkertijd door onafhankelijke instituten in toom wordt gehouden. In die toekomstige samenleving zijn de belangen van bedrijven en markten verbonden met het algemene welzijn en geen werelden op zich. Die samenleving verdedigt de waardigheid van de burger, is kritisch naar commercialisering en moderne technologie en geeft antwoorden op vragen waar zij mee wordt geconfronteerd. Het begint volgens jou met het formuleren van nieuwe ideeën, met nadruk op een goed functionerende samenleving waarin mensen kunnen floreren en waarbij het algemeen welzijn voorop staat. De laatste vastgelegde woorden van Adam Smith, voordat hij op 17 juli 1790 sterft en hij van zijn vrienden afscheid neemt, zijn “Ik geloof dat we onze bijeenkomst naar een andere plek moeten verplaatsen”. Jesse, die bijeenkomst heb jij naar een andere plek weten te verplaatsen en dankzij jou kunnen we dat gesprek met Adam Smith voortzetten.    


Dank je wel.


Grote groet, -Harrie Jonkman


Norman, J. (2018). *Adam Smith. What he thought, and why it matters*. London: Allen Lane. 400 pagina’s. € 24,99.


