# HEEL DE MENS


Amsterdam, december 2018


Beste Marilynne Robinson,


‘I told you last night that I might be gone sometime, and you said, Where, and I said, To be with the Good Lord, and you said, Why, and I said, Because I’m old, and you said, I don’t think you’re old. And you put your hand in my hand and said, You aren’t very old, as if that settled it’. Dominee John Ames voelt het einde van zijn leven naderen en schrijft een brief aan zijn jonge zoon over zijn eigen leven en dat van zijn voorouders. Met deze zinnen begin jij jouw trilogie (Gilead, Home en Lila). Jouw goede leven-verhalen spelen zich af in Gilead, een dorp in landelijke Iowa midden jaren vijftig waar de honden ’s nachts nog rustig op straat slapen. Jij beschrijft in die boeken het doodgewone, dagelijkse leven met al de pijn en het verdriet, het plezier en de vergeving die erbij horen. Toen Barack Obama tijdens zijn eerste verkiezingstournee in 2007 naar het midden van Amerika ging, las hij jouw boeken. Jouw religieus humanisme sprak hem aan en hij voelde zichzelf zeer verwant met John Ames en de beproevingen waar deze dominee en zijn familie in zijn leven mee te maken hebben. Die boeken lieten hem zien hoe het gewone leven van Amerikanen eruit ziet, van mensen die werken om hun kost te verdienen en voor hun eigen kinderen en mensen in hun omgeving zorgen. Toen Barack Obama tijdens zijn tweede presidentschap werd gevraagd met welke schrijver hij eens wat langer een gesprek wilde voeren, hoefde hij niet lang na te denken. In de zomer van 2015 vloog hij met zijn presidentiële vliegtuig naar jou toe in Iowa en voerde met jou dat gesprek. Het verslag daarvan verscheen in twee afleveringen in de New York Review of Books en onlangs las ik dat gesprek nog eens. Obama wilde van jou wel eens weten door welke culturele krachten onze democratie eigenlijk tot stand komt en hoe onze ideeën vorm krijgen. Hij wilde weten waar het om gaat bij burgerschap en welke kant het met het land op zou moeten gaan. Jullie hadden in die zomer van 2015 nog totaal geen idee wat er zou gebeuren en hoe ver het land af zou komen te staan van dat religieus humanisme waar jullie beiden veel mee op hebben. In dat gesprek komt dat optimisme over democratie duidelijk tot uitdrukking. De basis van die democratie is voor jou, zo maak jij jouw president in dat lange gesprek duidelijk, dat we van het goede van mensen moeten uitgaan en dat mensen aan de ander moeten denken en niet alleen aan zichzelf. Zo simpel als dat. In jouw nieuwe boek breng jij al die zaken die Obama van jou wilde weten nog eens duidelijk naar voren.


Jouw nieuwe boek, *‘Wat doen wij hier?’* is de Nederlandse titel, kwam onlangs in mijn land uit. Daarin zitten vijftien lezingen die jij de afgelopen jaren hebt gegeven op universiteiten, in kerken en op hogescholen in binnen- en buitenland. In het voorwoord stel jij vast dat jullie Amerikanen (maar dat geldt net zo goed voor ons, Europeanen) tegenwoordig in een gepolariseerde samenleving leven waar mensen recht tegenover elkaar zijn komen te staan. Maar tegengestelde kampen hebben allicht met dezelfde problemen te maken omdat ze beide niet goed nadenken, vaak uitgaan van dezelfde valse aannames en de verkeerde conclusies trekken. De progressieven zijn dan vooral cynisch en de conservatieven denken daarbij vooral aan zichzelf. Maar, zo vraag jij je aan het begin en het gehele boek door af, waar blijft de wijsheid, de moed, de ruimhartigheid en de persoonlijke waardigheid in dit alles? Waar is die schitterende geest gebleven die er lang is geweest en waar is er nog dat het respect voor de hulpbronnen die die geest scherpen? 
Je bent bijzonder kritisch over deze tijd waarin we aangemoedigd worden om alleen maar naar praktisch nut te kijken en onze culturele erfenis links laten liggen. We worden op allerlei manieren gestimuleerd ons in te zetten voor de efficiënte en doelmatige economie. We worden alleen maar daarop voorbereid met als resultaat een decadente cultuur en een beschaving die eronder heeft geleden. Hoe anders was het nog toen Toqueville door Amerika reisde en daar ‘de geschenken uit de hemel’ tegen kwam (poëzie, welbespraaktheid, intelligentie, verbeeldingskracht en denkvermogen), die bejubelde en er nog weinig sprake was van rivaliteit of hiërarchie. Die cultuur straalde nog, was vooruitstrevend en werd gesteund door onderwijssystemen en andere culturele bronnen die voor deze geschenken konden zorgen. Er was respect voor de wijzen, de vertalers, de drukkers, de dichters en de filosofen waar jij nu een utilitaire vijandigheid constateert tegenover de schoonheid en de kunsten. 
Ten onrechte hebben we volgens jou de belangstelling voor de ziel en de metafysica weggejaagd. De wetenschap heeft zich tegenwoordig het terrein van het intellect en de rede toegeëigend. Jij hebt je verdiept in marxisme en darwinisme maar bent ervan overtuigd dat dit soort wetenschappelijke theorieën de werkelijkheid reduceren tot hapklare brokken waar het onbekende en het onbenoembare van zijn afgehaald. De wetenschap biedt een soort ultieme waarheid en een saaie antropologie waarin voor verbeelding nog nauwelijks plaats is en wetenschap heeft al helemaal geen poëzie of ethica voortgebracht. Vakbonden, kerkgenootschappen en deskundigen doen er niet meer zo toe en de burger, die nog oog had voor het geheel en trots was op wat hij of zij had bereikt, heeft tegenwoordig plaatsgemaakt voor de belastingbetaler. Het gaat niet meer in de eerste plaats over het land, de gemeenschap, de kinderen en de kleinkinderen; het gaat om het pensioenplan en de verzekeringspremie en vragen hebben definitief plaats gemaakt voor antwoorden. 
Jij hebt een belangstelling voor zaken waar weinig mensen belangstelling voor hebben. Ik kijk mijzelf ook maar meteen aan. Jij hebt veel op met de calvinistische en puriteinse cultuur die tot in de negentiende eeuw, zeker in Noord-Oosten van Amerika, zo belangrijk was. Wij, onkundigen en nogmaals daar hoor ik zeker bij, hebben daar een verkeerd beeld over als wij direct denken aan streng, strak en stijf. Jij benadrukt steeds weer dat het zoveel meer was dan een strenge religieuze minderheid. Het was een politieke en religieuze beweging die experimenteerde met nieuwe sociale orde met wederzijdse ruimdenkendheid en waar rechten van andersdenkenden werden gerespecteerd. Jij schrijft enthousiast over Calvijn, Cromwell en, vooral, Edwards die de menselijke natuur breed opvatten en oog hebben voor perceptie en ervaring, complexiteit en veranderlijkheid en alles wat anders is dan we ons kunnen voorstellen. We moeten ons het beste wat het land is overkomen goed herinneren. Niet alleen dat, we moeten ook proberen het beter te doen. Jij legt de lat hoog.
Jouw kijk op de huidige tijd is bijzonder donker. Die moderne tijd is volgens jou een tijd van mistroostigheid, nostalgie, ontheemding en onmenselijkheid. Daar waar de klassieke religie nog tot weidsheid en verbondenheid leidde, schoonheid, verwondering en nederigheid nog werden gezien en de wereld kreeg wat het verdiende, is daar nu al lang geen sprake meer van. We zouden op zoek moeten naar meer samenhang in ervaring en op kleine dingen letten die weer betekenis krijgen. We moeten eenzaam durven zijn, weer leren mijmeren en ruimte creëren voor twijfel, dromen en herinneren en met elkaar een soort intellectuele integriteit opbouwen die niet reduceert maar verbreedt en verdiept.


Net in de week dat ik jouw boek las, schreef mijn president een open brief aan alle Nederlanders. Hij ziet ons land als een teer bezit, iets dat broos en breekbaar is. Het gezonde land als een vaasje dat we goed met elkaar vast moeten houden. Die kwetsbare cultuur zie jij ook maar jouw pleidooi voor een integrale, intellectuele integriteit die iedereen in zijn eigen omgeving hoog houdt, spreekt mij veel meer aan. Het is niet iets dat we moeten vasthouden, het is iets dat we moeten delen. Jij bent op zoek naar een nieuwe waarheid waarin we op een waardige manier met en tegenover elkaar komen te staan. Die waarheid is voor jou natuurlijk vooral democratie. Net als in het interview met Obama laat jij ook in jouw nieuwe boek zien dat democratie iets is wat je met elkaar bereikt. Daarbij horen woorden als respect en woorden als efficiëntie en ‘wij en zij’ passen daar niet bij. Van democratie is alleen sprake als je het beste met de ander voor hebt. Democratie is voor jou de basis van alles. Het is jouw esthetiek, schrijf je, jouw ethiek en eigenlijk ook jouw religie. Als er een woord is dat je graag zou afschaffen is het competitie, het beter willen doen dan de ander, waar onze wereld mee vol zit. Jij hebt daar een verfrissende blik op. Want competitie zorgt ook voor angst. Want waarom zouden we bang zijn als anderen het net zo goed of beter krijgen als ons? Ga van je eigen kracht uit, lijk je te zeggen, en gun de ander ook wat jij jezelf gunt. Bij jou gaat het bij democratie niet in de eerste plaats om instituten en wetten (ook al zie je het belang ervan in). Bij jou gaat het dan vooral om hoe we met elkaar om gaan, de woorden die we daarbij zoeken, het geloof, de hoop en de liefde. Tegelijkertijd ben je ook bevreesd over hoe we met onze cultuur omgaan. Hoe zorgen we ervoor dat zo’n democratie in stand blijft? Daar maak jij je druk over. Het brede openbare onderwijs dat er voor zorgde dat de geesten van mensen scherp blijven, is niet meer voor iedereen toegankelijk. De zorg voor de hulpbronnen die dit ideaal in stand houden lijken we uit het oog te zijn verloren. 
Jouw boek is niet altijd even makkelijk geschreven en er waren momenten dat ik de draad even kwijt was. Net op  momenten dat ik dacht waar heb je het precies over, overdonder je mij als lezer. Jouw boek is vooral een pleidooi om zuinig te zijn om onze scherpe geest en op de prachtige hulpbronnen die deze geest scherp houden. Want: ‘Hij heeft nooit genoeg, de geest, nooit’, zo schreef Wallace Stevens eens en jij wijst daar nog eens fijntjes op. Zeker jouw scherpe geest heeft nooit genoeg, nooit. 


Dank je wel.


Grote groet, -Harrie Jonkman


Robinson, M. (2018). *Wat doen wij hier? Over geweten, geloof, geluk en wat het betekent om te leven*. Amsterdam: De Arbeiderspers. 320 pagina’s. € 22,99.


