
# LEREN OVER LEREN


Amsterdam, januari 2019


Beste Cora Bagley Marrett,


Volgens de grote Amerikaanse ontwikkelingspsycholoog Jerome Bruner waren er in de twintigste eeuw, die hijzelf overigens bijna helemaal meemaakte, vooral drie personen belangrijk. Allereerst natuurlijk Sigmund Freud, de Oostenrijkse grondlegger van de psychoanalyse. Wanneer Freud het over ontwikkeling had, keek hij terug. Alles bijna was in die beginjaren te vinden en wat er mis was gegaan, was daar misgegaan. Om problemen te overwinnen moest allereerst het verleden worden verwerkt. Dan is er de Zwitser Jean Piaget, die de ontwikkeling in het moment plaatste. Juist door goed naar dat moment te kijken, kon hij vier ontwikkelingsfasen onderscheiden. Iedereen doorloopt deze fasen (de sensomotorische, de pre-operationele, de concreet operationele en de formeel operationele fase)op weg naar cognitieve volwassenheid.  Dan was er nog de Russische ontwikkelingspsycholoog Lev Vygotsky, waar Bruner zelf het meeste mee op had; omdat Vygotsky de meest open en sociale ontwikkelingstheorie ontwikkelde en vooral omdat leren bij hem op de toekomst is gericht. Bij deze ontwikkelingspsycholoog ging het om het kind dat op weg is en met volwassenen en culturele materialen zijn eigen weg zoekt. Dat is natuurlijk een persoonlijke en interessante interpretatie over hoe mensen zich ontwikkelen en hoe ze leren. Precies aan het begin van een nieuwe eeuw, in 2000, kwam er een boek uit dat op leren een bredere kijk biedt (How People Learn: Brain, Mind, Experience, Nationaal Research Council). Zeker het laatste kwart van de 20ste eeuw was er rondom leren heel veel gebeurd en dat boek vat die inzichten goed samen. Het gaat uitgebreid in op hoe mensen leren en op vragen zoals waar experts van niet-experts verschillen, hoe mensen kennis van de ene naar de andere setting overbrengen, waar kinderen wel en ook weer niet van volwassenen verschillen, hoe onderwijs het beste vorm kan krijgen en wat de leraar daarin moet doen. Het boek werd een groot succes en breed gebruikt op lerarenopleidingen. Bijna twintig jaar later is dat boek over leren alweer behoorlijk achterhaald. Cora, jij weet dat inzichten hierover zich razendsnel ontwikkelden, op het gebied van neurologie en biologie bijvoorbeeld, over wat we weten over individuele en culturele verschillen en ook door technologische ontwikkelingen. Daarom boog jij je, met al jouw collega’s en vakgenoten uit verschillende disciplines, over de vraag wat er op dit moment vanuit de wetenschap en de praktijk over leren te zeggen is. Wat leer jij ons over dat leren?  



Jij laat zien dat mensen op hele verschillende manieren en binnen hele verschillende culturele contexten leren. Leren vindt plaats binnen talloze cognitieve, fysieke, sociale en culturele systemen. Qua basisstructuur en in het ontwikkelingsproces komen mensen nog wel met elkaar overheen. Echter, zij hebben allemaal hun eigen ervaringen en relaties en al die culturele verschillen zorgen ervoor dat mensen zich individueel ontwikkelen. Vanaf de geboorte scherpen de culturele contexten als het ware die ontwikkeling aan en zo zijn leren en cultuur voortdurend met elkaar in gesprek, zou je bijna kunnen zeggen. Op allerlei niveaus zijn er allerlei factoren die daarbij meespelen en die er een dynamisch proces van maken. Dat kunnen invloeden op het allerkleinste niveau zijn, via bloed of hormonen bijvoorbeeld. Het kunnen uiteraard ook invloeden op een heel abstract en veel meer algemeen niveau zijn, en dan heb je het over cultuur, politiek en samenleving. De factoren op de verschillende niveaus spelen ook nog eens op elkaar in, hormonen en armoede bijvoorbeeld, en die zorgen voor interactie-processen tussen micro- en macrofactoren. Het leren en het brein werken ook op elkaar in en dat vindt plaats vanaf het begin van het leven tot dat je dood gaat. En zo verandert het leren het brein en het brein verandert het leren. 
Mensen als Oliver Sacks en Elkhonon Goldberg hebben er ook al eens op gewezen, en dat doe jij met jouw comité ook, dat je de basis van het leren als een orkest moet voorstellen waarin hele verschillende instrumenten samen spelen. Dit orkest is geen rotzooitje. Integendeel, er zit vaak veel samenhang en consistentie in en bepaalde elementen zorgen daarvoor. Denk daarbij aan het geheugen, het vermogen om kennis en informatie op te slaan, en aan attentie, het vermogen te reageren op wat er op een bepaald moment gebeurt of zou moeten gebeuren. Dit zijn elementen met een duidelijke rol in dat leren-orkest. Om niet helemaal om te komen in de hoeveelheid opgebouwde kennis en informatie gaan mensen in hun leven een relatie aan met bepaalde delen van die kennis. Mensen zijn heel goed in het categoriseren van kennis, gebruiken bepaalde delen en laten andere delen vervolgens los. Ze bouwen hun eigen typische kennissystemen op en zijn ze ook in staat om specifieke cognitieve processen aan te gaan. Daarbij gebruikt de een de ene structuur en de ander gebruikt daar weer een andere structuur voor. Handig is het dan vooral dat je bepaalde cognitieve modellen gebruikt waarin jouw kennis is opgeslagen, die jij steeds weer kunt gebruiken en aanpassen in andere situaties of wanneer jij nieuwe problemen moet oplossen. Bewust leren, veronderstelt ergens moeite voor doen en dan gaat het om motivatie en willen leren. Dan is het goed dat je ergens bij betrokken wordt en dat het willen van binnenuit aangestuurd wordt.  
In jouw boek leg je uit dat leren overal en voortdurend plaatsvindt en dat de school daarin al langere tijd een fundamentele schakel vormt. Op school is er de invloed van de schoolomgeving en de leraren en zijn er de ervaringen die de leerlingen over de jaren opdoen. Op school krijgt de academische inhoud vorm, krijgen de leerlingen steun en maken ze strategieën eigen waarmee ze het leerproces op een gegeven moment zelf over kunnen nemen. Technologie kan het leerproces daarbij ondersteunen. Ook hier is niet één manier de beste manier want dat hangt af van de individuele leerling, wat hij of zij wil leren, de context waarin het plaats vindt en de manier waarop de technologie gebruik wordt. Hoe belangrijk onderwijs ook is, wat mensen leren vindt voor een groot deel buiten dat onderwijs plaats. Het hangt samen met de keuzes die iemand op een gegeven moment maakt en de omstandigheden waarin hij of zij opgroeit. De capaciteiten die ze hebben aan de ene kant en de bronnen waar ze gebruik van maken aan de andere kant veranderen wel sterk over de tijd. Cognitieve capaciteiten nemen halverwege het gemiddelde leven af. Tegelijkertijd is het dan wel zo dat je, als je ouder bent, weer beter gebruik kunt maken van jouw bronnen om jou heen waar je uit kunt putten en die op latere leeftijd weer beter toegankelijk zijn. Gelukkig is er nog hoop voor mensen die ouder worden en willen blijven leren.    


Leren is een dynamisch proces waarin biologische elementen (waaronder de ontwikkelingsfasen, de gezondheid, interesses en motivatie) en culturele elementen (de omgeving waarin je opgroeit, de mogelijkheden die je krijgt) tegelijkertijd meespelen. Als we een goed beeld willen hebben van leren, is een totaalbeeld noodzakelijk. Eén wetenschapper kan dat al lang niet meer in z’n eentje omvatten, een eigentijdse Freud, Piaget, Vygotsky noch Bruner zou dat kunnen. Voor zo’n totaalbeeld heb je zo’n grote en brede onderzoeksgroep nodig die jij voorzat. Dat totaalbeeld schets jij, met jouw grote onderzoekscomité, op een heldere en duidelijke manier en jij maakt mij heel duidelijk waar we staan. Het algemene plaatje is duidelijk. In de toekomst echter, schrijf je met veel zelfinzicht, moeten die elementen beter op elkaar afgestemd worden en moeten we beter grip krijgen op wisselwerking tussen de interne krachten en het contextuele spanningsveld. Alleen zo kunnen we het leren beter gaan begrijpen. We weten dus onderhand veel over het gemiddelde leren, we weten nog bar weinig over de variatie in het leren. Wanneer we meer over die variatie weten kunnen we individuele kinderen op school beter helpen, is technologie beter te gebruiken en kan het levenslang leren werkelijk vorm krijgen. Gepersonaliseerd onderwijs, waar verschillende onderwijsvernieuwers tegenwoordig voor pleiten, heeft wetenschappelijke onderbouwing nodig. Jouw (jullie) bijdrage biedt zo’n eerste, goede onderbouwing. Jouw boek is natuurlijk veel meer een rapport dan een boek omdat je al die verschillende perspectieven moest samenbrengen. Boeken lees ik zelf met meer plezier en gemak. Maar soms is het goed en heel prettig om kennis op zo’n breed terrein samengebracht te zien en, in dit geval, te leren over leren. 


Dank je wel.


Grote groet, -Harrie Jonkman


National Academies of Sciences, Engineering, and Medicine (2018). *How People Learn II: Learners, Contexts, and Cultures*. Washington, DC: The National Academies Press. https://doi.org/10.17226/24783, 347 pagina’s.


