
# MENS EN MACHINE


Amsterdam, februari 2019


Beste Hannah Fry,


Miljarden mensen zijn tegenwoordig via machines met elkaar verbonden. De digitale revolutie heeft de wereld de laatste decennia fundamenteel veranderd en het einde van de ommezwaai is nog lang niet in zicht. Mensen als Bill Gates en Mark Zuckerberg zijn natuurlijk nerds maar zij hadden vanaf het begin ook een sociale missie: de wereld moet open worden en verbonden. Zij hadden met de nieuwe media een democratisch doel voor ogen. Die nieuwe media hebben ook een keerzijde en meer en meer mensen maken zich daarover zorgen. Zijn de sociale media niet veel meer anti-sociale media, zorgen die in plaats van verbondenheid niet veel meer voor versplintering en zijn die media niet iets waar mensen juist voor gewaarschuwd moeten worden? Ondertussen zijn er over dat anti-sociale karakter van deze media duidelijke voorbeelden. In Birma werden de sociale media gebruikt bij de etnische zuivering op grote schaal van de Rohingya-bevolkingsgroep in het noorden van dat land. En Cambridge Analytica zou op basis van hun inzichten op het gebied van persoonlijkheidsonderzoek de verkiezingen in Amerika hebben beïnvloed en hielp Trump zo aan een kleine meerderheid. Mensen weten niet goed hoe zij zich hier een houding moeten aannemen. Ze zijn op vele momenten op een dag met die nieuwe media bezig en voelen zich er ook weer niet helemaal gelukkig bij, ikzelf incluis. Misschien herken je het wel, maar als ik ’s ochtends vroeg de trein instap zie ik iedereen naar zijn of haar eigen beeldscherm kijken. Op die momenten vraag ik mij regelmatig af of we alleen voor onszelf zijn geschapen. Even later klap ik mijn eigen i-pad open om de krant te kunnen lezen en gaat er een wereld voor mij open. Hannah, jouw nieuwe boek ‘Hello world. How to be Human in the Age of the Machine’ is juist hier voor mij bijzonder leerzaam en inzichtelijk. Jij ziet de grote voordelen in van deze digitale ontwikkeling en laat ons zien wat er wel niet allemaal gebeurt en mogelijk is op dit terrein. Tegelijkertijd houd jij een gezonde afstand en neem je lang niet alles maar voor lief. Jij bent een wiskundige op het terrein van stedelijke problematiek en ruimtelijke analyse. Vanuit die positie houd jij je dagelijks bezig met allerlei sociale problemen. Met jouw wiskundige kennis en programmeertalent weet jij heel goed wat er allemaal onder de motorkap gebeurt en jij laat ons heel goed zien wat al die algoritmes ons brengen. Jij vindt dat we die moderne machine vooral goed moeten begrijpen. Alleen dan kunnen mensen zich beter tot de machine verhouden. Het lijkt er soms op dat we de controle verliezen en juist dat wil jij voorkomen. Maar hoe kunnen we die controle weer terugkrijgen en zorgen we voor een gezonde relatie tussen mens en machine? 


Algoritmes zijn procedures om stap voor stap een bepaald probleem op te lossen of ergens te komen. Daarvoor worden verschillende procedures gebruikt als prioriteren, classificeren, associëren en filteren. De algoritmes krijgen regels mee die door mensen zijn geprogrammeerd en dat alles wordt onder de paraplu van deep learning, machine learning en kunstmatige intelligentie. Er lijkt een soort strijd gaande tussen mens en machine waarbij jij vaststelt dat die machine nooit perfect is maar het alleen aan de mens overlaten nog tot meer fouten leidt. Daarnaast is er ook nog de strijd tussen privacy en wie er gebruik mag maken van gevoelige informatie. Jij bent enthousiast als we maar niet te ver doorschieten. In jouw boek ga je in op het gebruik van algoritmes op een aantal concrete terreinen. In het rechtelijke systeem wordt er vanuit gegaan dat absolute zekerheid nooit te verkrijgen is en rechters nooit op eenzelfde manier beslissen. Maar als een groep rechters eenzelfde geval wordt voorgelegd, worden er toch wel hele verschillende beslissingen genomen. Er is hier veel tegenstelling en complexiteit en algoritmes kunnen wat meer consistentie brengen en zorgen voor betere weging. Met data over een individu kunnen rechters bijvoorbeeld heel goed het risico berekenen of iemand weer in de fout gaat. Op Rhode Island (USA) worden deze algoritmes al gebruikt in de rechtspraak en daar hebben ze ervoor gezorgd dat het percentage mensen dat in de gevangenis zit met 17% is afgenomen en het recidive percentage met 6% is afgenomen. Ook in de gezondheidszorg wordt er op brede schaal van algoritmes gebruik gemaakt juist omdat ze zo goed zijn in het ontdekken van patronen, in het classificeren en het voorspellen. In het diagnosticeren van biopsies van kankercellen zien pathologen cellen nauwelijks voor kankercellen aan als er geen sprake is van een tumor. Maar in het vaststellen of er werkelijk sprake is van een tumor is het algoritme gewoon veel beter. Hier lijkt de samenwerking tussen mens en machine vooralsnog het beste te zijn. Ook dagelijkse objecten worden voorzien van algoritmes en de zelfrijdende auto is daar een voorbeeld van. De auto kan heel goed de informatie van o.a. de omgeving, de bestemming, het wegdek en de verkeersituatie tegelijkertijd inschatten. Al die informatie van verschillende kanten wordt gebruikt en zorgt er voor dat de beste oplossing wordt gekozen. Die zelfrijdende auto’s zitten boordevol met Bayesiaanse algoritmes die zorgen voor voortdurend updaten van informatie. In de kunst, tenslotte, zijn de algoritmes minder succesvol. Het voorspellen of een film bijvoorbeeld populair zal worden blijft een ingewikkelde kwestie. Misschien vooral ook wel omdat het moeilijk is kwaliteit vast te stellen. Wat wij hier zien is dat individuele voorkeuren gerangschikt kunnen worden en dat er zo groepen gevormd worden met een bepaalde smaak. Iets nieuws bedenken dat kan een machine niet omdat het toch voortbouwt op wat er al is en hier raken algoritmes aan hun grenzen.


Algoritmes en kunstmatige intelligentie hebben ons leven veranderd. Maar mens en machine hebben al heel lang met elkaar te maken. Mensen hebben zich altijd moeten positioneren ten opzichte van de techniek. Aan het begin van jouw boek geef je een mooi voorbeeld van de brug in New York waar door de lage ophanging alleen maar auto’s gebruik van konden maken. Bussen niet, en zo zorgde deze bewuste technische ingreep ervoor dat alleen rijke, blanke mensen bij de zee konden komen. Over dat soort zaken kunnen wij keuzes maken en alleen daarom al staat bij jou het menselijke aspect in alles voorop. Het is jou er vooral om te doen dat mensen kritisch staan tegenover deze nieuwe ontwikkelingen. Om zo’n houding aan te nemen, moet je weten hoe de techniek in grove lijnen werkt en wat er mogelijk is. Ten onrechte hebben wij vaak blind vertrouwen in zaken die we niet goed begrijpen, schrijf je ergens. Een gezond wantrouwen is hier eerder op z’n plaats en met dat gezonde wantrouwen heb jij dit boek geschreven. Bovendien moeten we met elkaar beter doorkrijgen wanneer vrijheden worden beperkt en hoe we dat wettelijk kunnen inkaderen. Het is niet alleen die kritische houding waar het jou om te doen is en die jij de lezer mee wilt geven. We moeten gewoon ook niet alles van die digitale ontwikkeling verwachten want die algoritmes en kunstmatige intelligentie kunnen gewoon niet alles. Er zijn gewoonweg grenzen aan het kwantificeren van de werkelijkheid. In het overdragen van emoties bijvoorbeeld zijn algoritmes heel beperkt. De magie van de frisse creatie hebben ze gewoon niet in zich omdat ze de dagelijkse ervaring missen. De machines zijn bijzonder bruikbaar in ons leven en de resultaten zijn nu al indrukwekkend. Maar die machines leveren weer hele nieuwe menselijke problemen op waaronder privacy, fouten en transparantie. Jij laat zien wat die machines wel niet opleveren en laat ook zien met welke problemen ze ons opzadelen. In jouw boek bespreek je geen kwesties op wereldschaal en wat de consequenties zijn van het moderne leven waarin we met desinformatie te maken hebben. Jij blijft in jouw boek dichtbij huis. De beste algoritmes houden voor jou in alle opzichten rekening met de mens. Algoritmes komen vooral tot hun recht waar mens en machine samenwerken en elkaars sterke en zwakke punten kennen. En zo is verbondenheid misschien wel nooit zo belangrijk geweest als in deze tijd van versplintering.


Dank je wel.


Grote groet, -Harrie Jonkman


Fry, H. (2019). *Hello world. How to be Human in the Age of the Machine*. London: Transworld Publishers Ltd, 256 pagina’s. € 18,99


