
# NEDERLAND VANUIT DE LUCHT


Amsterdam, maart 2019


Beste Kim Putters en Hans Boutellier,


Vorig jaar verscheen van Herman Tjeenk Willink Groot denken, klein doen. Zijn oproep doet qua inhoud en vorm recht aan de titel en hij neemt erin de staat van Nederland de maat. Over de Nederlandse staat maakt hij zich namelijk zorgen omdat hij denkt dat de staat de problemen waar hij tegenaan loopt (klimaat, migratie, ongelijkheid en maatschappelijke tegenstellingen) niet goed kan oplossen. Bovendien kan de staat nauwelijks nog de open samenleving garanderen. Concurrentie en consumptie hebben het overgenomen van samenwerken en solidariteit en dat vraagt ook om problemen. Volgens Tjeenk Willink zit het niet goed met de verbindingen; het zit niet goed met de verbindingen binnen de overheid, met de verbindingen tussen overheid en de burgersamenleving en ook niet met de verbindingen binnen de burgersamenleving zelf. De afgelopen tijd is er binnen de Nederlandse samenleving zoveel op de schop gegaan dat alleen nog het fundament van de democratische rechtsorde overeind is gebleven. Dat dreigt ook nog eens uit zijn evenwicht te geraken nu te veel macht in handen van de politiek terecht is gekomen. De politiek van tegenwoordig weet daar zelf niet goed mee om te gaan omdat visies zijn verbleekt, verantwoordelijkheid niet goed is gedefinieerd en het daar ontbreekt aan kennis. Tjeenk Willink is duidelijk. We moeten tegenwicht of tegenspraak organiseren en daarvoor is publiek debat nodig, dat kan niet zonder Europa en de verantwoordelijkheid van de burger en daarvoor zijn de kwaliteit van de uitvoering en de onafhankelijkheid van de rechters zo noodzakelijk. Het perspectief van Tjeenk Willink is subtiel en tegelijkertijd rechttoe rechtaan. Kim en Hans, ik had die tekst in mijn achterhoofd toen ik jullie nieuwe boeken de afgelopen twee weken las. Ook jullie sociaal-culturele studies gaan over Nederland en waar die samenleving mee te maken heeft.  


Kim, volgens jou gaat het behoorlijk goed in Nederland, als je de berichten mag geloven in ieder geval. Op allerlei terreinen schieten de positieve cijfers ons om de oren. Jij waarschuwt ons echter omdat we te weinig oog hebben voor een aantal smeulende kwesties waar in ons land ook sprake van is. Over die kwesties schreef jij de afgelopen jaren in het Financieel Dagblad een column. Op 12 februari 2014 schreef jij je eerste column, Decentraliseer niet zonder echte macht voor burgers, over het belang van onafhankelijke en kritische informatievoorziening. Op 25 oktober 2018, viereneenhalf jaar later, schreef jij de laatste column die in dit boek is opgenomen, Gevangenen van ‘dikke ik’, over menselijke gedrag dat steeds meer aan onszelf wordt afgemeten en steeds minder aan anderen of wat het voor de gemeenschap betekent. Die columns heb jij in dit boek van kop en staart voorzien en je hebt de columns gerangschikt naar vraagstukken rond werk, leren, zorgen en samenleven. In jouw boek maak je duidelijk dat onze samenleving van tegenwoordig het paradigma van de markt kent en de eigen verantwoordelijkheid van de burgers voor alles gaat. Dat heeft geleid tot verdere verzakelijking en individuali-sering, ontkerkelijking en technologische ontwikkelingen zorgden er al helemaal voor dat het individu met zijn en haar mogelijkheden centraal is komen te staan. De samenleving in zijn geheel heeft er onder te leiden gehad want die kan niet zonder verbindingen tussen mensen en die heeft meer gemeenschapszin nodig. Kim, jij bent vooral een beleidsman en in dat beleid is volgens jou teveel gedacht in losse maatregelen en te weinig in samenhang. Zo’n samenhangende visie is er nou net nodig wanneer het vraagstukken van werk, leren, zorg en samenleven betreft. Als we, schrijf jij aan het einde van jouw boek, op deze terreinen de nadruk gaan leggen, er nog wat Algemene Zaken, Defensie en Buitenlandse Zaken aan toevoegen, zijn we een heel eind. Het lijkt zo simpel.
Hans, jou ken ik natuurlijk als collega en ik weet enigszins hoe jij tegen zaken aan kijkt. In jouw Veiligheidsutopie en De Improvisatiemaatschappij leg je de moderne, complexe samenleving bloot met z’n dubbele spagaat van vitaliteit en controle. In die boeken verdedig jij al de stelling dat de moderne samenleving niet meer van bovenaf te organiseren is maar om zelf-organiserende processen onder structurele condities vraagt. Drie jaar geleden schreef jij Het seculiere experiment waarin het ook weer om de moderne samenleving gaat. Die moderne samenleving is seculier geworden. Maar is zo’n moderne samenleving, zoals we die sinds de jaren zestig hebben leren kennen, wel mogelijk en kunnen we wel van God los samenleven? Wat het ons maatschappelijk gebracht heeft, laat jij in enkele veldstudies zien. Sinds het verschijnen van dat boek is er veel gebeurd in de wereld en hebben we de Europese vluchtelingencrisis gehad, is Trump in Amerika tot president gekozen en wil hij dat land weer groo maken en hebben de Engelsen met de Brexit voor zichzelf kozen. Het is volgens jou nog duidelijker geworden dat we nergens meer in geloven, alles mogelijk is en we eigenlijk alleen nog in onszelf geloven. Onze ooit muurvaste, liberale tradities met universele pretenties zijn onder vuur komen te liggen en zelfs vijandschap is in ons vocabulaire terug van weggeweest. Stabiliteit van de samenleving is er volgens jou het meest bij gebaat als het algemeen belang voorop staat, divers samenleven mogelijk wordt gemaakt en problemen klein worden gehouden. Daarnaast is het goed om te improviseren en niet te claimen dat je de waarheid in pacht hebt. Het seculiere experiment dat we met z’n allen zijn aangegaan, leidde niet tot wanorde en ongeluk, zoals velen aanvankelijk dachten, en er zijn positieve en negatieve kanten te onderscheiden. Jij bent optimistisch over de ontwikkelingen omdat we nu de kracht uit onszelf moeten halen, we een moraal van onderop vormgeven en er geen instantie boven ons meer nodig is. Als wij mensen het maar met elkaar weten te vinden en er steeds wat op weten te verzinnen. De rechtstaat en rechten zijn voor jou essentieel maar jij veronderstelt ze bijna, misschien wel te veel en in ieder geval meer dan Tjeenk Willink, Putters en ikzelf. De laatste jaren is het voor jou duidelijk geworden dat nu ‘die hemel eenmaal in scherven naar beneden is gekomen’ (Kees Fens), wij ons zijn gaan afvragen wie we zijn. Eerst leek het in de jaren zestig en zeventig nog op hemelse herrie maar toen iedereen om respect en erkenning ging vragen, werd het ernst en is het omgeslagen naar helse herrie. Zelfrealisatie en identiteitspolitiek zijn de plaats in gaan nemen van collectief welbevinden en maatschappelijk welzijn en daar voel jij je, terecht, niet bij thuis. Moraliteit moet de plaats innemen van identiteit en zo moeten we, voor mij te relativerend, momenten zoeken, faciliteren en organiseren om de grote vraagstukken van deze tijd (milieu, migratie en kunstmatige intelligentie) te lijf te gaan. Jij zoekt het midden tussen de wereld van het individu en de markt aan ene en de staat en solidariteit aan de andere kant. Jij bent op zoek naar een wereld waar mensen elkaar in kleiner verband ontmoeten, van dagelijks samenleven en waar ieder mens een waarde in zichzelf is. 
 

Tjeenk Willink, de wijze staatsman, definieert het subtiel en rechttoe rechtaan, ik schreef het al: het is nodig om positie te kiezen, je stem te verheffen, het debat aan te gaan en uiteindelijk te zeggen hier ligt de grens. De huidige samenleving kan de maatschappelijke problemen niet aan. Alleen door tegenspraak te organiseren wordt die samenleving weer vitaal en gezond. Met het organiseren van tegenspraak zijn jullie het volledig eens. Kim, jij hebt er, net als Tjeenk Willink, weinig fiducie in dat grote maatschappelijke problemen goed kunnen worden opgelost op dit moment. We zijn de samenhang uit het oog verloren en daarom heeft onze samenleving een nieuwe visie en meer houvast nodig. Beter definiëren hoe we met elkaar omgaan, daar gaat het om, en zo ben jij, Kim, op zoek naar een beter verhaal over Nederland, een verhaal dat voor alle Nederlanders opgaat. Veenbrand (met een wel erg onheilspellende voorkant) wil hier een aanzet voor geven. Jij denkt aan een ‘sociaal contract’ tussen overheid en burgers waar filosofen als Locke, Rousseau en Rawls eerder voor pleitten. Maar jij bent veel meer een beleidsman dan een filosoof, voor mij soms te veel. Want als jij aan een sociaal contract denkt, heb jij het over een nieuw ‘Akkoord van Wassenaar’ waarin lusten en lasten redelijk verdeeld worden in Nederland. Of dat een beter verhaal over Nederland en voor alle Nederlanders wordt, vraag ik mij af. Uiteindelijk ben jij op zoek naar een nieuwe polder zonder veenbranden met een visie op vier grote sociaal maatschappelijke vraagstukken, ondersteund door de democratische rechtsstaat en actief gekoesterd door de politiek. In jouw verhaal is er een expliciete rol weggelegd voor de elite, die die nieuwe polder samen met de burgers en de bedrijven vormgeeft. Hans jij gelooft ook niet dat de huidige Nederlandse samenleving de maatschappelijke problemen kan oplossen waar ze tegenaan loopt, schrijf je in Het seculiere experiment. Anders dan Kim geloof jij echter niet in zo’n eenheidsscheppend verhaal en zoek jij het meer in betekenisvolle momenten, kleinere verhalen en inspirerende praktijken. Jij zoekt naar de wereld die we dagelijks met elkaar vormgeven. De rechtstaat en de rechten van de mens zijn voor jou fundamenteel maar in jouw boek leg jij de nadruk op een ander niveau, namelijk dat van de moraliteit en de wijze waarop mensen met elkaar omgaan. 
Kim en Hans, het is mij duidelijk dat jullie, net als Tjeenk Willink, naar nieuwe wegen zoeken om het oude liberale idee van representatieve democratie, mensenrechten, de vrije markt en de ondersteuning van zwakkeren in de samenleving overeind te houden. Dat oude, vertrouwde liberale ideaal is jullie, net als mij, heel veel waard, vraagt onderhoud en is nu werkelijk aan revisie toe. Het kan alleen overeind blijven staan als er sprake is van democratische participatie, er meer nadruk komt te liggen op morele actie en het algemeen welzijn van iedereen voorop staat. Dat ideaal, voeg ik er hier expliciet aan toe, heeft een politiek nodig die meer is dan marktdenken, een wetenschap die verbeeldt en verbetert en een mensbeeld dat meer op de ander en minder op onszelf is gericht. Ook in Nederland moeten we dat ideaal nieuw leven inblazen en daarom alleen al zijn jullie boeken waardevol. Als we ons er maar van bewust zijn dat dat oude, vertrouwde liberale ideaal niet alleen voor onze kleine polder geldt en we ook in dat opzicht niet alleen aan onszelf denken.  


Dank jullie wel.


Grote groet, -Harrie Jonkman

Boutellier, H. (2019). *Het seculiere experiment. Over westerse waarden in radicale tijden. Tweede, herziene druk*. Den Haag: Boom bestuurskunde. 225 pagina’s (verschijnt binnenkort). 

Putters, K. (2019). *Veenbrand. Smeulende kwesties in de welvarende samenleving*. Amsterdam: Prometheus, 224 pagina’s. € 19,99


