
# HANNAH ARENDT NU


Amsterdam, april 2019


Beste Richard Bernstein,


Nadat Trump in Amerika tot president werd gekozen, wilde ik John Rawls eens goed lezen. Nu in mijn land recent ook vreemd werd gekozen, had ik weer behoefte aan een stevig tegengeluid. Jouw boek Why read Hannah Arendt now lag al langer op mijn bureau en dit was het goede moment het te lezen. In de jaren na mijn studietijd las ik jouw boeken bijzonder graag, zoals The Restructuring of Social and Political Theory, Beyond Objectivism and Relativisme: Science, Hermeneutics and Praxis en Philosophical Profiles: Essays in a Pragmatic Mode. Ik nam ze mee op lange reizen en weet nu bij verschillende hoofdstukken nog waar ik ze las. Voor mij ben jij vooral altijd de goede lezer geweest met een smaak die ik van harte deel. Jij begrijpt al die interessante sociale en politiek filosofen van de twintigste eeuw zo goed die ik langzamerhand tot mijn vriendengroep ben gaan rekenen. Of het nu over Gadamer, Habermas, Rorty of Dewey gaat, jij wilt ze begrijpen, gaat met ze in gesprek en probeert er uiteindelijk jouw mening aan toe te voegen. Jij hebt altijd met groot enthousiasme over het Amerikaans pragmatisme geschreven, zoals ook weer in jouw meer recente boeken als Pragmatic Turn en Pragmatic Encounters. In jouw werk zoek je het midden tussen absolute waarheid en alles is mogelijk. Jij verdedigt het idee van het praktische oordeel (phronesis), de praktische wijsheid die we nodig hebben als we omgaan met de complexe wereld en geconfronteerd worden met politieke, sociale, ethische en culturele vraagstukken. We kunnen niet anders dan luisteren naar wat anderen te zeggen hebben; want als we dat niet doen komt die democratische samenleving in gevaar. Een van die filosofen waar jij ook altijd met groot enthousiasme over hebt geschreven is Hannah Ahrendt. Jij was haar leerling en ik ken niemand die zo goed over haar kan schrijven als jij dat kunt. Jouw elegante laatste boek, waarin jij haar denken in deze tijd plaatst, maakt dat weer duidelijk. Volgens jou was Arendt zich bewust van de problemen en gevaren van het moderne politieke leven. Met Hannah Arendt kunnen we waardigheid in dat leven terug brengen. Deze tijd vraagt niet zozeer om theorieën maar heeft meer aan het leven en het werk van individuen, zoals van Hannah Arendt, voor jou een lichtend voorbeeld in donkere tijden. 


Hannah Arendt studeerde filosofie bij belangrijke filosofen van haar tijd. Alles verandert voor haar als Hitler en zijn aanhangers ook haar als Jodin bedreigen en aanvallen. Als dat zo is, dacht zij, moet je jezelf ook als Jodin verdedigen en daarom houdt zij zich de jaren erna met het Joodse vraagstuk en het Zionisme bezig. Zij wil het fenomeen van statenloosheid doorgronden waar Europa op dat moment op grote schaal mee te maken heeft. Het nationalisme krijgt er voet aan de grond wanneer de macht in handen komt van een dominante groep die de cultuur, de taal en geschiedenis definieert. Echter, daar is ze van overtuigd, alle mensen verdienen het recht om rechten te hebben en een georganiseerde gemeenschap die in staat is die rechten te garanderen. Nationalistische en totalitaire staten worden gevormd, mensen worden ontdaan van hun spontaniteit, individualiteit en verscheidenheid en wat overblijft zijn levende lijken die nergens meer op terug kunnen vallen. Hannah Arendt zelf voelt zich vooral thuis in de traditie van de Joodse pariahs, bewust en bereid om tegen onrecht te vechten en die met hun anders zijn een plaats in de gemeenschap opeisen. Over het Zionisme is ze kritisch omdat die geen oog heeft voor het perspectief van de Palestijnen en Arabieren. Zij is voor een Joods thuisland met zelfbestuur waarin Joden en Palestijnen vreedzaam samenleven in plaats van een Joodse natiestaat die er uiteindelijk is gekomen. Haar standpunt in deze krijgt veel kritiek, vooral in eigen kring. Met zware kritiek krijgt zij in haar leven vaker te maken. Ook wanneer zij al enige tijd in Amerika woont en zich uitspreekt tegen verplichte schoolintegratie. De keus voor een school is, volgens Arendt, de keus van ouders en de overheid mag en kan deze integratie niet aan burgers opdringen. De opvoeding van kinderen moet gescheiden blijven van politieke strijd. Zij onderschat de politieke consequenties en dat zal ze zelf later ook inzien. Tegelijk wijst zij erop dat het racisme niet eindigt wanneer de integratie op scholen een feit is omdat het tegengaan van racisme veel meer vraagt. In de zestiger jaren wordt ze wederom fel aangevallen met haar nieuwe kijk op het kwaad wanneer ze het Eichmann-proces in Jerusalem verslaat. Zij bekritiseert de rol van de Joodse Raden en het Joods leiderschap tijdens de Tweede Wereldoorlog. Kritiek krijgt zij vooral omdat ze Eichmann niet als een monster en veelmeer als doodgewone crimineel ziet. Voor deze grootste misdaden acht zij hem volledig verantwoordelijk. Zij laat echter zien dat Eichmann zich niet realiseerde wat hij deed omdat hij een, wat Kant noemde, een ‘vergrootte mentaliteit’ miste. Precies dat maakt zijn handelen zo banaal. Haar analyses over waarheid en politiek zouden gisteren geschreven kunnen zijn. Om goed te kunnen functioneren kan politiek niet zonder feitelijke informatie. Zij weet maar al te goed dat politiek wel iets heel anders is dan verpleegkunde en dat politiek feitelijke informatie als gewoon een andere mening kan definiëren. Zeker autoritaire systemen gebruiken deze werkwijze en we zien nu ook dat binnen democratische politieke systemen regelmatig alternatieve feiten worden gepresenteerd. Voor mensen die niet meedoen, die over het hoofd worden gezien en angstig zijn, zijn deze alternatieve feiten vaak een sterker narratief dan redelijke argumenten. Ook daarom is zij voor politiek die dicht bij mensen staat en waar mensen direct in participeren. Vrijheid is alleen mogelijk als het ruimte geeft aan individualiteit, spontaniteit en verscheidenheid en het is onze persoonlijke en politieke verantwoordelijkheid dit leven vorm te geven. 


Ook in Nederland is er op dit moment grote belangstelling voor het leven en werk van Hannah Ahrendt. Ik werd begin jaren tachtig op haar boeken gewezen door een docent die, net als jij, colleges bij haar had gevolgd en keer op keer met haar boeken aan kwam zetten. Hans Achterhuis maakt haar in mijn land breder bekend en Elisabeth Young-Bruehl maakt haar met haar biografie wereldwijd bekend. Ondertussen is Hannah Arendt ook in mijn land een cultfiguur geworden, een positie waar zijzelf, zo stel ik mij voor, heel hard om zou hebben gelachen. Met regelmaat wordt over haar geschreven, onlangs nog door Joke Hermsen. In Het tij keren. Met Rosa Luxemburg en Hannah Arendt ziet Hermsen haar, net als jij, als lichtend voorbeeld in deze tijd van neoliberaal kapitalisme, elitarisme en technocratie, die ons voorbij individuele belangen laat kijken. In al die aandacht die er voor haar is, laat bijna niemand zien waarom zij eigenlijk zo belangrijk is. Jouw boek is dan misschien geen systematische beschrijving van haar werk maar jij haalt er een groot aantal thema’s uit die volgens jou zo belangrijk zijn voor deze tijd. Zo laat jij zien waarom het denken van Hannah Arendt bijzonder en eigentijds is, of het nu over vluchtelingen gaat, Israël, de verschrikkingen van totalitaire regimes, liegen en alternatieve feiten, waardigheid of, bovenal, verantwoordelijkheid. Voor jou is Arendt de kritische dwarsdenker die ons er keer op keer op wijst dat we iets kunnen beginnen en dat wij iets in beweging kunnen brengen. Zij is pessimistisch noch optimistisch en besteedt in haar werk evenveel aandacht aan menselijkheid als aan onmenselijkheid. Zij weet waar het mis kan gaan en ook weer waar mensen de rug rechten. Zij is wantrouwig naar zowel doemdenken als vooruitgangsgeloof en kan niet tegen nihilisme, cynisme en onverschilligheid. Het enige dat we kunnen en moeten doen is steeds zelf nadenken en een oordeel vellen. Het is zaak om ons politieke kwesties aan te trekken en politiek niet alleen aan politici over te laten. Jij geeft een overtuigend antwoord op de vraag waarom we Hannah Arendt juist nu moeten lezen. Ik heb jouw boek ook dit keer meegenomen op een lange reis en kan mij nauwelijks een betere reisgenoot voorstellen.
 

Dank je wel.


Grote groet, -Harrie Jonkman


Bernstein, R.J. (2018). *Why read Hannah Arendt Now?* New York: Polity Press 120 pagina’s. € 43,63.



