
# DE MEER DONKERE KANT


Amsterdam, mei 2019


Beste Justin Smith,


In het één na laatste hoofdstuk van jouw nieuwe boek ‘Irrationality: A History of the Dark Side of Reason’ schrijf jij over de dood. Het besef dat wij allemaal op termijn doodgaan, schuiven wij graag door, het liefst tot het einde. We doen liever of we het eeuwige leven hebben, terwijl we eigenlijk heel goed weten dat het anders in elkaar zit. Dit alleen al geeft volgens jou aan dat irrationaliteit tot de kern van ons bestaan behoort. We denken heel graag anders. Zeker tegenwoordig, nu we zo druk bezig zijn met ons persoonlijk welzijn en onze individuele gezondheid en de schaduw van de dood verre van ons houden. Sinds de Grieken en vooral de Verlichting zijn rationaliteit en de rede steunende begrippen voor onze cultuur. Er zijn volgens jou echter altijd weer filosofen die ons op de andere kant van ons mens-zijn wijzen. Socrates en Montaigne waren zich daar bijvoorbeeld veel beter van bewust dan die hele filosofie van tegenwoordig die maar geen oog heeft voor eindigheid van ons bestaan en maar doet of we het steeds beter krijgen. De horizon van de dood kleurt volgens jou onze ervaring en heeft invloed op wat wij besluiten; we willen het gewoon niet zien. Socrates zelf bereidde zich voor op de dood maar dat besef weerhield hem er niet van om anderen kritisch te laten nadenken en keuzes te laten maken die bij hen passen. Wat deze irrationele kant betreft denk jij ook vaak aan jouw vader die tot op hoge leeftijd rookte. Hij wist dat dat slecht voor hem was maar hij wilde zich gewoon liever dertig voelen dan stoppen en beseffen dat hij de tachtig had gepasseerd. Mensen maken nu één keer irrationele keuzes in het volle besef dat het niet goed voor ze is. Jij bent hoogleraar Geschiedenis en Wetenschapsfilosofie aan de Universiteit van Parijs, kenner van de 17e eeuw en het werk van Leibniz. Jij hebt onlangs een bijzonder uitdagend boek geschreven. Tussen wat we doen en weten ligt er een heel groot grijs gebied waar we geen grip op krijgen. Alleen daarom is het volgens jou goed om het onderwerp rationaliteit eens helemaal van de andere kant aan te vliegen om te kijken of dat middengebied zo beter is in te kleuren. Nu eens niet over rationaliteit en rede, nu eens wel over irrationaliteit en de donkere kant ervan.   


Rationaliteit en rede houdt ons al heel lang bezig. De Grieken hadden het erover en in de Bijbel lezen we erover. Zeker in die ‘begin’-periode wordt er breed over gedacht en omvat rationaliteit de hele natuurlijke orde. Het perspectief verengd zich wanneer filosofen zich verder druk gaan maken over de waarheid. Menselijke en dichterlijke aspecten verdwijnen en logische argumenten blijven over. Men schoolt zich in specifieke vaardigheden en zoekt een mathematische taal om zich uit te drukken. Natuurlijk zijn er filosofen die aantonen dat deze taal leeg is, anderen die gaan mystificeren of juist vreemde gedachten hiertegen inbrengen. De Tempel van Rede probeert zich op verschillende manieren te beschermen maar slaagt er maar niet om irrationeel denken uit te sluiten. Dat krampachtige is ook op een ander terrein te zien. Wordt er lang nog vanuit een geheel gedacht, tegenwoordig mogen we graag geloven dat de kosmos één bron van irrationaliteit en chaos is met daar binnen de mens als enig rationeel wezen. Zijn wij wel de enige rationele wezens? Dieren handelen meer en daarin hebben ze altijd gelijk. Is het niet eerder zo dat wij juist die irrationale wezens zijn, vraag jij je af. Dromen en kunst hebben ook zo’n irrationale naam. Dromen heeft dat sinds Descartes en sinds die tijd is het wakkere leven het enige leven dat telt. De beroemde psychiater uit Wenen brengt dit onderdrukte aspect weer tot leven. Maar waarom hebben we hier toch zo’n moeite mee? Allicht omdat deze nachtelijke ervaringen de geordende wereld, zoals wij die zo graag zien, ondermijnen. Van metafysica willen we weinig weten en mysteries houden we het liefste voor onszelf. Wakkere dromen als passies, emoties en verbeelding hebben ook dat irrationele. Maar niets is zo menselijk, schrijf jij, als verliefd of boos worden, plezier hebben of zelfbeheersing verliezen en dat komt terug in muziek, literatuur, visuele en andere kunstvormen. Verbeelding heeft voor jou zelf wel degelijk met rede te maken maar wetenschap en kunst zijn uit elkaar gegroeid en staan tegenwoordig niet zelden op gespannen voet met elkaar. De toekomst voorspellen aan de hand van de sterrenstand (astrologie), theeblaadjes (tasseografie) of dobbelstenen (astragalomantie) is voor ons nu kwakzalverij. We kennen daarentegen nog wel  horoscopen, persoonlijkheidstesten en on-line keuzetesten. Met pseudowetenschap weten we ook moeilijk om te gaan en we weten niet goed wat we met alternatieve feiten aan moeten. Het is volgens jou niet toevallig dat nadat de Verlichting de wereld op zijn kop had gezet er een tegenbeweging komt. Die verzet zich tegen het universele, het seculiere en de rede, wil al dat wat de Verlichting had opgeleverd elimineren of onderdrukken en benadrukt het belang van het nationale, het geloof, de gevoelens en de passie. Zo krijgt de irrationaliteit via mythologie weer een maatschappelijke en culturele plek. Het internet, dat irrationele beest of Shiva-de Vernietiger zoals jij het ook wel noemt, laat helemaal duidelijk zien dat irrationaliteit deel uit maakt van ons leven. Het internet was veelbelovend toen het opkwam omdat we dachten dat het universele en voortdurende communicatie tussen iedereen mogelijk zou maken. De donkere kant wordt zichtbaar wanneer Russische trollen zich met verkiezingen in het buitenland gaan bemoeien en de communicatieve toon harder en onaangenamer wordt. Het internet heeft de media (televisie, kranten, tijdschriften en boeken)en de instituten (winkels, universiteiten, theaters, democratie) vernietigd (kun je niet beter zeggen op z’n kop gezet?) en zaagt aan de poten van onze liberale democratie. Dat komt omdat wij in wezen irrationeel zijn en onszelf alleen niet zo willen zien. Het is duidelijk dat we leven in tijden van extremen, zeker in de politiek en de sociale media. Voor mensen die daar tussenin leven is het moeilijk maar juist die groep moet niet ophouden met hun mening te geven, te tweeten en hierover boeken te schrijven. Dan zijn er nog de grappen en de leugens waar het internet mee volstaat en die ook het grensgebied opzoeken. Waar houdt vrijheid van meningsuiting op en waar begint immoraliteit. Over de dood, tenslotte, had ik het al.

 
De geschiedenis zit vol met voorbeelden van mensen die worden vervolgd of vermoord omdat ze op iets anders wijzen. Rationaliteit en brutaliteit zijn de twee polen van de menselijke geschiedenis. Jij begint jouw boek met de moord op Hippasus, de Griekse wiskundige uit de kring van Pythagoras, die zijn mond voorbij praat en vertelt dat niet alles met natuurlijke getallen is op te lossen. Dat is niet iets dat men wilde horen en dat moest hij met de dood bekopen. Dan is er ook nog de Russische schrijver Isaac Babel die in zijn boeken laat zien wat er wel niet allemaal onder de gladde oppervlakte leeft van de families en gemeenschappen in de buurt van Odessa. Dat beeld voldoet niet aan het ideaal van Stalin en Babel wordt vermoord omdat de communisten bang zijn om hun controle te verliezen. Irrationeel handelen manifesteert zich in dromen, emotie, passie en verlangen, al of niet in combinatie met drugs, alcohol of meditatie. Op sociaal niveau toont het zich in religie, mystiek, samenzwering, sport, opstand en retoriek. Irrationaliteit maakt een groot deel uit van ons leven en onze geschiedenis. Jouw boek laat zien hoe het verweven is met filosofie, politiek en dagelijkse gebeurtenissen. Voor jou is het heel duidelijk dat hoe meer we ons druk maken om rationaliteit en de rede, hoe meer irrationaliteit en onredelijkheid het oproept. De twintigste eeuw heeft duidelijk gemaakt waar dit toe leidt en ook nu leven we in een extreme tijd van irrationaliteit, instabiliteit en angst. Het populisme wordt in verschillende landen sterker, de positie van wetenschap en experts wordt ondermijnd, alternatieve feiten worden belangrijker, mondiale klimaatverandering wordt ontkend en de vaccinatiegraad van de jonge bevolking loopt terug. We switchen van rationaliteit naar irrationaliteit en weer terug en dat blijft zo als we niet open staan voor dat grote grijze middenveld er tussenin. Irrationaliteit vormt ons leven en geeft ons sociaal bestaan waarde. Het is goed dat jij mij hier zo duidelijk op wijst. Ook al heb je voor mij wel heel veel omhalen nodig, je hebt een punt. Tegelijkertijd zie ik ook dat je eenzijdig naar rationaliteit en rede kijkt en weinig aandacht besteed aan mensen die juist het sociale en morele aspect van rationaliteit benadrukken zoals Weber, Arendt, Habermas en Sen. Bij hen voel ik mij zeer thuis waar het rationaliteit en de rede betreft. Ik heb ook het idee dat jij het betreurt dat wetenschap en kunst bijvoorbeeld uit elkaar zijn gegroeid. Misschien is de wereld wel te complex geworden om alles vanuit één perspectief te zien en is zo’n samenhangend Goethe-perspectief wel achterhaald. Als we elkaar, denk ik zeker na het lezen van jouw boek, maar inspireren en niet in onze eigen wereld opgesloten blijven. Het irrationele is onuitroeibaar, dat heb je mij wel duidelijk gemaakt. Dat hoeft ons niet te weerhouden over rationaliteit en wat ons leven zou kunnen verbeteren te blijven nadenken. Als we maar oog houden voor elkaar en de wereld en het om gedeelde menselijkheid gaat; het ideaal in het achterhoofd, vanuit de situatie waarin we zitten en met het diepe besef dat er altijd nog veel meer is.


Dank je wel.


Grote groet, -Harrie Jonkman


Smith, J.E.H (2019). *Irrationality: A History of the Dark Side of Reason*. Princeton and Oxford: Princeton University Press 330 pagina’s. $ 21,78.



