
# DE AARDE DIE ONS MAAKTE


Amsterdam, juli 2019



Beste Lewis Dartnell,



Afgelopen week was ik het ruim van mijn woonark aan het opruimen. In de hoeveelheid spullen kwam ik een geschiedenisboek van mijn middelbare school tegen: Fasen en facetten. Geschiedenis voor het eindexamen. Ik was al snel afgeleid. Dat geschiedenisboek begint bij de Grieken en het ontstaan van de democratie en loopt dan chronologisch de tijd door naar de twintigste eeuw waar het gaat over de nieuwe tijd en Oost-Azië. Geschiedenis-boeken uit die tijd beginnen betrekkelijk recent en slaan met gemak miljarden jaren over. Tegen geschiedenis kijk jij heel anders aan en jij houdt er een brede blik op na. Jij bent astrobioloog en het gaat jou om de oorsprong, de evolutie, de ontwikkeling en de toekomst van het leven. Astrobiologie is een, voor mij althans, wat vreemde interdisciplinaire studie waarin biologie, geologie, sterrenkunde, astronomie, scheikunde en andere wetenschappen met elkaar worden gecombineerd. Op jouw vakgebied zijn er grote ontwikkelingen geweest en over het leven op aarde weten we, volgens jou, onderhand veel meer. In jouw nieuwe boek Origins. How the earth made doe je daar uitgebreid verslag van. Na het lezen van jouw bijzonder interessante boek weet ik zelf heel veel meer hierover. Wat jij ons in jouw nieuwe boek laat zien is dat wij eigenlijk kind zijn van de aarde en dat die aarde ons gemaakt heeft tot wie wij zijn. Jij bent duidelijk: om onszelf te begrijpen, moeten we de geschiedenis van onze planeet kennen met z’n landschappen, zeeën, atmosferen, klimaatwisselingen en tektonische platen. Jouw boek was voor mij de afgelopen week één groot avontuur met hele andere fasen en facetten dan die ik tot op heden kende. 

 

Ooit waren we apen die over de takken van dichte bossen rondzwierden. Ook in Oost-Afrika (Riftvallei), een interessant gebied met meren en waterbekkens die zich daar toen vanwege geologische redenen hadden gevormd. Wanneer ook dat gebied afkoelt en de bomen zich tot kale grasgrond omvormen, moeten we wel uit de bomen komen om aan voedsel te komen. Om grotere afstanden over de grond af te leggen gaan we onze benen gebruiken en veranderen we. Vanuit aapsoorten ontstaan in die tijd verschillende menssoorten (waaronder Homosapiens, Neanderthalers en de Denisovans) waarvan uiteindelijk alleen de Homosapiens overblijft. In oorsprong zijn alle mensen met elkaar verbonden en zo kan het zijn dat mensen die op grote afstand van elkaar leven meer met elkaar overeenkomen dan aapsoorten aan weerzijde van een Afrikaanse rivier. Om met veranderende omstandigheden om te kunnen gaan, ontwikkelt de Homosapiens een bepaalde intelligentie om zich gemakkelijker te kunnen aanpassen. Taal hebben we nodig, we leren omgaan met gereedschappen en met elkaar en samenwerken moeten we ook zo begrijpen. De Homosapiens gaat 60.000 jaar geleden ook nog eens op pad wanneer de aarde voor de zoveelste keer afkoelt. Bepaalde werelddelen, die nu gescheiden zijn, zitten dan nog aan elkaar vast. Ook ijsmassa’s stellen ons in staat om verre delen van de aarde te bereiken. Wanneer de aarde weer opwarmt, worden delen uit elkaar getrokken, mensen uit elkaar gedreven en volgen civilisaties elk hun eigen ontwikkelingspad. Bossen ontstaan weer wanneer de regen toeneemt en de ondoordringbaarheid daarvan maakt het reizen moeilijker. 11.000-5.000 jaar geleden ontstaan eerste dorpen op zeker zeven verschillende plekken op de aarde, waar mensen hun eigen groenten (waaronder erwten, bonen en kool) en fruit kweken en er sprake is van de eerste landbouw. Ook leren we met dieren omgaan, vanwege melk, vlees en spierkracht. Drie kwart van de aarde bestaat uit water en toch noemen we het vreemde genoeg, jij merkt het nog eens op, aarde. Dat water is voor het leven op aarde heel belangrijk. Allereerst natuurlijk vanwege het voedsel, maar ook om dat voedsel en onszelf te verplaatsen. Met het water leren we beter omgaan en we leren zelfs (in mijn eigen land vooral) dat in aarde om te zetten. Het water is voor de ontwikkeling van culturen en het ruilen van goederen heel belangrijk, zoals bijvoorbeeld de Middellandse Zee, de Rode zee en de Nijl. We bouwen in die lange geschiedenis niet alleen in maar ook met onze eigen omgeving en gebruiken daarvoor het hout, de klei en verschillende soorten stenen die we in de nabijheid vinden. Dat doen duizenden werkers van de farao’s natuurlijk al 4.500 duizend jaar geleden met die grote stenen die ze in de buurt van de Nijl en de wijdere omtrek vinden en die ze op slimme wijze tot enorme bouwwerken ombouwen. Zo komt bijvoorbeeld die grote piramide van Cheops tot stand die tot de bouw van de grote kathedraal van Köln (1880) het grootste bouwwerk van de wereld zal blijven. Vanaf het Bronzen Tijdperk leren we ook om met andere materialen om te gaan. Koper en tin leren we om te smelten en zink, lood, zilver en goud weten we te bewerken. 1300 jaar voor Christus wordt in Anatolië (Turkije) ijzer voor het eerst bewerkt. In het gebied van Europa en Azië is er, anders dan in Amerika en Australië, een sterke uitwisseling van goederen en ideeën en de lange Zijderoute van Middellandse zee naar de Stille Oceaan maakt dit mogelijk. In datzelfde EurAzië-gebied, laat jij zien, ontstaan er eigenlijk twee soorten volkeren, elk gekoppeld aan de eigen omgeving. Aan de ene kant het volk dat veel meer op hun plaats blijft zitten en hun eigen grond bewerkt. Aan de andere kant het steppenvolk dat vanwege hun omgeving (grasland, hoge temperatuursverschillen en dergelijk) genoodzaakt is een nomadisch bestaan te leiden. Die twee soorten volkeren gaan regelmatig met elkaar op de vuist; of dat nu de Hunnen zijn ten opzichte van het Romeinse Rijk of de Mogols met het landbouwvolk in India en China. Vanaf de 15e eeuw leren we de wereld verder ontdekken wanneer de Portugezen de zee verder op gaan varen. Eerst nog voorzichtig in de buurt van de kust, met de Kanarische eilanden, de Azoren en Kaap Verdië als veilige tussenstations om water en voedsel te laden. Schippers maken gebruik van wind en stroming en houden nauwlettend de poolster in de gaten. Dan kiezen we het ruime sop en aan het einde van die eeuw vindt Diaz in het zuiden van Afrika een doorgang naar het oosten, Columbus zet voet in Zuid-Amerika en denkt een andere doorgang naar het oosten gevonden te hebben en Vasco da Gama reist via Kaap de Goede Hoop naar India. Steeds beter leren we met de wind, de stroming en verschillende atmosferen op aarde om te gaan en op zoek naar kruiden, zilver en goed komen koloniale machten tegenover elkaar te staan en slaven ingezet. 10.000 jaar lang zijn we een agrarische samenleving en leven van groente en fruit uit onze eigen omgeving, gebruiken onze eigen kracht of zetten dieren daarvoor in en leven in kleren van linnen, zijde, wol en leer. Met waterwiel en windmolen gaan we al wat anders met energie om en dat verandert zeker wanneer we kolen gaan gebruiken. Dat doen we vooral sinds de Industriële revolutie in de 18e en 19e eeuw, wanneer kolen, ijzer en de stoommachine en kolen een sterke drie-eenheid vormen. Olie, omgevormde massa uit dode organismen, wordt aan het einde van de negentiende eeuw en vooral in de twintigste de belangrijkste energiebron op aarde. Dat is het nog steeds. Een kleine hoeveelheid olie kan in veel energie omgezet worden. In de Perzische Golf, maar ook in het westen van Siberië, de Golf van Mexico, de Noordzee en Venezuela worden grote olievelden gevonden. Bij die olie en de nadelen ervan (voor het eerste beïnvloeden we zelf ook de ontwikkeling van de aarde en voor het eerst ons eigen bestaan) houdt jouw grote en lange geschiedenis op.



Die grote en lange geschiedenis van oorsprong, evolutie en ontwikkeling is populair tegenwoordig. Guns, Germs, and Steel van Jared Diamond en Sapiens van Yuval Noah Harrari kun je op het vliegveld kopen. Die boeken geven antwoorden op vragen die iedereen interessant vindt, zoals waarom zijn wij uit de bomen geklommen, op twee benen gaan lopen en waarom nam intelligentie toe. Of, waarom ontwikkelden mensen zich in bepaalde delen van de wereld verder en waarom stagneerde dat civilisatieproces in andere delen?. Jouw boek geeft op heel veel van dit soort fundamentele, evolutionaire vraagstukken een boeiend antwoord en jij rijgt die geschiedenis op een logische wijze aan elkaar. Er zijn momenten dat je als lezer moeite hebt met de jaartallen, misschien wel vooral omdat hij/zij, in ieder geval ik, een hele andere tijdslijn in het hoofd heeft zitten. Veel van wat jij vertelt is voor mij nieuw. Eerlijk gezegd heb ik bijvoorbeeld altijd gedacht dat er maar één ijstijd was; de IJstijd stond er ook bovenaan de plaat die vroeger in het klaslokaal hing. Ik wist helemaal niet dat er wel zo’n 40-50 van dat soort ijstijden zijn geweest, die elk weer door een periode van opwarming werden afgewisseld. Jouw boek eindigt met een hoofdstuk over energie en over recente ontwikkelingen als digitalisering en automatisering schrijf jij niet (ook al weet ik niet hoe zich dat met de aarde zelf verhoudt). Enige aandacht daarvoor en hoe die ontwikkelingen ons weer vormen, zou op z’n plaats zijn geweest. In jouw boek gaat het om de vraag waarom de wereld zo is zoals die is en vooral waarom wij zijn zoals wij zijn. Om ons eigen verhaal te kennen, moeten we dat verhaal van de aarde kennen. Daarover schrijf jij overtuigend. Voor het begrijpen van de evolutie is het goed om de geschiedenis van miljarden jaren te kennen. De geschiedenis van miljoenen jaren is nodig om het ontstaan van de mens te snappen. Met de geschiedenis van honderdduizenden jaren begrijpen we de ontwikkeling van onze intelligentie en capaciteiten beter. In de geschiedenis van tienduizenden jaren zien we civilisatieprocessen. De geschiedenis van duizend jaar is nodig om de globalisering en industrialisatie te snappen. De laatste honderd jaren zijn nodig om het verhaal zelf goed te begrijpen, schrijf jij in de inleiding. De komende 100 jaar, denk ik dan weer, hebben we deze kennis nodig voor onze toekomst. Voor welke toekomst we ook kiezen, het is de aarde die ons zal blijven maken.



Dank je wel.



Grote groet, -Harrie Jonkman



Dartnell, L. (2019). **Origins. How the earth made us**. London: The Bodley Head 352 pagina’s. 25,99 euro.



