
# HUWELIJKSE WAARDEN



Amsterdam, augustus 2019



Beste Sophia Rosenfeld,



Jij bent hoogleraar Geschiedenis aan de Universiteit van Pennsylvania en gespecialiseerd in de revolutionaire achttiende eeuw. Een paar jaar geleden schreef jij een boek over het belang van het gezonde verstand in de politiek (**Common Sense: a Political History**, 2012); dat gezonde verstand dat ontstaat uit de sociale interacties en de ervaringen van mensen en zo van belang voor democratie. In dat boek laat je zien hoe de Engelsen, de Schotten, de Nederlanders en de Amerikanen met gezond verstand zijn omgegaan en hoe dat via Duitsland en Rusland naar het heden doorloopt en ook hoe filosofen, als Kant, Gadamer en Arendt, daar tegenaan keken. Zoals zovelen ben jij in 2015 en 2016 door de ontwikkelingen in jouw eigen land verrast; verbijsterd meer over het ‘fake news’, de samenzweringstheorieën en de leugens die vanaf die tijd dagelijks op jouw iphone verschijnen en waardoor de publieke sfeer in korte tijd zo verandert. Het duurt even voor het tot jou doordringt dat jij met jouw kennis in een positie zit om die verandering te duiden en kleur te geven. Jij bent je ervan bewust dat wat in Amerika gebeurt, op verschillende plaatsen in de wereld gebeurt en weet dat democratie en waarheid al veel langer op gespannen voet met elkaar staan. In de zestiger en zeventiger jaren is er bijvoorbeeld al sprake van leugens en misleiding rondom de Pentagon Papers, dan is er Nixon met z’n Watergate schandaal, Clinton met z’n seksschandaal en Bush rommelt met z’n vrienden Irak binnen. Jij schuift jouw iphone wat aan de kant om opnieuw die hele periode van de achttiende eeuw tot heden te onderzoeken en te ontdekken hoe politiek en filosofie met democratie en waarheid zijn omgegaan. Het resultaat: een kleine, maar zeer compacte geschiedenis over deze twee waarden en de gespannen verhouding ertussen in de laatste honderdvijftig jaar aan weerzijden van de Atlantische Oceaan. Het is de geschiedenis van een fragiel en moeizaam huwelijk van twee waarden die niet zonder elkaar kunnen maar het regelmatig met elkaar aan de stok hebben. De laatste jaren zijn enkele nieuwe elementen mee gaan spelen die een crisis in dat huwelijk teweeg hebben gebracht. Jij schetst de geschiedenis van die twee waarden samen, waarom die relatie zo belangrijk is en wat we kunnen doen om die relatie uit het slop te halen.



De laatste jaren wordt er keer op keer over geschreven dat we de grip op een gedeelde werkelijkheid aan het kwijt raken zijn en dat zo een gezamenlijke toekomst opbouwen wel heel erg moeilijk wordt. Leugens en omdraaiingen van de werkelijkheid lijken met Trump als president dagelijkse kost te zijn. Duizenden leugens en het ene na het andere schandaal beheersen het nieuws en de president lijkt er steeds mee weg te komen. Tegelijkertijd lijkt hij de autoriteit van gerenommeerde instituten te ondermijnen en zet hij vraagtekens bij institutionele expertise, of het nu over klimaatbeheersing, buitenlandse politiek of economie gaat. Deze Amerikaanse president staat hierin niet alleen want grote delen van de bevolking steunen hem. Waarheid is de laatste jaren persoonlijk geworden en een zaak van individueel gevoel. Niet alleen in Amerika. Orban doet hetzelfde in Hongarije, Aung San Suu Kyi, niet zo lang geleden nog Nobelprijswinnaar van de Vrede, in Myanmar en heel veel andere voorbeelden zijn er te geven. Afgelopen jaren heb jij deze ontwikkelingen in een historisch perspectief geplaatst. Tot voor kort zijn validatie en standaards waarmee waarheid kan worden getoetst belangrijk en wordt waarheid als resultaat van communicatie met anderen gezien. Er is uiteindelijk dat vertrouwen in anderen, transparantie en openheid zoals we dat sinds de achttiende eeuw kennen, om de eenvoudige reden dat jezelf niet alles kunt overzien en democratie niet zonder kan. Uitgangspunt is steeds dat de meeste mensen de meeste tijd de waarheid spreken, dat waarheid iets anders is dan onwaarheid, dat we verschil kunnen maken tussen waarheid en onwaarheid en dat dat verschil er toe doet. Het probleem waar we de laatste jaren mee te maken hebben gekregen is, volgens jou, niet zozeer een moreelprobleem maar meer een kennisprobleem: we weten niet meer goed waar waarheid op is gebaseerd en hoe daarmee om te gaan. Natuurlijk, jij weet ook dat mensen in andere tijden en op andere plaatsen anders tegen waarheid aankijken en dat waarheid altijd met macht te maken heeft. Maar democratie moet zich op een bepaalde manier wel tot waarheid durven te verhouden en kan niet zonder. 
Op zoek naar die verhouding wordt er sinds de achttiende eeuw naar een balans gezocht tussen experts aan de ene en een actieve bevolking aan de andere kant. Een goed functionerende democratie heeft experts nodig die geschoold, bevoegd en betrouwbaar zijn. Met de Verlichting werden mensen in Europa en de Nieuwe Wereld opgeroepen zelf na te gaan denken en niet alles voor zoete koek aan te nemen. Moderne koningen krijgen door dat het niet zonder geschoolde mensen als bibliothecarissen, archivarissen, kaartenmakers en doctoren gaat. In die tijd ontstaat ook een intellectuele klasse van wijze en betrouwbare journalisten, schrijvers en andere kritische geleerden. Met deze goed getrainde elitaire sector wordt de politiek meer rationeel. In de negentiende en twintigste eeuw bereidt deze intellectuele sector zich verder uit, ontstaan er grote statistische, economische en sociaal culturele instituten en ontstaat er een klasse die zich gaat onderscheiden. In de tijd van het toenemend liberalisme waar we de laatste decennia mee te maken hebben, krijgt dit alles ook een technocratisch en meer bureaucratisch karakter, gaan experts steeds meer enkel met elkaar zelf spreken en komt het los te staan van de democratische samenleving en gelijkheid, pluralisme en gedeeld beslissingen nemen waarop die samenleving is gebaseerd.  
Net zo goed als experts heeft democratie actieve burgers nodig om gezond te blijven. Hieronder valt in eerste instantie lang niet iedereen. Kant heeft bij deze groep de lezers van een goede krant voor ogen en Voltaire had al helemaal weinig vertrouwen in een groot deel van de mensen. Mede onder invloed van het protestantisme wordt ruimer tegen actieve burgers aangekeken, slavernij afgeschaft en krijgen steeds grotere groepen mensen kiesrecht, ook vrouwen. Met de oprekking van het begrip actieve burgers ontstaat ook een inverse tegenbeweging die opkomt voor mensen die zijn buitengesloten en die de waarheid beter zouden zien omdat ze dichter bij die waarheid zitten. Populisme komt op voor de ‘echte’ mensen en ingewikkelde zaken als mensenrechten, burgerschap en nationale soevereiniteit staan veel te ver van deze gewone mensen af, die veel meer op hebben met praktische wijsheid. Van dat populisme geef jij veel voorbeelden, van Perón in Argentinië, naar Wallace in Amerika en jij noemt boer Koekoek en Wilders in mijn eigen land niet maar daar moet ik natuurlijk zelf aan denken. Het populisme keert zich tegen de expertise in de politiek of het nu over Chirac of LePen in Frankrijk gaat of Gove in Engeland, ‘de mensen hebben genoeg van de experts’. Of gewone mensen hierbij gebaat zijn, kun je je natuurlijk afvragen en het perspectief wordt wel heel klein als we geen rekenschap meer geven van geschoolde kennis, dat is voor jou wel duidelijk. 
Democratie leeft van de subtiele combinatie van specifieke en publieke kennis en daarvoor is een gecultiveerde bevolking nodig, net zoals wetten en mediërende instituten die ervoor zorgen dat mensen op een fatsoenlijke manier met elkaar praten. Die communicatie nu tussen de experts en populatie is behoorlijk scheef gaan lopen en deze werelden zijn gevaarlijk uit elkaar gaan lopen. 



Wat gebeurde er na 1990 toen dat huwelijk tussen democratie en waarheid nog zo stralend leek? Met het postmodernisme in de wetenschap en kunst zijn we sceptischer en relativistisch tegen de werkelijkheid aan gaan kijken, lijkt berusting de plaats van hoop te hebben ingenomen en is politiek vooral identiteits-politiek geworden. We hebben te maken gekregen met infotainment en massamedia met eindeloze uitzendingen en praatprogramma’s waarin perspectieven minder naast en meer tegenover elkaar worden geplaatst. En dan is er ook nog de technologische doorbraak, internet en de macht van sociale media waarmee onze communicatieve omgangsvormen behoorlijk veranderden en het gat tussen experts en bevolking eerder werd vergroot dan verkleind. Disinformatie wordt in de informatieoorlog ook nog eens bewust van buiten ingebracht. Hoe is in deze overvloed van informatie waarheid nog van onwaarheid te scheiden, alle vormen van expertise lijken er toe te doen en om het een beetje overzichtelijk te houden lijken we alleen nog in onszelf te geloven. In dit klimaat gedijt opportunisme goed. Halverwege het laatste hoofdstuk van jouw boek, wanneer ik als lezer al behoorlijk radeloos ben geworden, vraag jij jezelf af wat kunnen we doen, als we al wat kunnen doen. Teveel doen is voor jou geen optie, maar niets doen ook niet. Het is voor jou in ieder geval duidelijk dat journalisten en al die mensen die zich met communicatie bezig houden voor zorgvuldig geverifieerde informatie hebben te zorgen. Droog en daadkrachtig, als het moet. Allicht is het ondertussen ook goed om meer oog te krijgen voor de schade die vrijheid van meningsuiting voor de ander kan hebben. De verantwoordelijkheid voor waarheid ligt niet alleen in de handen van de kranten, omroepen, websites, podcast en andere vormen van moderne media. Er zijn instituten omheen die er ook voor zorgen dat we respect hebben voor verschillen en erkennen dat democratie nooit een eindpunt kent. Daarvoor is het heel erg nodig dat verkiezingen eerlijk blijven verlopen en dat alle stemmen tellen en geld niet teveel dat proces verstoort. Dan is er natuurlijk nog een onafhankelijke rechtspraak die er voor zorgt dat de rechten van mensen worden verdedigd. In dat verhaal van jou spelen scholen en universiteiten, publieke en private onderwijsinstellingen, een essentiële rol. Daar leren jonge mensen hoe aan legitieme en verifieerbare kennis te komen en na te denken over wat gebeurd is. Alle wetenschappen, zeker de menswetenschap en al helemaal jouw eigen domein geschiedenis, leren hen wat er voor hen is gebeurd en hoe ze kennis kunnen gebruiken om een toekomst op te bouwen. Niet heel uitgebreid, en allicht te mager, ga je wel in op gelijkheid. Bij jou gaat het om fatsoenlijke communicatie en dan kan het niet zo zijn dat de afstand tussen mensen en de sociaal economische verschillen alleen maar groter worden. En dat is precies wat er gebeurt nu. Het ideaal van democratie en waarheid heeft het gesprek tussen mensen nodig. Democratie kan overleven als het zowel van bovenaf als van onderop wordt gedragen en er een breed gedragen commitment is voor waarheid en we met elkaar verder willen komen. Jouw verhaal is een verhaal over de basis van democratie, wat er mis ging en wat we kunnen doen. Je laat niet zien waar het wel goed gaat en ik had graag wat goede en hedendaagse voorbeelden gezien van initiatieven die democratie en waarheid bij elkaar brengen. Jouw boodschap, dat democratie en waarheid niet iets is dat er is maar dat we met elkaar maken en waarmee we met elkaar naar de toekomst kunnen kijken, blijft met jouw verhaal hangen. Of, om het in mijn eigen woorden te zeggen: democratie en waarheid vraagt als elk gezond huwelijk onderhoud.



Dank je wel.



Grote groet, -Harrie Jonkman



Rosenfeld, S. (2019). **Democracy and truth. A short history**. Philadelphia/Pennsylvania: University of Pennsylvania Press 213 pagina’s. 22,99 euro.



