
# OVER DE NEUSHOORN



Amsterdam, september 2019



Beste Adam Gopnik,



Toen ik jouw nieuwe boek ‘A Thousand Small Sanities. The Moral Adventure of Liberalism’ uit had, keek ik nog eens rustig naar de korte bibliografische opmerkingen aan het einde van het boek. Meer dan twintig jaar schrijf jij over liberale (en niet-liberale) denkers, filosofen en politici. Het zijn artikelen, essays en hoofdstukken over Popper, Voltaire, J.S, Mill, Churchill, Smith, Burke, Glucksman, Montaigne, Hitler, Roth, De Gaulle en Douglas, om er enkelen te noemen. Jouw stukken plaats je in de New Yorker, waar jij al lang in dienst bent. Daarnaast schrijf je ook fictie, kritieken en essays over hele andere onderwerpen. Jij bent een veelschrijver. Met jouw laatste boek breng je jouw historische, filosofische en biografische kennis over het liberalisme samen en wil je laten zien wat die liberale waarden inhouden. In de late avond van 8 november 2016 loop jij met jouw dochter een blokje om, teleurgesteld over de uitslag van de Amerikaanse verkiezing. Jouw dochter is nog meer geschokt dan jijzelf over wat er is gebeurd. Jij wilt haar moed inspreken want op dit soort momenten moet je er als vader zijn. Je probeert haar te vertellen waar het in het liberalisme om draait en waar dat denken vandaan komt. De wandeling die avond is te kort voor het hele verhaal. In dit boek neem je daar wel uitgebreid de tijd voor. Jij presenteert geen abstracte ideeën maar roept beelden op en laat zien hoe liberalen op verschillende momenten in de geschiedenis en plaatsen in de wereld hebben gedacht en gehandeld. Zo het boek opbouwen spreekt veel meer aan dan principes uitleggen, moet je gedacht hebben. Ook in dit boek loop jij met jouw dochter in de hand rond, nu door de geschiedenis, spreek jij haar op bepaalde momenten rechtstreeks aan en lijkt het of die novemberavond van 2016 nog niet voorbij is.



De eerste liberalen die jij portretteert zijn John Stuart Mill en zijn geliefde Harriet Taylor. Jij plaatst hen op het bankje in de dierentuin van Londen. Mill en Taylor ontmoeten elkaar daar regelmatig in het geheim. Harriet is getrouwd en het is de eerste helft van de negentiende eeuw. Daar op dat bankje kunnen ze elkaar zien want de mensen hebben alleen maar aandacht voor de dieren. Mill kennen we natuurlijk van Over Vrijheid. Samen schrijven ze ook nog The Subjection of Women, een boek over de rechten van vrouwen in een tijd dat daar toch heel anders over wordt gedacht. Wanneer de man van Taylor overlijdt trouwen zij twee alsnog. Ook al wordt Mill beschouwd als de grote rationalist, zij laat hem zien dat liefde voor alles gaat. Even later in het boek beschrijf je de relatie van een ander legendarisch liberaal paar, nu in de tweede helft van de negentiende eeuw: George Henry Lewes en Marian Evans (bekend als de schrijver George Eliot). Lewes is een leerling van Mill en de grote liberale journalist van de negentiende eeuw. Zij, Evans (Eliot), is een van de drie bekendste schrijvers van haar tijd (samen met Trollope en Dickens). Anders dan Mill en Taylor, die veel meer over politiek en de principes van liberalisme schrijven, heeft dit liberale paar het over het private, het proces en het gedrag van mensen. Voor hen begint vrijheid in de slaapkamer en in het hoofd, zoals jij schrijft. Zij zijn zich ervan bewust dat verandering vaak al plaats heeft gevonden voordat de politiek er wat mee kan. Bayard Rustin is ook zo’n liberale hoofdpersoon van jouw boek. Hij is zwart en homo, socialist en liberaal, een nette man en iemand die Gandhi’s niet-gewelddadige principes aanhangt. In conservatief naoorlogs Amerika komt hij natuurlijk tientallen keren vast te zitten. Hij is zich ervan bewust dat de zwarte bevolking van Amerika een minderheid is en wil je wat veranderen, je samen moet werken met de blanke meerderheid. Rustin werkt direct samen met Maarten Luther King en deze King weet dat hij hem nodig heeft om in 1963 de mars naar Washington te lopen. King wordt bekend om zijn toespraak, het is Rustin die deze succesvolle mars organiseert en niemand anders. Rustin leert je om te gaan met tolerantie en verschillen tussen mensen. Al de liberale personen die jij beschrijft in jouw boek zetten waarden om in actie, doen dingen nooit alleen maar altijd in relatie tot anderen en bij al deze mensen gaat de praktijk aan de ideologie vooraf. Jou gaat het niet zozeer over deze individuen maar veel meer om de relaties die zij hebben en de waarden die ze daarin met anderen delen. In het boek sta je overigens stil bij veel meer liberale karakters en acties die daarbij horen, van Montaigne tot en met Putnam. Met die beschrijvingen wil je mij ook duidelijk maken dat liberalisme bovenal een temperament is, een toon als het ware en een manier om met de wereld om te gaan. Voor jou geldt steeds de menselijke maat en jij distantieert je van droge en emotieloze doctrine. Als je het persoonlijke hebt gepresenteerd, heb je ruimte om wat over dat liberalisme te zeggen. Jij vat liberalisme breed op en verbindt het met woorden als vrijheid en democratie, maar net zo goed met menselijkheid, verandering, tolerantie, pluralisme, zelf-realisatie en autonomie. Met gepaste veranderingen kan die wereld voor meer mensen iets te bieden hebben en mensen kunnen leren beter met verschillen om te gaan. Die aanpassingen lopen via communicatie, het experiment, het debat en de rede. In jouw liberale denken gaat het om relatie, compassie, sympathie en empathie, om argumenteren en het maken van keuzes en verschil. Dat liberalisme dat jou lief is, wordt vandaag de dag van verschillende kanten flink aangevallen. Vanaf rechts wordt het vooral aangevallen omdat het de nadruk legt op rede en dat je met debat verder kunt komen. Aan die rechter kant gaat het om autoriteit en de natuurlijke orde, vooral via familie, gemeenschap en het land. In een bepaald opzicht kunnen liberalen hier van leren. Charles de Gaulle is daarbij zo’n positief voorbeeld met zijn republikeins idee en hij begrijpt wat democratie, collectiviteit en gemeenschap in het naoorlogse Frankrijk betekenen. Vanaf de links wordt het liberalisme aangevallen vanwege het denken in verandering en ontwikkeling. Liberalisme denkt niet zozeer aan revolutie  en het hanteert een veel minder radicaal concept. Ook hier sta je geruime tijd stil bij een links hoofdpersoon, Emma Goldman, een anarchiste die wel degelijk tot jouw verbeelding spreekt; een hard-core anarchiste maar ook een humoristisch, fijngevoelig en relativerend persoon waar er in de kringen van anarchisten en communisten niet heel veel van te vinden zijn. Maar liberalen moeten ook van personen als Emma Goldman leren en open voor ze staan. Anders dan in mijn land vaak gedacht wordt, gaat het bij jouw liberalisme altijd om verbinding met anderen en een zelfgekozen omgeving. Daarbij staat het bij jou vast dat de wereld nooit perfect is en dat ook nooit zal worden.         
 


In 1945 verscheen Karl Poppers De open samenleving en haar vijanden. Voor de moderne samenleving bestaat geen blauwdruk en het enige wat we kunnen doen is stapsgewijs vooruitgaan, problemen oplossen en tekorten weghalen. Ook Isaiah Berlin keert zich in zijn Four Essays on Liberty tegen determinisme en de rechtlijnigheid van de geschiedenis en verdedigt het pluralisme. Een gezonde samenleving kan hij zich niet anders voorstellen dan met conflicten over waarden en iedere keer weer afwegingen maken en op basis daarvan beslissingen nemen. Het derde naoorlogs standaardboek over liberalisme is Een theorie van Rechtvaardigheid van John Rawls, over hoe met al die verschillen die er tussen mensen bestaan toch een rechtvaardige samenleving is op te bouwen. Dat kan alleen als mensen zich in de positie van een ander kunnen blijven verplaatsen. Wanneer dertig jaar geleden de Berlijnse muur valt, ontstaat er in korte tijd een grenzeloos optimisme over dat liberalisme. In combinatie met democratie en kapitalisme, heeft het als politieke idee gewonnen en het einde van de geschiedenis wordt ingeluid. Hoe anders blijkt het niet heel veel later te zijn wanneer er nationalistische, populistische en autoritaire geluiden in het westen en daarbuiten te horen zijn. De geschiedenis is helemaal niet geëindigd, het optimisme verdampt en het liberalisme lijkt in de hoek gedreven. Met alle politieke verwarring van de laatste jaren wordt er wel weer veel geschreven over liberalisme. Daar is het de tijd ook naar en daar ben jij je als bezorgde burger en vader van bewust. Met alles wat jij over liberalisme geschreven hebt, had jij ook de behoefte daar een levend verhaal van te maken. Jouw boek is een intelligent en zeer goed geschreven boek.
In het laatste deel ervan schrijf jij dat het jou nodig lijkt dat het liberalisme de komende tijd meer passie gaat tonen, patriotischer wordt en zich meer gaat richten op de publieke zaak in plaats van de markt. Jij hebt in jouw boek weinig over de grote maatschappelijke problemen waar wij tegenwoordig voor staan. Over het klimaat, bijvoorbeeld, heb jij het niet en je kunt je afvragen of de kleine lichtpuntjes en handelingen waar jij het over hebt, hier wel voldoende zijn. Maar goed, jou staat een liberalisme voor ogen dat minder materialistisch is en meer gericht op een rijker leven en dat spreekt mij zeer aan. Want het is simpel voor jou: vrijheid is er niet om rijker en machtiger te worden maar om beter te begrijpen wat het is om te leven. Net als Popper, Berlin en Rawls zie jij niets in een groot ideaal. Het gaat om vallen en opstaan, problemen zien en problemen oplossen. Iedere keer opnieuw. Het is niet voor niets dat jij Mill en Taylor aan het begin van jouw boek op het bankje voor de neushoorn positioneert. De neushoorn staat voor het imperfecte, het lelijke en uiteindelijk spreekt dat toch tot de verbeelding. Heel anders dan de mythische eenhoorn die sinds de Oudheid wordt beschreven maar die niemand ooit heeft gezien en ooit zal zien. Ik ben het met jou eens dat we het met de neushoorn moeten doen en we al moeite genoeg hebben om dit beest te laten voortbestaan.



Dank je wel.



Grote groet, -Harrie Jonkman



Gopnik, A. (2019). **A Thousand Small Sanities. The Moral Adventure of Liberalism**. London: Basic Books 256 pagina’s. 16,99 euro.






