
# POWER GIRL



Amsterdam, november 2019



Beste Samantha Power,



Het is de Amerikaanse filosofe Susan Neiman die ons er regelmatig op wijst dat we ons niet hoeven te schamen voor idealisme en optimisme. Integendeel. Volgens haar is het goed om het pessimisme en de relativering meer van ons af te gooien en op zoek te gaan naar, wat zij noemt, volwassen vormen van idealisme. Daar is volgens haar sprake van als we niet alleen denken over hoe de wereld zou moeten zijn maar ook denken over hoe de wereld is. Een volwassen vorm van idealisme richt zich op allebei en zoekt naar een goede balans daartussen. Die gedachte heeft mij altijd zeer aangesproken en daarom was ik ook zo benieuwd naar jouw nieuwe boek ‘Leerschool van een idealist’, jouw memoires die onlangs uitkwamen. Ik ken jou als journalist van stukken over de oorlog in Joegoslavië en vooral van jouw boek *A problem from Hell (2002)* waarin je het kwaad van de twintigste eeuw beschrijft. In dat boek plaats jij de grote volkerenmoorden van de gewelddadige vorige eeuw in een breder kader en laat je vooral zien dat jouw land en het hele vrije westen steeds weer een oog dicht doet wanneer het grote kwaad de kop opsteekt. Dat is het geval bij de moord op de Armeniërs in oost Turkije, de Joden in Europa en later in Cambodja, Irak, Joegoslavië en Rwanda. Voor jou brengt vrijheid verantwoordelijkheid met zich mee. Na die periode als mensenrechtenactivist en journalist waarin je schreef over hoe de wereld zou moeten zijn, ga je de politiek in en werk je voor de Amerikaanse overheid. Meer dan tien jaar lang zit jij in het hart van de Amerikaanse en internationale politiek en van buitenstaander word jij deelnemer. Hoe verhoudt dat beeld van de toekomst zich met het realisme van nu en alledag en wat blijft er van hoop over als je hoog in de politieke ladder geklommen bent?



Jij wordt in 1970 geboren en groeit de eerste jaren in Ierland op. Jouw moeder is biochemicus en studeert later medicijnen en jouw vader is tandarts. Guinness is de lievelingsdrank van jouw vader, de pub zijn heiligdom en jouw tweede huis. Jouw ouders scheiden en in 1979 emigreer je met jouw moeder en broer naar Amerika. Eerst naar Pittsburg, later naar Atlanta. Jouw vader sterft op jonge leeftijd en over zijn dood voel jij je lang schuldig. Je past je snel aan in Amerika en gaat geschiedenis studeren op de Yale-universiteit. De opstand in China en vooral die moedige ‘Tankman’ in wit overhemd voor de tanks (1989) maken grote indruk op jou. Dat is misschien wel het eerste moment waarop de belangstelling voor de wereld zich bij jou openbaart. In datzelfde jaar valt de Berlijnse muur en jouw stiefvader attendeert jou op Fukuyama’s ‘Het einde van de geschiedenis’. Kort daarna reis je door bevrijd Europa. De opstand van mensen tegen onderdrukking gaat jou meer en meer interesseren, alleen weet je nog niet hoe je die interesse vorm moet geven. Je gaat stage lopen bij een vredesinstituut in Washington en daar kom je personen tegen die voor jouw ontwikkeling belangrijk zijn: Mort Abramowitz (een gepensioneerde diplomaat) en Fred Cuny (internationale crisismanager). Zij hebben een groot netwerk (waar jij wel raad mee weet) en zijn actief in Bosnië waar dan de oorlog is losgebarsten. Je wilt iets doen en reist als journalist af naar Joegoslavië waar je freelance oorlogscorrespondent wordt. Je zit daar vooral in Sarajevo, probeert jouw stukken in kranten geplaatst te krijgen en pleit voor Amerikaans ingrijpen. Na meer dan een jaar wil je meer en kies je ervoor om in Harvard mensenrechten te gaan studeren. Hier ga jij je bezig houden met vraagstukken als wanneer is militair ingrijpen gerechtvaardigd, wanneer heb je de morele plicht iets te doen en hoe verhoudt zich dat met geweldloosheid, wat zijn de risico’s van ingrijpen en wanneer mag je geweld gebruiken. Hier ontstaat jouw idee om een boek te schrijven over genocides en de reacties hierop vanuit de vrije wereld. Daarnaast zet je met anderen het Carr Centrum voor mensenrechtenpolitiek op. In deze jaren ben je, zoals anderen zeggen en waar ik mij van alles bij kan voorstellen, ‘een en al genocide, de hele dag door’. Aan het boek werk je vijf jaar en je moet nogal wat doen om het gepubliceerd te krijgen. Uiteindelijk win je er de Pullitzerprijs mee. Je zet je in voor de zaak Darfur (Soedan) en hoort senator Obama spreken met zijn verheven, niemand uitsluitende boodschap. Een vriend van jou raad je aan jouw boek naar Obama op te sturen die jou uitnodigt om erover te komen praten. 
Je gaat voor hem werken en niet heel veel later maakt hij bekend om mee te doen aan de presidentsverkiezingen. Jij steunt hem hierin maar wordt uit het team gehaald omdat je Hillary Clinton in een interview ‘monster’ noemt. Obama wordt uiteindelijk tot president gekozen en jij gaat, natuurlijk, nadenken over wat jijzelf politiek zou kunnen betekenen. Jij krijgt een speciale directeursfunctie bij de Nationale Veiligheidsraad en houd je bezig met zaken als mensenhandel, onderdrukking minderheden en grootschalig geweld. Hier leer je baas spelen en om te gaan met bureaucratische processen. Dit waren de jaren dat je werkt aan de situatie in Soedan, Ivoorkust, Oeganda, de Centraal Afrikaanse Republiek en voor LHBT-rechten wereldwijd. In 2010 ontstaat de Arabische Lente in Tunesië, Egypte en Libië. Vanuit jouw functie raak je betrokken bij de inzet van de luchtmacht in Libië. Hier leidt de westerse inmenging tot chaos. 
In 2012 wordt Obama voor de tweede keer gekozen en jij wordt Amerikaanse Ambassadrice bij de Verenigde Naties. Je wordt het hoofd van een groot team, neemt intrek in een enorm penthouse in New York, beschikt over huispersoneel en wordt in een gepantserde suv rondgereden. In deze functie krijg je te maken met de oorlog in Syrië. Er worden chemische wapens gebruikt en een weekend lang overweegt Obama om daar militair in te grijpen, waar jij voor bent. Dan betrekt hij het Congres erbij en wordt ingrijpen niet meer reëel met alle gevolgen van dien. Jij krijgt in jouw functie natuurlijk met Rusland van doen, bouwt een goede relatie op met de Russische ambassadeur en merkt dat met Rusland uiteindelijk nauwelijks is samen te werken. In 2015 breekt de Ebola crisis uit in West-Afrika en een grote uitbrak wordt uiteindelijk met kunde en leiderschap van Obama tegengehouden. Veel belangrijke zaken die in de wereld gebeuren, passeren de revue en in 2016 wordt Trump tot president van Amerika gekozen en eindigt (voorlopig?) jouw politieke carrière en ga je weer lesgeven op het Carr Centrum voor mensenrechten op de universiteit van Harvard.



Jouw carrière begint zo ongeveer wanneer de Berlijnse muur valt en de wereld vol optimisme zit over democratie en liberalisme en het idee in de lucht hangt dat alles wel goed zal komen. Bij het verschijnen van jouw memoires is de pendule naar de andere kant doorgeslagen. Liberale democratie trekt zich terug of lijkt soms volledig kopje onder te gaan en de aandacht en energie gaat uit naar zaken die misgaan. In jouw boek probeer je toch die andere wereld te schetsen. Jij bent niet naïef en ziet ook de problemen waar we vandaag de dag mee te maken hebben in de westerse wereld, of het nu gaat om de grote ongelijkheid, de invloed van geld op politiek, corruptie, nationalisme en polarisatie en racisme. Echter, jouw wereld is pragmatisch en hoopvol en jij vraagt je steeds af waar staan we voor en wat kunnen we bereiken. Je vraagt je af wat jij wil, wat anderen willen en wat mogelijk is. Het is niet voor niets dat Obama jou er steeds bij haalt omdat hij jouw mening wil horen. Het is ook duidelijk dat jij hem (en anderen) soms irriteert met jouw uitgesproken mening en hij naar jou snauwt: ‘Samantha, we hebben jouw boek allemaal gelezen’. Het is interessant om te lezen over de jonge Power met haar idealen. Later weet je maar al te goed dat je in een team opereert en in brede politieke context. Jij weet dat jij (jouw team) successen behaalt en mogelijkheden weet te verruimen, of het nu gaat om de LHBT-rechten wereldwijd, de aanpak van Ebola, de afspraken met Iran en die over het klimaat. Er blijven littekens achter, hoe kan het ook anders als je je met deze onderwerpen bezighoudt en op dit niveau operereert, en Syrië is daar het grootste van. Amerika en het westen hadden hier iets moeten doen volgens jou. Jouw boek is een combinatie van woede, hoop en geloof dat het beter kan en voor mij ben je vooral dat voorbeeld van volwassen idealisme. Van al die grote woorden als macht, vastberadenheid, verantwoordelijkheid en solidariteit is waardigheid jou misschien wel het meeste waard. Jouw denken en doen is verbonden met grote wereldproblemen, wat we hadden moeten doen, wat deden we en wat hebben we gelaten. Je kijkt terug op wat er is gebeurd en hoe jij daar zelf in hebt gehandeld. Je beschrijft de zaken die je tegenkomt en plaatst er kanttekeningen bij. Waarom je ergens voor bent en waar het op is gebaseerd, komt in jouw verhaal veel minder goed uit de verf. Jij kiest voor mensen die zich om anderen bekommeren en draagt concreet bij aan ontwikkeling en vooruitgang in de wereld. Niet om de hele wereld te veranderen maar wel om een aantal individuele werelden te veranderen. Ik denk dat jouw vriend gelijk had toen hij zei dat de wereld vol wanhopige situaties zit en dat je daarom niet anders kunt dan je eigen veldslagen kiezen en er voor te zorgen dat je er een paar wint. Natuurlijk zie jij ook in dat je lang niet op alle terreinen hebt gewonnen. Ergens in het boek haal je een motto aan dat aan de Koran is ontleend: “Wie een leven redt, redt de hele mensheid’. Dat ene leven heb je wel gered, neem dat van mij aan.



Grote groet, -Harrie Jonkman



Power, S. (2019). **Leerschool van een idealist. Memoires.** Amsterdam/Antwerpen: Atlas Contact 536 pagina’s. 34,95 euro.




