
# DE RIJKEN EN DE REST



Amsterdam, december 2019



Beste Daniel Markovits,



In 2015 word jij op Yale (New Haven, USA) uitgenodigd om er de jaarlijkse universitaire toespraak te houden. De universiteit is bijzonder trots op jouw wetenschappelijke werk en zet jou met deze gelegenheid in het zonnetje. Jij bent hier hoogleraar aan de Rechtenfaculteit en houd je met de moderne, rechtvaardige en inclusieve samenleving bezig. De decaan die jou op die bijeenkomst introduceert, omschrijft jou als een uitzonderlijke veelzijdige wetenschapper, in diepte en breedte. Ik denk het ook. Jij bent economische en econometrisch, filosofisch, sociaal- en rechtswetenschappelijk geschoold en overstijgt in jouw werk grenzen van disciplines. In jouw toespraak, waar je via YouTube nog rustig naar kunt luisteren en dat raad ik anderen graag bij gelegenheid aan, spreek jij jouw studenten van 2015 rechtstreeks toe. Jij houdt hen voor dat zij met het behalen van hun studie iets bijzonders hebben gehaald en dat zij daar terecht blij mee mogen zijn; de toekomst ligt aan hun voeten. Met hun talenten en competenties verlaten ze de universiteit met veel status, ze zullen vast veel gaan verdienen en ook hun kinderen maken veel kans op zo’n toekomst. Echter, het is goed als zij zich van meer zaken bewust zijn. Bijvoorbeeld, dat zij ooit geselecteerd zijn als topstudenten en dat heel veel jongeren dat niet gelukt is. Jij houdt ze voor dat zij het hebben gehaald met hun uitzonderlijke talenten en capaciteiten maar dat hun succes ook met hun achtergronden te maken heeft. Veruit de meesten van hen zijn in bepaalde families geboren, hebben op bepaalde scholen gezeten en hebben in hun voortraject heel veel educatieve ondersteuning gekregen. Zij hebben er veel voor moeten doen, zeker, maar selectie en competitie houdt met het behalen van het diploma niet op. Zij komen niet in een gespreid bedje terecht, zij zullen er knetterhard voor moeten werken en in hun werk zullen zij zich moeten blijven bewijzen. Alles bij elkaar behoren zij tot nu de nieuwe elite en aristocratie. Jij maakt die studenten in dat verhaal duidelijk dat meritocratie ooit de mobiliteit in de samenleving versterkte en dat dit maatschappelijke systeem nu sociale mobiliteit blokkeert. Er is een heel nieuw kastensyteem ontstaan waar zij zich van bewust moeten zijn, voor hun eigen bestwil en toekomst en die van anderen. 
Met meritocratie hield jij de al jarenlang bezig. Ondertussen zijn we een paar jaar verder en heb je gewerkt aan een boek hierover. In jouw nieuwe boek *‘The Meritocracy Trap. How America’s Foundational Myth Feeds Inequality, Dismantles the Middle Class, and Devours the Elite’* heb jij alles waarmee jij jouw studenten zo krachtig toespreekt verder uitgewerkt en nu spreek jij een brede groep aan. In dat doortimmerde boek laat je zien wat meritocratie betekent, hoe het systeem werkt en het leven van mensen organiseert. 

           

Honderd jaar geleden wordt er hard en lang gewerkt door het grote, arme deel van de bevolking. De helft en misschien wel driekwart van de bevolking leeft in armoede. De rijken daarentegen kunnen van vrijheid genieten dat ze verkrijgen door hun inkomen van hun land, fabrieken en ander kapitaal dat ze bezitten. Zij gaan ’s ochtends om tien uur eens wat doen en vinden het ’s middags om drie uur wel goed, met daartussenin drie martini’s en een lunch van twee uur. De omstandigheden waarin mensen in die tijd leven worden bepaald door de omstandigheden waarin ze worden geboren. Halverwege de twintigste eeuw maakt het hiërarchisch maatschappelijke systeem plaats voor een nieuwe maatschappelijke orde. Niet meer de geboorte maar studie en hard werken, talent en inspanning bepalen maatschappelijke positie en status en hoe rijk iemand wordt. Dat idee is zeer aansprekend en voor bijna iedereen is dit maatschappelijke vooruitgang. Echter, van de keerzijden en ondermijnende effecten zijn we ons te weinig bewust. Jij maakt in jouw boek heel duidelijk dat meritocratie een grote maatschappelijke competitie organiseert en dat het klassen isoleert, de rijken niet alleen van de armen maar ook van de middenklasse. 
De nieuwe elite, waar jij in jouw boek de nadruk op legt, wordt via onderwijs en werk geconstrueerd. Met meritocratie is onderwijs verandert in een grote krachtmeting van individuen om via studie en training uiteindelijk de maatschappelijke top te behalen. Direct en indirect zorgt de familie waarin je geboren wordt ervoor dat jij op bepaalde scholen (voorschool, basisschool, voortgezet onderwijs) en uiteindelijke op specifieke universiteiten (Harvard, Yale, Stanford, Princeton, MIT e.d.) terecht komt. Je moet tegenwoordig niet alleen over de goede diploma’s beschikken maar ook eindeloze testen en zware selectiesystemen doorlopen om op de juiste plek terecht te komen. Tegelijkertijd is werk zelf verandert in lucratieve banen maar die  bijzonder veel van de competenties en inspanningen van mensen vragen. De inkomens zijn enorm gestegen en zeker binnen de financiële sector en het management, waar jij met name over schrijft, duizelingwekkend. De rijken krijgen het niet meer voor niets en die drie martini’s tussen de middag zitten er niet meer in. Mensen aan de top moeten vaak twee keer zo hard werken dan de mensen aan de onderste helft van de maatschappelijke ladder en werkweken van 60, 80, 100 uur zijn hier niet uitzonderlijk. Het systeem zorgt ervoor dat het onderste deel van de samenleving en de middenklasse nauwelijks nog naar boven door kunnen schuiven en het hele systeem van onderwijs, training, vaardigheden en inkomen zorgt er ondertussen voor dat de elite van kinds af aan hun positie behoudt. Het meritocratisch systeem is dat geworden waar ze eigenlijk ooit zo tegen was, een intergenerationele beschermer van welvaart en status. 




Het meritocratisch systeem is volgens jou al lang niet meer ideaal, verdedigbaar en democratisch. Het trekt groepen uit elkaar, legt de macht en creativiteit in handen van een kleine groep, zet grote groepen buitenspel en zorgt voor angst en vervreemding. Het is volgens jou vooral de middenklasse die de afgelopen decennia slachtoffer is geworden van het systeem en het wordt ondertussen tijd hen meer status en inkomen te geven. Hun werk is in handen gekomen van de elite en verder overgenomen door technologische innovatie. Hun positie is ontmanteld en zij zijn er over een langere tijd niet meer op vooruit gegaan. Jij bent ervan overtuigt dat een meer gelijke samenleving iedereen ten goede komt. Daarom moet een oplossing vooral gezocht worden in een samenhangende visie die door iedereen gedeeld wordt, waarbij de meritocratische hiërarchie wordt ontmanteld en er meer democratische gelijkheid komt. In de geschiedenis is wel vaker zo’n appeltje geschild. In 2015 pleitte jij wel voor een nieuw democratisch systeem, maar toen had jij daar nog geen antwoorden op. Vier jaar later heb jij hier wel wat over te vertellen. Beperkt weliswaar. Jij denkt vooral aan maatregelen gericht op onderwijs en werk, samen op en over langere tijd. Het onderwijs moet open en inclusief worden met minder competitie en strijd, ook op de goede scholen en universiteiten. Overdracht van gemeenschapsgelden naar private educatieve instellingen moet worden afgebouwd. Minder perfect onderwijs aan de elite en meer goed onderwijs in de breedte. Daarnaast is het volgens jou verstandig om belastingmaatregelen door te voeren en om het werk van de middenklasse weer serieus te nemen, te waarderen en te betalen. Het is goed als gespecialiseerd werk dat nu vooral ten goede komt aan een relatief kleine groep plaats maakt voor werk dat ten goede aan veel mensen, werk dat door een brede groep goed geschoold personeel kan worden geleverd.    
Jouw verhaal is mooie combinatie van empirische en morele analyse. Jij zet de feiten op rij zoals niemand dit tot nu toe op dit terrein zo heeft blootgelegd (alleen al die negentig pagina’s aan noten!) en vergelijkt de cijfers over tijd. Tegelijkertijd zijn het steeds morele vragen die jij oproept over de opbouw van een meer rechtvaardig maatschappelijk systeem. Ik vind wel dat jij je soms herhaalt en, in alle bescheidenheid, denk dat de redacteur hier een beter en toegankelijker boek van had kunnen maken. Maar ik wil het positief houden omdat ik jouw boek zo goed vind. Alles wat we intelligent en effectief beleid bedenken moet gebaseerd zijn op politiek begrip. Daar begint het mee en het begrijpen van de situatie waar we met elkaar inzitten, daar nu gaat het jou om. Zo zijn er van die boeken die veel politieke en maatschappelijke stof hebben doen opwaaien over klassenindeling in de samenleving. Rond 1900 schreef Thorstein Veblen zo’n boek (The Theory of the Leisure Class) waarin hij laat zien hoe klassen tegenover elkaar staan, hoe ze via vrije tijd en hun wijze van consumptie indruk op elkaar maken en vooral hoe de rijken hun vrije tijd invullen. The Affluent Society van John Kenneth Galbraith, dat verschijnt in het jaar dat Michael Young het begrip meritocratie introduceert, is ook zo’n boek. Het laat zien dat er veel geld zit in de private sector maar dat de publieke sector nog steeds heel arm is. In dezelfde tijd verschijnt The Other America van Michael Harrington dat zichtbaar maakt hoe een groot deel van Amerika nog steeds in bittere armoede leeft. Jouw boek hoort in dit rijtje klassieke sociaal wetenschappelijke boeken over klassen thuis met, vermoed ik,  maatschappelijke impact. We gaan doorkrijgen dat meritocratische ongelijkheid niet iedereen op eenzelfde wijze dient en dat het tijd wordt dat we de meritocratisch val die we met elkaar hebben neergezet gaan ontwijken. Niet omdat er winnaars en verliezers zijn, maar omdat het de rijken én de rest ten goede komt.   



Grote groet, -Harrie Jonkman



Markovits, D. (2019). **The Meritocracy Trap. How America’s Foundational Myth Feeds Inequality, Dismantles the Middle Class, and Devours the Elite.** London: Penguin, 448 pagina’s. 26,99 euro.




