
# TERUGSLAAN



Amsterdam, februari 2020


Beste Diana Ravitch,


Bijna meer dan tien jaar geleden schreef jij voor *The Wall Street Journal (9 maart, 2010)* een artikel dat toen bij veel mensen in jouw omgeving de wenkbrauwen deed fronzen: Waarom ik mijn mening over onderwijsvernieuwing veranderde. Je schrijft daarin dat je sinds 1975 onderwijshistorica bent en diverse boeken hebt geschreven over onderwijsgeschiedenis. Daarbij ging het jou vooral om de noodzaak om kennis en inzichten van leerlingen te versterken over geschiedenis, literatuur, geografie, wetenschap en burgerschap. Jarenlang verdedig jij het belang van heldere standaarden in het onderwijs, vind je vrije schoolkeus belangrijk en zie je de kracht in van speciale charterscholen. Met die achtergrond word je uitgenodigd om op het ministerie van Onderwijs te gaan werken in de regering van George H.W. Bush. Nieuwe strategieën die bij jouw denken aansluiten en die er in beginsel veelbelovend uit zien en jij mede vormgeeft, pakken in de loop van de jaren desastreus uit. Meer en meer raak jij teleurgesteld hierover. Hoe anders ziet het er in 2008 uit wanneer 35% van de scholen gekarakteriseerd wordt als zwakke scholen, een percentage dat met het jaar toeneemt. Het wordt jou duidelijk dat dit nieuwe perspectief een nachtmerrie is voor het Amerikaanse onderwijs, dat het gemeenschappen afbreekt, ervoor zorgt dat scholen op grote schaal worden gesloten, docenten worden afgerekend en ontslagen en leerlingen eindeloos niets zeggende testen voorgelegd krijgen. Tegelijkertijd komen nieuwe machtige partijen het onderwijs binnengestapt. Zij weten dit varkentje wel te wassen. Al de maatregelen hebben dan misschien positieve effecten op een heel klein deel van de populatie maar veel vaker geen of negatieve effecten op het overgrote deel (97%) van de leerlingen. Dit beleid zorgt niet voor een nieuwe generatie met meer kennis die beter is voorbereid op de verantwoordelijkheden van de moderne burger. Wanneer dat tot je doordringt, verander jij van mening en schrijf je met een hele andere pen. Dat artikel dus en in datzelfde jaar (2010) verschijnt *The Death and Life of the Great American School System* en een paar jaar later (2014) *The Reign of Error. The Hoax of the Privatization Movement and the Danger to America’s Public School*. Je laat zien wat er in het publieke onderwijs gebeurt en wordt daarnaast een publiek figuur die op tv verschijnt, mee demonstreert, leraren toespreekt en vele stukken voor kranten en tijdschriften schrijft. In 2019 komt nog *The Wisdom and Wit of Diana Ravitch* uit met artikelen uit kranten en tijdschriften gedurende de laatste tien jaar. Onlangs schreef ik jou daarover terug (Publiek Goed, oktober 2019). Nu is er alweer een nieuw boek van jou uit: *Slaying Goliath. The Passionate Resistance to Privatization and the Flight to Save America’s Public Schools* uit. Ook hier verdedig jij dat openbare Amerikaanse onderwijssysteem dat verbonden is met gemeenschappen, ouders, leerkrachten en leerlingen. Jij bent de stem van publiek onderwijs in Amerika en weet en voelt dat iemand daarvoor moet opkomen.


   
Ten tijde van het presidentschap van Ronald Reagan kwam het Ministerie van Onderwijs met het rapport *A Nation at Risk: The Imperative for Educational Reform* waarvan de geest tot vandaag de dag doorwerkt in het Amerikaanse onderwijs. Een groot deel van de maatschappelijke ellende, zo staat in dat rapport, is toe te schrijven aan een falend publiek onderwijssysteem en nauwelijks onderbouwd wordt dat publieke onderwijs van alles in de schoenen geschoven. Het onderwijs wordt na dit rapport, schrijf jij weer in jouw nieuwe boek, een nationale politieke voetbal waar iedereen tegenaan gaat schoppen. Van links naar rechts kijkt men strenger aan tegen de ontwikkeling van kinderen en breed wordt het idee gedeeld om scholen en leerkrachten op resultaten af te rekenen. Reagan, Pa Bush, Clinton, zoon Bush, Obama tot en met Trump (zes administraties op rij) doen dat, net als hun staatssecretarissen Margaret Spellings, Arne Duncan (wat zal hij vaak over jou gedroomd hebben) en Betsy de Vos. Nieuwe standaarden en testen zorgen voor het kader en het hele onderwijsbeleid van de laatste decennia, van No Child Left Behind-beleid tot en met Race to the Top en Every Student Succeeds Act, ademen dezelfde geest: regio’s, scholen, leerkrachten en leerlingen die niet voldoende resultaten halen, moeten worden gestraft, financieel dan wel met sluiting, ontslag of verwijdering. 
Op dat falend onderwijssysteem en dat gebrek aan resultaten heeft een hele groep Ontwrichters wel een antwoord. Met hun expertise in het opzetten van miljardenbedrijven gaan zij zich uitgebreid met het onderwijs bemoeien. Zij willen het onderwijs opnieuw uitvinden zoals ze met hun bedrijf ook succesvol iets nieuws hebben uitgevonden. De marktgerichte benadering doet z’n intrede. Iedereen is te vervangen, desnoods door machines, iedereen kan lesgeven, iedereen kan een school runnen en iedereen kan onderwijsbeleid maken. Maar niet iedereen weet dat goed te sturen. Zij wel. Jij noemt een heel rijtje Ontwrichters, te lang om hier allemaal te herhalen. Maar natuurlijk horen Donald Trump en zijn staatssecrataris Betsy de Vos daarbij maar ook heel veel andere Republikeinen en Democraten. Ze zitten ook in de filantropie, komen uit de vrije markt of het zijn of waren hedge hunters. Bekende mensen als Bill Gates, de Walton familie, Michael Bloomberg, de Koch broers en Mark Zuckerberg horen daarbij. Ze hebben grote sommen geld met hun bedrijven verdiend en steken nu grote bedragen in het onderwijs. Niets voor niets natuurlijk want zij zijn gewend met hun geld resultaten te behalen. De een investeert in monitoring en testen van leerresultaten, de ander ondersteunt speciale charterscholen buiten het openbaar onderwijs om en dan zijn er Ontwrichters die inzetten op de vrije onderwijskeuze. Dit alles ondersteund door organisaties als Teaching for America en door media als Fox News en The Wall Street Journal. Je beschrijft hoe het onderwijs in Washington DC, Chicago, Florida, Pennsylvania, Michigan maar ook in Massachusetts en Connecticut verandert. Vooral laat je ook zien welke grote schandalen hierdoor worden veroorzaakt. Dit is geen reformbeweging volgens jou, dit is het ontwrichten van het grote Amerikaanse openbare onderwijssysteem. 
Jij hebt een Amerikaans boek geschreven en een Amerikaans boek is niet af als er geen duidelijke tegenpartij is. Tegenover de Ontwrichters staat het Verzet waar leraren, studenten, ouders en grootouders en religieuze leiders toe behoren. Zij die weten dat het openbaar onderwijs de basis is van een democratische samenleving. Zij hebben niets op met de privatisering van het onderwijs en de gestandaardiseerd testen. Hen gaat het om professionalisering van het onderwijs, middelen beschikbaar stellen, plezier in leren en lesgeven teruggeven, de waarde van kennis en zij snappen dat de sociale omgeving van het onderwijs van invloed is op de kwaliteit. Zij hebben natuurlijk niet het geld maar wel de passie en de overtuiging. Hier heb je mensen als Linda Darling-Hammond, Yong Zhao, Anthony Cody, Deborah Meier en al die andere lokale onderwijsdirecteuren, leerkrachten, bestuurders en bloggers. Zij brengen feiten en bewijzen naar voren dat die standaardtesten, lerarenevaluaties, de onervaren leerkrachten en de privatisering helemaal niet werken. Je laat zien hoe leerkrachten en studenten succesvol demonstreren en in verzet komen in New York City, Rhode Island, Seattle, Virginia, Oklahoma en Arizon. Je laat zien hoe deze groep terugslaat. Zij hebben niet het geld zoals de Ontwrichters dat wel hebben. Maar uiteindelijk is democratie niet te koop is. Jij vraagt je af hoe we het denken en doen van Franklin, Lincoln en King weer zijn te cultiveren in Amerika, van mensen die misschien helemaal niet zo goed waren in die testen (terwijl die jongens en meiden van Enron daar allicht heel goed in waren). 



Hoe verslaat David Goliath? Goliath is sterk, ervaren en goed bewapend. David daarentegen is klein, jong en slecht bewapend. Maar David heeft zijn slinger en weet Goliath goed te treffen. In de geschiedenis hebben deze twee vaak tegenover elkaar gestaan en David heeft wel vaker zo’n gevecht gewonnen. Die fabel spreekt jou aan en volgens jou, ik kan dat zelf niet heel goed beoordelen, is het Verzet aan de winnende hand en gaan de Ontwrichters zo’n beetje door hun knieën. Zij geven grote bedragen uit aan hun eigen projecten maar uiteindelijk zorgen ze er ook voor dat er weinig aan onderwijs wordt uitgegeven, nemen ze de professionalisering niet serieus en willen ze niet investeren in de sociale omgeving waarbinnen dat onderwijs zich moet verhouden. Het grote succes van de Ontwrichters blijft uit. Zoals de recente geschiedenis laat zien is de lichte aanpak met doortastende politieke actie de beste formule voor het Verzet tegenover de plunderende Ontwrichters. Ouders willen dat hun kind les krijgt van een leraar die hen ziet, met hen praat, die naar ze luistert, die hen kent en over een langere tijd voor hen zorgt. Die hele markttaal van de Ontwrichters werkt niet in het onderwijs. De taal van Dewey, die jou zo lief is, dat leergemeenschappen voor kinderen opkomen zoals ouders voor hun eigen kinderen opkomen, is een betere basis voor onderwijs en democratie. Onderwijs dient niet ten onder te gaan aan libertaire doelen. Voor democratie heb je passie nodig, betrokkenheid en moet je waarde inzien van goed onderwijs. 
In dat hele krachtenveld ben jij natuurlijk zelf vooral die kleine David die de slinger oppakt tegen Goliath. Meer dan tien jaar nu ben jij de stem van dat Verzet. Niemand die dat in de onderwijsdiscussie duidelijker, vasthoudender en overtuigender doet dan jij. Jij voelt die verantwoordelijkheid en kunt het natuurlijk ook nog eens; wat een kracht. Maar stilletjes hoop ik ondertussen ook dat je weer de tijd en de rust krijgt om te laten zien hoe dat onderwijs van het Verzet eruit ziet, hoe dat verbonden is met die rijke democratische geschiedenis en hoe het kinderen en jongeren voorbereidt op de moderne tijd. 





Grote groet, -Harrie Jonkman

Ravitch, D.(2020). **Slaying Goliath. The Passionate Resistance to Privatization and the Flight to Save America’s Public Schools**. New York: Alfred A. Knopf, 352 pagina’s. 23,99 euro.


