

# KAPITALE IDEEËN



Amsterdam, maart 2020


Beste Thomas Piketty,


Je bent hoogleraar economie aan de Parijse École des Hautes Étudus en Science Sociales. Daar werkten voorheen ook vooraanstaande historici van de Annales school, Braudel en LeGoff bijvoorbeeld. Als ik jouw boeken lees, denk ik steeds aan hen. Het zal wel komen door de gelaagde en structurele mentaliteitsgeschiedenis die jij bedrijft, de long durée. Daarbij betrek je niet alleen economische en historische kennis, maar net zo goed sociologie, statistiek, demografie, politicologie en filosofie. Dit alles om, in jouw geval, maatschappelijke ongelijkheid te begrijpen. In *Kapitaal in de 21ste* deed je dat al zo. Dat boek gaat over ongelijkheid in de moderne wereld en maakte jou in één klap wereldberoemd. Daar laat je zien dat het met welvaart en gelijkheid niet altijd maar automatisch beter gaat. De ontwikkeling daarvan kent een grillig patroon en is afhankelijk van de keuzes die we zelf maken. Om ongelijkheid goed te begrijpen is het goed niet alleen naar het inkomen van mensen te kijken maar tegelijk naar het vermogen dat ze hebben opgebouwd. Want heeft iemand vermogen opgebouwd, dan gaat het veel sneller dan de economie in het algemeen. In mijn jonge jaren heb ik genoeg Monopoly gespeeld om dit goed te begrijpen. Najaar 2019 kwam in jouw eigen land jouw nieuwe boek uit en deze maand verscheen het ook in mijn eigen land: Kapitaal en Ideologie. Dit keer rek je tijd en ruimte veel verder op. Je laat zien hoe ongelijkheid vorm krijgt op verschillende momenten in de geschiedenis, van de oudere drie standenmaatschappijen tot en met onze huidige samenleving van hyperkapitalisme. Dit keer heb je niet meer alleen oog voor de rijke, met name westerse landen. Nu krijgen ook ontwikkelingen in landen als India, China, Rusland, Haïti en Ivoorkust een plaats. In dit nieuwe, indrukwekkende boek wil je beter begrijpen hoe ongelijkheid tot stand komt en welke ontwikkelingspaden er te onderscheiden zijn. Net als Braudel en LeGoff gaat het jou om een mentaliteitsgeschiedenis die bij jou ideologisch en politiek van aard is. Want als jij iets hebt geleerd van die lange zoektocht is het wel dat alle maatschappelijke en politieke onderwerpen die ons bezig houden sociale en historische constructies zijn. Ze hangen altijd samen met het wettelijke, fiscale, onderwijs- en politiek systeem waarvoor in een samenleving wordt gekozen. Echter, anders dan die voorgangers aan jouw universiteit ooit wil jij die constructies en legitimaties niet alleen begrijpen er zelf ook een slinger aan geven.  



In het eerste deel van jouw boek laat je zien hoe de belangrijke oude stelsels er uit zien en waar ze op gebaseerd zijn. Je analyseert drie standen samenlevingen in Frankrijk en andere Europese landen die hier rond 1000-1100 tot stand komen. In deze sociale constructie, die in andere delen van de wereld al eerder tot stand waren gekomen, wordt alles op lokaal niveau geregeld. De geestelijkheid is de religieuze en intellectuele elite die de spirituele macht heeft, de adel is de militaire elite die verantwoordelijk is voor veiligheid en maatschappelijke orde. Dan is er nog de derde laag van werkenden, van boeren en ambachtslieden, die voor het voeden, kleden en voortplanten zorgt. Het percentage van de eerste twee lagen in de samenleving neemt over de tijd langzaam af. Maar al die tijd worden eigendom en regale functies lokaal georganiseerd en hebben de drie standen elkaar nodig. Rond 1800 ontstaat de bezitterssamenleving met een, wat jij noemt, propriëtaristische ideologie waarin de individuele emancipatie en het recht op eigendom en de regale rechten van de staat van elkaar worden gescheiden. De bezitterssamenleving wordt in het ene land snel, in het ander geleidelijk opgebouwd. Tegelijkertijd worden met financiële en militaire mogelijkheden de contacten met andere continenten verder aangehaald. Slavenstaten kenden we al veel langer, maar met het individuele recht op eigendom worden deze nu vanuit de welvarende landen elders opgebouwd. In die slavenstaten ontstaat extreme ongelijkheid en jouw beschrijving van Haïti en Santo Domingo (90% is slaaf en krijgt 20% van de jaarlijkse opbrengsten) is schrijnend. Wanneer halverwege de negentiende eeuw slavernij wordt afgeschaft, valt natuurlijk vooral de compensatie voor de individuele slavenhandelaren op die jij plaatst binnen de ideologie van de bezitterssamenleving. Slavenstaten worden na de afschaffing van slavernij tot koloniën omgebouwd, met gloriejaren voor de Tweede Wereldoorlog en na de oorlogsjaren worden ze definitief afgebroken. 
Dan is de twintigste eeuw al lang begonnen. Er ontstaat een crisis in de bezitterssamenleving die natuurlijk te maken heeft met wereldoorlogen, revolutie en crisis, met vernietiging, onteigening en inflatie. De discussie radicaliseert en het systeem transformeert. In de westerse wereld zien we dat aan het begin van de twintigste eeuw de inkomens van de 10% meest verdienenden gemiddeld 50% van het totale nationale inkomen in West-Europa omvat. In de jaren 1950-1980 daalt dat naar 30% en na 2000 neemt het weer toe naar 35%. Amerika laat eenzelfde trend zien maar daar is de ongelijkheid aan het begin juist kleiner en de laatste jaren is het verschil daar groter geworden. De verschillen in eigendommen waren begin 1900 bijzonder hoog, zouden tot 1980-1990 dalen om daarna weer te stijgen. De opbouw van progressieve belastingen, waar in Amerika en Verenigd Koninkrijk mee wordt begonnen, valt op. Dat geldt in deze periode ook voor de opmars van de fiscale en sociale staat, de opbouw van het sociaal recht- en zekerheidstelsel en het universeel onderwijssysteem. De sociaaldemocratische samenleving ontstaat in de rijkere landen en over deze gouden periode (1950-1980) ben je enthousiast. 
In die twintigste eeuw ontstaan ook communistische en postcommunistische samenlevingen in Rusland, Oost-Europa en China. Het communisme was natuurlijk de tegenpool van de bezitterssamenleving en alle individuele eigendom wordt hier tot een minimum beperkt. Hier ontstaat een staat van kruimeldieven die in alle opzichten als mislukt moet worden beschouwd. Over een samenleving waar 5% van de mensen gevangen zit, kun je alleen maar negatief aankijken. Dat is voor jou duidelijk. Na het echec van het grote Sovjetregime ontstaat daar een systeem dat volgens jou wordt beheerst door oligarchen en extreme individuele rijkdom, gegraai uit de staatskas en verduisteringspartijen. De Oost-Europese landen komen bij Europa en China had in 1980 al met een autoritaire gemengde economie een andere weg ingeslagen. Daar is ondertussen het ongelijkheidsniveau vergelijkbaar met Amerika ook al blijft veel hierover onduidelijk. 
In ons eigen westerse landen hadden we met de val van het communisme geen geloof meer in sociaal-economische rechtvaardiging van de samenleving en zijn we vooral geïnteresseerd in het definiëren van onze grenzen en onszelf. Er ontstaat een hyperkapitalisme dat in dit informatie- en datatijdperk en globalisering modern aan doet en tegelijk zo archaïsch en ouderwets van karakter is.  
Wat jij met al jouw beschrijvingen en analyses vooral duidelijk wilt maken is dat de oudere samenlevingen net zo goed als de moderne samenlevingen steeds weer voor de keuze staan richting te geven aan gelijkheid en ongelijkheid, ze antwoord geven op de vraag hoe individuele belangen en algemeen welzijn van elkaar zijn te onderscheiden en definiëren hoe het systeem gelegitimeerd, geloofwaardig en geïnstitutionaliseerd behoort te worden.



Na 1980 ontstaan er voorzichtig nieuwe scheidslijnen binnen de westerse samenlevingen. Een duidelijke klassenstructuur, voorheen zo herkenbaar, maakt plaats voor meerdere elites die elkaar afwisselen. De ene keer zijn de hoogopgeleiden aan de macht (brahmaans links), de andere keer hebben mensen met geld en vermogen (zakelijk rechts) het voor het zeggen. De kansarmen komen aan de zijkant te staan en voelen dat ook zo. Daar staan ze open voor ideeën van nationalisme en populisme. Het is, volgens jou, nodig dat dat vertrouwen met die mensen die daar staan weer wordt hersteld en dat er nieuwe gemeenschappelijke rechtvaardigheidsnormen komen voor sociaal handelen. Jij bent niet zozeer geïnteresseerd in algemene principes van rechtvaardigheid. Jou gaat het om de samenleving waarin we leven en de problemen waar wij mee te maken hebben, hoe oplossingen in beleid kunnen worden uitgewerkt en de rol van instituties daarbij. Jij presenteert jouw idee van een eigentijds socialisme dat nadruk legt op participatieve en egalitaire democratie. Bij jou telt iedereen en jij wilt dat zoveel mogelijk mensen aan die samenleving deelnemen. Eigendom zou niet zozeer permanent maar veelmeer tijdelijk en vloeiend moeten zijn. Het wordt tijd dat er weer meer werk wordt gemaakt van progressief belastingsysteem; niet alleen qua inkomen, net zo goed voor eigendom en erfrecht. Uitgebreid ga je in op emancipatie via onderwijs en het belang van kennisoverdracht. Met onderwijsongelijkheid zijn we de laatste jaren nogal hypocriet omgegaan. Beleid om onderwijsachterstanden weg te halen is meer een kleine pleister voor het bloeden dan dat het de grote ongelijkheid aanpakt. Jij doet concrete voorstellen die bij de opbouw van een meer participatief en egalitair systeem gebruikt kunnen worden. In de latere hoofdstukken van jouw boek ga je daarbij uitgebreid in op wat er politiek gebeurt en hoe dat ongelijkheid beïnvloedt. Op zich interessant allemaal, maar het voelt onevenwichtig aan. 
Met de klimaatopwarming van de aarde vormt de toenemende ongelijkheid volgens jou de grootste uitdaging waar we nu voor staan. Ik denk dat je hier gelijk hebt. Als een nieuwe Marx plaats jij ideologie in het centrum van jouw denken, dit keer losgekoppeld van onontkoombare wetmatigheden. Misschien heb je wel zoveel bladzijden (allicht te veel) nodig om vooral dat duidelijk te maken. Bij jou is het niet meer de materiële basis van de samenleving die de lijn van de geschiedenis bepaalt. Bij jou zijn het de ideeën. 
Je kent jouw eigen beperkingen en ondanks dat je duidelijk bent over wat jij wil, wil je niets opleggen en alleen maar bijdragen aan de ontwikkeling van ideeën over rechtvaardigheid. Een ideologie bouw je niet in je eentje op want die ontwikkelt zich over tijd door kennis en ervaring, door respect voor de ander, discussie en democratie. Aan dat gesprek en die discussie wil je actief meedoen. Met de analyse van de eeuwigdurende ideeënstrijd en de presentatie van jouw eigen ideeën wil je de lezer vooral helpen bij het aanscherpen van zijn eigen gedachten over gelijkheid en ongelijkheid. Uiteindelijk wil je na zoveel bladzijden niets anders dan belangstelling en interesse wekken voor een onderwerp dat ertoe doet. 
In mijn eigen land wordt, in de maand dat jouw boek uitkomt en waarin zoveel gebeurt dat jouw onderwerp raakt, de boekenweek gevierd. Die week staat dit keer in het teken van rebellen en dwarsdenkers die ons aanzetten tot lezen en ons voorstellingsvermogen vergroten. Voor mij ben je bij uitstek zo’n dappere dwarse denker die aan dat vermogen morrelt. Ze hadden deze maand jouw boek aan alle lezers cadeau moeten doen.


Grote groet, -Harrie Jonkman


Piketty, T.(2020). **Kapitaal en ideologie**. De Geus-Singel Uitgeverijen: Amsterdam, 1136 pagina’s. 49,00 euro.


